### ISSUE TITLE
allow to store "rulesDirectory" config in tslint.json

### ISSUE THREAD

**Issue by Strate** [palantir/tslint#1004]
Hey all!

It would be veru good, if `rulesDirectory` config options can be stored in `tslint.json`.

**Comment by JKillian** [comment]
Actually, this is already a feature! [See here](https://github.com/palantir/tslint/blob/fd43b3867eea07d97622b18193c5d835ee416470/test/config/tslint-custom-rules-with-dir.json) as an example.

**Comment by Strate** [comment]
Oh, sorry, I've not found this in readme :-(

**Comment by JKillian** [comment]
No worries! We should update the README to discuss this. In the meantime in case anyone else stumbles upon this, http://palantir.github.io/tslint/usage/tslint-json/ mentions the `rulesDirectory` field.
