### ISSUE TITLE
incorrect semicolon rule schema 

### ISSUE THREAD

**Issue by unional** [palantir/tslint#1011]
![image](https://cloud.githubusercontent.com/assets/3254987/13508087/5ba4ac8c-e13a-11e5-9613-7f5a4bff7023.png)

**Comment by adidahiya** [comment]
This issue needs more information. What schema are you referring to? What is the expected behavior? Please spend a little more time to write out meaningful issue reports.

**Comment by unional** [comment]
Ar sorry.

The `tslint.json` schema: http://json.schemastore.org/tslint
The rule `semicolon` takes array: http://palantir.github.io/tslint/rules/semicolon/
Currently it is expecting boolean.

It that schemastore maintained by `tslint`?

**Comment by adidahiya** [comment]
Nope, we haven't been maintaining schemastore. Feel free to send them a PR :)

**Comment by unional** [comment]
Ok. Closing. Thanks. PR sent. :smile:
