### ISSUE TITLE
Support TypeScript installed via JSPM

### ISSUE THREAD

**Issue by KarlPurk** [palantir/tslint#1014]
Currently TypeScript is assumed to have been installed via `npm`.  However, TypeScript can also be installed via `jspm`.

It would be great if the user could provide the location of TypeScript so that projects that use `jspm` for package management do not have to install TypeScript twice.

**Comment by adidahiya** [comment]
@KarlPurk I don't know too much about JSPM; can you outline the differences? Does a `require("typescript")` statement not resolve in the same way as it does with NPM? What do you anticipate are the required changes on our side?

**Comment by unional** [comment]
I use `jspm` too. But why do you need this feature? `tslint` is a tooling on the server side, while `jspm` is about loading on the browser.

Do you need to use `tslint` on the browser to do some online linting? That would be a valid use case.

If not, it should use local/global typescript via `npm`. 

My two cents.

**Comment by adidahiya** [comment]
Ah, yes, thanks for the info @unional. Perhaps @KarlPurk you are looking for #1001, in-browser linting?

**Comment by johnwiseheart** [comment]
Closing this as its old and seems irrelevant.
