### ISSUE TITLE
Proposal: Update "rulesDirectory" usage

### ISSUE THREAD

**Issue by unional** [palantir/tslint#1024]
Currently "rulesDirectory" usage suggested by custom rule packages are relatively reference the rules directory in `node_modules/<package>/<path to rules folder>`.

This prohibits the custom rule packages to be used in `extends` scenarios as it will break in npm < 3.

For example, an application uses `tslint-config-typings`, which is extended from `tslint-config-unional`, which uses the custom rule `tslint-eslint-rules`:

``` js
// tslint-config-typings/tslint.json
{
  "extends": "unional",
}

// tslint-config-unional/tslint.json
{
  "rulesDirectory": [
    "node_modules/tslint-eslint-rules/dist/rules",
    "./localRules/"
  ]
}
```

This configuration will work in npm 3 but not in npm < 3 because:
- "node_modules/tslint-eslint-rules/dist/rules" is resolved from the project root

It is possible to get around it by traversing up to look for "node_modules/tslint-eslint-rules/dist/rules" until the project root starting from the `tslint.json` local path. But that is wasteful and not necessary if the custom rules packages are written as config package:

``` js
// tslint-config-typings/tslint.json
{
  "extends": "unional",
}

// tslint-config-unional/tslint.json
{
  "extends": "tslint-config-eslint-rules",
  "rulesDirectory": "./localRules"
}

// tslint-config-eslint-rules/tslint.json 
// (renamed tslint-eslint-rules to tslint-config-eslint-rules
//  to match config package name convention.)
{
  "rulesDirectory": "./dist/rules"
}
```

**Comment by adidahiya** [comment]
What is the proposal here? To allow module identifiers in the `rulesDirectory` array and have TSLint import configs like this?

```ts
require(`${moduleIdentifier}/tslint.json`);
```

**Comment by unional** [comment]
Nope. Just need to keep `rulesDirectory` reference local and not referencing through `node_modules`. And consumer can use `extends` to get the rules package. 

I setup `tslint-config-unional/package.json/main="tslint.json"` so `require("tslint-config-unional")` will returns the conflict g file directly.

**Comment by unional** [comment]
Config file.... Stupid correction... :p

**Comment by unional** [comment]
Adding reference to extends PR:
https://github.com/palantir/tslint/pull/1016
And the most relevant discussion:
https://github.com/palantir/tslint/pull/1016#issuecomment-194682347

**Comment by unional** [comment]
Do you want to consider fixing this? I saw Blake have to do this to get around the issue:
https://github.com/blakeembrey/tslint-config-standard/blob/master/tslint.js#L4

**Comment by unional** [comment]
> To allow module identifiers in the rulesDirectory array

As I look back this may work too.

Another way is to enhance `extends` to accept array. This way the config author can supply the default values for they own rules

**Comment by ajafff** [comment]
This is fixed by supporting node module resolution for `rulesDirectory` since 5.2.0
