### ISSUE TITLE
Cannot install from fork

### ISSUE THREAD

**Issue by unional** [palantir/tslint#1032]
Hi,

I try to install my [fork](https://github.com/unional/tslint) using `npm install github:unional/tslint` so that I can futher test the `extends` feature while waiting for it to make its way into release.

The installation succeed but when I run it, it errors with:
```sh
ode_modules/tslint/bin/tslint src/*
module.js:327
    throw err;
    ^

Error: Cannot find module '../lib/tslint-cli'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/hwong/github/typings/vscode/node_modules/tslint/bin/tslint:3:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

And yes, the `lib` folder does not exist in under `node_modules/tslint/`.

Is there anything I can do to make it work?

I understand that this is kind of npm question but I haven't run into problem with other packages before (and I'm relatively green on `npm`).

Thanks for your help.

**Comment by JKillian** [comment]
The reason for this is that we run `grunt`, which generates the `lib` directories, before we publish to NPM.  You can do this locally and use [`npm link`](https://docs.npmjs.com/cli/link) to install local-to-local NPM dependencies. Let me know if you have any other questions!

**Comment by unional** [comment]
Thanks. Will do

**Comment by martellaj** [comment]
Have you been able to get `npm link` to work? I've used `grunt` to build successfully, but have had no luck linking. I've had no issue with `npm link` in other projects in the past, not sure what I'm doing wrong. I've tried in the root and in `lib`, but I'm getting the following error:

_npm ERR! Refusing to delete: /usr/local/bin/tslint not in /Users/martellaj/Repositories/tslint
File exists: /usr/local/bin/tslint_

Any guidance would be awesome. Thanks!

**Comment by unional** [comment]
You probably need to `sudo` or `npm rm -g tslint`

**Comment by martellaj** [comment]
`sudo` resulted in the same error. Removing the package would defeat the purpose of the link though.

**Comment by unional** [comment]
> Removing the package would defeat the purpose of the link though.

Not really. `npm rm` removes the package you originally install `npm install -g tslint`.

Since you are doing `npm link`, you want to use your custom copy of `tslint`. So `npm rm` make sense.

What's what I do.

**Comment by martellaj** [comment]
Oh, interesting. I was using Node v0.12.0; switched to v4.3.0 and it worked without issue.
