### ISSUE TITLE
False positive: not used variable in default exports

### ISSUE THREAD

**Issue by remojansen** [palantir/tslint#1036]
I'm working on a library and my its point looks as follows:

![untitled](https://cloud.githubusercontent.com/assets/10656223/13807906/860353e0-eb5b-11e5-9916-7dc243fbbd7d.png)

As you can see it says that some variables are not used. This is happening only for modules with `default` export.

**Comment by JKillian** [comment]
Thanks for the report @remojansen! This was fixed recently, you most likely have an old version of TypeScript somewhere in your workflow. See https://github.com/palantir/tslint/issues/684 for more info.
