### ISSUE TITLE
["typedef" > "variable-declaration"] conflicting in usage with ["no-inferrable-types": false]

### ISSUE THREAD

**Issue by drywolf** [palantir/tslint#1038]
Hi, I have the following tslint.json config:

        "no-inferrable-types": false,
        "typedef": [
            true,
            "call-signature",
            "parameter",
            "property-declaration",
            "variable-declaration",
            "member-variable-declaration"
        ],

When writing a variable with an inferrable type and no explicit type-definition, the `typedef` rule shows a problem, but the better behavior would be to allow this and recognize it as good code based on the above settings.

Here is a screenshot showing the problem with a very minimal example:

![image](https://cloud.githubusercontent.com/assets/394294/13818881/e82b1562-eb97-11e5-8d90-e2a4d2685b85.png)

Is my thinking about this behavior right ? I might try and provide a PR if I can get some agreement that this should be the correct behavior in this case.

Thanks

**Comment by JKillian** [comment]
Yes, this is an issue, thanks for the well-written report @drywolf! This is actually a duplicate though, check out #711 and feel free to discuss over there
