### ISSUE TITLE
import styling rule

### ISSUE THREAD

**Issue by trodi** [palantir/tslint#1040]
There doesn't appear to be a way to set a style on naming imported modules similar to how you can set the style of variable names. This may be an extension of an existing rule instead of an all together new rule.

If I have the following two imports, I'd like to check to see if they are in camelCase for example.

``` ts
import * as Q from "q";
import * as Path from "path";
```

I'd expect the following "Foo" likely not to be affected by the naming convention.

``` ts
import { Foo } from "foo";
```

In considering this, I referenced variable-name rule as a comparison.

``` json
"variable-name": [true, "ban-keywords", "check-format", "allow-leading-underscore"],
```

**Comment by JKillian** [comment]
Isn't the format of module names more semantic than syntactic though?

For example:

```
import * as Cat from "cat";
import * as path from "path";

const myCat = new Cat();
const somePath = path.resolve("some/path");
```

In other words, wouldn't you name your imported modules based off of how they are used?

**Comment by trodi** [comment]
Potentially, though I see value in being able to distinguish a given item was imported instead of created locally. Similar to the value you get from a naming convention distinguishing private members/functions versus public ones (which you might find in a [checkstyle](http://checkstyle.sourceforge.net/config_naming.html#LocalVariableName) rule configuration).

**Comment by JoshuaKGoldberg** [comment]
@trodi this is covered by [`tslint-microsoft-contrib`](https://github.com/microsoft/tslint-microsoft-contrib)'s `import-name` rule. This issue is really a subset of #1142 for determining which rules should be ported over.
