### ISSUE TITLE
npm run lint failing where as ./node_modules/.bin/tslint not

### ISSUE THREAD

**Issue by sasidhar** [palantir/tslint#1057]
### Bug Report

- __TSLint version__: `3.6.0`
- __TypeScript version__: `1.8.9`
- __Running TSLint via__: CLI

#### Bug

I am linting in two ways

* Using following from command line
```node_modules/.bin/tslint ./**/*.ts -e './node_modules/**/*.ts' --verbose```
I am not getting any NPM errors after listing out all Lint issues.

* Using `npm run lint` with following script in `package.json`
  ```
  "scripts": {
      "lint": "node_modules/.bin/tslint ./**/*.ts -e './node_modules/**/*.ts' --verbose"
  },
  ```
In this case I am seeing following after listing out all the Lint issues.
> npm ERR! Linux 4.2.0-34-generic
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "lint"
> npm ERR! node v5.6.0
> npm ERR! npm  v3.6.0
> npm ERR! code ELIFECYCLE
> npm ERR! @scope/private-package@0.0.0 lint: `tslint ./**/*.ts -e './node_modules/**/*.ts' --verbose`
> npm ERR! Exit status 2
> npm ERR! 
> npm ERR! Failed at the @scope/private-package@0.0.0 lint script 'tslint ./**/*.ts -e './node_modules/**/*.ts' --verbose'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the @scope/private-package package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     tslint ./**/*.ts -e './node_modules/**/*.ts' --verbose
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs @scope/private-package
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls @scope/private-package
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /path/to/npm-debug.log
>

**Comment by adidahiya** [comment]
NPM scripts expect processes to exit with status code 0. If you have lint failures, TSLint does not return with a 0 status code to facilitate failing your linting build task.

Related: #1053
