### ISSUE TITLE
Add nofunc for no-use-before-declare

### ISSUE THREAD

**Issue by unional** [palantir/tslint#1058]
http://eslint.org/docs/rules/no-use-before-define

**Comment by unional** [comment]
Also applies to template string:
![image](https://cloud.githubusercontent.com/assets/3254987/14035178/68bee996-f1e8-11e5-8bdf-1104eb896cf0.png)

**Comment by JoshuaKGoldberg** [comment]
Looks like this has since been fixed 😊 closing as duplicate.
