### ISSUE TITLE
Feature request: allow excluding files for specific rule

### ISSUE THREAD

**Issue by atsu85** [palantir/tslint#1063]
### The problem
I'd love to use ["class-name" rule](https://github.com/palantir/tslint/blob/master/src/rules/classNameRule.ts) for all TypeScript files in my project, except one file, that is generated.

#### Current rule-options configuration format

Based on the [documentation](https://github.com/palantir/tslint/#cli-1) 
> Rule-options can be either a boolean true/false value denoting whether the rule is used or or a list [boolean, ...] where the boolean provides the same as in the non-list case, and the rest of the list are options to the rule that will determine what it checks for

So basically if i want to enable a rule, i have only two options in terms of rule-options format as shown here:

```json
{
    "rules": {
        "class-name": true,
        "some-otherrule": [ true, arg1, arg2, arg3],
        ...
    }
}
```

So current format doesn't allow me to enable/disable specific rule for some files. If i wanted to exclude one file from being checked for errors, then i'd need to exclude that file for all rules.

#### Proposing additional rule-options configuration format
To allow excluding some file(s), advanced format 
> list [boolean, ...] where the boolean provides the same as in the non-list case
> `"some-otherrule": [ true, arg1, arg2, arg3],`

could be extended so that first argument could be either boolean (as it is now) or array (or maybe object would be more clear compared to array?) that defines the files that are included/excluded.

I'm having in mind following syntax:
`"some-otherrule": [ [includeGlobPattern, excludeGlobPattern], arg1, arg2, arg3],`
for example 
`"some-otherrule": [ ["**/*", "**/generated.ts"], arg1, arg2, arg3],`
or maybe if object would be used instead of array, follwogin syntax would be even easier:
`"some-otherrule": [ {exclude: "**/generated.ts"}, arg1, arg2, arg3],`
where include property would default to all files.

**Comment by myitcv** [comment]
Why don't you simply use:

```
/* tslint:disable:class-name */
// your generated file here

```

Does this not work?

**Comment by atsu85** [comment]
That could indeed be used to make it work, but i filed this feature request in order to avoid modifying TypeScript generator (or add complexity to the generation process, by prepending generated files with tslint hints). 
Using wildcards could be also beneficial to declaratively apply certain rules to only specific types of sources (main/unitTests/e2eTests) from tslint config, not from each file individually.

What do You think?

**Comment by myitcv** [comment]
If you don't want to put comments in the file, then simply don't pass the file to `tslint` for linting, no?

It feels too heavyweight to be adding further options elsewhere when there are at least two means of achieving (partial) file exclusion

**Comment by atsu85** [comment]
> If you don't want to put comments in the file, then simply don't pass the file to tslint for linting, no?

That is exactly what I did, but now none of the rules are checked against excluded files.

> It feels too heavyweight to be adding further options elsewhere when there are at least two means of achieving (partial) file exclusion

Yeah, that is what I anticipated as an answer ;) I also had some doubts - at least about the implementation (that I tried to keep as simple as possible). 

In reality if this was to be implemented, it would be beneficial, if You could define constants for include and exclude patters, so You don't have to copy-past the same include/exclude pattern to all the rules where You want to filter the same files... I thought it might not be reasonable to make the example more complicated, but i had smth like that in mind:

```json
{
    "constants": {
        "generatedFilesGlob": "**/generated.ts",
        "someOtherConstant": "some other value, that could be reused",
        ...
    },
    "rules": {
        "class-name": true,
        "some-otherrule": [ true, "arg1", "arg2", "arg3"],
        "rule-with-exclude": [ {"exclude": "generatedFilesGlob"}, "arg1", "arg2", "arg3"],
        ...
    }
}
```
but that would make the config file harder to parse. That took me to think about supporting js files for configuration, in addition to json files. For example:
```javascript
const generatedFilesGlob = "**/generated.ts";
module.exports = {
    "rules": {
        "class-name": true,
        "some-otherrule": [ true, "arg1", "arg2", "arg3"],
        "rule-with-exclude": [ {exclude: generatedFilesGlob}, "arg1", "arg2", "arg3"],
        ...
    }
}
```
Using JavaScript files with modules (like gulp does) has another benefit - it allows commenting and isn't so strict about commas after last element in array or property in object.

**Comment by adidahiya** [comment]
@atsu85 interesting problem, but as @myitcv indicated I am reluctant to introduce file lists / globs into `tslint.json` because of the additional complexity / clutter in the config file. I do agree that TSLint should accept `.js` files for configuration in addition to simply `.json` files. I think that would help you address the use case -- you could set up two `tslint` build tasks (one for your regular sources, one for generated sources) and programmatically disable the `class-name` rule in one of them in the same `tslintConfig.js` file.

**Comment by adidahiya** [comment]
Filed #1065 for supporting `.js` config files

**Comment by atsu85** [comment]
Fair enough, I'll close this issue in favor of just js config files

**Comment by RomanGotsiy** [comment]
I have the similar use case to @Chowarmaan.

I have test files `*.test.ts` in which I use dev dependencies, e.g. `enzyme`.
In `tslint.json` I have `no-implicit-dependencies` rule enabled and I want to disable this rule only for `*.test.ts`. Those test files are not all in the same folder so right now I have to put:

```ts
/* tslint:disable:no-implicit-dependencies */
```

at the beggining on each test file which is annoying

**Comment by Chowarmaan** [comment]
This is a similar problem I run into as well as @RomanGotsiy where you can add disables at the top of the test files, but it does become cumbersome for each file.  The exclude files would be helpful as you could exclude rules for a certain pattern files (test files, *.spec.ts) and have one clean configuration file that also allows you to simply enable more rules as you need them, and allow your tests to use them as well.  Maybe the exclude files list would then just include the rules you want to disable, instead of adding the exclusion of files to each rule?

**Comment by djskinner** [comment]
This. 100%. Having this problem with a monorepo where the test dependencies are listed in the workspace so tslint is crying about `no-implicit-dependencies`. It has to be done with a single configuration file so that IDE linting still works

**Comment by zuozhiw** [comment]
I think this issue is also related to #3447

**Comment by millimoose** [comment]
Necrobumping this too. I'm trying to add tslint-microsoft-contrib to a Vue project and a bunch of its rules bomb on .vue files; this could be a useful workaround for issues like this before the rule authors get around to ironing out those bugs - if they ever choose to. As it stands adding a comment to disable a bunch of rules into absolutely every Vue file I write is indeed cumbersome. It also makes sense to be a bit less strict in UI code or to deal with framework idioms, e.g. use of default exports
