### ISSUE TITLE
Simplify ILinterOption and Linter constructor

### ISSUE THREAD

**Issue by unional** [palantir/tslint#1068]
https://github.com/palantir/tslint/blob/master/src/lint.ts#L47-L52

``` ts
export interface ILinterOptions {
    configuration: any;  // can now be IConfigurationFile
    formatter: string;
    formattersDirectory: string;
    rulesDirectory: string | string[];
}
```

The configuration need to be processed with features like `rulesDirectory`, `extends`, and `exclude`.
How do we enforce this processing?
One idea is to keep `loadConfigurationFromPath()` simple and move the path resolution and extends logic inside. i.e.:

``` ts
constructor(....options: ILinterOptions) {
  this.options = processOptions(options);
}
```

Related to:
https://github.com/panuhorsmalahti/gulp-tslint/issues/60

**Comment by JoshuaKGoldberg** [comment]
Agreed, `Linter` and `Runner` could be simplified & better typed. We'll want to discuss this (likely breaking) change a bit before taking any action.

**Comment by JoshuaKGoldberg** [comment]
Per #4534, this is lower priority now. Given the lack of activity over the last few years I'm going to go ahead and close it.
