### ISSUE TITLE
Allow PascalCase for "variable-name" rule

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [palantir/tslint#1079]
It would be nice to have this in addition to camelCase and UPPER_CASE. 

It would also be nice if you could assign me to implement it :)

**Comment by adidahiya** [comment]
sure thing, go for it @JoshuaKGoldberg!

(I can only officially assign someone to the GH issue if they're part of the palantir org)

**Comment by JKillian** [comment]
:+1: With Javascript constructor functions as first class objects, PascalCased names are going to exist in legit code. The rule will still disallow stuff like "crazyNamed_vairable" or "what-isThis_naming" type things.
