### ISSUE TITLE
Request: no-empty should ignore empty catch blocks

### ISSUE THREAD

**Issue by RomkeVdMeulen** [palantir/tslint#1088]
I'm getting a `no-empty` error on this:

``` js
try {
  doSomethingThatMayFail();
} catch (e) {
}
```

but not this:

``` js
try {
  doSomethingThatMayFail();
} catch (e) {
  // ignore this
}
```

Of course it's open to interpretation, but I would expect the first example to also be okay. What do you think?

**Comment by m-abs** [comment]
I'd like this too. +1

**Comment by JKillian** [comment]
This could be added as an option to the rule: `allow-empty-catch`

**Comment by adidahiya** [comment]
I don't really feel comfortable making this the only exception to the `no-empty` rule. Why should this be treated specially?

**Comment by ikokostya** [comment]
> I don't really feel comfortable making this the only exception to the no-empty rule. Why should this be treated specially?

Because add comment to every empty block is annoying. Eslint has similar option http://eslint.org/docs/rules/no-empty#options. Why not make this behavior configurable for users?

**Comment by adidahiya** [comment]
> Why not make this behavior configurable for users?

alright, sure, go for it, we'll accept a PR (but it won't make it into `tslint:recommended`).

**Comment by RomkeVdMeulen** [comment]
Hasn't there been a PR for this already which got reverted? Why not change it back?

**Comment by Izhaki** [comment]
Here's another case:

```
            try {
                await reject(this.dummyTask, 'Reject reason')
            } catch (err) {}
```

We want to reject a promise in an async block (in tests).
