### ISSUE TITLE
Expose an API that accepts ts.SourceFile or ts.Program directly

### ISSUE THREAD

**Issue by Arnavion** [palantir/tslint#1096]
Currently `Linter` accepts a filename and file contents, then creates a `ts.CompilerHost` and `ts.Program` internally to get the `ts.SourceFile` objects. I'm integrating tslint into a build script that already has its own custom CompilerHost and Program objects to compile the project, and it would be more performant if I could get Linter to use my Program object or the SourceFile objects from it directly.

**Comment by adidahiya** [comment]
cool, makes sense, we're on board. this would also bring us closer to supporting running TSLint in a browser environment (as the compiler is capable of doing).

**Comment by adidahiya** [comment]
partial progress has been made on this via #1363. the `Linter` class now accepts a `ts.Program` but still requires file contents.

**Comment by JKillian** [comment]
Actually, I think it might be possible now to just pass a `ts.Program` and not pass the actual textual source. You'd just pass `undefined` to the `source` parameter of `Linter` and make sure to pass something as the `program` argument. This does feel a little strange given how the API is set up now, admittedly.

cc @ScottSWu on this

**Comment by ScottSWu** [comment]
:thumbsup: that works. 

With the upcoming multilinter PR, would there multiple kinds of linters for different use cases? unless there is some way to package everything in a single interface + helper functions?

**Comment by JKillian** [comment]
cc @caugner here. I think it might end up being best to keep things as just one main Linter class, but i'm not sure yet

**Comment by caugner** [comment]
I would suggest separating things as follows:

* The **tslint core** should *lint a source* (a string or some sort of input stream) according to a configuration and *return the (raw) result* (with references to lines/positions in that source). It should not know anything about file names or file systems (and should not maintain results between lint runs, either).
* The **tslint client** should delegate the retrieval of a source to a **tslint source provider**, pass the source(s) to the **tslint core**, aggregate the returned results and pass these results to a **tslint result formatter**.
* A **tslint result formatter** should be opened first, then receive results and should then be closed (so it can write a header and footer or buffer the content, if required).

We could then have three **tslint source providers**:

1. A file path source provider which would provide the content of a file that it reads from the file system.
2. A `ts.Program` source provider which would provide the content of a file that it reads according to the `ts.Program` parameters.
3. (new) A string source provider which would provide the source with which it was instantiated (would fix this issue).

**Comment by ajafff** [comment]
Given that the file's name is important for typescript to know how to parse the file, I don't think the concept described above would work.
I think it's best to just add a `lint(Source)File` method to `Linter` which accepts an already parsed `ts.SourceFile`. Internally `Linter#lint` would just delegate to that new method.

Linting a whole `ts.Program` is a bit too much. It's also no big deal to do this in "userland" as you can easily iterate through the files in the program.

**Comment by JoshuaKGoldberg** [comment]
Per #4534 this seems like lower priority. Please do comment here if you absolutely need this for some reason (ideally to convert to ESLint!). Closing for housekeeping until then.

**Comment by JoshuaKGoldberg** [comment]
> cool, makes sense, we're on board. this would also bring us closer to supporting running TSLint in a browser environment (as the compiler is capable of doing).

By the way: https://palantir.github.io/tslint-playground/ is a thing now! 💃✨🕺
