### ISSUE TITLE
Feature request: disallow == or === for string comparions

### ISSUE THREAD

**Issue by prabirshrestha** [palantir/tslint#1100]
We want devs to use ignore case for string most of the time. Would be good to have support for this.

We most likely always want to use `equalsIgnoreCase('a', 'A')` instead of `a1 === a2`.

here is the rule for c#. https://msdn.microsoft.com/en-us/library/bb385972.aspx

**Comment by johnwiseheart** [comment]
This is too specific for a TSLint rule. Feel free to implement your own rule.
