### ISSUE TITLE
Regression on extends for 3.7.2

### ISSUE THREAD

**Issue by unional** [palantir/tslint#1106]
https://travis-ci.org/typed-typings/npm-bluebird/builds/122353976

Seems like the extends is not working in 3.7.2. Working in 3.7.1 and 3.7.0.

It is run through NPM script:
```js
{
  "scripts": {
    "lint": "echo linting... && tslint \"**/*.ts\" -e \"node_modules/**\" -e \"source/**\"  -e \"source-test/**\" -e \"out/**\" -e \"typings/**\"",
  }
}
```

**Comment by unional** [comment]
Probably related to fix for https://github.com/palantir/tslint/issues/1083

**Comment by unional** [comment]
Sample repo: 
https://github.com/typed-typings/npm-bluebird

**Comment by unional** [comment]
Confirmed locally. Works in 3.7.1 and fail in 3.7.2

**Comment by JKillian** [comment]
What's the failure in this scenario? It looks like it's finding lint errors as it should?

**Comment by unional** [comment]
Nope. The rule is to use single quote, not double quote.

**Comment by unional** [comment]
For reference:
```js
// tslint-config-typings
{
  "extends": "tslint-config-unional",
  "rules": {
    "no-empty": false,
    "no-internal-module": true,
    "no-require-imports": false,
    "no-string-literal": true,
    "object-literal-sort-keys": false,
    "member-ordering": [false],
    "no-arg": false,
    "no-console": [
      true,
      "assert",
      "count",
      "log",
      "warn",
      "trace",
      "error",
      "debug"
    ],
    "no-inferrable-types": false,
    "no-unused-expression": false,
    "typedef": [false],
    "typedef-whitespace": [
      false
    ],
    "variable-name": [
      false
    ],
    "whitespace": [
      false
    ]
  }
}

// tslint-config-unional
{
  "rules": {
    // ......
    "quotemark": [
      true,
      "single",
      "avoid-escape"
    ],
    // ......
  }
}
```
```

**Comment by JKillian** [comment]
Oh. Well, that's strange... I'll look into this tonight, but feel free to take a look yourself and let me know if you figure it out.

I think the only related change between 3.7.1 and 3.7.2 was https://github.com/palantir/tslint/pull/1093. Not sure why this would've broken things though.

**Comment by unional** [comment]
Yeah, I checked the PR and couldn't figure out why either. But confirmed it is between 3.7.1 and 3.7.2.

**Comment by JKillian** [comment]
New hunch: it could be related to this: https://github.com/palantir/tslint/pull/1090

**Comment by JKillian** [comment]
I verified that the upgrade of `findup-sync` was causing this. Reverting to version `0.3.0` should fix this, new release coming soon...

**Comment by unional** [comment]
Is there a test we can put in to validate that in the future (to avoid accidentally upgrade it to 0.4+)?

**Comment by JKillian** [comment]
The newly published release should fix this.

@unional, as far as a test, I think it would be a good idea! I didn't take the time to write one here because I wanted to have a working release quickly
