### ISSUE TITLE
no-unused-expression and use strict

### ISSUE THREAD

**Issue by scriby** [palantir/tslint#114]
'use strict'; is triggering a failure on the no-unused-expression rule. I suppose that's technically correct, but it also means we can't use that rule with strict mode code.

**Comment by lassebn** [comment]
This behaviour has snuck back in 390ac95e3c6b57552c655b362e633b4c861594a1 ?

**Comment by JKillian** [comment]
Hi @lassebn, what version of TSLint are you using?

**Comment by adidahiya** [comment]
Also what is the code that triggers the warning @lassebn?

**Comment by lassebn** [comment]
I was using version 3.7.4, and the code was a `'use strict';` statement as the first statement in a private function, in an exported class.

I also tested with these versions of tslint:

- 3.7.3, error
- 3.7.2, error
- 3.7.1, no error

**Comment by readme42** [comment]
I can confirm: this error occurs in 3.7.4 after updating from 2.5

**Comment by JKillian** [comment]
Thanks for the reports @lassebn and @readme42: turns out class methods accidentally were not considered a valid place to place a JS directive, such as "use strict". Will be fixed by #1144 which should be in a release tomorrow

**Comment by hashark** [comment]
hi,

I just got it again... using version 3.14.0

thanks!

**Comment by JKillian** [comment]
@hashark that likely means that you have the directive in an invalid place. Could you post some code that will produce the error?

**Comment by hashark** [comment]
import SomeModel = require("./SomeModel");

"use strict";

export class SomeClass {
...
}
