### ISSUE TITLE
Suggestion: provide tslintserver

### ISSUE THREAD

**Issue by angelozerr** [palantir/tslint#1141]
TypeScript provides today a tsserver in their distribution and several editors like VSCode, Sublime, Eclipse consumes it. It's a nice feature because it's very easy to update version of TypeScript since tsserver is included in the TypeScript distribution.

It should very cool if you could provide a tslintserver which works with 'readline' like tsserver. It mean move your work from https://github.com/palantir/eclipse-tslint/blob/master/com.palantir.tslint/src/bridge/main.ts to tslint.

**Comment by JoshuaKGoldberg** [comment]
Agreed, this could be very useful! We should nail down in detail how to achieve this. What would the API look like? How would it interact with #3155's watch option?

**Comment by JoshuaKGoldberg** [comment]
Given #4534 and the lack of activity since this was posted in 2016, closing this issue as out of scope. 😢
