### ISSUE TITLE
Generate linkable webpage for each rule

### ISSUE THREAD

**Issue by alexeagle** [palantir/tslint#1146]
The failure message printed by each check needs to be short, but some checks are not easily explained in a few words.
Also, it is nice to have example code snippets demonstrating which code is or is not legal given certain options.

I propose adding an es7 decorator on `Rule` classes which provides static data such as a longer description of the problem. We can add a build step that reads this metadata, and pulls in test cases from the test tree to produce the examples. This ensures that the published examples match the behavior of the rules.

I built a similar system for Error Prone, see eg. http://errorprone.info/bugpattern/CheckReturnValue as an example generated from source. The error messages reference this page.

That page would also be a natural place to record user feedback or bugs related to that rule.

**Comment by JKillian** [comment]
I like the idea of automatically adding examples to a rule's documentation, could add a lot of clarity.

Is there a benefit to using a decorator vs. a static member for each class? I prototyped something similar to what you are suggesting awhile back [see any rule on the `next-rule-metadata` branch](https://github.com/palantir/tslint/tree/next-rule-metadata/src/rules). The [docs here](http://palantir.github.io/tslint/rules/) are actually generated from that metadata.

I haven't looked into integrating some sort of comment section, I'm more prone to keeping discussion on Github. I guess discussion on when to use a rule, its tradeoffs, etc. would fit appropriately on each rule's documentation page.

**Comment by alexeagle** [comment]
OH that doc site is very nice. Is it kept up-to-date with each release?

A static member is nearly identical, and I don't have a strong feeling
about it. Both are checked by the type-checker, available at runtime, and
easy to pick off the class definition.

**Comment by myitcv** [comment]
Related-ish https://github.com/palantir/tslint/issues/846

**Comment by JKillian** [comment]
@alexeagle Yep, I go through and update it with every release. There's still a lot of information that could be expanded upon: rationales for rules, related information links, good and bad examples, versioning info, etc. but I just haven't had time to go through and do that thoroughly for every rule.

**Comment by myitcv** [comment]
We've also discussed automatically generating documentation and the sample `.json` config a couple of times:

* https://github.com/palantir/tslint/issues/717#issuecomment-145749210
* https://github.com/palantir/tslint/issues/830

**Comment by JKillian** [comment]
#1311 will merge metadata for each rule into master, which will make it easier to keep things up to date. I'm considering generating the rules portion of the README from this metadata and adding links to the website in the rEADME

**Comment by alexeagle** [comment]
I think this is done now? eg. https://palantir.github.io/tslint/rules/no-internal-module/
unless there is still some release automation left to do.

**Comment by nchen63** [comment]
automation is implemented. Will close, thanks
