### ISSUE TITLE
new rule: no-boolean-in-ternary

### ISSUE THREAD

**Issue by HamletDRC** [palantir/tslint#1147]
I propose a new rule called "no-boolean-in-ternary"

Sometimes people write boolean constants into ternary expressions. This code can always be written in a simpler and clearer manner by using the || and && operators.

`const isEnabled = someValue ? someValue.isTrue() : false; // violation
const isEnabled = someValue && someValue.isTrue(); // OK`

`const isEnabled = someValue ? true : someOtherValue; // violation
const isEnabled = someValue || someOtherValue; // OK`

Is there ever a reason to have a boolean constant in a ternary expression? I can't think of one.

We can implement this in tslint-microsoft-contrib as well, but I thought I'd give tslint a chance to take it in first.

**Comment by JKillian** [comment]
Hmm, your two expressions do have different semantics:

Say `someValue === null`:

```ts
const isEnabled = someValue ? someValue.isTrue() : false;  
// isEnabled === false

const isEnabled = someValue && someValue.isTrue(); 
// isEnabled === null
```

Or in the second case, say `someValue === 53`:

```ts
const isEnabled = someValue ? true : someOtherValue; 
// isEnabled === true

const isEnabled = someValue || someOtherValue; 
// isEnabled === 53
```

It seems to me that people could want both behaviors?

**Comment by HamletDRC** [comment]
null && false

evaluates to null.

OK then. close the issue I guess :(
