### ISSUE TITLE
285 MB of perf profile data was packaged as part of 3.8.0

### ISSUE THREAD

**Issue by dfederm** [palantir/tslint#1160]
It looks like tslint 3.8.0 was uploaded with 285 MB of perf profiling data with it. It's causing exceedingly long "npm install" times for everyone.

![image](https://cloud.githubusercontent.com/assets/6445614/14771280/3d3477a8-0a3b-11e6-820a-244e505f426b.png)

**Comment by JKillian** [comment]
Oh no! This is completely my fault - very sorry that those performance
profiles got included. I'll fix it when I can get back to a computer next

**Comment by dfederm** [comment]
Thanks!

**Comment by dfederm** [comment]
Oops, didn't mean to close. I'll let you do that when you upload a new version :)

**Comment by JKillian** [comment]
This should be all fixed up in now-published version 3.8.1, thanks again for noticing @dfederm!
