### ISSUE TITLE
Stop testing with node v0.10 and v0.12, add v6.0 instead

### ISSUE THREAD

**Issue by adidahiya** [palantir/tslint#1181]
https://nodejs.org/en/blog/release/v6.0.0/#what-about-node-js-v0-10-and-v0-12

Related Tasks:
- [ ] Use Object.assign in `buildDocs.ts` and other locations if necessary

**Comment by adidahiya** [comment]
At the same time, we should add testing for Node v6.

**Comment by JKillian** [comment]
It seems that AppVeyor sometimes breaks on Node 0.10 now for who knows what reason, so all the better to do this
