### ISSUE TITLE
New set of rules released: vrsource-tslint-rules

### ISSUE THREAD

**Issue by abierbaum** [palantir/tslint#1189]
Our team needed several new rules, so I released a package that implements them today.  (many thanks for @JKillian for helping me get the new test system working; it is awesome)

Full details are available here: https://github.com/vrsource/vrsource-tslint-rules

The rules added are:
- **conditional-expression-parens**: ensure any complete conditional expression clauses use parens
- **dot-notation-rule**: Use foo.bar instead of foo["bar"]
- **ext-variable-name**: Massively flexible variable name checker.  Allows cascading rules taking into account variable type and many other options.  Includes regex support.
- **max-params**: Place limit on number of parameters allowed
- **multiline-arrow**: Option to enforce need for parens and/or block if arrow function is multi-line.
- **no-duplicate-imports**: Flag importing from same module multiple times in single file.
- **prefer-case-blocks**: Check that all case statements use a block.
- **prefer-const**: Prefer use of const instead of let when never assigned to.  (borrowed from typescript project)
- **prefer-literal**: Allow flagging locations where "new Object/Array/Function()" is called
  - **literal-spacing**: Enforce always/never having spaces at beginning and end of array and object literals.

Please let me know if you find these useful.  If any of them are generally useful I am more than willing to submit them back to tslint to become part of the base rules.

**Comment by roman-petrov** [comment]
@abierbaum, vrsource-tslint-rules are great! We started using these rules in our project, and these rules enforce to use some good programming/style practices. +1 to include these rules int o standard tslint distribution

**Comment by adidahiya** [comment]
As a first step, I've added a link to your project in our README (https://github.com/palantir/tslint/commit/a1d5eab5530f1916584ad71293cddc86a651c569). Next we'll go through the rules and figure out which ones belong in core TSLint. Thanks @abierbaum!

**Comment by JoshuaKGoldberg** [comment]
👏 @abierbaum are you still interested in merging these rules into TSLint core? It'd be great to see some PRs if so!

**Comment by abierbaum** [comment]
@JoshuaKGoldberg I would be interested in it, but I have been having trouble getting PRs into tslint.  It is one of the reasons I started it as a separate project so I could always know our team could add and extend rules we need in production and know we could get changes through.

**Comment by JoshuaKGoldberg** [comment]
Closing per #4534 - since the rules are available as an external plugin, we can live without them being added to TSLint core. Thanks!
