### ISSUE TITLE
Single-line disabling flags also disable max-line-length for the next line

### ISSUE THREAD

**Issue by vitaminj** [palantir/tslint#1217]
### Bug Report
- **TSLint version**: `3.9.0`
- **TypeScript version**: `1.8.10`
- **Running TSLint via**: gulp-tslint / Visual Studio Code
#### TypeScript code being linted

Two long lines with the max-line-length rule.
First line either has disable-line on it, or disable-next-line before it.
#### Actual behavior

Linting passes.
#### Expected behavior

Linting should fail on second line.

PR with fix and testcases ready to be filed...

**Comment by ajafff** [comment]
This should be fixed by #2062
