### ISSUE TITLE
[indent] How to enforce tabs vs spaces?

### ISSUE THREAD

**Issue by Bartvds** [palantir/tslint#122]
Currently it is impossible to enforce indenting style using either tabs or spaces. Tabs work currently by using `"indent": [true, 4],`, but 4 spaces are also 4 spaces; the rule is ambiguous.

If somebody would convert some tab-indented code to 4 spaces (or create a new 4 spaced file) then TSLint would accept it and we'd still have mixed indents in the repos.

**Comment by adidahiya** [comment]
The indent rule now supports tabs, and I've made a [new issue](https://github.com/palantir/tslint/issues/581) for other enhancements, including a `"detect"` option as suggested here.
