### ISSUE TITLE
Ignoring constructor in member ordering

### ISSUE THREAD

**Issue by marines** [palantir/tslint#1222]
Recently #1158 has been fixed however I'd like to opose to that since the constructor is a special kind of method so it shouldn't be treated as any other public method.

Let's take a look at the example:

```javascript
export interface IFoo {
    bar(): void;
}

class Foo implements IFoo {
    static $inject: string[] = ['$rootScope',
                                '$state',
                                '$location'];

    constructor(private $rootScope: ns.RootScope,
                private $state: angular.ui.IStateService,
                private $location: angular.ILocationService) {}

    private baz1: string;
    private baz2: number;

    bar(): void {
        // ...
    }

    private fooBar(): void {
        // ...
    }
}
```

I'm using all three `"public-before-private", "static-before-instance", "variables-before-functions"` options for "member-ordering" rule which force me to move the private properties above the constructor. Keeping them as they are makes the static $inject and the constructor look easy to read as they are related to each other. Having multiple private properties in between them would move them too far away.

**Comment by JKillian** [comment]
Agreed that this is an issue! I think it's quite similar to #1205 though, so let's continue the discussion over there if necessary
