### ISSUE TITLE
Feature request: Linebreak style

### ISSUE THREAD

**Issue by Bartvds** [palantir/tslint#123]
A rule or setting to enforce (consistent) linebreaks would be good:

So either CRLF or LF (or CR), and no mixing.

**Comment by patsissons** [comment]
I think this ought to be fairly straight forward to implement. might look at this sometime soon if time permits. I think it's just checking the text content of the `NewLineTrivia` nodes.

**Comment by patsissons** [comment]
Something I ran into while writing this rule is that the tslint [parse.ts](https://github.com/palantir/tslint/blob/c9cfc119e4224740507c86eb9f1ad6d846967576/src/test/parse.ts) file is splitting code on `\n` to break it up into lines, whereas the typescript scanner (slash source file) is aware of the other potential line endings. This is not a problem for `CRLF` but is a problem for `CR`. I'm not sure if literally anyone still uses `CR` but if they do I cannot lint there line endings properly (likely tslint just doesn't support linting those files altogether).

For now I will leave the `CR` functionality stubbed in and implementation commented out. I'll leave it to you guys to decide if `CR` support is a desired bug fix or not.

**Comment by patsissons** [comment]
This is also going to be really hard to write a test for because creating a a test lint file with mixed line endings is going to be a nightmare with git. I think i may have to just settle for very basic tests where each file is just in a different line ending. It just means two tests for each line ending config (one fail and one success).

**Comment by patsissons** [comment]
i am going to mark the entire line as a failure because it is a bit awkward to mark just the line ending as a failure. Open to suggestions on how to better approach the failure range.
