### ISSUE TITLE
Rule question

### ISSUE THREAD

**Issue by Fank** [palantir/tslint#1231]
We are using angular2 in our company, and we need a rule for following example:
```ts
@Component({
  inputs: ['asd']
})
class foo {
  private asd;
}
```
```ts
@Component({})
class foo {
  @Input('asd') private asd;
}
```
In angular2 you can declare "input" variables in 2 ways, 1. via `@Component` Annotation or via the `@Input` Annotation inside the class.

I can wirte a rule that can handle this, my question is:
- How should this rule be named?
- How should the option be named?:
 - for prefering `inputs` in `@Component`
 - for prefering `@Input` in class

**Comment by JKillian** [comment]
@Fank This sounds like a great question for [Codelyzer](https://github.com/mgechev/codelyzer), which is a project of rules specifically for Angular2. I'd recommend asking over there!

**Comment by Fank** [comment]
Thanks
