### ISSUE TITLE
Feature request: multiple --init options

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [palantir/tslint#1255]
For personal projects I prefer an extremely restrictive tslint.json. It would be nice if we could have `--init-empty` / `--init-full` / etc. 

Thoughts?

**Comment by adidahiya** [comment]
tslint.json presets (what I think you're getting at) are best handled by creating config packages on NPM (i.e., "tslint-config-X") and using the [extends feature](http://palantir.github.io/tslint/usage/tslint-json/). We're planning on publishing an official recommended config package soon (something like "tslint-config-standard").

**Comment by JoshuaKGoldberg** [comment]
Cool thanks!
