### ISSUE TITLE
Support eslint quote-props rule

### ISSUE THREAD

**Issue by danvk** [palantir/tslint#1260]
I'd like a rule equivalent to eslint's [quote-props][1], so that I can enforce that object keys are quoted only when necessary.

i.e. I'd like a setting to make this illegal:

```ts
const o = { 'name': 123 };
```

in favor of:

```ts
const o = { name: 123 };
```

[1]: http://eslint.org/docs/rules/quote-props

**Comment by adidahiya** [comment]
sounds like a good rule to me. open to PRs.
