### ISSUE TITLE
Error: Could not find the following rules specified in the configuration: no-mergeable-namespace

### ISSUE THREAD

**Issue by yogeshlonkar** [palantir/tslint#1270]
### Bug Report

- __TSLint version__: `<3.10.2>`
- __TypeScript version__: `<1.8.9>`
- __Running TSLint via__: gulp-tslint

with using `sample.tslint.json` from tslint itself:

#### Actual behavior

```
Error: Could not find the following rules specified in the configuration:
no-mergeable-namespace
    at Object.loadRules (C:\...\node_modules\tslint\lib\ruleLoader.js:29:15)
    at Linter.lint (C:\...\node_modules\tslint\lib\tslint.js:25:44)
    at C:\...\node_modules\gulp-tslint\index.js:101:30
```

#### Expected behavior

When running tslint this error should not occur

**Comment by adidahiya** [comment]
we haven't made a release that contains the `no-mergeable-namespace` rule yet (the PR merged 9 days ago, https://github.com/palantir/tslint/pull/1253). sorry for the confusion, but you should just remove that rule from your config for now.

**Comment by yogeshlonkar** [comment]
Alright, Thanks.
