### ISSUE TITLE
README: Description of interface-name is duplicated

### ISSUE THREAD

**Issue by YuichiNukiyama** [palantir/tslint#1274]
### Bug Report

- __TSLint version__: `3.10.2`

#### Actual behavior

see this capture.
![interface-name](https://cloud.githubusercontent.com/assets/9623009/15592949/cc372840-23e2-11e6-9e39-fc0282d770f1.JPG)

#### Expected behavior

delete old description.

**Comment by JKillian** [comment]
Thanks @YuichiNukiyama! This is fixed now
