### ISSUE TITLE
Add a `VersionDisplayRule` lint rule

### ISSUE THREAD

**Issue by JKillian** [palantir/tslint#1278]
This lint rule would simply produce one failure for the first node in a source file with a message like: "You are running TSLint v3.10.7 using TypeScript v1.8.7".

Often times when TSLint is being run through other tools, it can be difficult to figure out what exact version of TSLint and TypeScript are being used for linting, and this would make things much easier.

Another version of this idea might be something like "DebugDisplayRule" which would print out the above information and other extra pertinent info.

Just thought of this idea tonight off the top of my head and can't decide if it's a crazy idea or a great idea 😁

**Comment by YuichiNukiyama** [comment]
duplicate #990?
In any case, Node modules dependence is too complex for me. So, I think this idea is good :+1:

**Comment by adidahiya** [comment]
I don't think this should be a rule; we can just always print out the current versions being used. And yeah, something like #990 is also desirable

**Comment by JKillian** [comment]
So the reasoning here is that if you're using TSLint integrated w/ an IDE, you might not be able to see anything other than the output from a rule - your IDE isn't going to show you TSLint console output.

**Comment by adidahiya** [comment]
fair, but I'm still pretty hesitant to implement what feels like a hacky solution to the IDE plugins' problems

**Comment by JoshuaKGoldberg** [comment]
This hasn't been touched in a couple of years. Closing for housekeeping purposes, but if someone feels passionately about adding this, please do speak up!
