### ISSUE TITLE
typedef rule improvement

### ISSUE THREAD

**Issue by Fank** [palantir/tslint#1279]
Currently there are 2 options for `parameter`:
- `parameter`: checks type specifier of function parameters for non-arrow functions.
- `arrow-parameter`: checks type specifier of function parameters for arrow functions.

But there is only 1 option for `call-signature`:
- `call-signature`: checks return type of functions.

It would be nice to split `call-signature` in 2 options:
- `call-signature`: checks return type of functions for non-arrow functions.
- `arrow-call-signature`: checks return type of functions for arrow functions.

**Comment by JKillian** [comment]
Agreed @Fank! Check out #1015 and PR #1284
