### ISSUE TITLE
Feature request: TFS formatter

### ISSUE THREAD

**Issue by cgwrench** [palantir/tslint#1281]
Firstly, thank you for providing a great tool.

It would be great to have support for a formatter that makes use of [the VSO/TFS logging commands](https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md) so that the output of TSLint can be parsed by Visual Studio Online/Team Foundation Server.

I'm currently using a custom formatter to achieve this, but I was wondering if you would consider including such a formatter within TSLint itself. I think that this would compliment the existing msbuild formatter.

If this is something that you would like to see incorporated, I am happy to provide a pull request.

**Comment by JKillian** [comment]
Yep, happy to add another formatter into TSLint if it's useful for integration! Just be aware that there are [some issues using formatters](https://github.com/palantir/tslint/issues/656) when running on multiple files at a time. Don't think that should stop this though, especially if the custom formatter is working well for you right now

**Comment by cgwrench** [comment]
Great, thanks. Pull request created. Please let me know if I've missed anything or if you'd like anything changing.
