### ISSUE TITLE
gives odd error

### ISSUE THREAD

**Issue by alvipeo** [palantir/tslint#1287]
I've got the following import in my code:
```ts
import * as uuid from "node-uuid";
```
and tslint gives me squiggly under '__* as uuid__'. And the module doesn't have default export. So what's wrong with that?

**Comment by JKillian** [comment]
What's the error message you're getting? What version of TSLint are you using? What does your config look like?

**Comment by alvipeo** [comment]
Sorry, was in a hurry.

error: import-destructuring-spacing
"tslint": "3.10.2"

do you still need config?

**Comment by adidahiya** [comment]
This looks like a rule from [codelyzer](https://github.com/mgechev/codelyzer/blob/master/src/importDestructuringSpacingRule.ts), not a core rule. There may be a bug in its implementation.
