### ISSUE TITLE
Add option to disallow require() for certain file types

### ISSUE THREAD

**Issue by erik-kallen** [palantir/tslint#1288]
We have a setup where we want to always use `import` for files of types `*.scss` and `*.tsx`, but we might need `require()` for other file types (eg. `require('!!file!image!styles/images/icons.svg')`) for webpack.

It would be neat if the tsconfig setting `no-require-imports` could be specified as a regex like

```
no-require-imports: '.*\.(scss|tsx)'
```

to disallow import just of files that match the specific pattern

**Comment by aluanhaddad** [comment]
See Microsoft/TypeScript#6615, you will be able to use standard import syntax for these dependencies.

**Comment by JoshuaKGoldberg** [comment]
Since this is now supported by TypeScript, closing this issue for housekeeping. Please do speak up if you have a need for this rule that's not yet achievable!
