### ISSUE TITLE
Rename no-constructor-vars to no-parameter-properties

### ISSUE THREAD

**Issue by adidahiya** [palantir/tslint#1296]
This is more consistent with the official name for this feature:

```ts
constructor(private foo: string) {
}
```

http://www.typescriptlang.org/docs/handbook/classes.html

**Comment by cspotcode** [comment]
The documentation for this feature is still out-of-sync.  The URL seems to have updated, but the content of that page still uses the old name.

**Comment by nchen63** [comment]
@cspotcode #1645 will update the docs

**Comment by adidahiya** [comment]
@cspotcode this change has not been released yet. The docs site will only reflect the most recent __stable__ release of tslint (what you get with `npm install tslint@latest`).

**Comment by cspotcode** [comment]
Ok, thank you for clarifying.  Still, the docs site has an inconsistency.

On https://palantir.github.io/tslint/rules/ it says "no-parameter-properties" but when I follow that link (https://palantir.github.io/tslint/rules/no-parameter-properties/) it says "no-constructor-vars".

**Comment by adidahiya** [comment]
@cspotcode you're right, thanks for pointing that out. That was a mistake in my PR https://github.com/palantir/tslint/pull/1616, I shouldn't have updated the docs/ folder there.
