### ISSUE TITLE
Add additional granularity for `trailing-comma`

### ISSUE THREAD

**Issue by maxdeviant** [palantir/tslint#1322]
It would be nice to have some additional granularity added to the `trailing-comma` rule. Our team currently desires to enforce trailing commas in certain cases, but not others.

Is this something we would be open to? And if so, would it be preferable to just extend the options on the existing rule, or split the rule up into different rules?

I would be happy to submit a PR for this, if it is something that we would want to do.

##### Approach 1: Additional Options

```json
"trailing-comma": [
    false,
    {
        "objectliterals": [
            true,
            {
                "multiline": "never",
                "singleline": "never"
            }
        ],
        "namedimports": [
            true,
            {
                "multiline": "always",
                "singleline": "never"
            }
        ],
        "arrays": [
            true,
            {
                "multiline": "always",
                "singleline": "never"
            }
        ]
    }
]
```

##### Approach 2: Separate Rules

```json
"trailing-comma-object-literals": [
    true,
    {
        "multiline": "never",
        "singleline": "never"
    }
],
"trailing-comma-named-imports": [
    true,
    {
        "multiline": "always",
        "singleline": "never"
    }
],
"trailing-comma-arrays": [
    true,
    {
        "multiline": "always",
        "singleline": "never"
    }
]
```

**Comment by adidahiya** [comment]
I think splitting the rule up like this defeats the spirit of the style convention we're trying to enforce with `trailing-comma`. If you use it in one of those syntaxes, then why not enforce it consistently across all of them?

For now, I'm disinclined to accept a PR for this change in core TSLint, but I'll leave this issue open for further discussion & feedback.

**Comment by maxdeviant** [comment]
Personally, I would agree. I turned on the rule, but immediately got negative feedback from some of the other team members. Not that the personal opinions of a single team is a good reason to go changing TSLint core :smile:

Thank you for the quick reply!

**Comment by JKillian** [comment]
I concur with @adidahiya here - it makes sense to have consistent lint rules for similar syntactic constructs. In this case, making the `trailing-comma` rule more granular would be more code and API complexity with the negative effect of encouraging inconsistent styles in users' codebases.

Of course, your team is always welcome to use the code from TSLint as as starting point and create a custom rule if you all decide you need something non-standard.

For what it's worth, `trailing-comma` with `multiline: true` is one of my favorite lint rules! It really makes line-wise editing simple which is great when working in an editor like VIM.
