### ISSUE TITLE
Documentation - comments in tslint.json files

### ISSUE THREAD

**Issue by IceCreamYou** [palantir/tslint#1331]
The [tslint.json format documentation](https://palantir.github.io/tslint/usage/tslint-json/) says:

> tslint.json configuration files may have comments in them (even though this is technically invalid JSON).

In what format are comments allowed? Since comments are not valid in JSON, saying "comments are allowed in our JSON" doesn't explain how to write valid comments.

**Comment by JKillian** [comment]
Comment types that are valid in JS should also work in tslint.json configurations. You're right though, we should mention this in the docs!

**Comment by IceCreamYou** [comment]
Thanks. I opened a PR to update the docs: #1333

**Comment by JKillian** [comment]
Thanks @IceCreamYou! Merged that PR
