### ISSUE TITLE
How do i find out a type of a CallExpression?

### ISSUE THREAD

**Issue by Fank** [palantir/tslint#1339]
Hello i have a question.
I haven't found a case who handle it.

Example code:

``` typescript
class AComponent {
    public test(): void {
        // ASD
    }

    public test2(): void {
        // ASD
    }
}

let a = new AComponent();
a.test();
a.test2();
```

I want to disallow using `AComponent.test()` because its deprecated, and people should `AComponent.test2()`.
Is there any way to find out that `a` is a `AComponent`?

Thanks in advance

**Comment by adidahiya** [comment]
@Fank it is currently not possible to get the types of identifiers in a robust way with a TSLint rule walker. See #1323 and #680 for more information.

**Comment by andy-hanson** [comment]
This can be done now with a `TypedRule`, which takes the `Program`. Call `program.getTypeChecker()` and `checker.getTypeAtLocation(location)`.
