### ISSUE TITLE
curly  

### ISSUE THREAD

**Issue by foxjazz** [palantir/tslint#1374]
### Bug Report

feature request
#### TypeScript code being linted

for(let i = 0; i < 50; i++)
{
   dosomething(i);
}
#### Actual behavior

tslint complains about my curly.  I prefer to code in this way.
#### Expected behavior

I would like it not to complain about this.;  It wants the curly brace after the ) which to me is bad form.

**Comment by johnwiseheart** [comment]
This report is pretty old and so I'm going to close it. It should be possible to disable the `one-line` rule which enforces this behaviour.
