### ISSUE TITLE
How can I run tslint for entire directory on Windows?

### ISSUE THREAD

**Issue by evusik** [palantir/tslint#1375]
Hi,

I have a directory structure like:
./checkout/src/random_dir/\*.ts
./checkout/test/random_dir/\*.ts

I'm trying to run tslint on Windows with './checkout_TEST/{,\*\*/}*.ts' as an argument (and other combinations), but unless I specifically run it for test dir, it always seems to pick up only .ts files in src directory. It totally ignores test.

Anyone has any pointers?

Thanks!

**Comment by adidahiya** [comment]
The CLI accepts standard node globs as strings. You should be able to use `tslint './checkout/**/*.ts'`.

**Comment by evusik** [comment]
Hello,

unfortunately, it does not work - that was one of the first things I tried. When I do `tslint './checkout/**/*.ts' ` it again finds everything in the src directory (recursively), but nothing in test folder at all.

When I do `tslint './checkout/test/**/*.ts' `, it find issues in test directory but nothing at all in src directory.

I have also tried `tslint './checkout/**/**/*.ts' ` - which again finds only issues in src directory but not in test.

No other configuration is changed between the runs.

Thanks in advance for any pointers, these would be very appreciated. Please let me know if providing further details about the directory structure and/or output files would help.

Eva

**Comment by JKillian** [comment]
Hi Eva,

This seems like the same issue described [here](https://github.com/palantir/tslint/issues/1091#issuecomment-206956050) in #1091. Single quotes aren't recognized by `cmd.exe`, so that's most likely what's causing you issues. You could try switching to PowerShell, which I believe allows the use of single quotes as quotes. Hope this helps!

**Comment by evusik** [comment]
Hi JKillian,

unfortunately I already run this from powershell :( (using Invoke-Expression)

The exact command being executed from a powershell script is:
`tslint './checkout_TEST/**/**/*.ts' --format json --config ./tslint.json --out TsLint_out_TEST_1.0.22779.json`

Eva

**Comment by JKillian** [comment]
I'm not sure how the command-line parsing library we use works, but I'd try specifying the name of the file  last:

```
tslint --format json --config ./tslint.json --out TsLint_out_TEST_1.0.22779.jso './checkout_TEST/**/*.ts'
```

**Comment by evusik** [comment]
I tried that, does not help :( Only issues from src directory are found.

**Comment by evusik** [comment]
Hi,

can anyone help with this?

**Comment by joeizy** [comment]
Make sure you **include single quotes when specifying the glob pattern** at the command line / terminal. This is implied in the previous comments but wasn't obvious for me at first.
