### ISSUE TITLE
Output rule name/id in command-line (like ESLint)

### ISSUE THREAD

**Issue by philcockfield** [palantir/tslint#1376]
Currently when linting the error message is shown, but the specific rule name/id is not emitted.  This makes it tedious to find if you want to ignore or adjust the rule.

One thing that is very attractive about eslint is that they emit these ID's in the console as stable handles for easy googling and ignoring/adjusting within the file as a comment or the `tslint.json`.

For example, and output from ESLint:

![image](https://cloud.githubusercontent.com/assets/185555/16601311/de263b9e-435f-11e6-8970-faea264b24d1.png)

The `semi` in grey is the rule.  SUPER SUPER helpful.

In TSLint, there does not appear to be any corresponding thing:

![image](https://cloud.githubusercontent.com/assets/185555/16601380/4ff94a22-4360-11e6-9bb3-b3af680b97db.png)

Admittedly the semi-colon rule is pretty easy to understand, but the `Shadowed variable: 'args'` is far harder to search for to track down the precise rule that is causing this outcome.

Thanks!

**Comment by adidahiya** [comment]
The built-in verbose formatter also prints the rule name for each lint failure.

**Comment by adidahiya** [comment]
Filed #1378 for better documentation.

**Comment by philcockfield** [comment]
Oh great - that's good to know.  Thanks @adidahiya.
