### ISSUE TITLE
Better documentation for built-in formatters

### ISSUE THREAD

**Issue by adidahiya** [palantir/tslint#1378]
We don't really document them anywhere.

related: #1376

**Comment by bencoveney** [comment]
Would the idea here to be to add some details to each formatter's TypeScript files similar to IRuleMetadata which then can be compiled into the website docs? My guess would be IFormatterMetadata with fields along the lines of:
- name
- description
- descriptionDetails
- example output
- whether the formatter output is for consuption by humans or other tools - ?
- notable tools which accept the format (helpful for people googling) - ?

Not tagged as accepting PRs but I'd like to give it a go if possible.

**Comment by adidahiya** [comment]
@bencoveney that sounds great, go for it
