### ISSUE TITLE
Best practices rules suggestions: handle-callback-err, enforcing new line after declarations

### ISSUE THREAD

**Issue by Brakkar** [palantir/tslint#1379]
Hello, it would be good to have these:

1) Enforce Callback Error Handling
http://eslint.org/docs/rules/handle-callback-err

2) Enforce the consistent use of either function declarations or expressions
http://eslint.org/docs/rules/func-style

3) require an empty line before return statements
http://eslint.org/docs/rules/newline-before-return

4) Enforce new line after variables declarations (not each declaration, but after the last of a consecutive group of declarations)

Would love to see them in tslint. Thanks for the great work.

**Comment by JoshuaKGoldberg** [comment]
FWIW, 2 and 3 are in now, so it looks like just 1 and 2. Editing the title to make this more discoverable.

**Comment by JoshuaKGoldberg** [comment]
Closing this formatting rule request per #4534. Thanks!
