### ISSUE TITLE
Making all number literals have consistent format

### ISSUE THREAD

**Issue by dusanlukic** [palantir/tslint#1391]
Thanks to JavaScript’s general float number type there are no differences between `1.0` and `1` or between `0.5` and `.5`.

We could add a rule to require leading `0.`, which would basically prevent number literals like `.1` and to require trailing `.0`. The later one would prevent number literals like `12` so it could be optional.

``` typescript
"number-format": {
    "pre": true | false, // whether to always include a preceding 0.
    "post": true | false // whether to always include a trailing .0
}
```

**Comment by JoshuaKGoldberg** [comment]
I'm having problems trying to implement this rule. What is the `visit` call for number literals?

**Comment by JoshuaKGoldberg** [comment]
@dusanlukic looks like this can be closed?

**Comment by adidahiya** [comment]
closing for now. future requests can be new issues
