### ISSUE TITLE
TSLint does not run for entire directory on Windows

### ISSUE THREAD

**Issue by evusik** [palantir/tslint#1392]
Hi,

trying once more as my previous report has been closed without resolution. 

I have a directory structure like:
./checkout/src/random_dir/*.ts
./checkout/test/random_dir/*.ts

I'm trying to run tslint on Windows with './checkout_TEST/{,**/}*.ts' as an argument (and other combinations), but unless I specifically run it for test dir, it always seems to pick up only .ts files in src directory. It totally ignores test.

When I do `tslint './checkout/**/*.ts'` it again finds everything in the src directory (recursively), but nothing in test folder at all.

When I do `tslint './checkout/test/**/*.ts'`, it find issues in test directory but nothing at all in src directory.

I have also tried `tslint './checkout/**/**/*.ts'` - which again finds only issues in src directory but not in test.

No other configuration is changed between the runs.

The exact command being executed from a powershell script is:
`tslint './checkout_TEST/**/**/*.ts' --format json --config ./tslint.json --out TsLint_out_TEST_1.0.22779.json`

I have also tried specifying the name of the file last:
`tslint --format json --config ./tslint.json --out TsLint_out_TEST_1.0.22779.json './checkout_TEST/**/**/*.ts'`

Anyone has any pointers?

Thanks!

**Comment by JoshuaKGoldberg** [comment]
👏 @evusik, sorry for the delay! I'm on Windows and can't reproduce your issue. Closing this for housekeeping, but if this is still an issue, please do comment here and @ me!
