### ISSUE TITLE
Prevent ts-lint outputting errors & breaking the build

### ISSUE THREAD

**Issue by RichardJECooke** [palantir/tslint#1396]
### Bug Report

- __TSLint version__: `3.13.0`
- __TypeScript version__: `1.8.10`
- __Running TSLint via__: (please choose one) CLI

#### Actual behavior

ts-lint runs correctly and gives me hundreds of lines of warnings without breaking.
But in my bash build script I think these warnings are treated as errors because it says:
`The command './node_modules/.bin/tslint -c "tslint.json" -e "node_modules/**/*" -e "typings/**/*" "**/*.ts*"'  returned a non-zero code: 2` 
And the script doesn't continue to the next line.

#### Requested feature

Have a build switch like `-w`, which when present will pipe lint statements to stdout, not stderr (or something, my Unix isn't good) so it won't break the build chain.

**Comment by JKillian** [comment]
Does the `--force` option help you?

**Comment by RichardJECooke** [comment]
Oh, that works, thanks.
