### ISSUE TITLE
TypeScript@next peer dependency with tslint@next

### ISSUE THREAD

**Issue by yuit** [palantir/tslint#1401]
Because TypeScript@next has now version 2.1.0-dev. For the `npm install`, we would need new tslint@next to be republished.

**Comment by adidahiya** [comment]
yep, working on that here: https://github.com/palantir/tslint/pull/1395

**Comment by adidahiya** [comment]
@yuit released 3.14.0-dev.0

**Comment by Turbo87** [comment]
@adidahiya I'm using:

```
    "tslint": "^3.14.0-dev.0",
    "typescript": "^2.1.0-dev.20160718"
```

and I'm still seeing:

```
├── tslint@3.14.0
└── UNMET PEER DEPENDENCY typescript@2.1.0-dev.20160808
```

**Comment by adidahiya** [comment]
@Turbo87 that issue is discussed here: https://github.com/palantir/tslint/issues/815
