### ISSUE TITLE
Feature Request: Support trailing comma for function arguments.

### ISSUE THREAD

**Issue by markwongsk** [palantir/tslint#1409]
Support trailing comma rule/enhance trailing comma rule for function args.

As per https://github.com/Microsoft/TypeScript/issues/7279, functions now support trailing commas for their arguments.

**Comment by adidahiya** [comment]
nice, thanks for the heads up! I'm looking forward to this

**Comment by markwongsk** [comment]
How far do we want to take this trailing comma rule? For example, type parameters and function types can also be linted:
```
var a: (
    foo: string,
    bar: string,
) => string
```
and
```
function foo<
    T,
    U,
    V,
>(firstArg: string, secondArg: string) { return 42; }
```

**Comment by adidahiya** [comment]
I'd say +1 for all of those @markwongsk -- anywhere a trailing comma is supported and a list is multiline, we should lint it

**Comment by timocov** [comment]
@adidahiya What do you think about be able to disable it for multiline?
