### ISSUE TITLE
Add visitor methods for decorators to RuleWalker

### ISSUE THREAD

**Issue by adidahiya** [palantir/tslint#1416]
Like `Ng2Walker` in codelyzer: https://github.com/mgechev/codelyzer/blob/83c5a3d60279635c7bb7e23cf43fa17780c8f5d8/src/util/ng2Walker.ts

**Comment by csnate** [comment]
Are you looking for a single additional `visitDecorator` method and switch clause in the `SyntaxWalker`?  Or something more complicated and Angular specific like `Ng2Walker`?  Could also be three additional methods - `visitClassDecorator`, `visitMethodDecorator` and `visitPropertyDecorator`.

**Comment by adidahiya** [comment]
I don't think this issue is relevant anymore given our latest guidelines for [writing rule walkers](https://palantir.github.io/tslint/develop/custom-rules/walker-design.html).
