### ISSUE TITLE
Ignore tslint:disable comments in comment-format/check-uppercase rule

### ISSUE THREAD

**Issue by glen-84** [palantir/tslint#1417]
### Bug Report

- __TSLint version__: `3.10.2`
- __TypeScript version__: `1.8.10`
- __Running TSLint via__: `VS Code`

#### TypeScript code being linted

```ts
// tslint:disable-next-line:no-unused-expression
```

with `tslint.json` configuration:

```json
(not relevant)
```

#### Actual behavior

`comment must start with uppercase letter`

#### Expected behavior

Not expected, but it would be nice if this was ignored as an exception to the comment rule.

A multi-line comment can be used instead, but it's not ideal.

**Comment by adidahiya** [comment]
agreed, this exception would be nice to have

**Comment by apacala** [comment]
I've just run into this issue, so :+1:.
