### ISSUE TITLE
Error: Unsupported TypeScript version: 2.0.0

### ISSUE THREAD

**Issue by evusik** [palantir/tslint#1428]
Hi,

I'm getting the `Error: Unsupported TypeScript version: 2.0.0` using 
`typescript@2.0.0 node_modules\typescript`
`tslint@3.13.0 node_modules\tslint`

Should TS 2.0 be supported in tslint 3.13.0? If yes, do you have any pointers what might be wrong?

The command I execute is
`tslint --format json --config ./tslint.json --out TsLint_out.json './checkout/**/*.ts'`

Thanks

**Comment by JKillian** [comment]
Hi @evusik, are you using custom rules while running TSLint? This sounds like a bug in an external rule implementation.

**Comment by evusik** [comment]
I'm using tslint-microsoft-contrib.

I will check with the owners there, thanks!

**Comment by JKillian** [comment]
Yep, sounds like the issue would be with them! Just as a side note, it's recommended to use `tslint@next` when working with TS 2.0, although TSLint 3.13.0 will likely work well enough in most cases as well.
