### ISSUE TITLE
Discussion : Should some files be ignored by default in IDE integration

### ISSUE THREAD

**Issue by basarat** [palantir/tslint#1434]
With `tslint.json` configuration:

```json
{
  "extends": "tslint:latest" 
}
```

Would you expect linting to be run on `.d.ts` files?  

e.g. `node_modules/tslint/lint.d.ts` has one error. 

I am linting all the files in the compilation context and *compilation context* contains these `node_modules` files and sometimes even `.ts` files and curious if I should switch off linting on these files.

## Back story

I am integrating tslint into [alm](http://alm.tools/) : https://github.com/alm-tools/alm/issues/155 and its error analysis https://basarat.gitbooks.io/alm/content/features/errors.html so you always get active full project linting :rose:

**Comment by adidahiya** [comment]
> Would you expect linting to be run on .d.ts files?

No, we generally don't expect the linter to be run on typings files. If community-generated typings files were ever linted, that should probably be done in the DefinitelyTyped build.

Related discussion: #73, #847

**Comment by basarat** [comment]
@adidahiya thanks for those links! Those were exactly the kind of discussions I was looking for. https://github.com/palantir/tslint/issues/73 seems to track the idea better and I will move further discussion there :rose:
