### ISSUE TITLE
Add docs for only-arrow-functions rule

### ISSUE THREAD

**Issue by glen-84** [palantir/tslint#1448]
I couldn't find them [here](http://palantir.github.io/tslint/rules/).

**Comment by JoshuaKGoldberg** [comment]
I can send a PR for this within a day or two.

**Comment by JKillian** [comment]
Updated the docs site with all the latest metadata from the `3.14.0` release! This rule should now have docs: http://palantir.github.io/tslint/rules/only-arrow-functions/
