### ISSUE TITLE
Add docs for typedef rule (option: arrow-call-signature)

### ISSUE THREAD

**Issue by glen-84** [palantir/tslint#1451]
I couldn't find them [here](http://palantir.github.io/tslint/rules/typedef/).

**Comment by JKillian** [comment]
Looks like [the rule's metadata is out of date](https://github.com/palantir/tslint/blob/fc9a72d6d3d36da056fe3d4bbfdbf3769e840f81/src/rules/typedefRule.ts#L24) so a PR to fix that from anyone would be great!
