### ISSUE TITLE
Problem extending from eshint (eslint-config-hapi)

### ISSUE THREAD

**Issue by mmc41** [palantir/tslint#1470]
I want to use hapijs eshint rules in a typescript project. The hapijs esrules are made available by the eslint-config-hapi npm module. Unfortunately, I can't extend from the eslint rules.

### Bug Report

- __TSLint version__: `3.14.0`
- __TypeScript version__: `1.8.10`
- __Running TSLint via__:  Cli (rpm)

#### tslint.json

{
"extends": "eslint-config-hapi",
"rules": {
"no-constant-condition": true
}
}

#### Actual behavior

Unfortunately, I get this error when ruinng eslint (after installing the eslint-config-hapi module):

Error:
Could not find implementations for the following rules specified in the configuration:
camelcase
consistent-return
vars-on-top
new-cap
no-constant-condition
no-native-reassign
no-underscore-dangle
no-undef
no-process-exit
no-unused-expressions
no-regex-spaces
no-catch-shadow
no-lonely-if
brace-style
no-shadow
no-unused-vars
one-var
handle-callback-err
hapi/hapi-capitalize-modules
hapi/hapi-for-you
hapi/hapi-scope-start
array-bracket-spacing
dot-notation
eol-last
no-trailing-spaces
no-eq-null
no-extend-native
no-redeclare
no-loop-func
yoda
sort-vars
arrow-spacing
hapi/no-arrowception
quotes
consistent-this
no-array-constructor
no-confusing-arrow
no-new-object
no-spaced-func
no-mixed-spaces-and-tabs
keyword-spacing
semi
semi-spacing
space-infix-ops
space-unary-ops
strict
eqeqeq
no-else-return
no-return-assign
no-new-wrappers
comma-dangle
no-sparse-arrays
no-ex-assign
no-var
prefer-arrow-callback
prefer-const
space-before-function-paren
func-style
object-curly-spacing
Try upgrading TSLint and/or ensuring that you have all necessary custom rules installed.
If TSLint was recently upgraded, you may have old rules configured which need to be cleaned up.

at Object.loadRules (/usr/local/lib/node_modules/tslint/lib/ruleLoader.js:29:15)
at Linter.lint (/usr/local/lib/node_modules/tslint/lib/tslint.js:56:44)
at processFile (/usr/local/lib/node_modules/tslint/lib/tslint-cli.js:138:29)
at /usr/local/lib/node_modules/tslint/lib/tslint-cli.js:177:74
at Array.forEach (native)
at Object.<anonymous> (/usr/local/lib/node_modules/tslint/lib/tslint-cli.js:177:41)
at Module._compile (module.js:541:32)
at Object.Module._extensions..js (module.js:550:10)
at Module.load (module.js:458:32)
at tryModuleLoad (module.js:417:12)

#### Expected behavior

I expected the eshint rules to work.

**Comment by mrmlnc** [comment]
These are two different projects. Both projects have a different API that is not compatible.

**Comment by adidahiya** [comment]
yeah, basically what @mrmlnc said. eslint rules are not compatible out-of-the-box with tslint -- the AST APIs are completely different.

**Comment by mmc41** [comment]
Thanks for the explaination. I tried tslint-eslint-rules also but it did not make a difference (same errors messages). Do any of you know of any other way - f.x. a tool to convert rules from eslint to tslint? 

P.S. I did notice a very recent eslint tweet of upcomming typescript support. That might be a way also?

**Comment by JKillian** [comment]
Unfortunately, there's no way to convert between the two. You could give the eslint-typescript thing a try, although I don't know how well it works at the moment.
