### ISSUE TITLE
@next older as @latest

### ISSUE THREAD

**Issue by donaldpipowitch** [palantir/tslint#1474]
`@next` is tslint@3.14.0-dev.1. `@latest` is tslint@3.14.0. So if you use `"tslint": "^3.14.0-dev.1"`, because you want typescript@next support, you'll get tslint@3.14.0 on `npm i` which doesn't support typescript@next. If you use tools like `npm-check` they will tell you that tslint@3.14.0 is newer than tslint@3.14.0-dev.1.

The only way to have correct typescript@next support is to use `"tslint": "3.14.0-dev.1"` with a fixed version.

**Comment by JKillian** [comment]
Hi @donaldpipowitch, see https://github.com/palantir/tslint/issues/815#issuecomment-238632524 for some ongoing discussion on this issue. I'm not sure which thread is a better location for the discussion, but as we have more content in the other one already, I'm just going to close this and let discussion continue over there
