### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by danvk** [palantir/tslint#1485]
On http://palantir.github.io/tslint/rules/whitespace/ the schema is listed as:

```json
{
  "type": "array",
  "items": {
    "type": "string",
    "enum": [
      "check-branch",
      "check-decl",
      "check-operator",
      "check-module",
      "check-seperator",
      "check-type",
      "check-typecast"
    ]
  },
  "minLength": 0,
  "maxLength": 7
}
```

It should be `check-separator` (`a` not `e`).

**Comment by adidahiya** [comment]
this has been fixed in the latest source code, but the docs site hasn't been updated. https://github.com/palantir/tslint/blob/81890b61d8c4a246e2c3d141f93f449d8e4fa221/src/rules/whitespaceRule.ts#L43
