### ISSUE TITLE
Change applicability order of "extends" array

### ISSUE THREAD

**Issue by DethAriel** [palantir/tslint#1503]
### Enhancement Request
- **TSLint version**: `3.14.0`
- **TypeScript version**: `1.8.10`
- **Running TSLint via**: CLI

`"extends"` config parameter supports an _array_ of "base" configurations to be passed. The current behavior of applying base configurations could be more intuitive. Right now the layout is like this:

``` json
{
  "extends": [
    "./base-rules-overrides.json",
    "./base-rules.json"
  ],
  "rules": {
    "override the overrides": ""
  }
}
```

Whereas the proposition is to reverse the order in which "extensions" are applied:

``` json
{
  "extends": [
    "./base-rules.json",
    "./base-rules-overrides.json"
  ],
  "rules": {
    "override the overrides": ""
  }
}
```

See #1487 for more context.

**Comment by JKillian** [comment]
I think I'm okay with this change - my guess is that most people aren't extending multiple configurations, and even if they are, they're non-overlapping configs.

**Comment by adidahiya** [comment]
PR is up for this, check out #1622
