### ISSUE TITLE
Update tslint:latest configuration for 3.15 release

### ISSUE THREAD

**Issue by adidahiya** [palantir/tslint#1506]
let's add

- `adjacent-overload-signatures`
- `object-literal-shorthand`
- `only-arrow-functions` with `allow-declarations` option enabled
- `ordered-imports` with `"import-sources-order": "case-insensitive"` option
- `arrow-parens`

**Comment by JKillian** [comment]
I'm not sure I think that `arrow-parens` provides enough intrinsic value to add. Some won't like the extra keystrokes tradeoff for a little bit of visual contrast.

The other four I'm 👍 with

**Comment by adidahiya** [comment]
found some more:

- `no-for-in-array`
- `object-literal-key-quotes` with `"as-needed"` option

**Comment by JKillian** [comment]
Not the first, `no-for-in-array` requires typechecking. (Need to update the docs to show which rules need typechecking). The other seems good to me
