### ISSUE TITLE
"allow-named-functions" option for "only-arrow-functions" rule

### ISSUE THREAD

**Issue by adidahiya** [palantir/tslint#1509]
I'd like to allow syntax like this with the `only-arrow-functions` rule:

``` ts
xmlhttp.onreadystatechange = function handleReadyStateChange() { ... };
```

In this case I made an intentional decision to name the function and I want to use the `function` syntax.

**Comment by glen-84** [comment]
Might want to keep [this](https://github.com/palantir/tslint/issues/1449#issuecomment-236786283) in mind.

`handleReadyStateChange` can't be called directly after that, can it?

**Comment by adidahiya** [comment]
yep, that's true, it can't be referenced directly anywhere else. I think the only benefit here is better stack traces. also I prefer this syntax for opting out of the tslint rule instead of the more verbose:

```ts
function handleReadyStateChange() {
    ...
}

xmlhttp.onreadystatechange = handleReadyStateChange;
```
