### ISSUE TITLE
[Suggestion]`only-arrow-functions` allow `no arrow function` when the 1st parameter is `this`

### ISSUE THREAD

**Issue by plantain-00** [palantir/tslint#1513]
#### TypeScript code being linted

``` ts
$(document).on("click", "a[href^='http']", function (this: HTMLAnchorElement, e: JQueryEventObject) {
    e.preventDefault();
    electron.shell.openExternal(this.href);
});
```

For this situation, I hope this function is allowed when the first parameter is `this`, and otherwise, I hope only arrow function is allowed.

**Comment by adidahiya** [comment]
@plantain-00 @andy-hanson can you explain this a bit more? Does an arrow function not work here? Why is a standard function declaration preferred?

**Comment by plantain-00** [comment]
@adidahiya 
yes, arrow function not work when the first parameter is `this`, eg: http://www.typescriptlang.org/play/index.html#src=const%20foo%20%3D%20function%20(this%3Aany)%20%7B%20%7D%3B%0D%0Aconst%20bar%20%3D%20(this%3Aany)%20%3D%3E%20%7B%20%7D%3B

**Comment by adidahiya** [comment]
@plantain-00 cool, makes sense, thanks.
