### ISSUE TITLE
Add JSX spread attribute case statement to SyntaxWalker?

### ISSUE THREAD

**Issue by bolatovumar** [palantir/tslint#1514]
[SyntaxWalker](https://github.com/palantir/tslint/blob/master/src/language/walker/syntaxWalker.ts) has no case statement for ts.SyntaxKind.JsxSpreadAttribute. Is there a reason it's missing?

I'm trying to write a jsx-curly-spacing rule for [TSLint React](https://github.com/palantir/tslint-react) but I can't target spread attributes unfortunately.

**Comment by JKillian** [comment]
👍 In the meantime, just override `visitNode` and check if the `node.kind` is the kind you're looking for

**Comment by adidahiya** [comment]
@bolatovumar generally we take PRs for additions to SyntaxWalker like that as they come up instead of trying to enumerate them all at once -- feel free to send a PR for an additional visitor method with its associated rationale any time
