### ISSUE TITLE
Lint passed file content not working

### ISSUE THREAD

**Issue by beckend** [palantir/tslint#1535]
### Bug Report
- **TSLint version**: `3.15.1`
- **TypeScript version**: `2.0.0`
- **Running TSLint via**: Node.js API
#### Actual behavior

Does not pass source content to the linter when using a program.
[https://github.com/palantir/tslint/blob/master/src/tslint.ts#L85](https://github.com/palantir/tslint/blob/master/src/tslint.ts#L85)
#### Expected behavior

Does pass content in constructor into linter, with or without program.
Will lint based on the source content as first priority as opposed to file read.
#### Notes

I am hacking a linter for `atom-editor`. But the linter only works when you actually save the file, and I am passing a program into the linter, seeing as the source(content) is never actually passed into the program and only reads from the file.

**Comment by adidahiya** [comment]
@beckend have you looked into https://github.com/AtomLinter/linter-tslint?

**Comment by beckend** [comment]
Yes, it's at a broken state with latest tslint. Thus I'm doing something on my own.

**Comment by JoshuaKGoldberg** [comment]
Looks like the code has been refactored quite a bit since this issue. Closing for housekeeping. @beckend if this is still an issue, please do comment here with more details!
