### ISSUE TITLE
Warn enums with possible 0 values used in logical operations

### ISSUE THREAD

**Issue by radykov** [palantir/tslint#1555]
I would like a rule that warns against enums with possible 0 values being used in logical operations. 

This is mainly an issue for enums with default values, as typescript (1.8.10) will give the first enum a default value of `0`. People might not realise that their enums as being treated the same as `0` in logical operations.

A problem with this is that assume you have
`enum MyEnum { A, B, C}`
`myObj.enumValue = MyEnum.A;`

Later on you perform the following, it's common to assume the if statement evaluates to `true`.
`if (myObj.enumValue)`

However`myObj.enumValue` evaluates to `MyEnum.A` which evaluates to `0`. `if(0)` is false.

While some people will be expecting this behaviour, my assumption is it might cause more problems than not.

**Comment by adidahiya** [comment]
looks like this is a related but more specific pattern than https://github.com/palantir/tslint/issues/253; maybe it would be incorporated as an option into that rule

**Comment by adidahiya** [comment]
strict-boolean-expressions should handle this.
