### ISSUE TITLE
TSLint errors when checking async fat arrow functions because of missing parentheses

### ISSUE THREAD

**Issue by markfejes** [palantir/tslint#1572]
### Bug Report
- **TSLint version**: `3.15.0-dev.0`
- **TypeScript version**: `2.1.0-dev.20160923`
- **Running TSLint via**: CLI
#### TypeScript code being linted

``` ts
private attachEventListeners ()
    {
        $("table#testTrackFilterSync td.autoSync").on ("contextmenu", async (event) =>
        {
            // some code..
        });
    }
```

with `tslint.json` configuration:

``` json

{
 "rules" :   {
        "member-access" : true
        , "no-inferrable-types": true
        , "ban": 
            [
                true
                , 
                [
                    "console", "functionTrace"
                ]
            ]
        , "curly" : true
        , "no-console" : [true, "debug"]
        , "no-empty"   : true
        , "no-eval"    : true
        , "no-unreachable": true
        , "eofline": true
        , "indent": [true, "spaces"]
        , "no-trailing-whitespace": true

        , "align": [true, "parameters", "statements", "arguments"]
        , "arrow-parens": true
        , "class-name" : true
        , "new-parens" : true
        , "no-consecutive-blank-lines": true
        , "one-line": [false, "check-catch", "check-finally", "check-else", "check-whitespace", "check-open-brace"]
        , "quotemark": [true, "double"]
        , "semicolon": [true, "always"]
        , "variable-name": [true, "ban-keywords", "check-format", "allow-leading-underscore"]
        , "whitespace": [true, "check-branch", "check-operator", "check-typecast", "check-decl", "check-type"]

    }
}
```
#### Actual behavior

TSlint gives me an error that I should write parentheses around the parameters
Without the async modifier it works fine.
#### Expected behavior

No error should be given

**Comment by IllusionMH** [comment]
Looks like TS 2.1.0-dev.x has `async` keyword as first token (`node.getFirstToken()`) for arrow function nodes instead of flag (`node.flags`).

Not sure if this is regression or new behavior.

**Comment by Deathspike** [comment]
This also happens, sometimes, with `2.0.3` TS. I have files where `async (param: type) =>` is fine, and files where it is not.

**Comment by tp** [comment]
Still experiencing this with TSLint 4.0.3

**Comment by adidahiya** [comment]
@tp do you mean 4.0.2? or 4.0.0-dev.3? https://github.com/palantir/tslint/releases

**Comment by charsleysa** [comment]
@adidahiya experiencing this with TSLint 4.0.2 and Typescript 2.1.1

**Comment by tp** [comment]
@adidahiya 4.0.0-dev.3 - sorry for the confusion.
