### ISSUE TITLE
Centralized rules lo cation to share among projects

### ISSUE THREAD

**Issue by bootrider** [palantir/tslint#1573]
### Bug Report
- **TSLint version**: `3.15.0`
- **TypeScript version**: `2.0.2`
- **Running TSLint via**:  CLI 
#### Actual behavior

In a Typescript project is expected to check the code using TSLint.

TSlint has some rules, but there is other initiatives that extends the rules, like tslint-microsoft-contrib and codelyzer.

I want to centralize the rules in a single location.

My first approach was to move the code of the rules to one same folder, then TSLint start to throw exceptions about not able to load modules
#### Expected behavior

TSLint works

**Comment by johnwiseheart** [comment]
This is pretty old so I'm going to close it out. I think the web is the best source of truth for which rules exist and what their functionality is, so putting all rules in one folder is not recommended.
