### ISSUE TITLE
Cyclomatic complexity rule not present at 3.15.1

### ISSUE THREAD

**Issue by bootrider** [palantir/tslint#1577]
### Bug Report

- __TSLint version__: `3.15.1`
- __Running TSLint via__: CLI

#### Actual behavior

Trying to implement the cyclomatic complexity rule in a project, I got an error that the rule is not present. I look for it in the node modules\tslint\lib\rules . The rule is not present. proceed to install again TSlint with npm using the command `npm install tslint@latest --save-dev` , the rule still not present. 

#### Expected behavior
the rule present in the folder node modules\tslint\lib\rules 
(fill this out)

**Comment by adidahiya** [comment]
We haven't made a release that includes this rule yet. You can see which release(s) a commit is included in on Github: https://github.com/palantir/tslint/commit/bfe06b25ce4e9f5cea95cecccf1021e5f2198765
