### ISSUE TITLE
Consistent property order in 'member-ordering' rule

### ISSUE THREAD

**Issue by roman-petrov** [palantir/tslint#1582]
Hello! I am not sure, if it possible to control property order (get/set accessors) via '**member-ordering**' rule. In tslint documentation I see that it is possible to control order of fields (instance variables) and methods. So it is possible to take control over property order using tslint?

Many thanks.

**Comment by lijunle** [comment]
It looks like this is an issue one year ago. Do something take a look into this?

**Comment by EternalPhane** [comment]
Any progress on this?

**Comment by JoshuaKGoldberg** [comment]
#3965, though newer, has a lot of discussion. Closing this issue in favor of it; sorry @roman-petrov! 😉
