### ISSUE TITLE
rule similar to one-line for promise methods

### ISSUE THREAD

**Issue by rcollette** [palantir/tslint#1586]
I really prefer to see promise methods structured similar to try/catch/finally blocks like

```
something()
   .then(() => {
   })
   .catch((e) => {
   })
   .finally(() => {
   });
```

I don't believe there is currently a rule that handles this.

**Comment by JoshuaKGoldberg** [comment]
This seems like a subset of `newline-per-chained-call`. `async`/`await` is also a bit cleaner. Closing as already fixed.
