### ISSUE TITLE
Issue when consuming the tslint API from a TypeScript client

### ISSUE THREAD

**Issue by egamma** [palantir/tslint#1592]
### Bug Report

- __TSLint version__: `3.15.1`
- __TypeScript version__: `2.0.3`

The Visual Studio Code `vscode-tslint` extension is implemented in TypeScript and it consumes the tslint API from TypeScript. The issue is that not all the required types are exported from [tslint.ts](https://github.com/palantir/tslint/blob/master/src/tslint.ts). 

vscode-tslint has tslint as a npm development dependency. 

tslint defines 
```json
  "typescript": {
    "definition": "lib/tslint.d.ts"
  },
```

The corresponding `tslint.d.ts` doesn't export required types so that the module can be used in a typed way from TypeScript:

```ts
import * as ts from "typescript";
import { findConfiguration, findConfigurationPath, getRulesDirectories, loadConfigurationFromPath } from "./configuration";
import { ILinterOptionsRaw, LintResult } from "./lint";
declare class Linter {
    private fileName;
    private source;
    private program;
    static VERSION: string;
    static findConfiguration: typeof findConfiguration;
    static findConfigurationPath: typeof findConfigurationPath;
    static getRulesDirectories: typeof getRulesDirectories;
    static loadConfigurationFromPath: typeof loadConfigurationFromPath;
    private options;
    static createProgram(configFile: string, projectDirectory?: string): ts.Program;
    static getFileNames(program: ts.Program): string[];
    constructor(fileName: string, source: string, options: ILinterOptionsRaw, program?: ts.Program);
    lint(): LintResult;
    private containsRule(rules, rule);
    private computeFullOptions(options?);
}
declare namespace Linter {
}
export = Linter;
```

Notice that the type `LintResult` is not exported as a separate type.

In the following code it is not possible (or I don't know how) to type a variable with the type LintResult.

```ts
import linter from 'tslint';
...
let result: linter.LintResult;  // ERROR module linter has no exported member LintResult
```

Therefore `tslint.ts` should re-export the type `LintResult` and `ILinterOptionsRaw`.

**Comment by adidahiya** [comment]
If you are consuming the API to do anything more complex than running the basic linter (like writing custom rules, etc.), we suggest importing the module `"tslint/lib/lint"` -- https://github.com/palantir/tslint#writing-custom-rules.

Perhaps we should remove the `"typescript"` block from package.json? I don't think it's very useful given that all our consumers probably use node-style TS module resolution.

**Comment by egamma** [comment]
@adidahiya importing the module 'tslint/lib/lint' works for my scenario. The vscode-tslint extension only runs the basic linter, so I was assuming that the `tslint.d.ts` typings are sufficient, but they are not. 

Why do you need both a `lib/tslint.d.ts` and a `lib/lint.d.ts`? If there would be only a single .dt.s file, then I wouldn't have picked the wrong one 😄

**Comment by adidahiya** [comment]
@egamma yeah, that's fair, I think a single .d.ts file is the way to go. We will consider including this breaking change in the v4.0 release.

**Comment by adidahiya** [comment]
closing in favor of #1595
