### ISSUE TITLE
UNMET PEER DEPENDENCY for typescript

### ISSUE THREAD

**Issue by SwintDC** [palantir/tslint#1594]
### Bug Report
- **TSLint version**: `3.15.1`
- **TypeScript version**: `2.0.3`
- **Running TSLint via**: gulp-tslint

The tslint package requires typescript 1.8.10 and another package (gulp-typescript) requires typescript version 2 or higher.

This causes the error 
`-- UNMET PEER DEPENDENCY typescript@1.8.10
when executing **npm update**.

Is it possible to update to make the version of typescript required less specific or to make it compatible with typescript 2 or higher ?

**Comment by adidahiya** [comment]
The peer dependency is already pretty permissive. It allows version `>=1.7.3`.

**Comment by SwintDC** [comment]
The problem isn't the peer dependencies setting of **tslint**, it is the peer dependencies setting of **gulp-typescript** and the fact that **gulp-typescript** is more up-to-date with typescript.

The following comes from the package.json from **gulp-typescript**
`"peerDependencies": {
    "typescript": "~2.0.3 || >=2.0.0-dev || >=2.1.0-dev"
  },`
If i understand correctly that is.

I guess the problem would be solved if tslint would be updated to the latest version of typescript ? Probably i could make use of tslint@next ?

**Comment by bensontrent** [comment]
Thanks SwintDC, This issue was solved for me by running `npm install tslint@next -g`
