### ISSUE TITLE
Simplify typings for API consumers

### ISSUE THREAD

**Issue by adidahiya** [palantir/tslint#1595]
right now we have both `lib/tslint.d.ts` and `lib/lint.d.ts`. let's try to consolidate them into one file.

via #1592

**Comment by egamma** [comment]
When you are at it, please also review how `package.json` exposes the typings.

**Comment by JKillian** [comment]
We should also export `MultiLinter` [here](https://github.com/palantir/tslint/blob/master/src/lint.ts#L37) and recommend that 3rd party libraries use it (as it gives appropriate results from formatters).

For now though, we should keep `Linter` exported to make it an easier transition for 3rd party tools. As of TSLint 5.0 it may be appropriate to drop `Linter` all together.
