### ISSUE TITLE
Support yaml configuration

### ISSUE THREAD

**Issue by remcohaszing** [palantir/tslint#1598]
It would be nice if the configuration file could be written in yaml format instead of json.

**why?** Unlike json, yaml supports comments.

**why?** Both [eslint](http://eslint.org) and [stylelint](http://stylelint.io) support this. It's nice if linters support similar configuration files.

**Comment by adidahiya** [comment]
yeah, that'd be nice. stylelint uses cosmiconfig, which I'm tracking as an enhancement here #1071. accepting PRs :)

**Comment by JKillian** [comment]
@remcohaszing We actually support comments in our configuration JSON files :) Yes, technically outside of the standard, but it's useful!

**Comment by remcohaszing** [comment]
JSON comments help a lot! :smile: However, I'd still prefer yaml support. :wink:

**Comment by foisonocean** [comment]
+1

**Comment by ajafff** [comment]
Fixed by #3433
