### ISSUE TITLE
Optionally disable `named-imports-order` check of `ordered-imports` rule

### ISSUE THREAD

**Issue by janslow** [palantir/tslint#1600]
It would be useful if the `named-imports-order` check could be disabled, so that only the import sources order is checked.

Either by allowing `named-imports-order` to be set to `true` or to `"any"` (or similar.

I'm happy to create a PR request for this if it seems seems sensible.

**Comment by adidahiya** [comment]
yeah, makes sense. would accept a PR that allows you to opt-out of that part of the rule. `"named-imports-order": "any"` sounds good
