### ISSUE TITLE
File list is ignored when using `--type-check` in CLI

### ISSUE THREAD

**Issue by janslow** [palantir/tslint#1603]
### Bug Report
- **TSLint version**: `3.15.1`
- **TypeScript version**: `2.0.3`
- **Running TSLint via**: CLI
#### TypeScript code being linted
1. Create file `src/foo.ts` and `src/bar.ts` and create a `tsconfig.json` which compiles `src/`.
2. Creating a lint issue in both files (e.g., set `semicolon` rule to `always` then omit a semicolon, but this can be any lint issue).
#### Actual behavior
1. Run `tslint --project tsconfig.json src/foo.ts`
   - As expected, it will only show issue in `src/foo.ts`
2. Run `tslint --project tsconfig.json --type-check src/foo.ts`
   - It will show issues from in files.
#### Expected behavior

`tslint` should only show issues in `src/foo.ts`, if that is what is specified

**Comment by janslow** [comment]
It appears from [tslint-cli.ts](https://github.com/palantir/tslint/blob/master/src/tslint-cli.ts#L277) that the `files` argument is ignored when `--type-check` is provided.

Based on the current code, I'd like to see a message saying that the `files` input is being ignored, or (ideally) it filters the TypeScript program input to inspect the specified files.

**Comment by janslow** [comment]
I suspect this can be fixed by filtering `parsed.fileNames` from [MultiLinter#createProgram](https://github.com/palantir/tslint/blob/d6513bae6af4b5c706f89d1d47b6c85fbed7beda/src/tslintMulti.ts#L71) to only include the specified files, if any are specified

**Comment by janslow** [comment]
Alternatively [`ts.getPreEmitDiagnostics()`](https://github.com/Microsoft/TypeScript/blob/master/lib/typescript.d.ts#L1965) accepts an optional SourceFile parameter, which will keep the complexity limited to `tslint-cli`

**Comment by andy-ms** [comment]
This issue is important because `--type-check` requires `--project` to be set. I would like to be able to specify files to lint even while using type-checked lint rules.
I also noticed that `--project` seems to exclude `.d.ts` files from linting.

**Comment by Orodan** [comment]
+1
I have to use --type-check --project for some rules. This causes my file options to be ignored, therefore my node_modules folder is being parsed. At the very least, indicate that the file option is ignored when using --type-check. This behavior is very annoying.

**Comment by ajafff** [comment]
Recent versions of tslint no longer ignore the specified files and excludes when using `--project --type-check`. Only errors from type checking are not filtered, because the whole project need to be checked at once.

Since `--type-check` is no longer necessary to use rule that require type information, I think this issue can be closed.
