### ISSUE TITLE
Not able to apply custom rule

### ISSUE THREAD

**Issue by yogesh-yadav** [palantir/tslint#1607]
I have created a custom rule and provided custom rule directory path to "rulesDirectory".

But after running the TsLint, I am not able to get the custom rule message.

Please suggest if am missing any other configuration to get custom rule.

**Comment by adidahiya** [comment]
Please provide more info: what does your custom rule look like, what exactly are you providing to `rulesDirectory`, etc.

**Comment by yogesh-yadav** [comment]
Hi, 

Many thanks for the prompt reply. 

I have added a custom rule noImportsRule.ts in CustRules directory of my project  and provided the path of CustRules to rulesDirectory in tslint.json. But after running the TsLint, I am not able to get the custom rule message.

Please find below code for your review.

**noImportsRule.ts:**
----------------------------------------------------------------------------------------------------------------
import * as ts from "node_modules/typescript/lib/typescript";
import * as Lint from "node_modules/tslint/lib/lint";

export class Rule extends Lint.Rules.AbstractRule {

    public static FAILURE_STRING = "import statement forbidden";

    public apply(sourceFile: ts.SourceFile): Lint.RuleFailure[] {
        return this.applyWithWalker(new NoImportsWalker(sourceFile, this.getOptions()));
    }
}

// The walker takes care of all the work.
class NoImportsWalker extends Lint.RuleWalker {
    public visitImportDeclaration(node: ts.ImportDeclaration) {
        // create a failure at the current position
        this.addFailure(this.createFailure(node.getStart(), node.getWidth(), Rule.FAILURE_STRING));

        // call the base version of this visitor to actually parse this node
        super.visitImportDeclaration(node);
    }
}
----------------------------------------------------------------------------------------------------------------
**TsLint.Json file:**

----------------------------------------------------------------------------------------------------------------
{
  "extends": "tslint:latest",
  "rulesDirectory": [ "WebApplication/CustRules" ],
  "rules": {
    "ban": [
      true,
      [ "_", "extend" ],
      [ "_", "isNull" ],
      [ "_", "isDefined" ]
    ],
    "class-name": true,
    "comment-format": [
      true,
      "check-space",
      "check-lowercase"
    ],
    "no-imports": true
    
  }
}
----------------------------------------------------------------------------------------------------------------
Thanks & Regards,
Yogesh Yadav

**Comment by olore** [comment]
@yogesh-yadav After trying to recreate this locally, I believe the problem is that you have `no-imports` (with an `s`) in your tslint.json, but your file name is `noImportRule.ts` (with no `s`).
