### ISSUE TITLE
Export interface declarations for public objects

### ISSUE THREAD

**Issue by demurgos** [palantir/tslint#1609]
Hi,
The TSlint module is currently exporting some functions, but keeps all of its interfaces private: they are not available from the generated `index.d.ts`.

This prevents tools coded in TS and depending on the Node API of `tslint` to benefit from the typings provided by tslint.

Here is an example of code that currently does not work because `IConfiguration` (from `configuration.ts`) is kept private:

```typescript
import {findConfiguration, IConfigurationFile} from "tslint";

function getConfig(): IConfigurationFile { # Impossible to type return type
  let config: IConfigurationFile; # Impossible to type variable type

  if (target === "...") {
    config = findConfiguration(..., ...);
  } else {
    config = findConfiguration(..., ...);
  }
  return config;
}
```

Would it be possible to export all the interfaces of publicly available objects ?

### Bug Report

- __TSLint version__: `3.15.1`
- __TypeScript version__: `2.1.0-dev.20161007`
- __Running TSLint via__: Node.js API

**Comment by adidahiya** [comment]
We expose a lot more types & values from the module `"tslint/lib/lint"`. This is a little unintuitive, however, so we plan to simplify this and export more from index.d.ts. See https://github.com/palantir/tslint/issues/1595

**Comment by demurgos** [comment]
Thank you for your quick answer.

Do you mean that there would be multiple entry points for the library ? (`import ... from "tslint"` for the main functions and `import ... from "tslint/lib/lint"` for extra content)

I understand that the ES6 import syntax makes it easier to provide multiple entry points for the same package, but as you said, it's not that intuitive (and seems harder to maintain since people can grab any module ?).

**Comment by adidahiya** [comment]
Yes, that's right, you can import any of the files in the package as a module (this is a CommonJS feature, not just ES6 modules). There are references to the "tslint/lib/lint" module in the README (see the custom rules section).

**Comment by demurgos** [comment]
Ok, thank you again for taking time to help me.

(And I appreciate that you are already working on simplifying this)
