### ISSUE TITLE
readonly variables

### ISSUE THREAD

**Issue by TimBo93** [palantir/tslint#1628]
What do you think about a rule, which checks whether a variable can be made read-only?
Read-Only is a TypeScript 2 Feature. The rule could maybe determined by checking whether a field is assigned only inside the constructor or the field will be initialized at the same place like the declaration.

**Comment by adidahiya** [comment]
yeah, this could be pretty cool; it's similar in spirit to the `prefer-const` rule (https://github.com/palantir/tslint/issues/491)

**Comment by dyst5422** [comment]
Perhaps an extension of this would be a `functional-programming-only` rule that ensures all function inputs are marked with the `Readonly<T>` annotation

**Comment by dyst5422** [comment]
Just found https://www.npmjs.com/package/tslint-immutable - Super!

**Comment by dyst5422** [comment]
Scratch that, definitely does not check function inputs. Will put an issue on that project though as it seems more tuned to this type of rule.

**Comment by akosyakov** [comment]
It should be configurable for access modifiers. `public` and `protected` properties could be assigned outside of the current class context.

**Comment by adidahiya** [comment]
Fixed by #2896
