### ISSUE TITLE
npm run test:bin fails on Windows platform

### ISSUE THREAD

**Issue by IllusionMH** [palantir/tslint#1635]
### Bug Report
- **TSLint version**: `4.0.0-dev`
- **TypeScript version**: `2.0.3`
- **Running TSLint via**: CLI
- **OS**: Windows 10

`npm run test:bin` fails on Windows (even in Git Bash).
#### Actual behavior

```
$ npm run test:bin

> tslint@4.0.0-dev test:bin D:\web\projects\tslint
> ./test/check-bin.sh &> /dev/null

The syntax of the command is incorrect.

npm ERR! Windows_NT 10.0.14946
npm ERR! argv "C:\\Program Files (x86)\\Nodist\\v\\nodev6.5.0\\node.exe" "C:\\Program Files (x86)\\Nodist\\bin\\node_modules\\npm\\cli.js" "run" "test:bin"
npm ERR! node v6.5.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! tslint@4.0.0-dev test:bin: `./test/check-bin.sh &> /dev/null`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tslint@4.0.0-dev test:bin script './test/check-bin.sh &> /dev/null'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tslint package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./test/check-bin.sh &> /dev/null
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tslint
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tslint
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\web\projects\tslint\npm-debug.log
```

If I remove `&> /dev/null` from this script it still fails, but with another error

```
$ npm run test:bin

> tslint@4.0.0-dev test:bin D:\web\projects\tslint
> ./test/check-bin.sh

'.' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.14946
npm ERR! argv "C:\\Program Files (x86)\\Nodist\\v\\nodev6.5.0\\node.exe" "C:\\Program Files (x86)\\Nodist\\bin\\node_modules\\npm\\cli.js" "run" "test:bin"
npm ERR! node v6.5.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! tslint@4.0.0-dev test:bin: `./test/check-bin.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tslint@4.0.0-dev test:bin script './test/check-bin.sh'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tslint package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./test/check-bin.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tslint
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tslint
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\web\projects\tslint\npm-debug.log
```
#### Expected behavior

Platform dependent scripts should be run only for targeted platforms. (e.g. with JS wrapper that will spawn child process for `test/check-bin.sh` only in *nix platforms).

As temporary I use next npm scripts in package.json

```
    "test:win": "npm-run-all test:pre -p test:mocha test:rules",
    "verify:win": "npm-run-all clean compile lint test:win docs"
```

**Comment by IllusionMH** [comment]
@adidahiya I see that there is no label, but will you accept PR for this issue?

I was curious if there is simple way to write tests for executable files (in context of npm) in Node.js which will allow use same tests for all platforms.

Experiment results: [Repo](https://github.com/IllusionMH/cli-bin-test) - [AppVeyor](https://ci.appveyor.com/project/IllusionMH/cli-bin-test) - [Travis CI](https://travis-ci.org/IllusionMH/cli-bin-test)

This reduced case shows that it is fair simply to implement test for all platforms. The only platform specific tuning is explicitly specified `.cmd` extension for Windows platform since `child_process.execFile` doesn't provide same lookup for executables as OS does.
`child_process.spawn` can be used as alternative to run executables with `sh` or `cmd`.

If you are OK with this approach I'll rewrite current tests cases from `check-bin.sh` as Mocha tests this weekend or by the end of next week.

**Comment by nchen63** [comment]
@IllusionMH I added the label to accept PRs

**Comment by IllusionMH** [comment]
@nchen63 thank you. Then I'll send pull request soon.
