### ISSUE TITLE
auto-fixer for import-ordering rule

### ISSUE THREAD

**Issue by adidahiya** [palantir/tslint#1640]
@nchen63

**Comment by nchen63** [comment]
@adidahiya @JKillian I'm worried about the future of fixers. In the near future, there will be fixes that overlap each other, but the way it's implemented now as a formatter, it runs only once and doesn't easily allow for multiple passes. One way around this might be to detect if 2 replacements overlap each other and then rerun the entire linter, but then you run into a halting problem. Maybe it shouldn't be a type of formatter

**Comment by JKillian** [comment]
cc @JoshuaKGoldberg
