### ISSUE TITLE
object-literal-sort-keys singleline/multiline

### ISSUE THREAD

**Issue by EugeneZee** [palantir/tslint#1642]
Hi,
I believe that it will be very useful to add multiline/singleline options to  `object-literal-sort-keys` rule as you have in [trailing-comma](https://palantir.github.io/tslint/rules/trailing-comma/), because having one line objects sorted alphabetically has no sense for simplifying of merging.
Thanks!

**Comment by adidahiya** [comment]
@EugeneZee you're right, I actually think the rule should _ignore_ single line literals by default. We probably don't even need an option to enforce sorting there, but can add one back if users request it. Will happily take this change for v4.0.

**Comment by EugeneZee** [comment]
@adidahiya thanks! I completely agree that it should be disabled for single lines by default.
