### ISSUE TITLE
How to use applyFixes

### ISSUE THREAD

**Issue by denkomanceski** [palantir/tslint#1663]
Hi, on the official page I saw the newest formatter "applyFixes". I uninstalled tslint and than ```npm install -g tslint@next``` but when I try to use it I get ```Error: formatter 'applyFixes' not found```. I try to use it like this
```tslint del.ts -t applyFixes``` or ```tslint del.ts --format applyFixes```. Could someone post an example of how to use it ? I cannot seem to find any

**Comment by alexeagle** [comment]
Sorry, the documentation is newer than the latest release of tslint (4.0.0-dev) which was before applyFixes formatter.
@adidahiya can you cut another `@next` release soon?

**Comment by mweststrate** [comment]
Is there currently any reasonable way in which we run applyFixes? Looking forward to that feature!

**Comment by adidahiya** [comment]
@alexeagle ok, working on it today: https://github.com/palantir/tslint/pull/1672
