### ISSUE TITLE
Member-access does not allow for static methods in classes.

### ISSUE THREAD

**Issue by JustinDFuller** [palantir/tslint#1665]
### Bug Report

- __TSLint version__: `3.15.1`
- __TypeScript version__: `2.0.3`
- __Running TSLint via__: Atom 

#### TypeScript code being linted

```ts
export class Module {
    constructor (public moduleName: string) {
        // Not relevant
    }

    static checkForBootstrap (): void {
        // code in here is not relevant.
    }
}
```

with `tslint.json` configuration:

```json
{
  "extends": "tslint:latest",
  "rulesDirectory": "node_modules/tslint-eslint-rules/dist/rules",
  "rules": {
      "quotemark": "single"
  }
}
```

#### Actual behavior

member-access - The class method 'checkForBootstrap' must be marked either 'private', 'public', or 'protected'

#### Expected behavior

It should let me use static..

**Comment by adidahiya** [comment]
This rule is working as intended. You should specify `public static` or `private static`.
