### ISSUE TITLE
Use `--fix` instead of `-t applyFixes`

### ISSUE THREAD

**Issue by nchen63** [palantir/tslint#1684]
Before we 4.0, I'd like to change the parameters so that fixes are not applied using a formatter

- ApplyFixes is not a typical formatter. Formatters are usually used to format the linter errors
- Using a formatter limits the number of cycles that the fixes can be applied in since all fixes are batched and applied at one time. Multiple cycles are needed since fixes can overlap.
- If we move to an AST transform based fixer in the future, fixes will most likely be done at the time the linting error is generated.
- Consistent with eslint

**Comment by nchen63** [comment]
@alexeagle @JKillian @adidahiya: thoughts?

**Comment by alexeagle** [comment]
Sorry I missed this. Thanks for helping with the fixes feature.
