### ISSUE TITLE
TSLint not using custom rule

### ISSUE THREAD

**Issue by cancio** [palantir/tslint#1685]
### Bug Report

- __TSLint version__: `3.2.1`
- __TypeScript version__: `2.0.3`
- __Running TSLint via__: grunt-tslint

with `tslint.json` configuration:

```json
{
  "rulesDirectory": ["./tslint_rules/"],
  "rules": {
    "class-name": true,
    "curly": true,
    "eofline": false,
    "indent": [true, "spaces"],
    "label-position": true,
    "label-undefined": true,
    "no-arg": true,
    "no-bitwise": true,
    "no-consecutive-blank-lines": true,
    "no-console": [true,
      "time",
      "timeEnd",
      "trace"
    ],
    "no-construct": true,
    "no-constructor-vars": false,
    "no-debugger": true,
    "no-duplicate-key": true,
    "no-duplicate-variable": true,
    "no-empty": false,
    "no-eval": true,
    "no-string-literal": false,
    "no-switch-case-fall-through": true,
    "no-trailing-comma": true,
    "no-trailing-whitespace": true,
    "no-unused-expression": true,
    "no-unused-variable": false,
    "no-unreachable": true,
    "no-use-before-declare": true,
    "one-line": [true,
      "check-open-brace",
      "check-whitespace"
    ],
    "radix": false,
    "semicolon": true,
    "variable-name": false,
    "whitespace": [true,
      "check-branch",
      "check-decl",
      "check-operator",
      "check-separator"
    ],
    "no-var-keyword": true,
    "no-imports": true
  }
}
```

I copied and pasted the example from [here](https://palantir.github.io/tslint/develop/custom-rules/) into a file named `noImportsRule.ts`, compiled the TypeScript fine, and then placed it in a `tslint_rules` directory at the same level as my `tslint.json`. I've tried multiple different forms of the path, I've tried passing it from the Gruntfile.js, and it will absolutely not load the custom rule. What could I be doing wrong?

**Comment by cancio** [comment]
Also, why is it so hard to debug something like this? If there is something with the path that I'm passing in, why doesn't tslint fail? If the rule doesn't exist, why doesn't tslint fail with a useful error message?

**Comment by adidahiya** [comment]
As of TSLint 3.4, you do get an error when a rule can't be found: https://github.com/palantir/tslint/issues/598.

Can you try upgrading TSLint and also running with the CLI instead of through Grunt?

**Comment by cancio** [comment]
Yes, upgrading resolved the issue. Thank you.
