### ISSUE TITLE
label-undefined rule does not exist.

### ISSUE THREAD

**Issue by michaeljota** [palantir/tslint#1693]
### Bug Report

- __TSLint version__: `4.0.0-dev.1`
- __TypeScript version__: `2.0.3`
- __Running TSLint via__: CLI

#### Actual behavior

No rule for label-undefined.

#### Expected behavior

I guess there is now a TS compiler option for this, as you had remove other rules for that reason. So I open this for people to know that rule `label-undefined` as been removed, and for my to know what TS compiler option should I use now. 

Thank you!

**Comment by adidahiya** [comment]
It comes for free in the compiler; you don't have to enable any options. See https://github.com/palantir/tslint/issues/877. For a full changelog in 4.0 (sorry, haven't gotten around to writing this up in markdown yet, maybe @nchen63 can take a stab?), you can check out the github milestone: https://github.com/palantir/tslint/milestone/26?closed=1

**Comment by michaeljota** [comment]
Ok. Thank you. :).
