### ISSUE TITLE
Add more lintable locations to completed-docs rule

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [palantir/tslint#1713]
As per the list by HamletDRC in https://github.com/Microsoft/tslint-microsoft-contrib/issues/162, a more complete list of things that could have rules:

* modules
* exported classes
* all classes
* exported interfaces
* interfaces
* interface members
* exported variables
* functions
* exported functions
* public member variables
* all member variables
* public member methods
* all member methods

**Comment by Ritzlgrmft** [comment]
For me it would be interesting to prevent the check of private properties...
