### ISSUE TITLE
Lint error shows up when running from CLI, but not in VSCode

### ISSUE THREAD

**Issue by bcherny** [palantir/tslint#1724]
Plugin: https://github.com/bcherny/tslint-no-circular-imports

Lint errors thrown by TSLint show up on both the CLI and in VSCode, but errors thrown by this plugin only show up on the CLI.

From reading the VSCode-TSLint docs, it might be related to [this piece of global state](https://github.com/bcherny/tslint-no-circular-imports/blob/1820f0bb97fa3f6731795c8c9f74543abacf5564/noCircularImportsRule.ts#L24). Is there a better way to crawl dependencies and build a dependency graph with the TSLint or TS APIs?

**Comment by nchen63** [comment]
The global state is problematic. 

I think you're not seeing the errors in VSCode because of the way vscode-tslint calls the API.

**Comment by bcherny** [comment]
That's what it seems like to me too.

Is there a better algorithm to use for cycle detection? I was thinking of updating it to:

- When walking an import node:
  a. Traverse the import, and get the imported file's imports
  b. Repeat (a) for each imported file
- Compute cycles from the resultant dependency graph

My concern was that this would be too costly, but I'll try it and see how it performs, and tune as necessary.

Do you know what TS/TSLint APIs to use for getting a dependency graph, or if that API doesn't exist, then for parsing a file (`fs.readFile` + `ts.preProcessFile`?)? The API docs are pretty sparse for both TS and TSLint.

**Comment by nchen63** [comment]
Take a look at `applyWithProgram`. This gets you the `program` object from the TypeScript API which might help you, but like you said, the TypeScript docs are sparse. Even with this, you might not get very far since I think you need a rule that runs once per project, not once per file.

**Comment by bcherny** [comment]
`applyWithProgram` looks promising, thanks @nchen63. We'll need to merge https://github.com/palantir/tslint/pull/1728 (or another solution) before I can use it, though.

I'll keep this issue open for now, and will close it once I have a working solution.

**Comment by nchen63** [comment]
cleaning up... feel free to reopen after you investigate
