### ISSUE TITLE
[Feature request] Enable AppVeroyr for PR checks

### ISSUE THREAD

**Issue by IllusionMH** [palantir/tslint#1736]
Since Windows builds on AppVeyor are now can perform full test suite without problems may be it reasonable to brings it back for PR checks?

Also this will allow to see right on GitHub if changes related to CLI aren't compatible with Windows (path, escapes etc.)

**Comment by adidahiya** [comment]
We used appveyor for a long time but it started flaking on us constantly. We could look into it again, perhaps the stability has improved. @nchen63 you could work with @ashwinr since we were using his account

**Comment by IllusionMH** [comment]
Haven't checked it for a day and looks like it does something strange again. Builds stuck in queue.

I've posted about this issue in their support forum [link](http://help.appveyor.com/discussions/problems/5558-all-builds-are-in-queued-status)

**Comment by IllusionMH** [comment]
Looks like queue was fixed and there are no more deviations from normal works for a few days.

**Comment by JoshuaKGoldberg** [comment]
How about Travis instead?

/cc @IllusionMH - since we're now using Linux + Windows on `tslint-microsoft-contrib`.

**Comment by IllusionMH** [comment]
I have no strict preference for CI here, so Travis is good.

This issue was created when some testa failed on Windows and before Travis CI supported Windows VMs or public release on Azure DevOps.

**Comment by JoshuaKGoldberg** [comment]
Per #4534 this seems no longer relevant. Ah well.
