### ISSUE TITLE
Feature: tslint comment override

### ISSUE THREAD

**Issue by rogierschouten** [palantir/tslint#177]
Sometimes I have a file with a tslint comment here and there, and I want to temporarily disable tslint on the whole file.  The comment 
```javascript
/* tslint:disable */
```
does not work in that case, because the existing tslint comments will turn tslint on again. Would it be an idea to have some kind of uber-comment e.g. 
```javascript
/* TSLINT:DISABLE */ 
```

**Comment by ashwinr** [comment]
I'm not sure this is a major pain point for folks using TSLint now. I'm closing this issue now, but if you're willing to send us a draft of how this change looks as a PR, we can reconsider. Thanks.
