### ISSUE TITLE
Rule Suggestion: block indent

### ISSUE THREAD

**Issue by diminutivesloop** [palantir/tslint#1814]
It would be helpful to have a rule that enforces consistent statement indentation for code blocks. For example the following snippet would violate this rule because the block statements are not indented:

    if (x) {
    this.y = val;
    this.doSomething();
    }

Likewise this snippet would violate the rule because the block statements are indented but not aligned:

    if (x) {
        this.y = val;
            this.doSomething();
    }

**Comment by adidahiya** [comment]
Your first example does not produce lint failures with any current rule, but I believe the `align` rule should produce a failure for your second example.

**Comment by nchen63** [comment]
https://github.com/palantir/tslint/issues/581 is a proposal to enhance the `indent` rule, which I think addresses the first one

**Comment by adidahiya** [comment]
closing in favor of #2814
