### ISSUE TITLE
orderedImportsRule sort by long name

### ISSUE THREAD

**Issue by bookman25** [palantir/tslint#1818]
**Proposal:** add option to sort imports by long name
```
import b from 'a';
import a from 'b';
```
gets sorted to
```
import a from 'b';
import b from 'a';
```

**Comment by JoshuaKGoldberg** [comment]
@bookman25 this works for default imports as you've shown and `* as` imports, but how would this work for destructured named imports?

```typescript
import { b } from 'a';
import { c, d } from 'b';
```

...then if we add an `a` to the `'b'` module import, that would make the import lines need to reorder, right?

I'm -1 on this rule as we tend to prefer named imports for the better code completion.

**Comment by bookman25** [comment]
I was able to leverage this [rule](https://github.com/jwbay/tslint-misc-rules/#1) so this ticket is no longer necessary.
