### ISSUE TITLE
Inappropriate generated docs for orderedImportsRule.ts

### ISSUE THREAD

**Issue by egel** [palantir/tslint#1825]
### Bug Report
Missing space line in [orderedImportsRule.ts](https://github.com/palantir/tslint/blob/master/src/rules/orderedImportsRule.ts#L42) between lines 42-43. That's why docs are incorrectly generated.

### Screenshot
![selection_037](https://cloud.githubusercontent.com/assets/3322106/20930820/3394946c-bbcf-11e6-984e-3c2abf85a16e.png)

**Comment by adidahiya** [comment]
@egel did you mean to make this PR against `palantir:master`? https://github.com/egel/tslint/pull/1

@nchen63 note the difference in markdown syntax. Github flavored markdown is more forgiving; it lets you get away without that empty line preceding lists, but most markdown parsers are sensitive to it.

**Comment by egel** [comment]
@adidahiya Yeah, I tried to make it against `palantir:master` because it was so simple. Actually for this I should clone `palantir:master` (not fork) then create branch, push code to the branch and then create request request, right?

**Comment by adidahiya** [comment]
it's simpler than that. if you just open up https://github.com/palantir/tslint, Github should prompt you with a yellow alert that lets you make a PR against master. https://github.com/egel/tslint/pull/1 is currently _not_ against `palantir:master`; it's against the master branch on your fork.

**Comment by egel** [comment]
@adidahiya Unfortunately for me, I don't any kind of option (yellow alert) right now. There is another way? :)

**Comment by adidahiya** [comment]
Here's the URL that will create the right PR: https://github.com/palantir/tslint/compare/master...egel:egel-patch-1?expand=1

**Comment by egel** [comment]
I've done it. @adidahiya Thank you for the guide and advice.

**Comment by JoshuaKGoldberg** [comment]
Awesome, this was merged! 🎉
