### ISSUE TITLE
New rules for linting type declarations

### ISSUE THREAD

**Issue by andy-ms** [palantir/tslint#1844]
We've been working on lint [rules](https://github.com/Microsoft/types-publisher/tree/master/src/tslint) for [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) and most may be of general use. Would you be interested in my making PRs for some of these rules?

| Name | Description | PR |
| --- | --- | --- |
| `forbidden-types` | This forbids the `Function`, `Object`, `Boolean`, `Number`, and `String` types. These have better alternatives (specific function types, `{}`, `boolean`, `number`, `string`). |  #2271 |
| `functional-interfaces` | This prefers `type Foo = () => void` over `interface Foo { (): void; }`. | #1891 |
| `interface-over-type-literal` | This prefers `interface Foo { x: number; }` over `type Foo = { x: number; }`. |  #1890 |
| `no-empty-interface` | This forbids `interface Foo { }`. (TypeScript is structurally typed, so this doesn't accomplish anything.) | #1889 |
| `no-public` | This forbids the `public` keyword. This could be an option for `member-access` to make it forbid instead of mandate. | #2247 |
| `unified-signatures` | This prefers `interface Foo { foo(x: number | string): void; }` over `interface Foo { foo(x: number): void; foo(x: string): void; }`. |  #1944 |
| `void-return` | This forbids `foo(x: void): number` but allows `foo(x: number): void`. This could be joined with `forbidden-types`. | N/A |

(`dt-header` and `no-single-declare-module` will probably not be useful outside of DefinitelyTyped.)

**Comment by nchen63** [comment]
when would someone ever write `foo(x: void)`?
`forbidden-types` 


| Name | Description |
| --- | --- |
| `forbidden-types` | This is covered by the `ban rule`. |
| `functional-interfaces` | 👍 I like it  |
| `interface-over-type-literal` | 👍 I like it  |
| `no-empty-interface` | 👍 I like it |
| `no-public` | 🤔 I don't see the benefit of this one |
| `unified-signatures` | How would this work for more complex signatures like `interface Foo { foo(x: number, y: boolean): void; foo(x: string, y: SomeInterface): void; }`? Would it allow a bad combo like `foo(true, "bar")`?. |
| `void-return` | I don't understand why someone would write `foo(x: void): number` in the first place |

**Comment by adidahiya** [comment]
I don't think the `ban` rule covers anything in type positions

**Comment by nchen63** [comment]
right, I'll edit the table

**Comment by andy-ms** [comment]
With #2273 this should be done.
