### ISSUE TITLE
Semicolon rule incorrectly fixes trailing commas

### ISSUE THREAD

**Issue by greglo** [palantir/tslint#1856]
### Bug Report

- __TSLint version__: `4.0.2`
- __TypeScript version__: `2.0.3`
- __Running TSLint via__: CLI

#### TypeScript code being linted with `--fix`

```ts
interface ITest {
    trailingComma: string,
}
```

#### Actual behavior

A semicolon is appended instead of replacing the comma

```ts
interface ITest {
    trailingComma: string,;
}
```

#### Expected behavior

The comma is replaced with a semicolon

```ts
interface ITest {
    trailingComma: string;
}
```

See failing test case: https://github.com/greglo/tslint/commit/66e7022370a238134439548c3cff6262556b8e22

**Comment by rjmunro** [comment]
Also, if every time you run the fix again, you get another `;`:

So:

    interface ITest {
        trailingComma: string,;;
    }

Then:

    interface ITest {
        trailingComma: string,;;;
    }

etc.

I would expect fixes to be idempotent.
