### ISSUE TITLE
"Fix" options dissapeared in TSLint extension >= 0.6.0 in VS Code

### ISSUE THREAD

**Issue by greuze** [palantir/tslint#1859]
### Bug Report

- __TSLint version__: `3.15.1`
- __TypeScript version__: `2.1.4`
- __Running TSLint via__: `Visual Studio Code`
- __TSLint extension version__: `>= 0.6.0`

#### Actual behavior

When using TSLint extension `0.6.0` or above (with TSLint version `3.15.1` or `4.0.2`), the old "fix" options dissapeared when clicking the light bulb, now there is only one option:
- Disable "xxx" rule?

#### Expected behavior

Those options when clicking the light bulb:
- Fix this "xxx" tslint warning?
- Fix all "xxx" tslint warnings?
- Fix all auto-fixable problems
- Disable "xxx" rule?

**Comment by nchen63** [comment]
works for me in 0.7.1

**Comment by johnwiseheart** [comment]
I'm going to close this as its old and I don't think this issue exists any more.
