### ISSUE TITLE
When project hasn't any ts-file, throw error

### ISSUE THREAD

**Issue by arvitaly** [palantir/tslint#1863]
### Bug Report

My project has one d.t.s file and tslint throw error.

- __TSLint version__: `4.0.2`
- __TypeScript version__: `2.1.4`
- __Running TSLint via__: CLI

#### TypeScript code being linted

with `tslint.json` configuration:

```json
{
    "extends": [
        "tslint:latest"
    ]
}
```

#### Actual behavior

`TypeError: Reduce of empty array with no initial value in \node_modules\tslint\lib\tslint-cli.js:224:6`

#### Expected behavior

No error.

**Comment by IllusionMH** [comment]
@arvitaly I think there is easy fix, but unfortunately I can't reproduce your case.
Can you provide your file structure and exact command on how you call tslint?

**Comment by arvitaly** [comment]
@IllusionMH Hi!
![tslint-error](https://cloud.githubusercontent.com/assets/2562855/21469308/baf2a0f6-ca76-11e6-9659-d44b7f695fc9.png)

**Comment by IllusionMH** [comment]
@arvitaly thanks. This screenshots confirms my thoughts.
Looks like I reproduced case similar to yours and error will be fixed after merge of #1933.

TSLint is supposed to lint `.ts`, `.tsx`, `.js` and `.jsx` files.
`.d.ts` are skipped (see [linter.ts:88](https://github.com/palantir/tslint/blob/master/src/linter.ts#L88))

To make TSLint properly check files your `tsconfig.json` should have `files` or `include` section or/and you can pass globs for `.ts` files (along with `--project` flag) in command line.

**Comment by arvitaly** [comment]
@IllusionMH, thanks!

**Comment by arvitaly** [comment]
I faced with this situation, when i developed types for https://github.com/DefinitelyTyped/DefinitelyTyped.
This is projects hasn't ts-file usually, only d.ts.
