### ISSUE TITLE
Add "externals-first" option to ordered-imports rule

### ISSUE THREAD

**Issue by adidahiya** [palantir/tslint#1865]
### Rule option request

I use [tsunami-code](https://github.com/AndyMoreland/tsunami) to auto-import symbols in VSCode. It injects external NPM module imports before scoped packages (which are usually private modules). Rather than changing tsunami's behavior, I would like this to be compatible with the ordered-imports lint rule.

[Relevant code in tsunami here](https://github.com/AndyMoreland/tsunami/blob/516057e80860f0412abc96292a621f37bd03bad3/src/imports/SimpleImportBlockFormatter.ts#L15).

@AndyMoreland for SA

**Comment by AndyMoreland** [comment]
Thanks for the tag. I'm open to adjusting tsunami-code to support pure alphabetical ordering as well since I am sure lots of people prefer it, but I do prefer the import ordering that it ships by default.

**Comment by Maximaximum** [comment]
It's a pity this has not been implemented :(

**Comment by yanckst** [comment]
+1

**Comment by abierbaum** [comment]
Pretty sure your use case is covered by #4134
