### ISSUE TITLE
Task: simplify uses of `createFailure`

### ISSUE THREAD

**Issue by andy-hanson** [palantir/tslint#1867]
As of #1845, `noUnusedVariableRule.ts` and `objectLiteralKeyQuotesRule.ts` are the only rules using `createFailure` directly. We should look into simplifying these.

edit: other rules using `createFailure`:

- [x] `banTypesRules.ts`
- [x] `importSpacingRule.ts`
- [x] `noFloatingPromisesRule.ts`
- [x] `noStringThrowRule.ts`

**Comment by nchen63** [comment]
we can remove the deprecated functions now.

**Comment by nchen63** [comment]
having second thoughts on removing the deprecated functions, which would break almost all 3rd party rules. I think we should leave these in.

**Comment by adidahiya** [comment]
@nchen63 that's a good point; let's add a deprecation warning in the console in 5.0 though?

**Comment by nchen63** [comment]
taking out of 5.0 release since we can deprecate later in 5.x, and we're still using the `addFailure` in some files

**Comment by adidahiya** [comment]
fair enough
