### ISSUE TITLE
Exclude length from imports via max-line-length

### ISSUE THREAD

**Issue by Ne-Ne** [palantir/tslint#1872]
Hi,

Question / Possible feature..?

---

gulp-tslint: 6.1.1 via - Visual Studio

Rule:

https://palantir.github.io/tslint/rules/max-line-length/

`tslint.json` configuration:

```json
"max-line-length": [
  true,
  150
],
```
---
Is there any existing way we can exclude imports from this rule?

```ts
import { item1, item2, item3, item4, item5, item6, item7, item8, item9, item10, item11, item12, item13, item14, item15, item16, item17, item18, item19, item20 } from "@angular/router";
```

Many thanks.

**Comment by IllusionMH** [comment]
@Ne-Ne this is exact case for this rule.
In this case it is more preferable to write imports one in line (much easy merge/review changes in list) or you may load it as 
```ts
import * as routes from "@angular/router";
```

and then use required items as `routes.item2` when needed.

Or you can just use [rule flags](https://palantir.github.io/tslint/usage/rule-flags/) to disable this rule for single line.

**Comment by adidahiya** [comment]
This has been requested before in #1123. I wouldn't mind having an option to disable the rule for import statements, but we won't enable in the built-in configurations.

**Comment by ajafff** [comment]
Closing in favor of #1123
