### ISSUE TITLE
Support warnings for rules

### ISSUE THREAD

**Issue by ericanderson** [palantir/tslint#1877]
**Use Case:** As a developer trying to improve their code base, I want to enable certain rules at a "warning" level, so that I can work through lint issues over time.

**Proposal**: Switch from `boolean` for enabled/disabled rules to `boolean | "error" | "warn" | "warning"`.

This would also facilitate updating the vscode-tslint plugin to support both both errors and warnings.

**Comment by IllusionMH** [comment]
Already in work: https://github.com/palantir/tslint/pull/1738
