### ISSUE TITLE
New rule: no-bind

### ISSUE THREAD

**Issue by huashiyiqike** [palantir/tslint#1881]
To circumvent re-rendering by creating a new function each time when binding this to functions

https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md

"jsx-no-bind": [<enabled>, {
  "ignoreRefs": <boolean> || false,
  "allowArrowFunctions": <boolean> || false,
  "allowBind": <boolean> || false
}]

[https://basarat.gitbooks.io/typescript/content/docs/tips/bind.html](https://basarat.gitbooks.io/typescript/content/docs/tips/bind.html)
 TypeScript's lenient typing of bind (bind(this: Function, thisArg: any, ...argArray: any[]): any;), which results in parameter-mismatches not being caught.

**Comment by adidahiya** [comment]
React / JSX specific rules live here: https://github.com/palantir/tslint-react

There is already a request for no-bind: https://github.com/palantir/tslint-react/issues/44
