### ISSUE TITLE
bugfix in prefer-const break on ts 2.0.10

### ISSUE THREAD

**Issue by fchiumeo** [palantir/tslint#1936]
### Bug Report

- __TSLint version__: `4.2.0`
- __TypeScript version__: `2.0.10`
- __Running TSLint via__: gulp-tslint and tslint

#### Actual behavior

prefer-const not working on typescript 2.0.10

TypeError: Cannot read property 'Export' of undefined
    at Function.PreferConstWalker.collectInVariableDeclarationList (\node_modules\tslint\lib\rules\preferConstRule.js:68:127)

this change e973b579118dacebad95dbbd954c65f40e8a725e
#1908

#### Expected behavior

working in typescript 2.0.10

**Comment by connor4312** [comment]
I've created a pull request to address this issue here: https://github.com/palantir/tslint/pull/1941
