### ISSUE TITLE
Put `docs` in `.gitignore`.

### ISSUE THREAD

**Issue by andy-hanson** [palantir/tslint#1968]
This is generated code, so it clutters PRs (that remember to run `npm run verify` to update docs), and can potentially get out-of-sync with the source (e.g.  #1947, which has correct `docs` but a typo in `src`).
It also causes merge conflicts when `docs/_data/rules.json` changes.

**Comment by nchen63** [comment]
If we did this, only `docs/_data/rules.json` and `docs/rules/*` should be ignored. Also, if we ignored, we could no longer use `/docs` on master for gh-pages

**Comment by nchen63** [comment]
just ignoring rules.json for merge conflicts. I think it's still valuable to be able to serve /docs to gh-pages
