### ISSUE TITLE
gulp-tslint broke because null is no longer a possible value for formattersDirectory

### ISSUE THREAD

**Issue by pe8ter** [palantir/tslint#1995]
### Bug Report

- __TSLint version__: `4.3.0`
- __TypeScript version__: `2.1.4`
- __Running TSLint via__: gulp-tslint `7.0.1`

#### Issue

Recently `getRelativePath()` [was updated](https://github.com/palantir/tslint/blob/master/src/configuration.ts#L269) to support `strictNullChecks`. Being stricter is great, but current consumers rely on the [previous version's laxness](https://github.com/palantir/tslint/commit/4f930637306391a7b987f3648ff992e86297ba01#diff-8b01d5598b81332eb62385d26f3ead22L270) which used the non-strict equality operator on passed-in paths. That check was [moved up to the only consumer `getResult()`](https://github.com/palantir/tslint/blob/master/src/linter.ts#L144) in _linter.ts_ but switched to using strict equality on `undefined`. This forces consumers to explicitly pass `undefined`, but other existing consumers already pass `null`.

An example is gulp-tslint which [sometimes passes `null`](https://github.com/panuhorsmalahti/gulp-tslint/blob/master/index.js#L91). The plugin is broken now because that `null` value makes it all the way down into `path.resolve()` in `getResult()` which throws an exception.

I would expect that for a minor version update that a breaking change like this would not be introduced.

**Comment by nchen63** [comment]
Agree, should not have broken apps relying on TSLint

**Comment by pe8ter** [comment]
I think the fix is as simple as changing from strict to non-strict equality on [this line](https://github.com/palantir/tslint/blob/master/src/linter.ts#L144) but I'm hardly familiar with this code base.

**Comment by nchen63** [comment]
@pe8ter could you verify this fix in #1997 before I publish another release?

**Comment by pe8ter** [comment]
Thanks!

**Comment by mgechev** [comment]
The fix works for me too.
