### ISSUE TITLE
Do not remove space after `async` 

### ISSUE THREAD

**Issue by mohsen1** [palantir/tslint#2001]
### Bug Report

- __TSLint version__: `4.3.1`
- __TypeScript version__: `2.1`
- __Running TSLint via__: CLI and `--fix`

#### TypeScript code being linted

```ts
const fn = async () => { /**/ }
```

with `tslint.json` configuration:

```json
{
  "extends": [
    "tslint:latest"
  ]
}
```

#### Actual behavior

Removes spaces after `async`:

```ts
const fn = async() => { /**/ }
```

#### Expected behavior

`async` should have an space after

I didn't notice which rule did this.

**Comment by nchen63** [comment]
it's caused by `space-before-function-paren`

**Comment by andy-hanson** [comment]
@mohsen1 Use `--format stylish` to see which rule is being used.
This is already an [option](https://palantir.github.io/tslint/rules/space-before-function-paren/) of the rule: you can use `"asyncArrow": "always"` to get the behavior you want. Maybe that should be the default for this rule.

**Comment by mohsen1** [comment]
Yes it should be default. Async is not the method name
