### ISSUE TITLE
Auto fix quotes should escape `"`

### ISSUE THREAD

**Issue by ericanderson** [palantir/tslint#2003]
### Bug Report

- __TSLint version__: `4.0.2`
- __TypeScript version__: `2.1.4`
- __Running TSLint via__: Visual Studio

#### TypeScript code being linted

```ts
console.log('"');
```

#### Actual behavior (via auto-fix)

```ts
console.log(""");
```

#### Expected behavior

```ts
console.log("\"");
```

**Comment by mohsen1** [comment]
`JSON.stringify` should be used in the fix

**Comment by IllusionMH** [comment]
Strange, but have no problems with this test case https://github.com/IllusionMH/tslint/commit/351dd2f2fdfc55e718b506ee11ba3640136f379f

**Comment by andy-hanson** [comment]
This already works with `tslint@next`.

**Comment by ajafff** [comment]
This case is covered by the tests:
https://github.com/palantir/tslint/blob/b80c5f2f68f54993aa1d060a886e5833b8077428/test/rules/quotemark/double/test.ts.lint#L5
https://github.com/palantir/tslint/blob/b80c5f2f68f54993aa1d060a886e5833b8077428/test/rules/quotemark/double/test.ts.fix#L4
