### ISSUE TITLE
Allow whitelist of keys to be excluded from `object-literal-key-quotes`

### ISSUE THREAD

**Issue by adidahiya** [palantir/tslint#2031]
### Feature Request

Working with Jackson-serialized classes. I have a `"@type"` field that I need to quote, but I don't want to quote everything else.

#### TypeScript code being linted

```ts
return {
    "@type": "MyFancyClass",
    someField: "foo",
};
```

#### Actual behavior

`object-literal-key-quotes` reports a failure on `someField` not being quoted.

#### Expected behavior

I would like to configure an exception whitelist:

```json
"object-literal-key-quotes": [true, {
    "exclude": ["@type"]
}],
```

**Comment by JoshuaKGoldberg** [comment]
`object-literal-key-quotes` now options such as `"consistent-as-needed"` to automatically pick this need up. Closing this for housekeeping purposes. 🎉
