### ISSUE TITLE
Feature Request: semistandard rules for tslint

### ISSUE THREAD

**Issue by tyleralves** [palantir/tslint#2044]
We currently use semistandard for all of our projects, and are just jumping into Typescript/ tslint. 

Is it currently possible to use semistandard via tslint.json "extends"? If not, we'd love it if that was possible possible. 

Been loving tslint so far. Cheers, Tyler.

**Comment by nchen63** [comment]
It looks like semistandard is a set of eslint rules which were aggregated by a 3rd party. In that case, no, those set of rules won't apply to tslint and probably wouldn't belong in the core set of preset configs

**Comment by adidahiya** [comment]
That being said, there have been other configs published that try to emulate existing ESLint presets. So if you created a `tslint-config-semistandard` package or something similar, I imagine it might be used by others as well.

**Comment by nfantone** [comment]
BTW, you could use [`tslint-eslint-rules`](https://github.com/buzinas/tslint-eslint-rules) + [`tslint-config-standard`](https://github.com/blakeembrey/tslint-config-standard) with the following `tslint.json` config:

```json
{
  "extends": "tslint-config-standard",
   "rules":{
    "semicolon": [true, "always"]
   },
  "rulesDirectory": [
    "node_modules/tslint-eslint-rules/dist/rules",
  ]
```

And, for the most part, get what you want.
