### ISSUE TITLE
no-constant-condition not in schemastore

### ISSUE THREAD

**Issue by unional** [palantir/tslint#2056]
Seems like it is missing. No completeion in vscode. 🌷

**Comment by ajafff** [comment]
This rule is not provided by tslint. You're probably using the rule from https://github.com/buzinas/tslint-eslint-rules
So this is out of scope for this project.

But I agree with you: It would be nice to have completion / intellisense for custom rules. Maybe you can ask for that in the vscode or vscode-tslint repo.

**Comment by unional** [comment]
Ar, sorry, didn't notice that. Should ask tslint-eslint-rules instead.
