### ISSUE TITLE
improve typeof-compare error message to contain the failing word and a suggestion

### ISSUE THREAD

**Issue by HamletDRC** [palantir/tslint#2066]
The typeof-compare error message is a static string that does not give the user a hint of what went wrong. 

It would be better to include the offending word in the error message. 

Additionally, it is quite simple to also print out what the word should most likely be by calculating the distance to the closest match. The microsoft rule for the same behavior does this: https://github.com/Microsoft/tslint-microsoft-contrib/blob/master/src/validTypeofRule.ts

**Comment by mohsen1** [comment]
See https://github.com/palantir/tslint/pull/2046

It's likely that the rule get deprecated

**Comment by ajafff** [comment]
@mohsen1 I'd recommend not to deprecate this rule. This one does not need the type checker.

But I'm also ok with tslint deprecating the rule, as long as the equivalent is still available in `microsoft-tslint-contrib`
