### ISSUE TITLE
CircleCI builds are failing from bad cache

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [palantir/tslint#2080]
Sample line from [failing build](https://circleci.com/gh/JoshuaKGoldberg/tslint/19):

```cmd
node_modules/@types/underscore/index.d.ts(3824,43): error TS2304: Cannot find name 'Element'.
```

Is there a way to... not do that?

**Comment by adidahiya** [comment]
yeah, look for the "rebuild without cache" dropdown action in the top right:

![image](https://cloud.githubusercontent.com/assets/723999/22137974/3b823ba2-deac-11e6-9c36-01906a92627c.png)

**Comment by JoshuaKGoldberg** [comment]
Is there a way to set that up by default?

**Comment by adidahiya** [comment]
No, probably because your builds would get very very slow.

**Comment by nchen63** [comment]
You shouldn't need to rebuild without cache more than once
