### ISSUE TITLE
Rules should be able to opt into --type-check

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [palantir/tslint#2091]
Spinning discussion out of #2073: it would be useful to have rules that run in the default mode but can also benefit from type checking.

For example, `no-string-throw` isn't able to use the type checker to detect non-`Error` objects that are thrown. The discussion in #1878 indicated a preference for making it available by default (since that catches most usages). 

Right now there are two rules types: `TypedRule` and `AbstractRule` (or something like that). I propose one of two options:
1. A third type, `OptionallyTypedRule` be added. It should implement both `apply` and `applyWithProgram`.
2. `TypedRule` be allowed to optionally implement `apply` as well as `applyWithProgram`.

I have a slight preference for 1. Later on, it could be reasonable to deprecate all both `AbstractRule` and `TypedRule` and rename `OptionallyTypedRule` to just `Rule`.

**Comment by ajafff** [comment]
Isn't that already possible?
A `TypedRule` simply throws an exception in `apply`. If you extend `TypedRule` and implement both `apply` and `applyWithProgram`, the former will be called if you run tslint without `--program` and the latter will be called if you run tslint with that flag.

**Comment by JoshuaKGoldberg** [comment]
Super interesting, I didn't even think to look for that. Thanks @ajafff!

Why bother keeping both a `TypedRule` and its parent `AbstractRule`? Feels like it would make sense to just have one class, `Rule`, that can have `apply` and/or `applyWithProgram`?

**Comment by ajafff** [comment]
Both of them are abstract to guide the developer which method hast to be implemented. I think it makes sense to keep both of them. 
Maybe it would make sense to also add a `OptionallyTypedRule` that has both methods `apply` and `applyWithProgram` as abstract members. That would make the intent of the rule clearer.
