### ISSUE TITLE
Need to improve when the `no-var-keyword` and `prefer-const` used together with `--fix`

### ISSUE THREAD

**Issue by heycalmdown** [palantir/tslint#2112]
### Bug Report

- __TSLint version__: `4.3.1`
- __TypeScript version__: `2.1.5`
- __Running TSLint via__: CLI(vscode)

#### TypeScript code being linted

```ts
var a = "1";
```

with `tslint.json` configuration:

```json
{
    "rules": {
        "no-var-keyword": true,
        "prefer-const": true
    }
}
```

#### Actual behavior

with `--fix`

```ts
let a = "1";
```

#### Expected behavior

```ts
const a = "1";
```

### Additional Notes

It works as expected when I put the sentence into a function block like

```ts
function test() {
    var a = "1";
}
```

goes

```ts
function test() {
    const a = "1";
}
```

with a message as "Fixed 2 error(s) in a.ts".

However vscode's TSLint@0.8.1 still replace it `let` from `var` only. (It would not this module bug.)

**Comment by JoshuaKGoldberg** [comment]
Yes, this is an amusing subset of #2556: handling overlapping fixes.
