### ISSUE TITLE
Type assertions as lint rule?

### ISSUE THREAD

**Issue by danvk** [palantir/tslint#2114]
I've been experimenting with ways of improving tests for type definition files over at https://github.com/danvk/typings-checker

The gist is that you add special comments to assert the types of expressions, e.g.

```ts
// $ExpectType number
_.find([1, 2, 3], 1);
```

This sort of thing could potentially be enforced via a tslint rule, rather than through a separate program (`typings-checker`). This would ease adoption in DT (which already supports tslint) and let it take advantage of all the machinery built into tslint.

What do you guys think? Is this in-scope for tslint? @adidahiya @JKillian

**Comment by JKillian** [comment]
Hey @danvk! It doesn't seem to me that this would be in-scope for core TSLint as it's fairly specific to DT. However, *I think* it could be implemented as a custom rule and used as part of the DT TSLint run.

**Comment by danvk** [comment]
Makes sense. I'll give that a try and report back.

**Comment by OliverJAsh** [comment]
I believe dtslint already converted typings-checker into a tslint rule: https://github.com/Microsoft/dtslint/blob/b26137f0e95a54fd19c91968ee73f98255391686/src/rules/expectRule.ts

Someone just needs to publish it somewhere independently of tslint… https://github.com/Microsoft/dtslint/issues/126
