### ISSUE TITLE
Ability to not overwrite source file when using `--fix`

### ISSUE THREAD

**Issue by ianks** [palantir/tslint#2125]
Currently, running `--fix` replaces the file in place. In certain cases, this causes problem with integrating with other editors, etc. For example, https://github.com/sbdchd/neoformat likes to have a copy of the changed file so it can perform diffs on the current buffer. Would you consider adding an option which allow `--fix` to emit the changes to stdout optionally?

**Comment by nchen63** [comment]
I'm not sure if this would belong in the this repo, but it would be pretty simple to write a custom formatter to write out the fixes in whatever format you want. The text replacements are available in the API even if --fix isn't used.

See https://palantir.github.io/tslint/develop/custom-formatters/

Each `RuleFailure` contains fix.innerReplacements which contains the offset and replacement texts. You just have to take that data and output a string in whatever format works for you.

**Comment by ianks** [comment]
@nchen63 how would this solve the problem of files being overwritten in place?

**Comment by nchen63** [comment]
don't call with --fix so nothing is overwritten
formatter outputs fix info

**Comment by ianks** [comment]
That sounds reasonable; however, I do not see a public API for getting the variables I would need to apply these changes. 

https://github.com/palantir/tslint/blob/master/src/linter.ts#L101

**Comment by ianks** [comment]
Thanks for the info @nchen63!

I created an MVP here: https://github.com/ianks/tslint-fix-formatter

It might be nice to include this in core, since I imagine it would be useful to many users (VIM users, at least). I will leave that up to the team though.

Cheers!

**Comment by adidahiya** [comment]
@ianks sure, we'd accept a PR for a fix formatter.

**Comment by ianks** [comment]
Continuing off of #2149. Making a copy of the file in a temp for is actually what neoformat attempts to do, however the imports , etc are broken at that point. Overall, that mechanism is a bit too error-prone and complicated to use in most cases.

**Comment by JoshuaKGoldberg** [comment]
Seems like this is a subset of #1760. Closing for housekeeping, but if I've misinterpreted and this is actually a separate issue, please do comment here!
