### ISSUE TITLE
Document no-unsafe-any

### ISSUE THREAD

**Issue by ethanresnick** [palantir/tslint#2127]
What constitutes an "unsafe" use of `any`. This isn't defined anywhere.

**Comment by adidahiya** [comment]
docs here could definitely use some work https://palantir.github.io/tslint/rules/no-unsafe-any/

for now it might be best to look at the rule test fixture https://github.com/palantir/tslint/blob/7cb4a9851f608aa60f8b4ff96d57adc3307f9ae5/test/rules/no-unsafe-any/test.ts.lint

as always, we'd accept docs PRs.

**Comment by glen-84** [comment]
Should this have been closed by #2245?
