### ISSUE TITLE
[RFC] which sem version for tslint ?

### ISSUE THREAD

**Issue by fforjan** [palantir/tslint#2138]
Hey guys, quick question for you...

We are new to nodejs and typescript and trying to improve every day.
As part of our dev processes, running TSLint is mandatory.
So far our package.config was referencing tslint using sem version and locking to major by using _^4.0.2_

**What happened** : it seems a new package was publish recentely..
Up to yesterday, TSLINT 4.3.1 was used. Last night TsLint 4.4.1 was started to be used by our nightly build and we got a new error failing the build : 

`src/TestReporter.ts[66, 77]: trailing whitespace`

**Yes, we are strict and we want TsLint as errors.**

**Now there is a debate in the team** : something broke the build without modification in our code base.
Some members are thinking we should lock ourself to a strict version - using _4.3.1_, some locking on the minor - using _~4.3.1_. 
There is also some members being surprised that a minor updated from TsLint are breaking our build.

**What's your recommendation and experience while working with TsLint ? 
Or more general, any recommendation while working with NPM packages ?**

**Comment by ajafff** [comment]
The new failure you describe comes from a bugfix. Trailing whitespaces in comments and before EOF was not found before that change.

My advice, how we do it at work (I'm not a member of palantir/tslint): pin your dependencies with `npm-shrinkwrap.json` or `yarn.lock` depending on the package manager you are using. This way you install the same version of every machine including CI.
If you want to update a package you can check compatibility first in your local workspace before you push your changes to your coworkers and eventually to CI.

**Comment by nchen63** [comment]
agree with @ajafff regarding best practices

For minor versions, we allow bugfixes that may affect the reported errors. In this case, it didn't seem reasonable to hold the change for a major release.

**Comment by fforjan** [comment]
Thanks for your feedback, we are trying npm-shrinkwrap approach !
