### ISSUE TITLE
4.4.0 declares unexpected minimum engine version in package.json

### ISSUE THREAD

**Issue by Bomret** [palantir/tslint#2140]
### Bug Report

- __TSLint version__: `4.4.0`
- __TypeScript version__: `2.1.5`
- __Running TSLint via__: gulp-tslint

#### Actual behavior

Commit [4ee78397af558db8f40c24f0e8c1d4a229b62ada](https://github.com/palantir/tslint/commit/4ee78397af558db8f40c24f0e8c1d4a229b62ada) includes a breaking change by specifying `engine: >=4.2.6` in the `package.json`. This breaks compatibility with projects targeting node `< 4.2.6` and should have led to an incremented major version.

#### Expected behavior

A minor version update should not break engine compatibility.

**Comment by adidahiya** [comment]
@Bomret sorry about that. Node 4.2 is the lowest version we test TSLint with; that's implicitly been the lowest version we support. I suppose we could relax that engine constraint if you successfully run TSLint with an older Node... what are you running?

**Comment by Bomret** [comment]
4.2.0 😉

**Comment by andy-hanson** [comment]
Should this be closed by #2148?
