### ISSUE TITLE
Print errors to stderr

### ISSUE THREAD

**Issue by ikokostya** [palantir/tslint#2141]
### Bug Report

- __TSLint version__: `4.3.1`
- __TypeScript version__: `2.1.5`
- __Running TSLint via__: CLI

#### TypeScript code being linted

Any code with errors.

#### Actual behavior

`tslint` prints error to `stdout`.

#### Expected behavior

`tslint` prints error to `stderr`.

**Comment by JoshuaKGoldberg** [comment]
This has since been done! 🎉

https://github.com/palantir/tslint/blob/61b0826d1547da617a2baac93497b1bf8993a568/src/tslintCli.ts#L283
