### ISSUE TITLE
Feature request: ignore-properties option for no-inferrable-types

### ISSUE THREAD

**Issue by buu700** [palantir/tslint#2158]
It'd be useful if I could disable #2081 (or even have a way to enforce the opposite); for now I've had to just disable this rule in my project entirely.

**Comment by ajafff** [comment]
Fixed by #2178
Now this rule also has a fixer. Maybe that's useful if you don't want to disable checking of properties but instead automatically fix all failures. At least that's what I wished for when updating to tslint@4.4

**Comment by buu700** [comment]
Nice, thanks!

**Comment by timocov** [comment]
#2081 also confused with enabled `member-variable-declaration` option in `typedef` rule, thanks!
