### ISSUE TITLE
Feature Request: use node module resolution semantics for rulesDirectory 

### ISSUE THREAD

**Issue by donaldpipowitch** [palantir/tslint#2163]
`extends` uses node module resolution semantics to find files and you can specify relative paths to files, too. I'd need the same behaviour for `rulesDirectory`. E.g. I want to use `tslint-react/rules` which is sometimes in `./node_modules/tslint-react/rules` and sometimes in `../node_modules/tslint-react/rules` in my case. (I build a generic build tool configuration similar to `create-react-app`, so I don't always have full control about the projects where my configuration is used..)

**Comment by donaldpipowitch** [comment]
With this pull request we can now write something like:

```
{
  "rulesDirectory": [
    "tslint-eslint-rules/dist/rules"
  ]
}
```

Instead of 

```
{
  "rulesDirectory": [
    "./node_modules/tslint-eslint-rules/dist/rules"
  ]
}
```

or

```
{
  "rulesDirectory": [
    "../node_modules/tslint-eslint-rules/dist/rules"
  ]
}
```

This is very useful for tools which offer a `tslint.json` and are installed as a dependency of other projects (like [this one](https://github.com/Mercateo/ws)), because you never really know where your exact dependency will be installed (because sometimes you install your package normally, sometimes it is symlinked, and so on).

**Comment by adidahiya** [comment]
@donaldpipowitch makes sense, that is a good motivation for making this change

**Comment by adidahiya** [comment]
Your PR #2358 seems fine as an enhancement, but I just realized that custom rule packages really ought to configure rulesDirectory themselves so that users don't have to worry about specifying the directory -- instead, you just can just rely on `"extends"` composition semantics. [tslint-react.json does this](https://github.com/palantir/tslint-react/blob/master/tslint-react.json).

**Comment by donaldpipowitch** [comment]
You're right. This would work, too. But then I maybe need to overwrite the default settings.

**Comment by donaldpipowitch** [comment]
From https://github.com/buzinas/tslint-eslint-rules/issues/214#issuecomment-297142208 I think the difference is this:

- `extends`: Allows me to use custom rules from other packages. I get all rules with default configs and can _opt-out_ from rules. If new rules are added in new version I get them automatically.
- `rulesDirectory `: Allows me to use custom rules from other packages. I _opt-in_ to use certain rules with my specific configs. If new rules are added in new version I don't get them automatically.
