### ISSUE TITLE
strict-boolean-expressions silently requires strictNullChecks TS option

### ISSUE THREAD

**Issue by usuyama** [palantir/tslint#2172]
### Bug Report

- __TSLint version__: `4.4.2`

#### Description

Some options (`allow-null-union`, `allow-undefined-union`, `allow-mix`) of [strict-boolean-expressions ](https://palantir.github.io/tslint/rules/strict-boolean-expressions/) assume strictNullChecks TypeScript compiler option, but it is not documented.

The related part of code is [here ](https://github.com/palantir/tslint/blob/master/src/rules/strictBooleanExpressionsRule.ts#L279). Only string, number, Boolean, and enum are handled as NOT always true or false. For example, object type is treated as always truthy, but it's not true without strictNullChecks . This code path is used even without the mentioned arguments, but somehow [the default test ](https://github.com/palantir/tslint/blob/master/test/rules/strict-boolean-expressions/default/test.ts.lint)passes, too.

The tests specify strictNullChecks option (Ex. https://github.com/palantir/tslint/tree/master/test/rules/strict-boolean-expressions/allow-null-union )

#### Actual behavior

strictNullChecks  option is assumed for these arguments `allow-null-union`, `allow-undefined-union`, `allow-mix`, but not documented.

#### Expected behavior

Should be documented. Or, nice if we can lift the assumption.

**Comment by nchen63** [comment]
cc: @andy-hanson

**Comment by nchen63** [comment]
it looks like you can check compiler options in program.getCompilationSettings().strictNullChecks

**Comment by andy-hanson** [comment]
How should a rule report a configuration error like that?

**Comment by usuyama** [comment]
For the sake of #2200, we need to lift the requirement of strictNullChecks, instead of just throwing error. Please check the discussion in #2200.
