### ISSUE TITLE
Warning with out-of-the-box config

### ISSUE THREAD

**Issue by OskarKlintrot** [palantir/tslint#2174]
### Bug Report

- __OS__: `W10`
- __TSLint version__: `4.4.2`
- __TypeScript version__: `2.1.5`
- __Running TSLint via__: npm script: `tslint \"./*/src/**/*.ts\" \"./*/src/**/*.tsx\" --exclude \"./**/node_modules/**/*.ts\" \"./**/node_modules/**/*.tsx\"`

#### TypeScript code being linted

```ts
not relevant
```

with `tslint.json` configuration: `tslint -i`

#### Actual behavior

One print out of:

```
no-unused-variable is deprecated. Use the tsc compiler options --noUnusedParameters and --noUnusedLocals instead.
```

Multiple print outs of:

```
Could not find implementations for the following rules specified in the configuration:
    label-undefined
    no-duplicate-key
    no-unreachable
Try upgrading TSLint and/or ensuring that you have all necessary custom rules installed.
If TSLint was recently upgraded, you may have old rules configured which need to be cleaned up.
```

#### Expected behavior

The rules dosen't exist in `tslint.json` so the warning should not be there. `no-unused-variable` is not used either.

**Comment by adidahiya** [comment]
Can you check if you used a global version of tslint to initialize `tslint.json`? The `tslint -i` CLI uses this default config, which has been appropriately updated as rules have been deprecated: https://github.com/palantir/tslint/blob/dc7c47344c15c11513dc1253ed14bab259edd3ce/src/configuration.ts#L43. I think you might've used an older version of the CLI there.

**Comment by OskarKlintrot** [comment]
This is the first use of tslint on this computer that I can remember of and I haven't installed it globally, I run it through npm scripts (`tslint -i` as well).

[This](https://gist.github.com/OskarKlintrot/79c417a6ecbe0d2a1c94e2b3a1148a04) is the tslint and tsconfig I'm using. There is some small changes done by me, like disabling semicolons. But the rules it's complaining about is not there.

**Comment by OskarKlintrot** [comment]
This issue went away when I changed the script to `"lint": "tslint \"./*/src/**/*.ts?(x)\" --exclude \"./**/node_modules/**/*.ts?(x)\""`.
