### ISSUE TITLE
Autofix `no-consecutive-blank-lines` rule

### ISSUE THREAD

**Issue by ryanmcnamara** [palantir/tslint#2185]
### Bug Report

- __TSLint version__: 4.0.2
- __TypeScript version__: 2.1.4
- __Running TSLint via__: CLI

#### TypeScript code being linted

```ts
const x = "x";


const y = "y";
```

With disallowing consecutive blank lines

TSLint could autofix this error. It currently does not.

**Comment by ryanmcnamara** [comment]
I would be interested in taking a shot at fixing this, however I'm not sure when I'll have time.

**Comment by ajafff** [comment]
Fixed by #2201
