### ISSUE TITLE
Rule option request: snake_case for variable-name rule

### ISSUE THREAD

**Issue by rajinder-yadav** [palantir/tslint#2190]
I would like to have an option to allow `snake_case` variable names, even enforce it exclusively.

**Comment by ajafff** [comment]
There are third party rule packages that do this pretty good. Maybe you want to take a look at these two:
https://www.npmjs.com/package/vrsource-tslint-rules#ext-variable-name
https://www.npmjs.com/package/tslint-consistent-codestyle#naming-convention

**Comment by rajinder-yadav** [comment]
I rather have an option, "allow-snake-case" added to Rule: variable-name

https://palantir.github.io/tslint/rules/variable-name/

**Comment by AJamesPhillips** [comment]
@ajafff would you review and potentially accept PR for this?  My personal motivation is that snake_case is reportedly easier for non-latin language natives to read such as native Japanese readers, at least according to the ruby coding style guide.
