### ISSUE TITLE
Simplify generated config for `tslint -i`

### ISSUE THREAD

**Issue by nchen63** [palantir/tslint#2193]
What do you guys think of changing the initial tslint.json file to just:
```
{
  "extends": "tslint:recommended",
}
```

right now what get generated is an old set of rules that never gets updated. The only reason I can think of to write a list of rules is so that it acts as a template for users to edit. In that case, can can just generate using the contents of the recommended list

**Comment by adidahiya** [comment]
sgtm :+1:
