### ISSUE TITLE
Custom rule not found when adding it to tslint.json

### ISSUE THREAD

**Issue by ftdube** [palantir/tslint#2203]
I just created my first custom TSLint rule and tried adding it to my tslint.json file.  I'm using WebStorm with Grunt-tslint.  So basically I followed the steps on this page :
https://palantir.github.io/tslint/develop/custom-rules/

I have two files, located under src/tslint in my project,
- noTodoWithoutTaskRule.ts
- noTodoWithoutTaskWalker.ts

My rule's definition is the following : 
 `export class Rule extends Lint.Rules.AbstractRule {
    public static metadata: Lint.IRuleMetadata = {
        ruleName: "no-todo-without-task",
        type: "maintainability",
        description: "Do not leave TODO comments in the code without specifying a task number in JIRA",
        options: null,
        optionsDescription: "",
        typescriptOnly: true
    };

    public apply(sourceFile: ts.SourceFile): Lint.RuleFailure[] {
        return this.applyWithWalker(new NoTodoWithoutTaskWalker(sourceFile, this.getOptions()));
    }
}`

And when adding this to my gruntfile :
`tslint: {
    options: {
        rulesDirectory: '/src/tslint'
    },`

And this the tslint.json file: 
`"no-todo-without-task": true`

I get the following message over and over again in my output : 
> Could not find implementations for the following rules specified in the configuration:
>     no-todo-without-task
> Try upgrading TSLint and/or ensuring that you have all necessary custom rules installed.
> If TSLint was recently upgraded, you may have old rules configured which need to be cleaned up.

I'm not sure what to check for next.  I'd appreciate some help.

Thanks!

**Comment by ajafff** [comment]
Have you compiled your rules with `tsc` before trying to use them?

**Comment by ftdube** [comment]
I have compiled it with grunt-ts

**Comment by nchen63** [comment]
can you try running tslint from the command line?

**Comment by ftdube** [comment]
If I run tslint in the command line with -r pointing at my rules directory and with an existing file, I stop getting the warning.  My rule does not do what it's supposed to do, but that's another story :)  I'll have to debug through it to understand where it fails.  Any idea why it would work in the command line but not with grunt?

**Comment by nchen63** [comment]
the problem is with grunt-tslint. It's fixed but the fix hasn't been released https://github.com/palantir/grunt-tslint/pull/66

**Comment by nchen63** [comment]
ok published grunt-tslint 4.0.1, which should fix the issue.

**Comment by ftdube** [comment]
Updating to 4.0.1 fixed it!  Thank you so much guys!  You're awesome!
