### ISSUE TITLE
Verbose should be the default formatter, and prose should be abandoned

### ISSUE THREAD

**Issue by gotofritz** [palantir/tslint#2228]
The only difference between prose and verbose is that the latter also has the rule name at the beginning of the error message. I can't think of a case when someone would NOT want the rule name - ESlint for example does it by default. To me prose seems completely useless and should be dumped in favour of verbose. Thank you.

**Comment by adidahiya** [comment]
I'm all for it, but it's a small break in case users are parsing the output of the default formatter. Will tackle it in 6.0.

**Comment by JoshuaKGoldberg** [comment]
Removing the `Type: Breaking Change` label per #4811. Now accepting PRs!
