### ISSUE TITLE
tslint won't install with node 7.5.0

### ISSUE THREAD

**Issue by agjs** [palantir/tslint#2238]
For some reason I cannot install tslint with this version of node. I tried google-ing stuff but no luck. Any idea how to fix this ?

### Bug Report

npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ENOTSUP

npm ERR! notsup Unsupported engine for got@5.7.1: wanted: {"node":">=0.10.0 <7"} (current: {"node":"7.5.0","npm":"4.1.2"})
npm ERR! notsup Not compatible with your version of node/npm: got@5.7.1
npm ERR! notsup Not compatible with your version of node/npm: got@5.7.1
npm ERR! notsup Required: {"node":">=0.10.0 <7"}
npm ERR! notsup Actual:   {"npm":"4.1.2","node":"7.5.0"}

**Comment by ajafff** [comment]
The problem comes from an outdated dependency. This is fixed by #2212 which will be published with the next release.

**Comment by agjs** [comment]
Fix being pushed any time soon ?

**Comment by joscha** [comment]
@ajafff would be awesome if we could get that release out ❤️

**Comment by adidahiya** [comment]
planning to release v4.5 this week
