### ISSUE TITLE
Space around Destructuring assignment braces?

### ISSUE THREAD

**Issue by avanderhoorn** [palantir/tslint#2242]
This may already exist but I can't seem to find it, how would I enforce putting spaces on the inside of the braces in destructuring assignment?

```
const {resize} = state.requests; // current
vs
const { resize } = state.requests; // wanted
```

**Comment by KurtPreston** [comment]
It looks like in eslint, this is the `object-curly-spacing` rule:
http://eslint.org/docs/rules/object-curly-spacing

Though it isn't supported by tslint natively, it does look like the [tslint-eslint-rules](https://github.com/buzinas/tslint-eslint-rules) project has added support for it:
https://github.com/buzinas/tslint-eslint-rules/blob/master/src/docs/rules/objectCurlySpacingRule.md

**Comment by RichardMisiak** [comment]
Are there any plans to add this to tslint natively?

**Comment by adidahiya** [comment]
duplicate of #1044
