### ISSUE TITLE
Feature request: ignore-file option for no-import-side-effect

### ISSUE THREAD

**Issue by buu700** [palantir/tslint#2264]
Similarly to the current option that takes a regex to match modules that should be allowed to be imported with side effects, it'd be nice if there were an option that would let me do the same thing except for files in my project.

Specifically, I have a main.ts that imports a decent number of external modules for their side effects by design, and it'd be more convenient to configure `"no-import-side-effect": [true, {"ignore-file": "main\\.ts"}]` than `"no-import-side-effect": [true, {"ignore-module": "(angular|angular-material|jquery|zone\\.js|etc.)"]`. This would also solve the problem that I don't necessarily want any other files performing side-effect imports of, say, zone.js just because main.ts does it.

**Comment by adidahiya** [comment]
I'm fairly opposed to adding file names or globs to rule config options. tslint.json should define __how__ to lint, not __what__ to lint. I suggest using comment flags for your use case. Related: https://github.com/palantir/tslint/issues/629#issuecomment-261291205

**Comment by buu700** [comment]
Cool, makes sense. In that case, is the ignore-module option most likely going to be deprecated at some point?
