### ISSUE TITLE
no-extraneous-dependencies rule

### ISSUE THREAD

**Issue by akosyakov** [palantir/tslint#2280]
Is there are a rule similar to https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md?

**Comment by Antony74** [comment]
I think it might be this one? https://palantir.github.io/tslint/rules/no-implicit-dependencies/

**Comment by JoshuaKGoldberg** [comment]
Yup, that's the one!
