### ISSUE TITLE
Performance : TypeScript 2.3 language service proxy

### ISSUE THREAD

**Issue by cyrilletuzi** [palantir/tslint#2282]
### Bug Report

- __TSLint version__: last
- __TypeScript version__: 2.3
- __Running TSLint via__: VSCode

#### Actual behavior

tslint uses its own TypeScript process, impacting performance.

#### Expected behavior

With TypeScript 2.3 language service proxy, already shipped in nightlys, tslint can use the main TypeScript process, with just this line in tsconfig.json : 
```
{
  "compilerOptions": {
    "plugins": [{ "name": "tslint" }]
  }
}
```

There are already : 
- a try : https://github.com/angelozerr/tslint-language-service
- instructions to do TypeScript plugins : https://github.com/RyanCavanaugh/sample-ts-plugin
- a working example : `@angular/language-service`

**Comment by ondrowan** [comment]
Isn't [angelozerr/tslint-language-service](https://github.com/angelozerr/tslint-language-service) already doing this?

**Comment by cyrilletuzi** [comment]
Closing, as a new VS Code extension is coming for this.
