### ISSUE TITLE
Feature Request: trailing-comma rule customization

### ISSUE THREAD

**Issue by anvish** [palantir/tslint#2286]
Allow separate settings for all covered cases, e.g. allow function parameters to have different settings from object initializers.

**Comment by adidahiya** [comment]
Why? How does it help to treat these things differently?

**Comment by smdern** [comment]
> Why? How does it help to treat these things differently?

Data structures and function signatures are not the same. Adding a trailing comma inside of a data structure makes it easier for you to add/remove re-order if necessary. Where as adding an additional argument to a function has greater consideration. 

Personally I prefer to see trailing commas on multiline objects + lists and no trailing commas when it comes to functions.

**Comment by smdern** [comment]
Having a level of config similar to eslint would be ideal

http://eslint.org/docs/rules/comma-dangle
