### ISSUE TITLE
Rule suggestion: check type of `await`able function

### ISSUE THREAD

**Issue by jvitkauskas** [palantir/tslint#2310]
For example:

```typescript
const returnsVoid = () => { };

async function a() {
    await returnsVoid(); // may be a rule: awaiting on function returning void
}
```

After refactoring code I found that some of my tests were awaiting on void functions. It would be nice if tslint could find those issues.

**Comment by ajafff** [comment]
Try [no-void-expression](https://palantir.github.io/tslint/rules/no-void-expression/)
Admittedly the name is not the best choice and the docs are pretty sparse, but it should do what you need.

**Comment by andy-hanson** [comment]
Better: [await-promise](https://palantir.github.io/tslint/rules/await-promise/)
