### ISSUE TITLE
Use TS 2.3 transformation API for auto-fixes

### ISSUE THREAD

**Issue by adidahiya** [palantir/tslint#2324]
https://github.com/Microsoft/TypeScript/pull/13940

**Comment by ajafff** [comment]
Currently fixes are also included in formatted output and used by tools like `vscode-tslint` to apply only specific fixes.
How do we handle such cases?

Maybe we could use the code actions aka quickfix aka refactorings mechanism provided by tsserver to advertise fixes to editors. Don't know if there is a hook for that, but that probably requires tslint to be used as language service plugin (#2282)

**Comment by JoshuaKGoldberg** [comment]
Given the deprecation of TSLint (#4534), this is no longer a priority. 😢
