### ISSUE TITLE
Test utils used only in eofRuleTests

### ISSUE THREAD

**Issue by andy-ms** [palantir/tslint#2337]
In `test/utils.ts`, the following functions are only used by `eofRuleTests.ts`: `getRule`, `getFormatter`, `applyRuleOnFile`, `createFailure`. `eofRuleTests.ts` could probably be simplified so that these utilities aren't necessary.

**Comment by ajafff** [comment]
I think this test can be removed completely. As of #1966 there are rule tests with markup for this rule.
