### ISSUE TITLE
no-unnecessary-semicolons doesn't pick up semicolons after class functions

### ISSUE THREAD

**Issue by Harley-Adams** [palantir/tslint#2345]
tslint's no-unnecessary-semicolons rule won't report errors for semicolons that are placed after class functions. 

```ts
public doStuff() {

}; 
```

I noticed this when comparing with the no-extra-semi rule from https://github.com/buzinas/tslint-eslint-rules.

**Comment by ajafff** [comment]
Do you mean the rule [`semicolon`](https://palantir.github.io/tslint/rules/semicolon/)?
The behaviour you describe, was added with #2240 and will be released with tslint 5.0

**Comment by Harley-Adams** [comment]
Oh Excellent! 

I got mixed up between tslint's semicolon rule and tslint-microsoft-contrib's no-unnecessary-semicolons rule. Neither currently picked up semicolons after class functions but happy it's being added in 5.0

Thanks!
