### ISSUE TITLE
Which rules will be automatically fixed?

### ISSUE THREAD

**Issue by NCC1701M** [palantir/tslint#2349]
In your documentation you write 

> --fix &nbsp;&nbsp;&nbsp;&nbsp;fixes linting errors for select rules (this may overwrite linted files)

But I found no place where you describe which rules these are. Please update your documentation.

**Comment by nchen63** [comment]
Our docs have tags indicating whether or not the rule is auto fixed https://palantir.github.io/tslint/rules/
