### ISSUE TITLE
Code with regular expression gets incorrectly "fixed"

### ISSUE THREAD

**Issue by benny-medflyt** [palantir/tslint#2366]
This code snippet:

```ts
    if (!(/^[0-9.]+$/.test(val))) {
        return "Invalid number";
    };
```

get incorrectly "fixed" into this broken code:

```ts
    if (!(/^[0-9.]+$/.test(val))) {
        return "Invalid number";
    ;
```

I'm using a pretty basic tslint.json that extends "tslint:latest"

**Comment by ajafff** [comment]
It would be nice to know which rules applied fixes to the file.
Can you restore the file to the state where the problem occured and run `tslint` without the `--fix` option and post the output here.

There have been similar issues with fixes corrupting files recently. Unfortunately they can not be reproduced very easily. It seems to occur on larger files with many rule failures and applied fixes.
It would be nice if you could share some more code so we can invesitage this further.

**Comment by benny-medflyt** [comment]
Turns out to not have anything to do with regular expressions:

### Test.ts
```ts
function foo(val: string): string | null {
    if (val.trim().length === 0) {
        return "Required";
    };
    return null;
}
```

### tslint.json
```json
{
    "extends": ["tslint:recommended"]
}
```

```
$ ./node_modules/.bin/tslint --version
4.5.1
$ ./node_modules/.bin/tsc --version
Version 2.2.1
$ ./node_modules/.bin/tslint -c ./tslint.json ./Test.ts -t verbose --fix
(align) Test.ts[4, 5]: statements are not aligned
(align) Test.ts[5, 5]: statements are not aligned
```

### Fixed Test.ts
```ts
function foo(val: string): string | null {
    if (val.trim().length === 0) {
        return "Required";
    ;
    return null;
}
```
