### ISSUE TITLE
Bug with "strict-type-predicates"

### ISSUE THREAD

**Issue by benny-medflyt** [palantir/tslint#2376]
This is the simplest example i could find that shows the error. The "strict-type-prediates" rule gives the message "Expression is always true" on a code fragment where it is not so.

The following example requires the https://github.com/gcanti/monocle-ts library

```
$ npm install --save monocle-ts
```

### tslint.json
```json
{
    "extends": ["tslint:recommended"],
    "rules": {
        "strict-type-predicates": true
    }
}
```

### tsconfig.json
```json
{
    "compilerOptions": {
        "strictNullChecks": true
    }
}
```

### Helper.ts
```ts
import { Lens } from "monocle-ts";

export interface IFieldState<T> {
    value: T;
}

export interface IFormField<S, T> {
    lens: Lens<S, IFieldState<T>>;
    validate: (val: T, state: S) => string | null;
}

export function makeFormField<S, T>(
    lens: Lens<S, IFieldState<T>>,
    validate: (val: T) => string | null): IFormField<S, T> {
    return {
        lens,
        validate,
    };
}
```

### Test.ts
```ts
import { Lens } from "monocle-ts";
import { IFieldState, makeFormField } from "./Helper";

export interface IState {
    gender: IFieldState<string | undefined>;
}

makeFormField(Lens.fromProp<IState, "gender">("gender"), (v) => v !== undefined ? null : "Required");
```

```
$ ./node_modules/.bin/tsc --project .
$ ./node_modules/.bin/tslint -c ./tslint.json -t verbose --type-check --project ./tsconfig.json 
(strict-type-predicates) Test.ts[8, 65]: Expression is always true.
```

It is referring to the expression `v !== undefined`. Note that the type of `v` in this expression is `string | undefined`, as can be determined by a careful analysis of the code, or by asking visual studio code:

<img width="389" alt="tmp0010" src="https://cloud.githubusercontent.com/assets/24827547/24086831/007ef7f6-0ced-11e7-8174-b29fcd2981fe.png">

Notes:
  - If the files Helper.ts and Test.ts are merged into a single file, then tslint works as expected and does not report the incorrect message.
  - If an explicit type annotation is added to the arrow function in question(`(v: string | undefined) => ...`), then tslint works as expected and does not report the incorrect message.

Thank you

**Comment by andy-hanson** [comment]
May be a mismatch of the TypeScript version used to lint ant the TypeScript version in VSCode. When I try this code in VSCode using `typescript@next`, I see `v: string`. Try setting [`typescript.tsdk`](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions) in your settings.

**Comment by benny-medflyt** [comment]
thanks for the reply. in order to try to figure out what's going on, i'm completely taking VSCode out of the equation...

I've changed the "makeFormField" call in "Test.ts" to have an intentional type error, in order for the `tsc` compiler to report what it is inferring the type of the `v` to be:

```ts
makeFormField(Lens.fromProp<IState, "gender">("gender"), (v) => {
    const x: number = v; // <- type error here so that tsc will tell us the type of v
    return v !== undefined ? null : "Required";
});
```

```
$ ./node_modules/.bin/tsc --project .
Test.ts(9,11): error TS2322: Type 'string | undefined' is not assignable to type 'number'.
  Type 'undefined' is not assignable to type 'number'.
```

As you can see, `tsc` is reporting that v is of type `v: string | undefined`. I get this result with typescript versions 2.1.4, 2.2.1, and 2.3.0-dev.20170325.

Would you mind using this modified code snippet and sharing the error message that `tsc` gives you? i appreciate you taking the time to look into this

Thank you

**Comment by andy-hanson** [comment]
Now I'm getting `v: string | undefined` correctly in both situations (no lint error). So I suspect you have different configurations when you compile/lint the project. I used these steps:

* `mkdir tslint-fresh`
* `cd tslint-fresh`
* `echo "{}" > package.json`
* `npm install --save typescript@next tslint@next monocle-ts`
* `echo '{ "compilerOptions": { "strictNullChecks": true } }' > tsconfig.json`
* Create `test.ts` containing:

```ts
import { Lens } from "monocle-ts";

interface IFieldState<T> {
    value: T;
}

interface IFormField<S, T> {
    lens: Lens<S, IFieldState<T>>;
    validate: (val: T, state: S) => string | null;
}

function makeFormField<S, T>(
    lens: Lens<S, IFieldState<T>>,
    validate: (val: T) => string | null): IFormField<S, T> {
    return {
        lens,
        validate,
    };
}

interface IState {
    gender: IFieldState<string | undefined>;
}

makeFormField(Lens.fromProp<IState, "gender">("gender"), (v) => {
    //const x: number = v; // <- type error here so that tsc will tell us the type of v
    return v !== undefined ? null : "Required";
});
```

* `tsc` (no errors)
* `echo '{ "rules": { "strict-type-predicates": true }}' > tslint.json`
* `tslint --project tsconfig.json --type-check` (no errors)
