### ISSUE TITLE
Publish a NuGet package

### ISSUE THREAD

**Issue by JustinBeckwith** [palantir/tslint#239]
Our team uses MSBuild, and we'd like to run tslint as part of that build process.  We're interested in building a package that includes the nuspec, targets file, and build script.  We can either stand up a repo that just has this content and a package.json, or we could submit a PR here with those files.  Would you prefer supporting NuGet/MSBuild from this repro, or should that be a separate project?

**Comment by ashwinr** [comment]
closing for now. let us know if we can help with the PR
