### ISSUE TITLE
Youtube video request/opportunity

### ISSUE THREAD

**Issue by QuantumInformation** [palantir/tslint#2397]
Would be great to have a video on how to use it, not much up there.

![image](https://cloud.githubusercontent.com/assets/216566/24297905/45650074-109c-11e7-93f3-74ce84824e14.png)

**Comment by johnwiseheart** [comment]
Theres a number of TSLint videos on youtube now, so going to close this one out.

**Comment by QuantumInformation** [comment]
np thx
