### ISSUE TITLE
Windows usage instructions

### ISSUE THREAD

**Issue by lookbusy1344** [palantir/tslint#24]
Can we have some instructions about using tslint on Windows? Tried cscript tslint-cli.js -f myfile.ts but no joy

**Comment by jmolero** [comment]
I've got the same error: Cannot find module './tslint-cli'

**Comment by johnsparrowuk** [comment]
Have you got Node.js installed? I'm no expert but this is what I do:

Install Node.js
Log out, and back in (just in case, to set up path)
Open cmd.exe and run 'npm install tslint -g'
From a command prompt, check 'tslint --version' to check it's installed

I think palantir should add some installation instructions, I'd never used Node before TsLint.

Incidentally, for noobs here's a quick and dirty Powershell script to TsLint all your project's ts files (with an exclude list for 3rd party d.ts files etc):

https://www.dropbox.com/s/ne9m3hkag5bnd9r/TsLint%20files.ps1?dl=0

**Comment by jmolero** [comment]
It's working. My path was pointing to a wrong tslint installation.

Thanks for the help.
