### ISSUE TITLE
Suggestion: add a formatter for Visual Studio

### ISSUE THREAD

**Issue by aleksey-bykov** [palantir/tslint#240]
It would be really nice to have an official formatter for Visual Studio output. The format is described here: http://msdn.microsoft.com/en-us/library/yxkt8b26.aspx

Working JS code can be found here: https://gist.github.com/aleksey-bykov/f83411143506c5c50e4a#file-vsformatter-js

**Comment by JKillian** [comment]
I think this is fixed by #947
