### ISSUE TITLE
rule: all switch statements must have a default case statement

### ISSUE THREAD

**Issue by ashwinr** [palantir/tslint#242]

**Comment by Pajn** [comment]
Is this `switch-default`?

**Comment by adidahiya** [comment]
yep, good catch @Pajn

**Comment by adidahiya** [comment]
fixed by #338

**Comment by sahilanguralla** [comment]
Shouldn't it only warn if all cases are not covered similarly like Swift? 

Suppose I have switched enum. If I have handled all the case, it shouldn't throw lint error.

**Comment by adidahiya** [comment]
@sahilanguralla this issue is quite old, please open a new one or search for existing issues which are more relevant to your question
