### ISSUE TITLE
Ignore rules for all files

### ISSUE THREAD

**Issue by beckmx** [palantir/tslint#2429]
### Bug Report

- __TSLint version__: 4.5.1
- __TypeScript version__: 2
- __Running TSLint via__: CLI

I have been trying to make tslint to ignore some rules for all the files in a repository and I used this configuration in the files but is not working, my current configuration is:

{
    "extends": "tslint:recommended",
    "tslint:disable": "max-line-length quotemark"
}

**Comment by ajafff** [comment]
`tslint:disable` can be used as comment to disable rules in specific files / line ranges

if you want to disable some rules completely in your `tslint.json`, try the following:
```json
{
  "extends": "tslint:recommended",
  "rules": {
    "max-line-length": false,
    "quotemark": false,
  }
}
```
