### ISSUE TITLE
List all rules that haven't been specified in your tslint.json

### ISSUE THREAD

**Issue by khoomeister** [palantir/tslint#2444]
Wow, tslint has improved so much - awesome!  However, there are so many new rules now it's hard to keep track of them.

Is there a way to list all rules that haven't been explicitly specified in your tslint.json?

That way, when new rules come out, I can just run a command, look at the list of new rules that aren't specified in my `tslint.json`, read up on the documentation and specify them.  This is better than my suboptimal eyeballing at the moment.

**Comment by adidahiya** [comment]
Fair point. We're working on a `tslint:all` configuration that lists all the rules (https://github.com/palantir/tslint/pull/2417). Do you think that sufficiently addresses this problem?

It would also be pretty easy to write a Node script to compare your list of configured rules to the list of files that match `node_modules/tslint/lib/rules/*Rule.js`. [This code](https://github.com/andy-hanson/tslint/blob/71b3107ed2b0c6b8add013f84692a5087f863cbf/test/ruleLoaderTests.ts#L157) does something close to this.

**Comment by khoomeister** [comment]
How about if you use custom rules, like tslint-react, etc.?

Is there some code path which reads the extends & rulesDirectory settings and makes a list of every single rule available?  Then I can use this to diff against tslint.json.

**Comment by khoomeister** [comment]
Hacked up something just now: https://github.com/khoomeister/check-tslint-all

**Comment by JoshuaKGoldberg** [comment]
Thanks for that `check-tslint-all`! This seems out of scope for TSLint itself, so closing this issue for now. If there's a spike in interest we can always revisit.
