### ISSUE TITLE
Add custom handlers for errors

### ISSUE THREAD

**Issue by AlexanderBukhtaty** [palantir/tslint#2448]
Hello, How i can auto-fix error like "missing whitespace" or "== should be ==="?
Maybe I can add error handlers?

**Comment by JoshuaKGoldberg** [comment]
👏 @AlexanderBukhtaty - you can run TSLint with `--fix` when simpler rules such as `whitespace` report how to fix complaints.

For more complicated rules such as `triple-equals`, there's ongoing discussion in #2625.
