### ISSUE TITLE
Rule suggestion: add "allow-multiline" for rule `prefer-template`

### ISSUE THREAD

**Issue by vilic** [palantir/tslint#2471]
E.g.:

```ts
function foo(texts: string[]) {
    return texts
        .map(text => ...)
        .join('\n') + '\n';
}
```

**Comment by JoshuaKGoldberg** [comment]
☠️ *TSLint's time has come!* ☠️ 

TSLint is no longer accepting most feature requests per #4534. See **[typescript-eslint.io](https://typescript-eslint.io)** for the new, shiny way to lint your TypeScript code with **ESLint**. ✨ 

It was a pleasure open sourcing with you all!
