### ISSUE TITLE
Subtle bug in the severity rules when using nested tslint.json files

### ISSUE THREAD

**Issue by jonaskello** [palantir/tslint#2476]
### Bug Report

- __TSLint version__: 5.0.0
- __TypeScript version__:  2.2.2
- __Running TSLint via__:  CLI

#### TypeScript code being linted

Minimal repro with failing travis build available here:

https://github.com/jonaskello/tslint-repro

#### Actual behavior

When I have nested tslint.json files the `no-consecutive-blank-lines` rule fails with this error:

`Error: Severity for rule 'no-consecutive-blank-lines not found`

See the [travis build](https://travis-ci.org/jonaskello/tslint-repro) for full stack.

The same seems to happen with the `whitespace` and `semicolon` rules.

#### Expected behavior

To sucessfully lint without exceptions.

**Comment by jonaskello** [comment]
Btw, I extracted this repro from a larger code base where I got the error. I managed to work around it now. With tslint4 our linting took about 17 seconds. Now with tslint5 it takes 7 seconds. Thank you for the performance boost 👍 🚀.

**Comment by huy-nguyen** [comment]
I'm having this problem as well. @jonaskello How did you work around this bug?

**Comment by jonaskello** [comment]
I temporarily removed the nested `tslint.json` file from the sub-tree. This way the rules from the parent file is applied to the code in the sub-tree. This gave me a bunch of error because the rules in the parent are not meant to be applied to the sub-tree (hence the nested tslint.json). However from these errors I filtered out only errors concerning `no-consecutive-blank-lines`, `whitespace`, and `semicolon` and fixed those in the sub-tree. Then I put the nested tslint.json back and it worked. Seems only those three rules are affected by this bug.
