### ISSUE TITLE
Proposal: ban-syntax

### ISSUE THREAD

**Issue by andy-hanson** [palantir/tslint#2497]
The only way to use JavaScript and maintain sanity is to ban 90% of it.
That's why there are many current and desired tslint rules that do nothing but ban a particular kind of syntax from appearing. May not always be as simple as banning a SyntaxKind, but it's usually very simple.

|           Syntax           |   Name   |
| -------------------------- | -------- |
| `import "foo";`            | `no-import-side-effect` |
| `any`                      | `no-any` |
| `namespace`                | `no-namespace` |
| `x!`                       | `no-non-null-assertion` |
| `/// <reference path="">`  | `no-reference` |
| `<<<`, `~`, etc.           | `no-bitwise` |
| `debugger`                 | `no-debugger` |
|  `eval`                    | `no-eval` |
| `null`                     | `no-null-keyword` |
| `var`                      | `no-var-keyword` |
| `==` / `!=`                | `triple-equals` |
| `<T> x`                    | `no-angle-bracket-type-assertion` |
| `constructor(public x)`    | `no-parameter-properties` |
| `export default`           | `no-default-export` |
| `class`, `this`, `new`     | [`no-class`, `no-this`, `no-new`](https://github.com/jonaskello/tslint-immutable#functional-style-rules) |
| `let`, `arguments`         | [`no-let`, `no-arguments`](https://github.com/jonaskello/tslint-immutable#other-rules)
| `label: while (true) {}`   | [`no-label`](https://github.com/jonaskello/tslint-immutable#other-rules)
| `[,]`                      | `no-sparse-arrays` (#2407) |
| `delete`                   | TODO |
| `x in y`                   | TODO |
| `for (x in y)`             | TODO |
| `with (x) {}`              | TODO |
| `{ [x: string]: number }`  | TODO |
| `import x = require("y");` | TODO |
| `;` (empty statement)      | TODO |
| `new.target`               | TODO |
| Your most hated feature    | TODO |

My proposal is to deprecate them all and have a single rule `ban-syntax` rule that is configurable.
It would behave the same as the separate rules, but would help cut down on rule bloat.

**Comment by andy-hanson** [comment]
One problem would be that `// tslint:disable ban-syntax` isn't as nice as `// tslint:disable no-bitwise`. `ban-types` has the same problem.
But I also think the [Rules list](https://palantir.github.io/tslint/rules/) is getting kind of intimidating.

**Comment by IllusionMH** [comment]
Other possible downside (or plus side for someone) - using extend in `tslint.json`: If new rule can be added to `tslint:recommend` with own configuration - than it will be applied to consumers code.

With single rule list of banned syntaxes will be overridden(if I remember it correctly) and changes to recommended config won't have any effect.

**Comment by JoshuaKGoldberg** [comment]
### 💀 _**It's time!**_ 💀

**TSLint is being deprecated** and no longer accepting pull requests for new rules. See #4534. 😱

If you'd like to see this rule implemented, you have two choices:
* **Recommended:** Use [typescript-eslint](https://typescript-eslint.io) to lint your TypeScript code with ESLint ✅
* **Legacy:** Write it as a [custom TSLint rule](https://palantir.github.io/tslint/develop/custom-rules/) 🤷‍♂️

👋 It was a pleasure open sourcing with you!

_If you believe this message was posted here in error, please comment so we can re-open the issue!_
