### ISSUE TITLE
Suggestion: Add checkstyle formatter

### ISSUE THREAD

**Issue by huerlisi** [palantir/tslint#250]
The checkstyle format is supported by the jshint library and support in Jenkins Validation plugin. It would make tslint a bit more up to par with jshint.

**Comment by ashwinr** [comment]
closing for now. please comment with a spec and we can support the checkstyle formatter natively

**Comment by huerlisi** [comment]
The homepage of the project is http://checkstyle.sourceforge.net/

I haven't found an actual spec unfortunately, but it seems a simple form.

**Comment by huerlisi** [comment]
I did some more googling but was actually not able to find something:-(

According to this google message https://groups.google.com/forum/#!topic/checkstyle-devel/ozgxErB4DdQ the output format for the XML is defined here: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/XMLLogger.java

Here's a list of checks that are implemented in the checkstyle project for Java: http://checkstyle.sourceforge.net/checks.html

This plugin adds checkstyle reporting to jshint: https://github.com/sublimeye/jshint-jenkins-checkstyle-reporter Here's the actual code generating the XML output: https://github.com/sublimeye/jshint-jenkins-checkstyle-reporter/blob/master/src/reporter.js

Hope this helps:-)

**Comment by sshev** [comment]
Hi! I've created PR for checkstyle formatter - pls check it
https://github.com/palantir/tslint/pull/1143

**Comment by JKillian** [comment]
Merged #1143 which fixes this. It will be available in the next release! Please note that #656 is still open which can cause issues with formatters depending on use
