### ISSUE TITLE
casing of ruleSeverity 

### ISSUE THREAD

**Issue by chrismbarr** [palantir/tslint#2507]
I have a set of custom rules that I'm trying to convert over to TSLint 5, but I'm having some issues getting my tests to pass due to the new `ruleSeverity` property.  Right now my rules do not specify a severity, so they must be picking up the default severity of `"ERROR"` , but in my tests I'm only allowed to specify the severity names in lowercase due to [this type](https://github.com/palantir/tslint/blob/master/src/language/rule/rule.ts#L90)

Here's a sample of my current test output:
![2017-04-05 15_19_27-](https://cloud.githubusercontent.com/assets/463685/24723124/3af9181a-1a14-11e7-83f7-7308133f92ee.png)

and here's the error I get if I attempt to force it up uppercase

![2017-04-05 15_25_52- appriverangularcallrequiresprefixrule tests ts - appriver tslintrules - visual](https://cloud.githubusercontent.com/assets/463685/24723141/4bd37f90-1a14-11e7-9b40-86b684bd2057.png)

So... why does this maintain a strongly-typed list of allowed strings, but actually use a different string internally?  Right now my quick fix is to just ignore the severity from the failure comparisons in my tests, I don't love it, but it works for now since none of my custom rule have a severity specified anyway.

**Comment by nchen63** [comment]
Is your default rule severity uppercase? Try changing it to lowercase. I'll put in a check for that

**Comment by nchen63** [comment]
Actually, there is a check to ensure that defaultRuleSeverity is consistent https://github.com/palantir/tslint/blob/master/src/configuration.ts#L306

Not sure how you're getting the uppercase

**Comment by chrismbarr** [comment]
I have not defined any severity anywhere, I am migrating old rules from the TSlint 4 syntax to 5, and I'm not specifying severity anywhere, not even in a config file.  Note that the red & uppercase text in the screenshot above is the "actual".

Looking into it a bit, it seems to come from this: https://github.com/palantir/tslint/blob/master/src/language/rule/rule.ts#L290

If I remove the `.toUpperCase()` in my local copy, it works as expected. It seems to me like this shouldn't be there.

**Comment by nchen63** [comment]
Yeah, this isn't ideal to have the JSON output severity as uppercase, but they are different types. Can you modify IExpectedFailure to use IRuleFailureJson instead?

**Comment by chrismbarr** [comment]
I suppose I can just uppercase the severity in my own tests right before the comparison... just seems like a strange workaround.

**Comment by olore** [comment]
I think this was my bad. @chrismbarr Can you see if #2622 fixes it for you?
