### ISSUE TITLE
[no-use-before-declare] too strict on class members

### ISSUE THREAD

**Issue by RIAstar** [palantir/tslint#251]
Given this example:

```ts
class Foo {

    // variables go here

    constructor() {
        this.fooBar = sequence(this.foo, this.bar);
    }

    // methods go here

    public fooBar:() => void;
    private foo():void {}
    private bar():void {}

}
```

Since `fooBar` is a function, I like to group its declaration with the rest of the class methods.
However tslint throws a `variable 'fooBar' used before declaration` error.

I think this is too strict because those declarations are TypeScript compiler markers that don't result in any generated JavaScript. This is the generated JS for the example:

```ts
var Foo = (function () {
    function Foo() {
        this.fooBar = sequence(this.foo, this.bar);
    }
    Foo.prototype.foo = function () { };
    Foo.prototype.bar = function () { };
    return Foo;
})();
```

Completely legit.

The ordering of the members that I use here might be debatable, but [member-ordering] is supposed to check that, not [no-use-before-declare].

Possibly related to the fix for #89

**Comment by leeavital** [comment]
I just tried both examples with the most up-to-date version of tslint and there were no issues. Can we close this one?
