### ISSUE TITLE
improve docs for no-reference import

### ISSUE THREAD

**Issue by chrismbarr** [palantir/tslint#2511]
https://palantir.github.io/tslint/rules/no-reference-import/

The **entire** documentation for this rule is as follows:

>"Don’t if you import “foo” anyway."

I have no idea what that means or what this rule does based on this description.  "Don't" what?

**Comment by adidahiya** [comment]
<reference> probably needs to be escaped in the HTML.

**Comment by adidahiya** [comment]
.... and I did it again here. `<reference>` path imports are disallowed

**Comment by nchen63** [comment]
should escape in code generation, not in metadata

**Comment by hyndsite** [comment]
@adidahiya maybe I am missing something, but is that any different than the [no-reference ](https://palantir.github.io/tslint/rules/no-reference/) rule?
