### ISSUE TITLE
Using (Block/)ScopeAwareRuleWalker with typed programs

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [palantir/tslint#2514]
I don't see any examples of creating a `ScopeAwareRuleWalker` with a typed rule. Is this intended to be doable?

There could be `TypedScopeAwareRuleWalker` + `TypedBlockScopeAwareRuleWalker`, but it feels wrong to make a cross-matrix of all the potential rule types against each other.

**Comment by ajafff** [comment]
You can just override the constructor, pass the type checker as argument
and save it in a property. That's the whole magic `ProgramAwareRuleWalker`
does

Am 06.04.2017 22:12 schrieb "Josh Goldberg" <notifications@github.com>:

**Comment by JoshuaKGoldberg** [comment]
This is true, but then for the first `createScope` call it won't have access to the type checker. Overriding a constructor also feels dirty.

**Comment by andy-hanson** [comment]
These classes should really not be used. In every example I have seen they were just used to maintain some context, and the actual rule had nothing to do with scopes. It's better to just use `ts.forEachChild` and use local variables to store context.

**Comment by JoshuaKGoldberg** [comment]
Should they be deprecated then?
