### ISSUE TITLE
tslint marking carriage returns as errors

### ISSUE THREAD

**Issue by shudson250** [palantir/tslint#2523]
### Bug Report

- __TSLint version__: 5.0.0
- __TypeScript version__: 2.2.0
- __Running TSLint via__: VSCode
Windows 10, Node 7.8.0

This started occurring after upgrading from tslint 4.5.1

I would run my app using Yarn, and once it finished compiling, I would get 67 warnings thrown in the Chrome console and command window, all with nothing listed as the error:
![image](https://cloud.githubusercontent.com/assets/3361507/24826931/45ca3006-1bf6-11e7-8a28-8ae80606747d.png)

I debugged the error, it pointed to where webpack would just console.warn any warnings it was passed. Inspecting the warnings I could see a carriage return symbol being listed, but as it was shown in the console/command window, it was just as the image above shows.

After going back to tslint 4.5.1 the warnings have disappeared, so it's not something else.

**Comment by nchen63** [comment]
Could you diff your WebPack outputs before and after upgrading TSLint?

**Comment by johnwiseheart** [comment]
Not sure if this still exists, but because of its age I'm going to close it as it's likely been fixed since this issue was created.
