### ISSUE TITLE
New rule to only allow boolean statements in logical expressions

### ISSUE THREAD

**Issue by oefirouz** [palantir/tslint#253]
Disallow if (expr) unless expr is a boolean.

So no if (obj)... rather if (obj != null)

**Comment by adidahiya** [comment]
I think the new TS APIs have support for type information about nodes. This should be doable.

**Comment by adidahiya** [comment]
blocked on #680

**Comment by JKillian** [comment]
See https://github.com/Microsoft/TypeScript/issues/9702 as well, although as far as I can tell they haven't decided to implement this yet. This shouldn't be too hard to do now on our end!

**Comment by Sammons** [comment]
I would really like this to help with not coercing promise-like types to booleans, but I think it would be really nice if we could explicitly enable certain types (strings, numbers) for coercion.

**Comment by radykov** [comment]
> I think the new TS APIs have support for type information about nodes. This should be doable.
 
Would this be able to pick up things such as `x = y || z`;? 
I'm unfamiliar with TS APIs and what was meant by nodes

**Comment by OliverJAsh** [comment]
This would be really handy and catch so many bugs.

**Comment by adidahiya** [comment]
fixed via #1820
