### ISSUE TITLE
How to make trailing-comma "false" for multiline, but "never" for singleline?

### ISSUE THREAD

**Issue by trusktr** [palantir/tslint#2541]
For example, something like

```
"trailing-comma":            [true, {"multiline": false, "singleline": "never"}]
```

so that multiline trailing commas are optional (tslint won't care if they exist or not), but will enforce never for singleline trailing commas?

Or does that work?

**Comment by trusktr** [comment]
Ahh, apparently `"multiline": false` works, but that isn't documented, the docs say it should be "alway" or "never", maybe that can be made more clear.

**Comment by JoshuaKGoldberg** [comment]
☠️ *TSLint's time has come!* ☠️ 

TSLint is no longer accepting most feature requests per #4534. See **[typescript-eslint.io](https://typescript-eslint.io)** for the new, shiny way to lint your TypeScript code with **ESLint**. ✨ 

It was a pleasure open sourcing with you all!
