### ISSUE TITLE
Opposite of one-line

### ISSUE THREAD

**Issue by borsosl** [palantir/tslint#255]
I think many prefer C-style placement of curly brackets, who would like to enforce this style, not only tolerate it.
Eg. my preference is this: starting curly is right under if, else, for, while. But on the same line with try, catch, do. Ending curly is on the same line with catch and while of do-while.

**Comment by ashwinr** [comment]
would love this as a PR, let us know if you need any help.

**Comment by joelday** [comment]
@ashwinr What would be the right name for the rule?
