### ISSUE TITLE
Handle overlapping fixes

### ISSUE THREAD

**Issue by ajafff** [palantir/tslint#2556]
How should the linter handle overlapping fixes? Currently the behavior is not documented and sometimes not even predictable.

Rules like `prefer-const` work around this restriction by maintaining a list of fixes to deduplicate them.

#2225 faced a problem when the replacements started at the same position. 
The fixer for `callable-types` (#2552) destroy parts of the code when there are also fixes for nested nodes.

There are several ways to handle this.
1. Check overlapping and bail out before applying any fix
2. Apply fixes and ignore ones that overlap the previous fix and ...
    * just continue
    * log a warning
    * lint the file again with that rule and try to apply the new fixes ...
        * once
        * n times
        * until there are no more fixes (probably not the best idea)
3. just ignore it until we can use transforms for the fixes

**Comment by andy-hanson** [comment]
If #2557 is fixed, then I think an individual rule *should* be responsible for not giving contradictory (overlapping) fixes.

**Comment by adidahiya** [comment]
There's also a related problem of sequential fixes -- see #2918. Since rules don't communicate with each other, you might produce invalid code after one round of fixes, unrelated to the disabled intervals problem.

I propose that we go with option 2 above and try to apply fixes multiple times in succession. We could set n = some reasonable default value (perhaps 2 to start) and let the user configure it with a CLI flag.

**Comment by gruberb** [comment]
Any progress on this?

**Comment by ericanderson** [comment]
Proposal pseudo-code:
```
declare function recheckFileWithAllRules();
declare let fixesToApply: Array<{ fix: Function; type: string }>;
const appliedFixes = new Set<string>();

while (fixesToApply.length) {
  fixesToApply[0].fix();
  appliedFixes.add(fixesToApply[0].type);

  fixesToApply = recheckFileWithAllRules().filter(a => appliedFixes.has(a));
}
```

Only thing is this might get expensive if the rule requires the `TypeChecker`.

**Comment by JoshuaKGoldberg** [comment]
Given the deprecation of TSLint (#4534), this is no longer a priority. 😢
