### ISSUE TITLE
DisabledIntervals are not updated after applying fix

### ISSUE THREAD

**Issue by ajafff** [palantir/tslint#2557]
After a fix was applied to a file, the disabled intervals are not updated to reflect that change.
All rules that follow will be disabled for the wrong intervals.

When line breaks are inserted or removed by the fix, comments like `disable-line` or `disable-next-line` will be completely wrong.
To make sure the intervals are right, the linter needs to scan the whole file again after every rule with fixes.

**Comment by andy-hanson** [comment]
Should be fixed in #2369.

**Comment by ajafff** [comment]
Fixed by #2369
