### ISSUE TITLE
Selectively enable Completed-docs based on names/keywords

### ISSUE THREAD

**Issue by jdolle** [palantir/tslint#2574]
I would like to be able to selectively enforce `completed-docs` on my variables based on variable names.

This is for my react project. I want to enforce documenting `propTypes` and the props defined inside, but I don't want to enforce this for other variables.

**Comment by JacobRReed** [comment]
I second this, but for method names. Currently developing with Angular and I want to enforce JSDoc on all methods and classes, but not the lifecycle methods such as ngOnInit, ngOnDestroy etc etc

**Comment by JoshuaKGoldberg** [comment]
☠️ *TSLint's time has come!* ☠️ 

TSLint is no longer accepting most feature requests per #4534. See **[typescript-eslint.io](https://typescript-eslint.io)** for the new, shiny way to lint your TypeScript code with **ESLint**. ✨ 

It was a pleasure open sourcing with you all!
