### ISSUE TITLE
Don't copy-paste '.ts.lint' tests for '.js.lint' tests

### ISSUE THREAD

**Issue by andy-hanson** [palantir/tslint#2578]
Many tests have a `test.js.lint` file that is identical to, or an outdated version of, the `test.ts.lint` file.
I'm not convinced these tests really need to exist, since rules will run the exact same code on the exact same AST regardless of file extension.

If the concern is that people will forget to set `typescriptOnly` on a rule that only deals with a TypeScript construct, these tests won't help since TypeScript will let you put types in a `.js` file, then issue a diagnostic which we ignore.

**Comment by nchen63** [comment]
I agree, we can deduplicate most of these
