### ISSUE TITLE
Import Spacing Rule

### ISSUE THREAD

**Issue by davidbarratt** [palantir/tslint#2593]
Is there a way to enforce:
```
import { TitleComponent } from "./title.component";
```

Instead of:
```
import {TitleComponent} from "./title.component";
```

If not, can this be added?

**Comment by adidahiya** [comment]
the whitespace rule ought to do this, but it may have a bug at the moment: https://github.com/palantir/tslint/issues/2401

**Comment by rimiti** [comment]
This issue could be reopen, the problem persist... 🙏 😞
