### ISSUE TITLE
Question: can we log the duration of individual rules?

### ISSUE THREAD

**Issue by negberts** [palantir/tslint#2594]
(Gulp-)TSLint is taking pretty long (> 2 minutes) since we are using rules from codelyzer and rules from tslint-contrib-microsoft. I wanna know which rules are 'expensive'. Is there any way in the report system to maybe log the duration of each individual rule executed?

**Comment by JoshuaKGoldberg** [comment]
Related:
* Discussion in #2522 on logging a map of rule times
* #2267 for having a "summary" report

It'd be nice to add timing information to that summary report.

Blocked on #2267's summary report being implemented.

**Comment by JoshuaKGoldberg** [comment]
Given the deprecation of TSLint (#4534), this is no longer a priority. 😢
