### ISSUE TITLE
Question underscore

### ISSUE THREAD

**Issue by darklinki** [palantir/tslint#2595]
Hello,

just a small question, I dont see there an option to allow underscores in variable names.  Is there a reason for this ? 

Got the the problem e.g. item_id. 
If I rename it to itemid I get a error cause of spell checking and it looks not very well. 
If I rename it to ItemId I get a problem to fetch the infos in ts from json(php).

**Comment by ajafff** [comment]
#2383 added the option `"allow-snake-case"` which does exactly what you want. This option initially shipped with tslint@5.0.0

**Comment by adidahiya** [comment]
fixed with #2190

**Comment by darklinki** [comment]
Ty than I just have to wait until codealyser supports ts lint 5.
