### ISSUE TITLE
Strict options for 'no-console-rule' in 'tslint:all' configuration

### ISSUE THREAD

**Issue by roman-petrov** [palantir/tslint#2602]
### Bug Report

- __TSLint version__ : 5.1.0
- __TypeScript version__: 2.2.2
- __Running TSLint via__: CLI

Recently we migrated TSLint to 5.1.0, extended our tslint.json from '**tslint:all**' rule set and removed many rules from our tslint.json. We found that '**no-console**' rule specified as

``
 'no-console: true';
``

in 'tslint:all' configuration, but we used it as 

``
 "no-console": [
            true,
            "log",
            "debug",
            "info",
            "time",
            "timeEnd",
            "trace"
        ];
``

So if, for example, **console.log** function is used in code, it successfully passes '**tslint:all**' configuration. I suggest one of these changes:

- change '**tslint:all**' rule set and add all options to '**no-console**' rule 
- change '**no-console**' rule so it will show error on all console functions if '**no-console: true**' is specified.

**Comment by adidahiya** [comment]
good catch. I prefer your second proposal:

> change 'no-console' rule so it will show error on all console functions if 'no-console: true' is specified.

this is a small breaking change, but this might be ok to introduce in a minor version. any current configs that rely on `no-console: true` are probably using it incorrectly.

**Comment by roman-petrov** [comment]
thanks, I completely agree with you and prefer second option too
