### ISSUE TITLE
What's the rationale for the array-type rule?

### ISSUE THREAD

**Issue by trusktr** [palantir/tslint#2609]
For example, by default we have to do

```ts
Array<DataNode<GameObjectTreeNode>>
```

instead of

```ts
DataNode<GameObjectTreeNode>[]
```

Is there some problem that this prevents? Or is it just style preference, and I can disable the rule without concerns?

**Comment by adidahiya** [comment]
It's a stylistic preference that attempts to help reduce mental overhead when parsing TS syntax. Feel free to disable it.
