### ISSUE TITLE
Request: add exception for chai to no-unused-expression

### ISSUE THREAD

**Issue by danvk** [palantir/tslint#2614]
This is correct code:

```ts
import { expect } from 'chai';
expect(foo).to.be.true
```

even though it looks like an unused expression:

```
ERROR: foo_test.ts[2, 5]: unused expression, expected an assignment or function call
```

See analogous issue for eslint: https://github.com/eslint/eslint/issues/2102

It would be nice if there were a convenient way to disable this specifically for chai.

**Comment by abenhamdine** [comment]
A port of https://www.npmjs.com/package/eslint-plugin-chai-friendly would be great

**Comment by ajafff** [comment]
The conclusion of the linked eslint issue is: disable the rule in your tests or use dirty-chai.
I'd say it's also very unlikely that tslint will add special handling for library specific code.
See related discussion in #2485

@abenhamdine you can still create your own rule and use that one instead.

**Comment by kwonoj** [comment]
I got bitten by this changes, went ahead and created custom rule to override this - sharing here just in case if anyone's interested: https://www.npmjs.com/package/tslint-no-unused-expression-chai

It reuses tslint's default rule and naïvely excludes chai's expect assertion.

**Comment by JoshuaKGoldberg** [comment]
As per discussion, this is out of scope for TSLint itself. Library-specific code is more welcome in `tslint-microsoft-contrib` and other independent repositories.
