### ISSUE TITLE
Relative paths get messed up

### ISSUE THREAD

**Issue by michaelaird** [palantir/tslint#2620]
### Bug Report

- __TSLint version__:  4.5.1
- __TypeScript version__:  2.2.2
- __Running TSLint via__: gult-tslint

With this command :     
```
const program = tslint0.Linter.createProgram('../BigBrain.ScriptTS/BigBrain.Host.ScriptTS/tsconfig.json');
    return gulp.src(['../BigBrain.ScriptTS/BigBrain.Host.ScriptTS/**/*.ts', '!../BigBrain.ScriptTS/BigBrain.Host.ScriptTS/**/*.d.ts', '!../BigBrain.ScriptTS/BigBrain.Host.ScriptTS/**/DTOs.ts'])
        .pipe(tslint({program: program, formatter: 'msbuild'}))
        .pipe(tslint.report({ summarizeFailureOutput: true }));
```
#### Actual behavior

Fails with this exception: Invalid source file: E:\Projects\BigBrain\trunk\Presentation\BigBrain\BigBrain.ScriptTS\BigBrain.Host.ScriptTS\Application.ts. Ensure that the files supplied to lint have a .ts, .tsx, .js or .jsx extension.

#### Expected behavior

correctly parse the extension after the final "."

**Comment by michaelaird** [comment]
On taking a second look at the error message and the paths, it looks like the relative paths are getting messed up between the linter program and gulp.

**Comment by JoshuaKGoldberg** [comment]
@michaelaird this looks like an issue with Gulp itself. Could you please file an issue on them?
