### ISSUE TITLE
http://palantir.github.io/tslint/news/ is out of date

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [palantir/tslint#2627]
Belated congrats on 4.0 ;)

**Comment by CSchulz** [comment]
@palantirtech Again for 5.3.0 out of date. Can it be updated please?

**Comment by JoshuaKGoldberg** [comment]
### 💀 _**It's time!**_ 💀

**TSLint is being deprecated** and no longer accepting pull requests for major new changes or features. See #4534. 😱

If you'd like to see this change implemented, you have two choices:
* **Recommended:** Check if this is available in [ESLint](https://eslint.org) + [typescript-eslint](https://typescript-eslint.io) ✅
* _Not Recommended: Fork TSLint locally_ 🤷‍♂️

👋 It was a pleasure open sourcing with you!

_If you believe this message was posted here in error, please comment so we can re-open the issue!_
