### ISSUE TITLE
Code is ruined when prefer-const and another rule are fixed on the same line

### ISSUE THREAD

**Issue by Xapphire13** [palantir/tslint#2641]
### Bug Report
When multiple rules (one of which being `prefer-const`) target the same line and you use `--fix`, the code generated isn't valid TypeScript

- __TSLint version__: 5.1.0
- __TypeScript version__: 2.2.2
- __Running TSLint via__: **CLI** and **Atom**

#### TypeScript code being linted

```ts
function test() {
    let foo= "foo";
    let foobar = foo + "bar"
}
```

with `tslint.json` configuration:

```json
{
  "defaultSeverity": "warning",
  "rules": {
    "prefer-const": true,
    "semicolon": true,
    "whitespace": [
      true,
      "check-branch",
      "check-decl",
      "check-operator",
      "check-separator",
      "check-type"
    ]
  }
}
```

#### Actual behavior
```ts
function test() {
    const f oo= "foo";
    const foobar = foo + ";bar"
}
```
#### Expected behavior
```ts
function test() {
    const foo = "foo";
    const foobar = foo + "bar";
}
```

**Comment by adidahiya** [comment]
related: #2326, #2606, #2556
