### ISSUE TITLE
tslint@5.1.0 requires a peer of typescript@>=2.1.0,  tsutils@1.8.0 requires a peer of typescript@>=2.0.0

### ISSUE THREAD

**Issue by mateiacd** [palantir/tslint#2647]
### Bug Report

Hello, 

- __TSLint version__: 5.1.0 
- __TypeScript version__: 2.3.1
- __Running TSLint via__:  CLI

I have installed on my Windows 7 computer  typescript version 2.3.1 in my user folder
"C:\Users\mateia\AppData\Roaming\npm\node_modules\typescript"

When I run `npm install -g tslint` I get the warnings below:

`npm WARN tslint@5.1.0 requires a peer of typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >=2.4.0-dev but none was installed.`
`npm WARN tsutils@1.8.0 requires a peer of typescript@>=2.0.0 || >=2.0.0-dev || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >= 2.4.0-dev but none was installed.`

#### TypeScript code being linted

```ts
// code snippet
```

with `tslint.json` configuration:

```json

```

#### Expected behavior
Could you please clarify how to eliminate the warning ?

**Comment by ajafff** [comment]
> I have installed on my Windows 7 computer typescript version 2.3.1 in my user folder
"C:\Users\mateia\AppData\Roaming\npm\node_modules\typescript"

I don't know what this means. Is that where npm put globally installed modules?

Did you run `npm install -g typescript` ?

**Comment by mateiacd** [comment]
Yes, I have first installed typescript by using  npm install -g typescript  
Then I tried to install tslint  and got the warnings above.

But, thank you, I solved the problem, here is what I did.
npm uninstall -g typescript
npm install -g tslint typescript

**Comment by commendatore** [comment]
Thank you

**Comment by Amalsanthoshp** [comment]
Thank you ;)
