### ISSUE TITLE
Rule suggestion: use-strict: "never"

### ISSUE THREAD

**Issue by danvk** [palantir/tslint#2657]
As [this question][1] indicates, it's not entirely clear whether you should include `"use strict"` in your TypeScript source files. I lean towards "no" but others think it's a good idea.

Sounds like a good tslint rule! What about a `use-strict` rule which could enforce that either all or none your TS files have a `"use strict"` directive, depending on the settings.

The equivalent eslint rule is [`strict`][2].

[1]: http://stackoverflow.com/questions/31391760/use-strict-needed-in-a-typescript-file
[2]: http://eslint.org/docs/rules/strict

**Comment by akdor1154** [comment]
+1. I want to make sure I don't have extraneous 'use strict's in my ts files, this is exactly the sort of thing I would hope tslint can find.

**Comment by thomascmost** [comment]
Considering Typescript outputs code with 'use strict' automatically added (in `alwaysStrict` mode), I too would appreciate this rule

**Comment by ajafff** [comment]
Incidentally I have developed a similar rule in my Fimbullinter project: https://github.com/fimbullinter/wotan/blob/master/packages/mimir/docs/no-useless-strict.md

You can find instructions on how to use it in the CLI docs: https://github.com/fimbullinter/wotan/blob/master/packages/wotan/README.md

**Comment by JoshuaKGoldberg** [comment]
Note: per #4534, this issue will be closed in less than a month if no PR is sent to add the rule. If you _really_ need the rule, custom rules are always an option and can be maintained outside this repo!

**Comment by JoshuaKGoldberg** [comment]
### 💀 _**It's time!**_ 💀

**TSLint is being deprecated** and no longer accepting pull requests for new rules. See #4534. 😱

If you'd like to see this rule implemented, you have two choices:
* **Recommended:** Use [typescript-eslint](https://typescript-eslint.io) to lint your TypeScript code with ESLint ✅
* **Legacy:** Write it as a [custom TSLint rule](https://palantir.github.io/tslint/develop/custom-rules/) 🤷‍♂️

👋 It was a pleasure open sourcing with you!

_If you believe this message was posted here in error, please comment so we can re-open the issue!_
