### ISSUE TITLE
Warn on unused disables

### ISSUE THREAD

**Issue by andy-hanson** [palantir/tslint#2679]
When there is a `// tslint:disable-line foo-rule` comment, we should verify that `foo-rule` has a failure on that line. Similar for `disable-next-line`.
For `// tslint:disable` we should verify that at least one rule has a failure in the disabled range.

Depends on #2369, since if we're doing this, we can't allow rules to do anything "smart" with the disable intervals.

**Comment by adidahiya** [comment]
dupe of #1330
