### ISSUE TITLE
migration of typedef rule to 1.4

### ISSUE THREAD

**Issue by adidahiya** [palantir/tslint#269]
[this line](https://github.com/palantir/tslint/blob/1.4/test/files/rules/typedef.test.ts#L21) in `typedef.test.ts` has slightly different semantics in TS 1.4 now that computed property names are allowed.

as it stands:
```ts
class NoTypesClass {
    [index]
}
```
gives a compiler error: `Computed property names are not allowed in class property declarations`. adding a semicolon at the end of that line gives the same error.

changing it to:
```ts
class NoTypesClass {
    [index: number];
}
```
also gives an error: `An index signature must have a type annotation`.

does this obviate the need for checking index signature properties (of type `ts.IndexSignatureDeclaration`)?

**Comment by ashwinr** [comment]
looks like you're right. there's no need to check for index signatures any more
