### ISSUE TITLE
Formatters except "prose" do not print fixes.

### ISSUE THREAD

**Issue by mxl** [palantir/tslint#2710]
### Bug Report

- __TSLint version__: 5.2.0
- __TypeScript version__: 2.3.2
- __Running TSLint via__:  CLI / Node.js API

Other formatters do not receive `fixes?: RuleFailure[]` parameter in `format()` method.

**Comment by mxl** [comment]
If there is no PR for that and no one is working on this then I can make a contribution.

**Comment by nchen63** [comment]
It probably doesn't make as much sense for some formatters with an externally defined format like msbuild.

**Comment by JoshuaKGoldberg** [comment]
`verbose` and `stylish` could print these, sure. +1 that msbuild and other externally defined formats likely don't want this.

**Comment by JoshuaKGoldberg** [comment]
☠️ *TSLint's time has come!* ☠️ 

TSLint is no longer accepting most feature requests per #4534. See **[typescript-eslint.io](https://typescript-eslint.io)** for the new, shiny way to lint your TypeScript code with **ESLint**. ✨ 

It was a pleasure open sourcing with you all!
