### ISSUE TITLE
Give rule name

### ISSUE THREAD

**Issue by Jameskmonger** [palantir/tslint#2714]
At present, I get errors like so:

```
ERROR: index.ts[5, 19]: Array type using 'Array<T>' is forbidden for simple types. Use 'T[]' instead.
```

To figure out which rule to modify, I need to then go into [the rules list](https://palantir.github.io/tslint/rules/array-type/) and search for "array" to try and figure out which one it is.

It would be good to have the rule info added to the error message, like so:

```
ERROR: index.ts[5, 19]: [array-type] Array type using 'Array<T>' is forbidden for simple types. Use 'T[]' instead.
```

**Comment by ajafff** [comment]
use a different formatter, for example the `verbose` formatter:

`tslint -t verbose`

**Comment by Jameskmonger** [comment]
Thanks @ajafff I didn't notice that in the readme.
