### ISSUE TITLE
Feature Request: Allow definition of fixer to be executed via CLI

### ISSUE THREAD

**Issue by CSchulz** [palantir/tslint#2717]
### Feature Request
It would be great if it would be possible to define an argument for executing defined fixer without running any other rules.

**Comment by adidahiya** [comment]
Do you mean running a fixer for only one rule? I'd suggest just pointing the CLI at a special tslint.json to accomplish this:

```json
{
  "rules": {
    "prefer-const": true
  }
}
```

```sh
tslint -c tslint-fix.json --fix
```

**Comment by CSchulz** [comment]
Yes you are right I can achieve it with a special file, too. But in this case we have to change both files to have consistent changes.

I hoped I can reuse the existing file and tell tslint which fixer should be used.
