### ISSUE TITLE
For compability with vscode, output errors like (line, column) instead of [line, column] 

### ISSUE THREAD

**Issue by jonaskello** [palantir/tslint#2722]
In the April 2017 (version 1.12) release of vscode it is possible to hold down CTRL and click an error message in the integrated console to go to the line of the error. See the announcement [here](https://code.visualstudio.com/updates/v1_12#_integrated-terminal-link-line-and-column-ranges). I think it just searches for the pattern like `filename.extension(line, col)`.

Now this work with tsc becuase it outputs it's errors with paranthesis for the line and column like this:

```
src/foo.ts(69,22): error TS2304: Cannot find name 'bar'
```

However tslint outputs brackets instead so it does not work with vscode. Like this:

```
ERROR: src/foo.ts[61, 28]: Missing semicolon
```

I suggest that `tslint` use parenthesis same as tsc so it is compatible with vscode out-of-the-box.

**Comment by jonaskello** [comment]
Related vscode [issue](https://github.com/Microsoft/vscode/issues/21182).

**Comment by adidahiya** [comment]
makes sense. this should probably be implemented as a new "vscode" formatter so that we don't break the existing formatter output (who knows what people are doing with it...)

**Comment by Tyriar** [comment]
While it would be nice to have consistency with tsc and tslint, I think VS Code should probably support `[line, col]` https://github.com/Microsoft/vscode/issues/26330

**Comment by eliprand** [comment]
FWIW, the [msbuild](https://palantir.github.io/tslint/formatters/msbuild/) formatter (included with TSLint) does just that and is compatible with the latest release of VSCode.
Simply pass the `-t msbuild` argument as per the [documentation](https://palantir.github.io/tslint/usage/cli/).

**Comment by jonaskello** [comment]
@eliprand Works like a charm! Thanks :-). @Tyriar If vscode adds support for brackets that is even better.
