### ISSUE TITLE
JSX Alignment Error

### ISSUE THREAD

**Issue by alsiola** [palantir/tslint#2735]
### Bug Report

- __TSLint version__: 5.2.0
- __TypeScript version__: 2.2.2
- __Running TSLint via__: VSCode

#### TypeScript code being linted

```ts
render() {
        const suggestionsBottomOffset = 32 + (this.props.rows * 24) + 'px';

        return (
	    <div
                style={{
                    height: suggestionsBottomOffset
                }}
                className='textarea--wrapper'
            >
                {/* other code here but makes no difference to the error */}
	    </div>
	);
}
```

with `tslint.json` configuration:

```json
{
    "defaultSeverity": "error",
    "extends": [
        "tslint:recommended",
        "tslint-react"
    ],
    "jsRules": {},
    "rules": {
        "indent": [false],
        "quotemark": [true, "single"],
        "object-literal-sort-keys": false,
        "ordered-imports": [
            false
        ],
        "interface-name": [
            false
        ],
        "member-access": [
            false
        ],
        "trailing-comma": [
            true,
            {
                "multiline": "never",
                "singleline": "never"
            }
        ],
        "arrow-parens": false,
        "jsx-wrap-multiline": false,
        "jsx-no-lambda": false,
        "jsx-no-multiline-js": false,
        "eofline": false,
        "jsx-self-close": false,
        "jsx-boolean-value": false,
        "no-unused-expression": false
    },
    "rulesDirectory": []
}
```

#### Actual behavior
This produces an error on the rule "jsx-alignment" - "Tag closing must be on its own line and aligned with the opening of tag."
![screen shot 2017-05-11 at 11 42 45](https://cloud.githubusercontent.com/assets/18228137/25945505/04c54448-363f-11e7-89a8-dea695753817.png)

This error seems to occur only when the element in question is the outermost element, i.e. it does not appear in this situation:
![screen shot 2017-05-11 at 11 47 35](https://cloud.githubusercontent.com/assets/18228137/25945817/326ed232-3640-11e7-9dec-ead3b5ebc053.png)

#### Expected behavior
No error.

**Comment by IllusionMH** [comment]
@alsiola this issue should be reported to https://github.com/palantir/tslint-react repo

**Comment by alsiola** [comment]
Thanks @IllusionMH I have reported it #[here](https://github.com/palantir/tslint-react/issues/95)
