### ISSUE TITLE
new rule: ban for-loops

### ISSUE THREAD

**Issue by adidahiya** [palantir/tslint#274]
for loops are primitive constructs that JS programmers should rarely deal with. When targeting ES5, native array methods like `forEach`, `map`, etc. should be used instead.

**Comment by ashwinr** [comment]
This is too aggressive a rule. I don't think banning straight for loops is a useful rule for many code bases.

**Comment by chrismbarr** [comment]
I'd actually like to see the opposite of this proposed rule since native for loops are considerably faster than `someArray.forEach`

http://jsperf.com/fast-array-foreach/207

**Comment by adidahiya** [comment]
Agreed, I actually want the opposite rule as well. Now that for-of loops are in TS, I'd prefer to use those instead of `forEach`.

**Comment by chrismbarr** [comment]
Yes true!  I was just looking into those for the first time today.

**Comment by JKillian** [comment]
Related: https://github.com/palantir/tslint/issues/733
