### ISSUE TITLE
Suggestion: New rule categories

### ISSUE THREAD

**Issue by andy-hanson** [palantir/tslint#2759]
The current [rule categories](https://palantir.github.io/tslint/rules/) are "typescript", "functionality", "maintainability", and "style".

I would propose two new categories:

### `ban-syntax`

These are rules that just ban a particular type of syntax (e.g. the `null` keyword). I listed these in #2497.

### `format`

These are rules that just affect the layout of code (the many whitespace rules) or particular choice of tokens used (e.g. single or double quotes). If someone were already using a code formatter, they could turn off all of these rules.

These are:
- `typedef-whitespace`
- `eofline`
- `indent`
- `linebreak-style`
- `max-line-length`
- `trailing-comma`
- `align`
- `arrow-parens`
- `import-spacing`
- `jsdoc-format`
- `newline-before-return`
- `new-parens`
- `no-consecutive-blank-lines`
- `no-irregular-whitespace`
- `no-trailing-whitespace`
- `number-literal-format`
- `one-line`
- `quotemark`
- `semicolon`
- `whitespace`

**Comment by andy-hanson** [comment]
Instead of `ban-syntax` I'm thinking there should just be `ban`, which would include rules like "ban" and "ban-type". Whether the banned thing is "syntax" is relevant only to the implementation, and calling it "ban-syntax" would make people think "quotemark" belongs there (which bans a single-quote "syntax").

**Comment by JoshuaKGoldberg** [comment]
It's been quite a while without activity here. Per #4534, closing as aged away.
