### ISSUE TITLE
Documentation issue, Library Usage page

### ISSUE THREAD

**Issue by rich-newman** [palantir/tslint#2768]
Your [Library Usage page](https://palantir.github.io/tslint/usage/library/) has sample code that no longer works, I think.  The linter options now have to include a mandatory 'fix' flag, so the declaration of 'options' should look like:

`const options = {
    fix: false,
    formatter: "json",
    rulesDirectory: "customRules/",
    formattersDirectory: "customFormatters/"
};`

Also as far as I can work out the code on the page won't work directly with node.js, which doesn't (yet) recognize the ES6 'import' syntax.  This in spite of a title that says 'Using TSLint as a Node.js library'.

Can I politely suggest that it might be better to have JavaScript code that will run immediately with node here, rather than or as well as the TypeScript/ES6?  It would save everyone having to edit it or transpile it to run it.

I'm happy to raise a PR for these if you like.

**Comment by adidahiya** [comment]
Good points of feedback. Would be happy to accept those fixes / changes in a PR.

**Comment by ajafff** [comment]
Fixed by #2772
