### ISSUE TITLE
Cannot read property 'getStart' of undefined

### ISSUE THREAD

**Issue by StokeMasterJack** [palantir/tslint#2771]
My app works perfectly with no warnings or errors in dev mode (yarn start). But I am getting an error when I attempt a build (yarn build):

```
df2:client dford$ yarn build
yarn build v0.23.2
$ react-scripts-ts build 
Creating an optimized production build...
ts-loader: Using typescript@2.3.2 and /Volumes/repos/tc-web/client/tsconfig.json
Warning: Cannot read property 'getStart' of undefined
Failed to compile.
```

The string getStart appears no where in my code.

- __TSLint version__: The version provided with react-scripts-ts: 4.0.2
- __TypeScript version__: The version provided with react-scripts-ts: 2.3.2
- __Running TSLint via__: https://github.com/Microsoft/TypeScript-React-Starter

with `tslint.json` configuration:

```json
{
  "extends": [
    "tslint-react"
  ],
  "rules": {
    "jsx-no-lambda": false
  }
}

```

**Comment by adidahiya** [comment]
TSLint 4.0.2 is a very old version and is not designed to work with TS 2.3 (it's _six months_ older). Please upgrade TSLint.
