### ISSUE TITLE
default type could not be used.

### ISSUE THREAD

**Issue by taoqf** [palantir/tslint#2780]
### Bug Report

- __TSLint version__: 5.1.0
- __TypeScript version__: 2.2.2
- __Running TSLint via__: CLI

#### TypeScript code being linted

```ts
interface Test<T = number> {
  value: T;
}
```

#### Expected behavior
Exception: 
ERROR: 1:18     expect  TypeScript compile error: ',' expected.
ERROR: 1:20     expect  TypeScript compile error: Type parameter name cannot be 'number'

see [bug](https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/233520201?utm_source=github_status&utm_medium=notification)

**Comment by ajafff** [comment]
IIRC defaults for TypeParameters are only supported in typescript>=2.3
Try upgrading your typescript version

**Comment by taoqf** [comment]
Thanks.
