### ISSUE TITLE
Having problem in installation

### ISSUE THREAD

**Issue by aammfe** [palantir/tslint#2785]
`+-- tslint@5.2.0
| -- UNMET PEER DEPENDENCY typescript@>=2.0.0 || >=2.0.0-dev || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >= 2.4.0-dev
-- UNMET PEER DEPENDENCY typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >=2.4.0-dev

npm WARN tslint@5.2.0 requires a peer of typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >=2.4.0-dev but none was installed.
npm WARN tsutils@1.9.1 requires a peer of typescript@>=2.0.0 || >=2.0.0-dev || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >= 2.4.0-dev but none was installed.`

i m using TypeScript 2.3.2 but gaving above error.

**Comment by ajafff** [comment]
This may be a duplicate of #2647. Maybe you find a solution for your problem there.

**Comment by adidahiya** [comment]
duplicate of https://github.com/palantir/tslint/issues/815

**Comment by HonkMcFunk** [comment]
I had to change the required typescript version in the `package.json`to 2.4.0 to solve this.
`"devDependencies": {
        "@ionic/app-scripts": "^1.0.0",
        "typescript": "2.4.0"
    },`

... and of course npm install afterwards.
