### ISSUE TITLE
Make rule error text consistent

### ISSUE THREAD

**Issue by mmoore2006** [palantir/tslint#2794]
In a project that's all about making things consistent, the rule error text is very inconsistent:

![errormessages](https://cloud.githubusercontent.com/assets/15878532/26274777/93f487f8-3d49-11e7-95c5-33674dfdc6c6.png)

- Some end with a period, some don't
- Some keywords in single quotes, others not
- Some start with a capital letter, some don't

I **think** the rules that TypeScript error messages follow is that they should all end with a period, always be quoted when quoting from the code, and all be capitalized at the start unless starting with quotes.

Maybe we need a linter for the linter.  A metalinter.  This isn't entirely a joke.  I think the variable names all contain 'FAILURE_STRING' so someone smarter than me can probably do it with regexps.  Although it might be quicker to just go through them all.

(TSLint v5.2.0, TS v2.3.2)

**Comment by ajafff** [comment]
Writing a lint rule could become really tough. 
I think that's better done once for all rules. Later we check this as part of the code review for new rules. 

:+1: for the rules you proposed. 

Another thing to consider: `Missing semicolon` or `trailing whitespace` are not really sentences. Maybe we should make them real sentences.

**Comment by mmoore2006** [comment]
I'm not sure about the full sentences: a quick test shows that if you omit a semicolon C# gives me '; expected' and C (gcc) gives me 'expected ';' before '}' token', neither of which are sentences clearly

**Comment by JoshuaKGoldberg** [comment]
### 💀 _**It's time!**_ 💀

**TSLint is being deprecated** and no longer accepting pull requests for major new changes or features. See #4534. 😱

If you'd like to see this change implemented, you have two choices:
* **Recommended:** Check if this is available in [ESLint](https://eslint.org) + [typescript-eslint](https://typescript-eslint.io) ✅
* _Not Recommended: Fork TSLint locally_ 🤷‍♂️

👋 It was a pleasure open sourcing with you!

_If you believe this message was posted here in error, please comment so we can re-open the issue!_
