### ISSUE TITLE
Suggestion: `import-path` rule

### ISSUE THREAD

**Issue by andy-hanson** [palantir/tslint#2806]
```ts
import { x } from "foo/index";
import { x } from "foo.js";
```

This rule would warn when `/index` or `.js` are unnecessarily added on to the end of an import.
I noticed that `"../index"` is used a lot in this repository; I would really prefer just `".."` though.

**Comment by vladimiry** [comment]
Is it not enough to simply forbid "index"-like imports using existing rules? `importBlacklistRule` is about to get the regexp patterns support https://github.com/palantir/tslint/pull/3504 or there is [no-import-zones](https://github.com/vladimiry/tslint-rules-bunch) rule that supports 
[micromatch](https://github.com/micromatch/micromatch) patterns.

**Comment by JoshuaKGoldberg** [comment]
This seems difficult. What if the following all exist within a directory?

* `foo/index/index.js`
* `foo/index.js`
* `foo.js`
* `foo.js/index.js`

**Comment by JoshuaKGoldberg** [comment]
### 💀 _**It's time!**_ 💀

**TSLint is being deprecated** and no longer accepting pull requests for major new changes or features. See #4534. 😱

If you'd like to see this change implemented, you have two choices:
* **Recommended:** Check if this is available in [ESLint](https://eslint.org) + [typescript-eslint](https://typescript-eslint.io) ✅
* _Not Recommended: Fork TSLint locally_ 🤷‍♂️

👋 It was a pleasure open sourcing with you!

_If you believe this message was posted here in error, please comment so we can re-open the issue!_
