### ISSUE TITLE
Add support for tsconfig.json

### ISSUE THREAD

**Issue by ashwinr** [palantir/tslint#281]
Support https://github.com/Microsoft/TypeScript/issues/1667 https://github.com/Microsoft/TypeScript/pull/1692. Reported by @derekcicerone.

**Comment by lelong37** [comment]
+10

**Comment by pspeter3** [comment]
This would be awesome if tsconfig was just the canonical list of files.

**Comment by adidahiya** [comment]
1. If the `files` list in `tsconfig.json` contains typings files downloaded via `tsd`, we probably don't want to lint those, right? Should we exclude any `typings/` folder by default and add an option to include everything?
2. It's possible to compile a project where `tsconfig.json` lists some, but not all source files of the project. The compiler will resolve modules via external imports or reference paths unless the `--noResolve` [compiler option](https://github.com/Microsoft/TypeScript/wiki/Compiler-Options) is turned on. Given this, I'm not sure I would want `tslint` to default to reading the list of files to lint from `tsconfig.json`; it should be optional.

**Comment by ashwinr** [comment]
Should definitely not be the default. I'm not even sure about the optional part, is there any advantage to that instead of just using a files glob in grunt/gulp

**Comment by adidahiya** [comment]
The only advantage I see here is for CLI users -- they don't have to supply all their project files via arguments to the CLI.

**Comment by ashwinr** [comment]
yeah but projects can also have multiple tsconfig files, so they'd have to run tslint pointing to the correct tsconfig file in addition to tslint.json.

**Comment by adidahiya** [comment]
Yep, good point. I don't think it makes sense for tslint to use the `files` list in `tsconfig.json`. Was there any other idea to be discussed here regarding the project file? If not, let's close this issue.

**Comment by pspeter3** [comment]
The only other value would be picking up settings from the file but the tslint is probably sufficient.

**Comment by xogeny** [comment]
I'm confused.  The `tsconfig.json` seems to unambiguously specify which files are to be compiled.  Why would you not leverage this to determine what files to lint?  Am I missing something?  If I have TS project full of source files, who do I express that I want to "lint them all"?  I'm confused because the `tslint` command-line seems to expect me to list all those files individually.  Or am I missing something?

**Comment by adidahiya** [comment]
Sorry for the confusion -- we _do_ want to support tsconfig.json to supply files. There's another more up to date issue tracking that, so this one's resolution should be updated to "Duplicate" instead of "Won't Fix".

**Comment by xogeny** [comment]
You might want to include a reference to that other issue so people know where to go.  Is it #692 or #858 or ?

**Comment by adidahiya** [comment]
@xogeny both, since both of those issues are relevant for specifying files to lint, but yeah #858 is the specific one for tsconfig.json (I wasn't at a computer earlier to search for it)
