### ISSUE TITLE
prefer-const fixer fixes 'let' but doesn't fix 'var'

### ISSUE THREAD

**Issue by rich-newman** [palantir/tslint#2843]
### Bug Report

- __TSLint version__: 5.3.2
- __TypeScript version__: 2.3.3
- __Running TSLint via__: CLI

#### TypeScript code being linted

```ts
function foo() {
    var i = "test";
}
```

with `tslint.json` configuration:

```json
{
  "rules": {
	"prefer-const": true
  }
}
```

#### Actual behavior

If tslint is run then the error "Identifier 'i' is never reassigned; use 'const' instead of 'var'." is correctly reported.  However tslint is run with --fix no change is made.

If the code is changed to:
```ts
function foo() {
    let i = "test";
}
```
then the error "Identifier 'i' is never reassigned; use 'const' instead of 'let'" is correctly reported. If tslint is run with --fix the correct change is made.

#### Expected behavior

Code should be updated to:
```ts
function foo() {
    const i = "test";
}
```
This issue is I think different to #2112, which is about prefer-const not working in the global scope.

**Comment by ajafff** [comment]
That's on purpose. Fixing `var` -> `const` might break your program. There's another issue that tries to clarify if fixes are allowed to potentially change the semantics of the program #2625

**Comment by rich-newman** [comment]
OK, makes sense - the fixer's more difficult and isn't going to work well if naively extended to var

**Comment by rich-newman** [comment]
Although the end result at the moment is we have a var -> let fixer, which will work in the case above, and a let -> const fixer which will work in the case above if applied after the first one.  But the direct var -> const fixer we think is too dangerous to set up, even if it had exactly the same effect.  And the result of that is it's a bit confusing.  At least, I got confused, which maybe isn't the same thing.

**Comment by ajafff** [comment]
> at the moment we have a var -> let fixer

Initially I wanted to answer that you explicitly have to enable `no-var-keyword` and when you do, you should be aware that the fix might break your program.
Then I realized that it's part of `tslint:recommended`...

Do you mind sharing your opinion in #2625? Unfortunately there's not much discussion going on over there. I'd like to hear what others think. Otherwise there'll probably never be a decision.
