### ISSUE TITLE
How can I set '--project xxx' in the tslint.json?

### ISSUE THREAD

**Issue by chenxxzhe** [palantir/tslint#2844]
I use `SublimeLinter-contrib-tslint` and it is difficult to set the `--project` in the `sublimeLinter.sublime-settings`, to be more precise, i don't know how to set the path of `tsconfig.json` in this setting.

How can i set the `project` property just in the `tslint.json` ?

**Comment by adidahiya** [comment]
essentially a duplicate of https://github.com/palantir/tslint/issues/2227
