### ISSUE TITLE
space-before-function-paren: Cannot read property 'end' of undefined

### ISSUE THREAD

**Issue by clebert** [palantir/tslint#2848]
### Bug Report

- __TSLint version__: 5.3.2
- __TypeScript version__: 2.3.3
- __Running TSLint via__: CLI

#### TypeScript code being linted

```ts
export type Fn = (foo: string) => Promise<string>;

export const noWarning: Fn = async (foo) => foo;

export const warning: Fn = async foo => foo;
```

with `tslint.json` configuration:

```json
{
  "rules": {
    "space-before-function-paren": [true, {
      "asyncArrow": "always"
    }]
  }
}
```

#### Actual behavior

Warning: Cannot read property 'end' of undefined

#### Expected behavior

No warning (with TSLint 5.2.0 there is no problem)

**Comment by adidahiya** [comment]
fixed by #2833
