### ISSUE TITLE
Running --fix on .ts Files Creates Numerous Syntax Errors.

### ISSUE THREAD

**Issue by taicho** [palantir/tslint#2862]
### Bug Report

- __TSLint version__: 5.4.0 (also tried 5.4.2)
- __TypeScript version__:  2.3.2
- __Running TSLint via__: CLI

#### TypeScript code being linted

```Command
tslint -p "./tsconfig.json" --fix --type-check -c tslint.json
```

with `tslint.json` configuration:

```json
{
  "extends": [
    "tslint:recommended"
  ],
  "rules": {
    "quotemark": [true,
      "single"
    ],
    "align": [true,
      "statements",
      "arguments"
    ],
    "radix": false,
    "space-before-function-paren":false,
    "array-type": [
      true,"array"
    ]
  }
}
```

#### Actual behavior
Breaks code by inserting commas and spaces where there shouldn't be any.

File before "fix":
```
import * as winston from 'winston';

const DefaultOptions = {
    transports: [
    new winston.transports.Console({
        json: true,
        colorize: true,
        stringify:true
    })],
    rewriters:[
        (level,message,meta)=>{
            if(meta)
            {
                meta.timeStamp = new Date();
            }
            return meta;            
        }
    ]

};

export const Logger = new winston.Logger(DefaultOptions);
```
File after "fix" (notice the split-lambda, spaces between "if", commas between "export" and "const"...bizarre output; this code does not compile successfully:
```
import * as winston from 'winston';

//Modify winston here.
const DefaultOptions = {
    transports: [
    new winston.transports.Console({
        json: true,
        colorize: true,
        stringify: true,
    })],
    rewriters :[
        (level ,message ,meta )= >{
            i f(meta)
            {
                meta.timeStamp = new Date();
            }
            return meta;
        }
    ]

};

,export, const Logger = new winston.Logger(DefaultOptions);
```

#### Expected behavior
Expected to "fix" whatever fixable rules can be fixed with acceptable anomalies. Running "fix" completely rendered 59 files broken and unable to compile because of syntax errors introduced. I realize any "fix" operation is risky which is why I did a commit right before but in any case this seems like a major issue. Even "simple" files like the one above don't appear to be parsed and fixed correctly. Is this a problem on my side? Has anybody else run into this?

P.S. Also worth noting is this codebase compiles perfectly using tsc and/or gulp-typescript and/or ts-loader before the "fixes" are applied.

**Comment by ajafff** [comment]
> Is this a problem on my side? Has anybody else run into this?

You're not the first one to experience these problems: #2641, #2326 

I guess I've found the problem. With `--program` we update the file on disk but use the old source (before fixing) to lint again and calculate the position of the fixes. Then we apply the fixes with the wrong positions to the file contents on disk.

Will try to fix this today.

**Comment by taicho** [comment]
@ajafff Fantastic! Thanks for the prompt response + fix.
