### ISSUE TITLE
Allow `then(fulfillment, rejection)` for `no-floating-promises`

### ISSUE THREAD

**Issue by vilic** [palantir/tslint#2879]
Related to #2774

**Comment by JoshuaKGoldberg** [comment]
@vilic Is there a reason you're not using `async`/`await` instead?

**Comment by vilic** [comment]
@JoshuaKGoldberg usually the outermost entrance, like:

main().then(() => process.exit(), error => ...);

**Comment by ajafff** [comment]
Fixed by #3048
