### ISSUE TITLE
Error when linting files in subdirectories with v2

### ISSUE THREAD

**Issue by xt0rted** [palantir/tslint#288]
I'm trying to update [gulp-tslint](https://github.com/panuhorsmalahti/gulp-tslint) to use v2.0.1 and ran into a problem where my existing setup is now crashing but i'm not sure if it's due to gulp-tslint or tslint.

I'm using the pattern `"./app/**/*.ts"` to get the files to lint but this results in the following error now:
```
...\node_modules\gulp-tslint\node_modules\tslint\lib\tslint.js:26770
            this.limit = this.sourceFile.getFullWidth();
                                         ^
TypeError: Cannot call method 'getFullWidth' of undefined
```

The files under `/app` are linted, the error occurs on the first file in a subdirectory. If I change the pattern to `"./app/controllers/*.ts"` then the files are linted and there is no crash.

I've narrowed the origin of the cause to [where gulp-tslint passes in the file to be linted](https://github.com/panuhorsmalahti/gulp-tslint/blob/3402c029fa7d4f9ea6a7b1975d3ff78820a0edb5/index.js#L63). Currently it's using `file.relative` but if I change this to `path.basename(file.path)` everything works as expected.

The problem is being caused by `\` or `/` being in the file name that's passed to tslint. Is the correct fix to only pass the file name in?

**Comment by ashwinr** [comment]
can you refer to https://github.com/palantir/grunt-tslint/? Thanks!

**Comment by xt0rted** [comment]
Running `grunt tslint` on this project resulted in the same error
```
D:\GitHub\tslint [master...origin/master]> grunt tslint
Running "tslint:src" (tslint) task
src/configuration.ts
Warning: Cannot call method 'getFullWidth' of undefined Use --force to continue.
```

**Comment by ashwinr** [comment]
this might actually be a bug in tslint. can you find out which file it's failing on and send us a sample of the code that you're hitting this bug on? thanks!

**Comment by xt0rted** [comment]
I turned off linting and ran the tests, they also fail with the same error. After some poking around I was able to get all the tests to pass by making these two changes:

[ruleDisableEnableTests.ts#L30](https://github.com/palantir/tslint/blob/d328b18442694c1d89db050f5dec3fd26a8e4190/test/ruleDisableEnableTests.ts#L30)
```typescript
var relativePath = "test/files/rules/enabledisable.test.ts";
```

[utils.ts#L25](https://github.com/palantir/tslint/blob/d328b18442694c1d89db050f5dec3fd26a8e4190/src/language/utils.ts#L25)
```typescript
var normalizedName = fileName;
```

I'm on Windows so the file paths are being normalized to use `\`. TypeScript does [normalize these internally](https://github.com/Microsoft/TypeScript/blob/de13648c9f87e0da272f5ed14767afb2c8788322/src/compiler/parser.ts#L879) to `/` but for some reason `program.getSourceFile(normalizedName)` returns `undefined` when the path contains `\`.

The other option that seems to work is to modify only `getSourceFile` in `utils.ts` to normalize the file paths our self:
```typescript
fileName = fileName.replace(/\\/g, '/');
var normalizedName = fileName;
```

**Comment by Bruddles** [comment]
+1.

**Comment by JeroMiya** [comment]
I am also experiencing this issue. Here is our tslint.json:

```json
{
    "rules": {
        "class-name": true,
        "curly": true,
        "eofline": true,
        "forin": true,
        "indent": [ true, 4 ],
        "interface-name": true,
        "jsdoc-format": true,
        "label-position": true,
        "label-undefined": true,
        "max-line-length": [ true, 200 ],
        "no-any": false,
        "no-arg": true,
        "no-bitwise": true,
        "no-console": [
            true,
            "debug",
            "info",
            "time",
            "timeEnd",
            "trace"
        ],
        "no-consecutive-blank-lines": true,
        "no-construct": true,
        "no-constructor-vars": false,
        "no-debugger": true,
        "no-duplicate-key": true,
        "no-duplicate-variable": true,
        "no-empty": true,
        "no-eval": true,
        "no-string-literal": false,
        "no-switch-case-fall-through": false,
        "no-trailing-comma": true,
        "no-trailing-whitespace": true,
        "no-unreachable": true,
        "no-unused-expression": false,
        "no-unused-variable": true,
        "no-use-before-declare": true,
        "no-var-requires": true,
        "one-line": [
            true,
            "check-open-brace",
            "check-catch",
            "check-else",
            "check-whitespace"
        ],
        "quotemark": [ true, "single" ],
        "radix": true,
        "semicolon": true,
        "triple-equals": [ true, "allow-null-check" ],
        "typedef": false,
        "typedef-whitespace": [
            true,
            [ "call-signature", "nospace" ]
        ],
        "use-strict": [
            true,
            "check-function",
            "check-module"
        ],
        "variable-name": false,
        "whitespace": [
            false,
            "check-branch",
            "check-decl",
            "check-operator",
            "check-separator",
            "check-type"
        ]
    }
}
```

I made a smaller version of the original file that still causes the error (last line in the file does have an endline as it should - hard to show in a post):
```typescript
// app/common/cache/tslintRepoFile.ts
(function () {
    angular.module('app.cache.listCache', [])
        .factory('listCache', ['$cacheFactory', function ($cacheFactory: ng.ICacheFactoryService) {
        return $cacheFactory('listCache');
    }]);
})();

```

The command I use:
```
tslint --file app/common/cache/tslintRepoFile.ts
```

The output:
```
C:\Program Files\nodejs\node_modules\tslint\bin\tslint-cli.js:26770
            this.limit = this.sourceFile.getFullWidth();
                                         ^
TypeError: Cannot call method 'getFullWidth' of undefined
    at EnableDisableRulesWalker.RuleWalker (C:\Program Files\nodejs\node_modules\tslint\bin\tslint-cli.js:26770:42)
    at new EnableDisableRulesWalker (C:\Program Files\nodejs\node_modules\tslint\bin\tslint-cli.js:27023:20)
    at Linter.lint (C:\Program Files\nodejs\node_modules\tslint\bin\tslint-cli.js:27200:31)
    at processFile (C:\Program Files\nodejs\node_modules\tslint\bin\tslint-cli.js:27339:29)
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\tslint\bin\tslint-cli.js:27348:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by ashwinr** [comment]
normalized file-names on windows. @xt0rted please verify that latest master works for you and i can push out a new release. thanks!

**Comment by xt0rted** [comment]
I still get the same errors. What fixes it for me is this:
```ts
export function getSourceFile(fileName: string, source: string): ts.SourceFile {
    var normalizedName = path.normalize(fileName).replace(/\\/g, "/");
    var compilerOptions = createCompilerOptions();

    var compilerHost = {
        getSourceFile: function(filenameToGet: string) {
            if (filenameToGet === normalizedName) {
                return ts.createSourceFile(filenameToGet, source, compilerOptions.target, "1", true);
            }
        },
        writeFile: () => null,
        getDefaultLibFilename: () => "lib.d.ts",
        useCaseSensitiveFileNames: () => true,
        getCanonicalFileName: (filename: string) => filename,
        getCurrentDirectory: () => "",
        getNewLine: () => "\n"
    };

    var program = ts.createProgram([normalizedName], compilerOptions, compilerHost);
    // this will force the binder to properly set up parent pointers, which will allow getSourceFile to work on all nodes,
    // and will therefore allow our code to work even if the source doesn't compile
    program.getTypeChecker(true);
    return program.getSourceFile(normalizedName);
}
```

I moved the regex normalization so it happens after the native normalization (line 2) and then used the normalized name to compare against (line 6).

With only updating line 2 all tests pass except for those in `ruleDisableEnableTests.ts`, also making the change on line 6 results in all tests passing.

**Comment by ashwinr** [comment]
@xt0rted can you send a PR over, and I can review this? It's going take some time for me to test this on a windows machine.

**Comment by xt0rted** [comment]
@ashwinr sure thing

**Comment by ashwinr** [comment]
released 2.1.0 with this fix.

**Comment by xt0rted** [comment]
I updated gulp-tslint with this version and everything is working well for me now.

**Comment by ashwinr** [comment]
cool, thanks for the PR!
