### ISSUE TITLE
Rule to count lines of methods, functions or arrow functions

### ISSUE THREAD

**Issue by TristanFAURE** [palantir/tslint#2881]
### Bug Report

- __TSLint version__: 5.4.2
- __TypeScript version__: 2.3.0
- __Running TSLint via__: Visual Studio 

#### TypeScript code being linted

```ts
// code snippet
```

with `tslint.json` configuration:

```json

```

**Comment by JoshuaKGoldberg** [comment]
This was fixed by #4224. Hooray! 🙌
