### ISSUE TITLE
Should --fix exit with 0 if it successfully fixed all issues?

### ISSUE THREAD

**Issue by bahmutov** [palantir/tslint#2892]
Why does `--fix` exit with error even if it can fix every problem? This does not match what `eslint --fix` does.

### Bug Report

- __TSLint version__: 5.4.2
- __TypeScript version__:2.3.2
- __Running TSLint via__: CLI

#### Actual behavior

`--fix` should prints errors and exits with 1

#### Expected behavior

`--fix` should print warnings for things it fixed, but exit with 0

**Comment by kristerkari** [comment]
I'm running into the same problem. This for example prevents `--fix` to be used as a precommit hook. 

/cc @adidahiya

**Comment by kristerkari** [comment]
Actually this seems to be fixed in tslint 5.5.0, @bahmutov

**Comment by bradleyayers** [comment]
I'm using 5.7.0 and this is fixed. Not sure how far back it's been fixed.

**Comment by ajafff** [comment]
We usually don't port fixes to older releases. So this is fixed in 5.5.0 and above
