### ISSUE TITLE
tslint.json in JSON Schema Store

### ISSUE THREAD

**Issue by rich-newman** [palantir/tslint#2900]
This is just a quick question because I've got confused about it: is the JSON schema for [tslint.json in the JSON schema store](http://json.schemastore.org/tslint) out of date?  Is so is there an up-to-date version?

I think it is out of date because it doesn't support "options" or severities for individual rules, but as I say, I've got a bit confused.

**Comment by adidahiya** [comment]
It's out of date. We don't maintain it, but I bet they'd take PRs: https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/tslint.json

**Comment by rich-newman** [comment]
Thanks, I'm less confused.  Is there actually an up-to-date schema somewhere though?

**Comment by adidahiya** [comment]
Not a full up-to-date schema, no. Individual rules do have option schemas listed in their metadata: https://github.com/palantir/tslint/blob/ce73397d5c892ba00b2000306df3a6150c0635de/src/rules/banRule.ts#L59

**Comment by rich-newman** [comment]
OK thanks very much.  I'm closing this since you've answered the question, thanks.
