### ISSUE TITLE
Bug: fixer for 'ordered-import' ignore 'import-sources-order' rule

### ISSUE THREAD

**Issue by rokoroku** [palantir/tslint#2906]
### Bug Report

- __TSLint version__: 5.3.2
- __TypeScript version__: 2.3.4
- __Running TSLint via__: VSCode

#### TypeScript code being linted

![default](https://user-images.githubusercontent.com/5208632/26960635-a024bb18-4d13-11e7-8637-53a6848f86ef.gif)

with `tslint.json` configuration:

```json
{
   "ordered-imports": [
      true,
      {
        "import-sources-order": "any",
        "named-imports-order": "lowercase-last"
      }
   ]
}
```

#### Expected behavior

Original import-sources order should be preserved.

**Comment by JoshuaKGoldberg** [comment]
### 💀 _**It's time!**_ 💀

**TSLint is deprecated** and no longer accepting pull requests other than security fixes. See #4534. ☠️ 
We recommend you instead use **[typescript-eslint](https://typescript-eslint.io)** to lint your TypeScript code with **ESLint**. ✅

👋 It was a pleasure open sourcing with you!
