### ISSUE TITLE
"object-literal-key-quotes" quick fix does not take "quotemark" option in account

### ISSUE THREAD

**Issue by coreh** [palantir/tslint#2918]
### Bug Report

- __TSLint version__: 5.4.3
- __TypeScript version__: 2.3.4
- __Running TSLint via__: VSCode

#### TypeScript code being linted

```ts
let x = {
  a: 1, // should be quoted
  'b-c': 2,
}
```

with `tslint.json` configuration:

```json
{
  "quotemark": [
    true,
    "single",
    "jsx-double"
  ],
  "object-literal-key-quotes": [
    true,
    "consistent-as-needed"
  ]
}
```

#### Actual behavior

When I use auto fix on VSCode, the property gets quoted, but using double quotes, so I need to do a second auto fix to get it to respect the `quotemark` option.

#### Expected behavior

It should be auto-fixed with single quotes, so that no further fixing is required.

**Comment by adidahiya** [comment]
This seems like a specific form of the problem in https://github.com/palantir/tslint/issues/2556. Rules don't communicate with each other and we don't handle overlapping fixes. If you run the fixer twice, it should produce the right output.

**Comment by JoshuaKGoldberg** [comment]
Closing as subset of #2556.
