### ISSUE TITLE
"no-void-expression" add option similar to "allow-fast-null-checks"

### ISSUE THREAD

**Issue by coreh** [palantir/tslint#2919]
Would be really nice if the `no-void-expression` check had an option to allow expressions like:

```typescript
condition && someMethodReturningVoid()
```

This would be similar to the `allow-fast-null-checks` option of `no-unused-expression`.

**Comment by adidahiya** [comment]
This probably makes sense, but can you provide a bit more context? Where are you using these expressions in non-statement positions?

**Comment by scott-ho** [comment]
@adidahiya There are a lot of cases in Angular community;

For example
```
class A {
   sub: Subscription;
   ngOnDestroy() {
		this.sub && this.sub.unsubscribe();
   }
}
```
