### ISSUE TITLE
[Fixer] Pre-declare objects as undefined

### ISSUE THREAD

**Issue by goatandsheep** [palantir/tslint#2935]
### Fixer Suggestion

- __TSLint version__:
- __TypeScript version__:
- __Running TSLint via__: Visual Studio

#### TypeScript code being linted

```ts
var column = {};
column.title = "hi"
```

with `tslint.json` configuration:

```json
"autoFixOnSave": true
```

#### Actual behavior

Error: Property 'title does not exist on type '{}':

#### Expected behavior

Fixer: pre-declare the object value as undefined

```ts
var column = {
    title: undefined
};
column.title = "hi"
```

**Comment by ajafff** [comment]
The error you are seeing comes from the typescript compiler and not from tslint.
Since it's not a lint rule failure, there's no way to apply a fix

**Comment by goatandsheep** [comment]
Is there any way of picking up the error beforehand? Or is that out of scope for this project?

**Comment by ajafff** [comment]
I think you're better off posting this feature request in the typescript repo. TypeScript has the ability to add code fixes to diagnostic messages (errors) that you can apply in your IDE.
