### ISSUE TITLE
Feature: `tslint install <config>` command

### ISSUE THREAD

**Issue by unional** [palantir/tslint#2939]
I wonder if it makes sense to create this `tslint install <config>` command.

I write and use my own config: https://github.com/unional/tslint-config-unional
and one of the main objectives of my config is to define a coding style that works across IDEs.

I'm able to do that by finding common possible settings so that the IDE can be configured in a way that works seamlessly with the style.

However, that also means that the user needs to configure their IDE of choice to a specific setting out-of-band.

This is ok in company environment but for open source project, it is crucial to set up the IDE setting with minimal friction.

If we introduce `tslint install <config>`, we can add a function in the config that can create these settings in the project automatically.

Currently, my "workaround" would involve a custom cli tool that will scaffold the project with these settings to be checked in into github.

Oh, by the way, it would be even better if we can write some tools that will read the tslint config file and output config settings for different IDEs. 🌷

**Comment by ajafff** [comment]
You're probably trying to solve your problem on the wrong end.
IMO tslint should not be responsible to configure any IDE based on your tslint.json.

Instead you could write your own tool that installs tslint with your config and has plugins to configure your preferred IDEs. Maybe that's what you meant and already implemented as "workaround".

**Comment by unional** [comment]
Yes, I would agree that is outside the responsibility of the linting service.

I'm looking at this on the consuming side and it doesn't help if the IDE you use doesn't collaborate with it.

If you consider tslint has two components: linting service and cli, this may be suitable in the cli component as it can take the responsibility of configuring the environment (and in a sense similar to ESLint providing the `eslint:recommend` rule set).

Currently, it is extra work from the user to get things setup and ready.
For contributing to open source project, many times you would fork a repo, make some fix, and create a PR. 

You do not need to work on it in the future for the most part, and this (or similar solution) would help making that experience more streamlined.

**Comment by JoshuaKGoldberg** [comment]
Seems like consensus is that this should be an external tool. Closing as external, but please do post here if you think this should be a part of TSLint itself!
