### ISSUE TITLE
Fix rules for dynamic imports.

### ISSUE THREAD

**Issue by ashwinr** [palantir/tslint#2945]
The `whitespace`, `member-access` and `member-ordering` rules don't handle the new syntax element.

Example:
```ts
   class Test {
      private handleDownload = () => {
          const { tab } = this.props;

          const Papa = import("papaparse").then((Papa) => {
            //
          });
      }
  }
```

**Comment by ajafff** [comment]
What exactly is the problem with `member-access` and `member-ordering`? 
`whitespace` is already fixed on master.

**Comment by Crazometer** [comment]
Can we get a new npm release with the `whitespace` rule fixed?

Typescript 2.4 has been out for a few days now and it's likely a few people are running into this.

**Comment by adidahiya** [comment]
5.5.0 has been released, please comment here if you continue to experience issues
