### ISSUE TITLE
TSLint leaks file handles - encoding rule

### ISSUE THREAD

**Issue by irengrig** [palantir/tslint#2954]
### Bug Report

- __TSLint version__: 5.4.3
- __TypeScript version__: 2.3.4
- __Running TSLint via__: (pick one) WebStorm

#### TypeScript code being linted

tslintTest.ts
// code snippet
``//type any text``

with `tslint.json` configuration:

tslint.json

`{
  "rules": {
    "encoding": true
  }
}`

#### Actual behavior
WebStorm currently uses language service for running TSLint, i.e. a service process is run with Node.js, and tslint is initiated and used for many invocation => i.e. all leaks resist

see https://github.com/palantir/tslint/blob/master/src/rules/encodingRule.ts
method detectEncoding opens the file and never closes it.
The file remains opened for read -> blocked for write operations.
Please fix.

Related issues:

WebStorm:
https://youtrack.jetbrains.com/issue/WEB-27456
https://youtrack.jetbrains.com/issue/WEB-27391

VS Code:
https://github.com/Microsoft/vscode-tslint/issues/213

#### Expected behavior
TsLint closes all file handles, files are not blocked by it.

**Comment by ajafff** [comment]
Thank you for the detailed report. I opened #2958 to fix this.

**Comment by vilic** [comment]
@irengrig @ajafff Thanks for locating and fixing this bug, it has been driving me crazy for a while.

**Comment by irengrig** [comment]
Thank you for the fix!
