### ISSUE TITLE
Extending configuration that uses npm packages for rules is not working without installing those npm packages

### ISSUE THREAD

**Issue by mohsen1** [palantir/tslint#2966]
### Bug Report

- __TSLint version__: 5
- __TypeScript version__: 2.4

Consider we have a npm package that is our base config

```json
{
"rulesDirectory": [
        "node_modules/tslint-eslint-rules/dist/rules",
        "node_modules/tslint-microsoft-contrib",
        "node_modules/tslint-react/rules"
],
"rules": { 
// ...
}
}
```
this package has a package.json file like this:

```json
{
  "name": "base-config",
  "dependencies": {
    "tslint-eslint-rules": "^4.1.1",
    "tslint-microsoft-contrib": "^5.0.0",
    "tslint-react": "^3.0.0"
  }
}
```

Now if I install this package and extend the rules:

```
npm install  --save-dev base-config
```
**tslint.json**
```json
{
  "extend": "base_config"
}
```

I also need to install `tslint-eslint-rules`, `tslint-react` and `tslint-microsoft-contirb` to make TSLint happy.

This is a bug, since my base-config package already depending on those packages.

**Comment by ajafff** [comment]
`rulesDirectory` is always relative to the tslint.json file they are specified in.

What you really want is node's module resolution.
You can get that by removing the `node_modules/` part from the directory

The following should work (with tslint@>=5.2.0)
```js
{
    "rulesDirectory": [
        "tslint-eslint-rules/dist/rules",
        "tslint-microsoft-contrib/dist/rules",
        "tslint-react/rules"
    ],
    "rules": { 
        // ...
    }
}
```
