### ISSUE TITLE
--fix for explicit privacies in member-access

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [palantir/tslint#2967]
#### TypeScript code being linted

```typescript
class Foo {
    member: number;
    constructor(member: number) {
        this.member = member;
    }
}
```

Many people coming from C# and friends assume class members to be `private` by default. That's not true in TypeScript. ~~A rule that requires all constructs have an explicit privacy modifier would help a lot.~~

Auto-fixing logic should be easy: just add "`public `".

**Comment by ajafff** [comment]
There is `member-access` that does what you want except auto-fixing.

**Comment by JoshuaKGoldberg** [comment]
:( oh. Whoops.

Retargeting for just auto-fixing... would you consider it valid to auto-fix to `public`? It would be nice to auto-detect the ability to be `private` or `protected`, but that would be a dangerous change and hard with exported constructs.

**Comment by ajafff** [comment]
Opened #2969 to automatically add `public` when fixing
