### ISSUE TITLE
Rule to block unnecessary JSDoc-style type annotations

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [palantir/tslint#2968]
#### TypeScript code being linted

```typescript
class Cow {
    /**
     * @param {string} name
     */
    public speak(name: string) { }
}
```

The `{string}` is unnecessary in TypeScript and should be removed. 

Note that this is easy to auto-fix, and should be TypeScript-only (JS files want these annotations).

**Comment by ajafff** [comment]
There's an open PR for a rule named `no-redundant-jsdoc'. IIRC it does this and checks even more stuff.

**Comment by JoshuaKGoldberg** [comment]
Ha.
