### ISSUE TITLE
Strict mode for scripts

### ISSUE THREAD

**Issue by Deathspike** [palantir/tslint#297]
If I have the following code using TSLint 2.1.0:

	'use strict';

	function example1(): number {
	  return 123;
	}

	function example2(): string {
	  return String(example1());
	}

Which will generate the following output:

	'use strict';
	function example1() {
		return 123;
	}
	function example2() {
		return String(example1());
	}

With the following TSLint settings:

	"use-strict": [true,
	  "check-module",
	  "check-function"
	],

Will produce the following errors:

	src/test.ts[3, 1]: missing 'use strict'
	src/test.ts[7, 1]: missing 'use strict'

This is wrong. The 'use strict' statement applies to all functions in the file (reference to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode). Can this be changed?

**Comment by ashwinr** [comment]
just turn off the `check-function` option please.

**Comment by Deathspike** [comment]
If you turn that off, it will not check the script scope. The module scope does not apply here.

Please test the example.
