### ISSUE TITLE
--version flag missing in newest releases

### ISSUE THREAD

**Issue by rsxdalv** [palantir/tslint#2971]
### Bug Report

- __TSLint version__:
- __TypeScript version__:
- __Running TSLint via__: (pick one) CLI / Node.js API / VSCode / grunt-tslint / Atom / Visual Studio / etc

`tslint -v`

#### Actual behavior
`unknown option: -v`

#### Expected behavior
`version: 1.2.3`

**Comment by ajafff** [comment]
Fixed by #2926. Will be part of the next release
