### ISSUE TITLE
Use nearest node_modules

### ISSUE THREAD

**Issue by Nkmol** [palantir/tslint#2973]
### Bug Report

- __TSLint version__: 5.3.2
- __TypeScript version__:  2.3.4
- __Running TSLint via__: VSCode

#### TypeScript code being linted

```ts
// No End of Line
export class AppComponent {
  title = 'app';
}
```

with `tslint.json` configuration:

```json
"eofline": true
```

<hr />

I am using a project that consists of two child projects, both child projects use different lintings (one front-end, one back-end). 

```
project
   app
   server
```
Where the "app" map uses the tslint.
When opening the "project" map, the linting does not seem to work. Only when I open the "app" map, _the linting does works_.

This does seem to be related to an implementation of **eslint** (where it does work this way)? https://github.com/Microsoft/vscode-eslint/issues/32

**Comment by ajafff** [comment]
This might be a bug with https://github.com/Microsoft/vscode-tslint
I also experienced this when opening different folders in one vscode window.

I don't think there is anything tslint can do to fix this.

**Comment by Nkmol** [comment]
@ajafff Thanks for your reply.

I should have noted this, but the reason for me posting it here, is because _it has been addressed_ at **vscode-tslint**. Where the issue was redirected to this project, as **vscode-tslint** uses the **tslint** API.

_source: https://github.com/Microsoft/vscode-tslint/issues/222_

<hr />

Would you suggest posting a new issue at the **vscode-tslint** project again?

I do not want to be stuck in the never-ending cycle of redirection :smile:

**Comment by ajafff** [comment]
I looked into this a bit more. It seems like `vscode-tslint` doesn't even try to load `tslint` when it is installed as dependency in a subdirectory when opening a file in that directory.

> Would you suggest posting a new issue at the vscode-tslint project again?

That's the best thing you can do for now. Can you @-mention me in the new issue?

**Comment by Nkmol** [comment]
Solves this with the `.vscode/settings.json`

```json
{
   "tslint.enable": true,
   "tslint.configFile": "app/tslint.json",
   "tslint.nodePath": "app/node_modules"
}
```

This works _for one typescript project_, which was the case for me.

Thank you for your time @ajafff 🥇
