### ISSUE TITLE
Rule to stop using <T>s that are the same as their defaults

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [palantir/tslint#2974]
#### TypeScript code being linted

```typescript
type StringContainer<TString extends string = string> = {
    data: TString
};

let container: StringContainer<string> = {
    data: "foo"
};
```

#### Actual behavior

No rule for this kind of behavior.

#### Expected behavior

Now that a generic defaults are a thing, it'd be great to have a rule & auto-fixer to get rid of unnecessary declarations.

**Comment by adidahiya** [comment]
this was added in [5.4.0](https://github.com/palantir/tslint/releases/tag/5.4.0) as `use-default-type-parameter` :)
