### ISSUE TITLE
Fail where project installed with npm, but success where project installed with yarn

### ISSUE THREAD

**Issue by nottoseethesun** [palantir/tslint#2978]
### Question
- __TSLint version__: 4.5.1
- __TypeScript version__: @2.3.4
- __Running TSLint via__: (pick one) CLI 

#### TypeScript code being linted

```ts
// code snippet
/node_modules/@types/request/index.d.ts:66:15: Interface 'DefaultUriUrlRequestApi<TRequest, TOptions, TUriUrlOptions>' incorrectly extends interface 'RequestAPI<TRequest, TOptions, TUriUrlOptions>'.
  Types of property 'defaults' are incompatible.
```

with `tslint.json` configuration:

```json
{
  "compilerOptions": {
    "experimentalDecorators": true,
    "outDir": "build/dist",
    "module": "commonjs",
    "target": "es5",
    "lib": ["es6", "dom"],
    "sourceMap": true,
    "allowJs": false,
    "jsx": "react",
    "moduleResolution": "node",
    "rootDir": "src",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true
  },
  "exclude": [
    "node_modules/**/*",
    "build",
    "scripts",
    "acceptance-tests",
    "webpack",
    "jest",
    "src/setupTests.ts"
  ],
  "include": [
    "src/**/*"
  ],
  "types": [
    "typePatches"
],
  "files": [
    "src/types/react-sizeme.d.ts",
    "src/types/cycle-test/main.d.ts",
    "src/types/reviz/Accordion.d.ts",
    "src/types/reviz/AccordionItem.d.ts",
    "src/types/reviz/ResizeContainer.d.ts"
  ]
}
```

#### Actual behavior
tslint tries to lint content in npm_modules.

#### Expected behavior
tslint should not try to lint content in npm_modules.

**Comment by ajafff** [comment]
I guess you are using `tslint -p tsconfig.json --typecheck`?

That error is not directly from tslint. By using `--type-check` tslint first triggers a full check by `tsc` and that's where the error comes from.

That means you probably have a different version of typescript in `node_modules/typescript` and/or `node_modules/tslint/node_modules/typescript` when installing with yarn or npm.
Do you have any `npm-shrinkwrap.json` or `package-lock.json` files that could change how `npm` installs dependencies? Or do you have a `yarn.lock` that tells yarn to install something differently?

Btw.: That's not your `tslint.json` but your `tsconfig.json`

**Comment by nottoseethesun** [comment]
Found the issue - it was indeed the version of typescript.  There were some breaking changes for this project in a typescript update.  `yarn.lock` caused the prior, non-breaking-changes typescript version to be loaded, whereas npm had no such equivalent file in the project and thus loaded the update.
