### ISSUE TITLE
Rule request: no-jsdoc-types

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [palantir/tslint#2979]
```typescript
/**
 * Does a thing.
 * 
 * @param {Function} action   Action to do.
 */
function do(action: () => void) {
  action();
}
```

There's no need for the `{Function}`. In code bases converted from JavaScript with filled out JSDoc annotations, it's common to have these unnecessary (and often vague or incorrect) types left over.

**Comment by adidahiya** [comment]
looks like this is covered by `no-redundant-jsdoc`
