### ISSUE TITLE
no-use-before-declare and export

### ISSUE THREAD

**Issue by Deathspike** [palantir/tslint#298]
If I have the following code using TSLint 2.1.0:

	'use strict';
	export = main;
	var main = {};

Which will generate the following output:

	'use strict';
	var main = {}
	module.exports = main;

With the following TSLint settings:

	"no-use-before-declare": true,

Will produce the following errors:

	src/subtitle/formats/index.ts[2, 10]: variable 'main' used before declaration

Which does not make much sense. Export statements are moved to the correct location.

**Comment by ashwinr** [comment]
sorry, we don't consider generated JS when enforcing rules on TS. All export statements that reference a variable should still happen after the variable is declared with this rule turned on.
