### ISSUE TITLE
`no-this-reassignment` in v5.5.0 Release Notes

### ISSUE THREAD

**Issue by whitetrefoil** [palantir/tslint#2999]
### Bug Report

- __TSLint version__: v5.5.0
- __TypeScript version__: N/A
- __Running TSLint via__: ANY

#### TypeScript code being linted

N/A

#### Actual behavior

The [v5.5.0 release notes](https://github.com/palantir/tslint/releases/tag/5.5.0) says "[new-rule] no-this-**re**assignment".

#### Expected behavior

But it should be `no-this-assignment`

**Comment by adidahiya** [comment]
whoops, good catch!
