### ISSUE TITLE
Bypass `no-floating-promises` with void operator?

### ISSUE THREAD

**Issue by glen-84** [palantir/tslint#3020]
I'm currently using TSLint 4.5.1.

With the `no-floating-promises` rule, I get `Promises must be handled appropriately` messages for code like this:

```ts
    public activate(): void {
        this.loadSiteSections(); // *** Problem here ***
    }

    private async loadSiteSections(): Promise<void> {
        try {
            const siteSections = await this.serviceSiteSections.getSupportedSiteSections(
                new Query().setFields("id,name")
            );

            this.siteSections = siteSections.data;
        } catch (e) {
            this.handleError(e);
        }
    }
```

If I await the call, then the `activate` method will block until the site sections are loaded, but I want to display the view/form while the list is loading.

Would it make sense to turn off this message if you use the `void` operator, as mentioned [here](https://github.com/Microsoft/TypeScript/issues/13376#issuecomment-273289748)? Like this:

```ts
    public activate(): void {
        void this.loadSiteSections(); // Intentional.
    }
```

**Comment by glen-84** [comment]
I thought that I tested this, but it seems now that this already works! Closing.

**Comment by DominicTobias-b1** [comment]
This error is so dumb to begin with
