### ISSUE TITLE
TSLint Arrow Function Rule conflicts with Angular2 AOT

### ISSUE THREAD

**Issue by zfranklyn** [palantir/tslint#3023]
Angular AOT [does not support ](https://github.com/rangle/angular-2-aot-sandbox#arrow-function-exports-top)importing arrow functions into an `ngModule`. However, TSLint requires use of arrow functions.

Is there some way to resolve this incompatibility without disabling TSLint's general rule about arrow functions?

**Comment by ajafff** [comment]
You can enable function declarations (like the example on the linked page) by adding `"allow-declarations"` to the config of the rule.

**Comment by zfranklyn** [comment]
Thanks - I think I'll go with your suggestion. I've tried many different ways of importing into `ngModule` without arrow functions, but it seems like AOT needs a function declaration to work. 

Doesn't seem like an issue for TSLint, more for AOT. Thanks!
