### ISSUE TITLE
Tab Indentation Not Respected, Wonky Output

### ISSUE THREAD

**Issue by netpoetica** [palantir/tslint#3027]
### Bug Report

This issue arose when I upgraded tslint-config-airbnb from 1x to 5x. I don't think the problem could be with tslint-config-airbnb but I opened an error there as well to see if the author might have an idea as to why. See: https://github.com/progre/tslint-config-airbnb/issues/16

- __TSLint version__: "5.5.0
- __TypeScript version__: 2.3.4
- __Running TSLint via__: (pick one) CLI

```
node_modules/.bin/tslint -c tslint.json 'src/**/*.ts*'
```

#### TypeScript code being linted

```ts
// definitely contains all tabs
```

with `tslint.json` configuration:

```json
{
	"extends": [
		"tslint-react",
		"tslint-config-airbnb"
	],
	"rules": {
		"switch-default": true,
		"no-switch-case-fall-through": true,
		"indent": [true, "tabs"],
		"ter-indent": [true, "tabs"],
		"trailing-comma": [true, {"multiline": "never", "singleline": "never"}],
		"max-line-length": [false],
		"jsx-no-multiline-js": false,
		"import-name": false,
		"align": false,
		"jsx-no-lambda": false
	}
}

```

#### Actual behavior
A variety of strange output - this is just a sample. But there are thousands of errors, all like this:

```
ERROR: ... Expected indentation of NaN spaces but found 1 tab.
ERROR: ... Expected indentation of NaN spaces but found 0.
ERROR: ... Expected indentation of 0 spaces but found 1 tab.
ERROR: ... Expected indentation of 0tabs spaces but found 2 tabs.
```
#### Expected behavior
Should expect tabs, not spaces, per tslint config

**Comment by netpoetica** [comment]
... looks like it is supposed to be "tab", not "tabs"? The documentation is incorrectly showing "tabs": https://palantir.github.io/tslint/rules/indent/

**Comment by ajafff** [comment]
> ... looks like it is supposed to be "tab", not "tabs"? The documentation is incorrectly showing "tabs": 

No, it's really "tab*s*".

The error message is not from the tslint `indent` rule. Looks like that's from `ter-indent` of https://github.com/buzinas/tslint-eslint-rules

**Comment by netpoetica** [comment]
I can assure you that I have changed it from "tabs" to "tab", and all of a sudden all of those errors have gone a way and it gives errors as expected (that is to say, if I use spaces, I will get an error, or if I use too many/too few tabs, I get an error - it works with "tab"). Here is my tslint.json config file now, which behaves as expected:

```
{
	"extends": [
		"tslint-react",
		"tslint-config-airbnb"
	],
	"rules": {
		"switch-default": true,
		"no-switch-case-fall-through": true,
		"indent": [true, "tab"],
		"ter-indent": [true, "tab", {
			"SwitchCase": 1
		}],
		"trailing-comma": [true, {"multiline": "never", "singleline": "never"}],
		"max-line-length": [false],
		"jsx-no-multiline-js": false,
		"import-name": false,
		"align": false,
		"object-shorthand-properties-first": false,
		"no-param-reassign": false,
		"array-bracket-spacing": false,
		"jsx-no-lambda": false
	}
}
```

**Comment by netpoetica** [comment]
I think I see what is happening here.

One of my extensions is using tslint-eslint-rules repo, which uses "tab" instead of "tabs".

TSLint internally is using "tabs", but tslint-eslint-rules is overriding that option to be "tab". See: http://eslint.org/docs/rules/indent#options

If you agree this is the issue, feel free to close this issue.

I think it would be valuable to ensure supporting both singular and plural, because in my situation, it was not clear to me that tslint-eslint-rules is even present (I am not using it directly).

**Comment by adidahiya** [comment]
> If you agree this is the issue, feel free to close this issue.

Yes, I believe this is the issue.

> it was not clear to me that tslint-eslint-rules is even present

I suppose we could solve this problem by requiring rules in non-core packages to have scoped names, e.g. `eslint-rules/ter-indent`, `react/jsx-no-multiline-js`. Would be willing to consider this for the 6.x or 7.x major version.
