### ISSUE TITLE
Add new `max-import-line-length` rule

### ISSUE THREAD

**Issue by SchnWalter** [palantir/tslint#3037]
It would be nice to have a larger line length limit for import rules. Depending on the project, the default `max-line-length` limit sometimes isn't enough.

Here's an example:
```
import { OrganizationErpConnectionSyncStatusComponent } from 'app/MYORG-modules/admin/pages/organizations/components/organization-erp-connection-sync-status/organization-erp-connection-sync-status.component';
```

Thank you!

**Comment by adidahiya** [comment]
I think this is best implemented as a new option to exempt `max-line-length` from checking import statements, similar to https://github.com/palantir/tslint/issues/2693. Specifying multiple max line lengths based on syntax would get overly complex.

**Comment by adidahiya** [comment]
based on above, this is a duplicate of https://github.com/palantir/tslint/issues/1872
