### ISSUE TITLE
new rule: file found without jsdoc documentation

### ISSUE THREAD

**Issue by HamletDRC** [palantir/tslint#305]
I'd like my build to fail when there is no jsdoc documentation in the file. The documentation can appear on the module or the class, whichever is top level. If the file contains neither, then just validate that /** is used somewhere.

**Comment by gscshoyru** [comment]
This rule is too narrow for inclusion in tslint. But you can use our rule pluggability framework to write this rule yourself so that tslint can use it to lint your own project. You can find documentation on this under "custom rules" in our readme.
