### ISSUE TITLE
Finding tslint.json doesn't work like it used to after update.

### ISSUE THREAD

**Issue by vhakulinen** [palantir/tslint#3050]
### Bug Report

After upgrading from tslint from 4.0.2 to 5.5.0, tslint doesn't find `tslint.json` anymore unless it sits in the some directory you're running tslint from. @ajafff suggested that this relates to some recent refactoring of the code that finds the config file.

One notable (maybe a bit unique) note on the code base I'm working in; it has multiple (nested) typescript "projects" (aka `tsconfig.json` files) and one global `tslint.json` file on the root of the code base. The `tslint.json` file is found if I open my editor (or run `tslint` from command line) in the directory where `tslint.json` file is. IIRC, my co workers have the same issue with vscode also. Currently I have some viml written to check for the file (in the path) and pass it as commandline option.

- __5.5.0__:
- __2.4.1__:
- __Running TSLint via__: (neo)vim's plugin and/or command line

#### TypeScript code being linted

Can be anything.

with `tslint.json` configuration:

This can also be anything.

#### Actual behavior

`tslint.json` file is not found.

#### Expected behavior

`tslint.json` file is found and it's rules loaded.

**Comment by ajafff** [comment]
`findup-sync` used to search until the root directory is reached.
IIRC the current implementation stops at the current directory (when using relative paths). To fix this, the path needs to be resolved to an absolute one before the lookup.
