### ISSUE TITLE
Suppressing no-floating-promises on specific function

### ISSUE THREAD

**Issue by rokoroku** [palantir/tslint#3056]
#### TypeScript code being linted

```ts
// tslint:disable-next-line:no-floating-promises
async function asyncFunction() { ... }

asyncFunction(); // no error for this function
```

Could it be possible?

**Comment by ajafff** [comment]
Use the `void` keyword when calling the function to indicate that you are not interested in the returned value:

```ts
void asyncFunction();
```

**Comment by rokoroku** [comment]
I never knew about `void` technique. 👍 
However, it seems like it's not different with this.

```ts
// tslint:disable-next-line:no-floating-promises
asyncFunction();
```

**Comment by ajafff** [comment]
You're right, disabling the rule for that line has the same effect.

There's a reason I suggested `void`. There's an open issue (and a PR https://github.com/Microsoft/TypeScript/pull/15195) for the typescript compiler to disallow floating promises in async functions. For example:

```ts
async function foo() {
    asyncFunction(); // will result in an error
}
```
To avoid this error, the proposed workaround is to add the `void` keyword https://github.com/Microsoft/TypeScript/issues/13376#issuecomment-273289748
```ts
async function foo() {
    void asyncFunction(); // no error
}
```

**Comment by rokoroku** [comment]
I got it. thank you for the information.
There will be new compiler options on async/await, and it'll be better to use them in the future.
