### ISSUE TITLE
new rule: filename must match the exported module name

### ISSUE THREAD

**Issue by HamletDRC** [palantir/tslint#306]
I'd like my build to fail when the .ts filename does not match the exported module name of the code within. 

For example: 
    class Foo {
    }
    export = Foo;

Should be in Foo.ts

foo.ts would produce an error because the case is different.

**Comment by gscshoyru** [comment]
This rule is too narrow for inclusion in tslint. But you can use our rule pluggability framework to write this rule yourself so that tslint can use it to lint your own project. You can find documentation on this under "custom rules" in our readme.
