### ISSUE TITLE
All TSL warnings & errors should be prefixed with [TSLint] or similar.

### ISSUE THREAD

**Issue by SteveALee** [palantir/tslint#3060]
When we get messages like "Warning: Cannot read property 'flags' of undefined" in often busy build command output it would help us track down the source if TSLint always prefixes it's messages.

thanks

**Comment by JoshuaKGoldberg** [comment]
Agreed, it's easy to mistake TSLint errors for TypeScript and vice versa. https://github.com/microsoft/typescript/issues?utf8=%E2%9C%93&q=is%3Aissue+tslint+is%3Aclosed+label%3AExternal

It'd be great to see a full proposal here. How should we address this? Should the default formatter(s) (#3460) include `[TSLint]` in the output in some form?

**Comment by JoshuaKGoldberg** [comment]
Coming back to this: I think it's the responsibility of the _reporter_ to report TSLint complaints more specifically. A Vim integration would complain differently from a VS Code plugin, for example.

The TSLint CLI now reports "The x-y-z rule threw an error in source-file.ts:" before complaints too.

**Comment by SteveALee** [comment]
Quite possibly, I was probably in the context of VS Code. Would need to be some sort of contract between plugins and display module.

Will close .
