### ISSUE TITLE
new rule: no relative path imports

### ISSUE THREAD

**Issue by HamletDRC** [palantir/tslint#307]
I'd like my build to fail when someone uses a relative path import, like this: 

import Foo = require('../Foo');
or 
import Foo = require('./Foo');

**Comment by gscshoyru** [comment]
This rule is too narrow for inclusion in tslint. But you can use our rule pluggability framework to write this rule yourself so that tslint can use it to lint your own project. You can find documentation on this under "custom rules" in our readme.
