### ISSUE TITLE
new rule: import name must match export name

### ISSUE THREAD

**Issue by HamletDRC** [palantir/tslint#308]
I'd like my build to fail when a module is imported with a different name than it is exported with. 

For example, these should pass: 
import Foo = require('Foo');
import underscore = require('underscore');
import Thing = require('foo/bar/Thing');

These should fail: 
import Foo = require('Bar');
import _ = require('underscore');
import thing = require('foo/bar/Thing'); // case is different

**Comment by gscshoyru** [comment]
This rule is too narrow for inclusion in tslint. But you can use our rule pluggability framework to write this rule yourself so that tslint can use it to lint your own project. You can find documentation on this under "custom rules" in our readme.
