### ISSUE TITLE
Could not find implementation for "no-unused-new" rule

### ISSUE THREAD

**Issue by cfmano** [palantir/tslint#3086]
### Bug Report

- __TSLint version__: 5.5.0
- __TypeScript version__: 2.2.1
- __Running TSLint via__: CLI

with `tslint.json` configuration:

```json
{
   "rules": {
        "no-unused-new": true
    }
}
```

#### Actual behavior
I get error:

```
Could not find implementations for the following rules specified in the configuration:
    no-unused-new
Try upgrading TSLint and/or ensuring that you have all necessary custom rules installed.
If TSLint was recently upgraded, you may have old rules configured which need to be cleaned up.
```

When I search for the rule definition, the file is missing in code, both in package in node_modules and also in source code here on GH.

#### Expected behavior
Should work as stated in [documentation](https://palantir.github.io/tslint/rules/no-unused-new/)

**Comment by IllusionMH** [comment]
@cfmano looks like PR #2269 removed (in semver major release) `no-unused-new` rule and merged into `no-unused-expression`, but docs weren't updated.

**Comment by cfmano** [comment]
@IllusionMH Thank you. I've just found that this rule doesn't exist in a list of rules in docs, but its page still exists. I came there from list of props in [tslint-eslint-rules](https://github.com/buzinas/tslint-eslint-rules) repo. I created issue there buzinas/tslint-eslint-rules/issues/249
