### ISSUE TITLE
Why is the IWalker interface imported in the same file in which it is declared?

### ISSUE THREAD

**Issue by BehindTheMath** [palantir/tslint#3093]
In [walker.ts](https://github.com/palantir/tslint/blob/30f83444fe1a0f2f999c95e7297f54361e4ad9eb/src/language/walker/walker.ts#L22-L28), the `IWalker` interface is declared, and it's also imported in the same file.
It looks like the import was added in [this commit](https://github.com/palantir/tslint/commit/8a7cfbf585b5d2a1ad05e55e336669703424f452#diff-eca27285305f267a4b665b0ed6894ad9R22).
I don't understand why it's necessary to import it in the same file. Wouldn't it be accessible even without that?

**Comment by adidahiya** [comment]
it's unnecessary; that must've been an erroneous line introduced by an auto-importing tool in the dev's IDE. easy to fix
