### ISSUE TITLE
no-unused-variable not working

### ISSUE THREAD

**Issue by phil123456** [palantir/tslint#3094]
(I asked this on SO but nobody ever answers TSLINT issues there)

I have many unused params for my functions and constructors, usualy, an underscore does the trick

1) but here I still get the error message

I tried this (or adding an underscore)

/* tslint:disable-next-line:no-unused-variable */
constructor(private el: ElementRef) {  }

with no luck

2) how do we deal with parameters that are only used in the templates, such errors will be triggered ?

I have to console.log to faint using a variable

thanks

**Comment by ajafff** [comment]
Just make it public. Making it private is wrong anyway: the Angular compiler creates a new class from your template at compile time. That class accesses your private property from outside. That only works when using JIT compilation. If you compile AOT, you will get a compiler error.

**Comment by phil123456** [comment]
AOT threw errors when I tried to use it, logged an issue, nobody helped me out, so I never used it

but how do you deal with variables used only in templates ? does not make much sens to make them public if they are not meant to be

**Comment by ajafff** [comment]
Properties used in the template need to be public. They are accessed from outside the class. That's what my comment from above tries to explain.
I know that's not desirable, but that's just how it is.

**Comment by phil123456** [comment]
all my variables are private and are clearly working well with the template

anyway I just find odd tslint has no per line instruction to have exceptions

**Comment by ajafff** [comment]
> all my variables are private and are clearly working well with the template

Because you access them from generated JavaScript and not from TypeScript. Access modifiers in TypeScript are only enforced during compilation.

> anyway I just find odd tslint has no per line instruction to have exceptions

I tried to reproduce that with your code snippet from above and it worked as intended, i.e. no error was shown:
```ts
/* tslint:disable-next-line:no-unused-variable */
constructor(private el: ElementRef) { }
```

You might be using an older version of TSLint ...

Can you please provide a working reproduction and open a new issue for that.

**Comment by phil123456** [comment]
I'd be better using a more recent version

I use
    "tslint": "^4.3.1",
    "tslint-loader": "^3.3.0",

**Comment by ajafff** [comment]
> "tslint": "^4.3.1"

That may be the cause of your problem. The rule was completely rewritten in tslint@5.0.0
