### ISSUE TITLE
Lint against static-only classes

### ISSUE THREAD

**Issue by lfairy** [palantir/tslint#3111]
Users who come from a Java-style OO language may wrap their utility functions in an extra class, instead of putting them at the top level. In this case, they probably should instead use inner namespaces or remove the nesting altogether.

I propose a `no-static-only-class` rule that warns on

* a class
* with only static members
* which does not:
    * extend another class or implement an interface, or
    * have a non-empty constructor

**Comment by ajafff** [comment]
Fixed by #3119
