### ISSUE TITLE
Count number of files linted

### ISSUE THREAD

**Issue by liquorvicar** [palantir/tslint#3123]
We had some issues with globs when running tslint via npm (solved by adding quotes as per https://github.com/palantir/tslint/issues/1862). While we were investigating the issue it was really hard to tell if tslint was running as expected or not. In the end we had to deliberately break the linting in certain files to check tslint was linting the files we expected. I couldn't see anyway of enabling any verbose or debug output (for example) to show how many files have been linted. Is this a feature that would be of interest/fit with the direction of tslint? If so, I would be willing to work on a PR for it.

**Comment by ajafff** [comment]
There's already an issue tracking this feature request. I'm closing this in favor of #2267
