### ISSUE TITLE
The description details on rule `no-floating-promises` has a typo on rule `no-unused-expression` (an  extra `s`)

### ISSUE THREAD

**Issue by sdeprez** [palantir/tslint#3124]
See:
https://github.com/palantir/tslint/blob/3369ff8603381fe2990e052f1f74a2c138b33e0b/src/rules/noFloatingPromisesRule.ts#L28

The actual rule is  [`no-unused-expression`](https://github.com/palantir/tslint/blob/3369ff8603381fe2990e052f1f74a2c138b33e0b/src/rules/noUnusedExpressionRule.ts#L39) without the final `s`.

**Comment by ajafff** [comment]
Fixed by #3125. Thanks for reporting.
