### ISSUE TITLE
Allow tslint to use require hooks such as ts-node/register for custom rules

### ISSUE THREAD

**Issue by MadaraUchiha** [palantir/tslint#3133]
Howdy!

I was pretty excited when I saw you could write your own TSLint rules! I was less so when I discovered all custom rules had to be compiled ahead of time. 😢 

Mainly, tslint is part of my build, if I want to have custom rules I have to either:

- Add a build for my build: compile rules before I call `webpack` or whatever build system I use
- Add the compiled output of my `tslint-rules` directory to source control.

Neither of those options seem great to me (If there's a better, third option, I'd love to hear it!)

I propose a similar feature to Mocha's `mocha -r ts-node/register` which gives it the option of a register hook. That would allow TSLint to read custom rules in any* language which has a register hook (for example, Babel, and more importantly, TypeScript).

WDYT?

cc @linkgoron @ssube

**Comment by ajafff** [comment]
There has been a PR recently that added the ability to load any* source as tslint rule. #3108 will be part of the next release.

Instead of using `tslint -p .` you could then `ts-node node_modules/.bin/tslint -p .`

**Comment by MadaraUchiha** [comment]
Huzzah! I missed that! Is there a roadmap for the next release? When can I expect this to land?

**Comment by ajafff** [comment]
There's no schedule or roadmap. I guess you can expect a new release within the next 2 weeks.

**Comment by MadaraUchiha** [comment]
Cheers, will be looking forward to it!

**Comment by aleclarson** [comment]
I can't get tslint to load custom rules from a given `rulesDirectory` while using `ts-node/register` to skip the compilation phase for unit testing.

```ts
import 'ts-node/register';

// Later on...
const linter = new Linter({
  fix: false,
  formatter: 'json',
  rulesDirectory: 'src/',
})
linter.lint(fileName, source)

// Error: No valid rules have been specified
```
