### ISSUE TITLE
Rule request: no throwning new errors in non-never functions

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [palantir/tslint#3134]
Looking forward to some :fire: discussions around this one. 😉 

I recently spent some time diagnosing "miscellaneous" errors in a large web app (many edge cases, wide browser support, internally developed HTML view layer). Miscellaneous in this context means they came **without stack traces or line/column information**, which happens with Internet Explorer in cross-origin `<iframe>` embeds or generally from older builds of Edge.

In order to still get stack traces on IE and old Edge, we had to stop directly `throw`ing `new Error`s and instead use a factory:

```typescript
function errorFactory(message: string): Error {
    if (isInternetExplorer()) message += `\nStack: ${new Error().stack}`;
    throw new Error(message);
}

// Error case, instead of throw new Error("foo");
throw errorFactory("foo");
```

Alternative could be using a function returning `never` or an Error sub-class that takes in a stack.

```typescript
function throwAndLog(message: string): never {
    if (isInternetExplorer()) message += `\nStack: ${new Error().stack}`;
    throw new Error(message);    
}

class ErrorWithManualStack extends Error {
    constructor(message, stack) {
        if (isInternetExplorer()) message += `\nStack: ${stack}`;
        super(message);
    }
}

throwAndLog("foo");
throw new ErrorWithManualStack("foo", new Error().stack); // eww
```

Vaguely related: there's also the (controversial?) ["exceptions are bad"](https://stackoverflow.com/questions/1736146/why-is-exception-handling-bad) mindset some folks have. A tl;dr is that throwing errors adds an implicit "this might do something else" to functions that then must be accounted for.

So, **would it make sense for TSLint to have any variation of a `no-throwing-new-errors` rule**? Some options to enable by default could be...
* Allowing `throw errorFactory("foo")` and similar
* Allowing `throw new ErrorWithManualStack("foo", new Error().stack)` and similar
* Allowing throws in functions whose return types are only `never`
* Not enabling this in `tslint:all`

**Comment by ajafff** [comment]
Sounds a bit too specific to be in TSLint core.

> - Not enabling this in tslint:all

I think this is evidence enough that it's probably better off in a custom rules package.

> - Allowing throws in functions whose return types are only never

That one would make sense, but you still need `throw neverReturningFunction("message")` to make the compiler happy. Related: https://github.com/Microsoft/TypeScript/issues/12825

I acutally had to think about `throw errorFactory("foo")` for some time. You need to throw there to tell the compiler that control flow ends. But the `throw` is actually never executed because the factory already throws. That's not a pattern I'd like to advertise.

**Comment by JoshuaKGoldberg** [comment]
> But the throw is actually never executed because the factory already throws

Alternately:
```typescript
function errorFactory(message: string): Error {
    if (isInternetExplorer()) message += `\nStack: ${new Error().stack}`;
    return new Error(message);
 // ^^^^^^
}

// Error case, instead of throw new Error("foo");
throw errorFactory("foo");
```
