### ISSUE TITLE
Selectively suppres unused variable warning

### ISSUE THREAD

**Issue by wereHamster** [palantir/tslint#314]
Haskell has a nice way to selectively suppress their equivalent of *unused variable* by prepending the variable with an underscore. I'm particularly interested in suppressing the warning for unused function arguments.

**Comment by wereHamster** [comment]
So my pull request was rejected saying that I should either use a custom rule or tslint flags instaed. Both are not ideal solutions. It's not really a new rule but rather an extension or modification of an existing rule.  

When implementing this as a custom rule, I'd basically have to copy the existing rule and adapt it. Then keep it in sync with changes in the main repository. Having this part of the core ruleset is desirable because then we can use the existing test infrastructure and it becomes immediately available to all users.

TSLint flags is not a good solution either, because those work on whole lines, but I'd prefer to enable/disable the check on individual variables. Flags also add quite a bit of noise to the code, compared to a subtle underscore. And there's greater potential to screw the configuration up by forgetting to re-enable the checks.

**Comment by Pajn** [comment]
I have the code `.map(([_, value]) => value)` an currently get a warning on `_`.
In Dart `_` is a name that is used when you are ignoring parameters and you don't get unused warnings for it. I would like that pattern in TS to as it's clear that you don't care about that parameter.

I understand that you maybe don't want to support that specific case either, but maybe some kind of flag can be added to enable users to configure something like that. Maybe a list of names to ignore or something like that?

I would be happy to provide a PR if I only knew what design that you would like.

**Comment by wereHamster** [comment]
#318 was rejected, I'm not sure if you'd have better luck now. You can try though. If you don't succeed then a custom rule is the way to go.

**Comment by Pajn** [comment]
Yes, I know. But I would like input from the tslint team if there is some design they would accept, or even like :)
Some unused parameters may come up by code style so a design that isn't too complex but solves most use cases can be useful for many tslint users.
Eslint uses [patterns](http://eslint.org/docs/rules/no-unused-vars) which would solve both of our use cases and still be generic enough to solve other possible use cases as well

**Comment by adidahiya** [comment]
Apologies for the delay / lack of feedback on this @wereHamster. 

I think ignore patterns like those supported by ESLint are a good idea. Would be happy to look at a PR!
