### ISSUE TITLE
Docs - for style rules, before/after code snippets

### ISSUE THREAD

**Issue by aervin** [palantir/tslint#3142]
The rationale for many style rules is readability. In the docs, examples of the "bad" code being linted against, as well as the "ideal" code enforced by tslint would be very helpful.  It may introduce users to the more obscure or lesser-used rules provided by tslint. 

Some rules that may benefit from this change:
`align`,
`import-spacing`,
`completed-docs`,
`one-line`,
`prefer-template`,
`space-within-parens`

**Comment by ajafff** [comment]
#1329 tracks adding examples to the docs.
I agree with @adidahiya https://github.com/palantir/tslint/issues/1329#issuecomment-319597483 that adding links to the rule tests might be sufficient.

**Comment by aervin** [comment]
I agree the test files demonstrate the functionality very well, but they're somewhat cryptic at first glance. Anyway I'll close this as the linked issue is practically identical.
