### ISSUE TITLE
Proposal: add `files` field in config file.

### ISSUE THREAD

**Issue by acrazing** [palantir/tslint#3167]
The proposal allows user specify which files should be checked when use command line. And for IDE to determining the current opening fie if should be checked or not. For example, the WebStorm will check any `*.ts` files opening in edit tab, even if it is not in the current project.

**Comment by ajafff** [comment]
WebStorm does not use the CLI, therefore it has to include and exclude files on its own behalf.
That part of you feature request is better suggested in their issue tracker.

---

Re: `files` in tslint.json
* would only work if you use `tslint -c tslint.json`
* once you specify a file as CLI argument, it should override the ones specified in the config
* how should `tslint-c tslint.json -p tsconfig.json` work? Take all files specified in `tsconfig.json` or `tslint.json`?

**Comment by adidahiya** [comment]
Related: https://github.com/palantir/tslint/issues/858

**Comment by adidahiya** [comment]
`--project path/to/tsconfig.json` should be sufficient for most use cases like this.
