### ISSUE TITLE
object-literal-sort-keys: allow grouping with new lines

### ISSUE THREAD

**Issue by Merott** [palantir/tslint#3190]
### Feature Request

The `object-literal-sort-keys` can sometimes get in the way of logically grouping properties of an object. By allowing additional new lines inside the object literal, it makes it possible to logically group properties while keeping the elements within each group in alphabetical order, like this:

```ts
const person = {
  id: 123

  height: 180
  weight: 85

  preferences: {
    ...
  }
}
```

instead of:

```ts
const person = {
  height: 180
  id: 123
  preferences: {
    ...
  }
  weight: 85
}
```

**Comment by ajafff** [comment]
Fixed by #3191
