### ISSUE TITLE
Help determine when tslint.config needs to be updated.

### ISSUE THREAD

**Issue by jschank** [palantir/tslint#3213]
### Bug Report

- __TSLint version__: 5.3.2
- __TypeScript version__: 2.3.4
- __Running TSLint via__: (pick one) ng CLI

#### TypeScript code being linted

Not a code problem, it is a config problem.

#### Actual behavior

My tslint.config had among the rules
    "semicolon": "always",

This rule was being completely ignored. Possibly because the new format should be this:
    "semicolon": [true, "always"],

#### Expected behavior

As tslint evolves, it seems like configurations need to be kept up-to-date. And this current problem with "semicolon" leads me to wonder what other rules I have, are no longer correctly configured.

It would be nice if there were either:
* a way to validate my current rules against the current schema, so I can learn what rules need to be updated.
* a way to version the config. So that newer versions of the tslint engine, could be compatible with older versions of rules. So that migrations can be better managed
* a way to lint the config, if you see what I mean, so that I could correct any problems with my rules
* an error thrown, in cases like "semicolon" so that I know what I need to fix.

Any of those options would be nice. As you can see, there is a problem with staying on top of the configuration.

Thanks
Schank

**Comment by ajafff** [comment]
> ng CLI

> "semicolon": "always",

I had that problem, too. It's not your fault. The Angular CLI does it wrong when scaffolding the project.

> so I can learn what rules need to be updated

There should be no need to alter your config between minor releases. Even major releases can make sense of the old config and convert it to the newer one internally.

> a way to version the config.

Unlikely to happen as it adds a big maintenance burden.

> a way to lint the config

JetBrains IDEs and VSCode-tslint do a decent job at validating your tslint.json according to the schema. Unfortunately that depends on an external schema store which is likely out of sync.

> an error thrown

Tracked by #889. Waiting for someone to implement it.

**Comment by jschank** [comment]
Thank you for the reply.
You totally hit all the points.

:)

**Comment by JoshuaKGoldberg** [comment]
Great answer by ajafff - closing this as a duplicate!
