### ISSUE TITLE
undefined variable in html code

### ISSUE THREAD

**Issue by houcode** [palantir/tslint#3218]
Is there a rule or possibility to output a error warning/message with tslint, if a variable in the Html code is undefined or wrong?

for example:
<h2> {{ selectedHero.name.SOMETHINGSTUPID | uppercase }} </h2>

(there´s no error or warning when i have the SOMETHINGSTUPID-part in my code !? 

Thank you

**Comment by ajafff** [comment]
TSLint core does not contain any library specific rules.
Since your request is about angular templates, you should take a look at https://github.com/mgechev/codelyzer (or use the AOT compiler)
