### ISSUE TITLE
Rule idea: Warn about babel-plugin-transform-typescript caveats

### ISSUE THREAD

**Issue by epeli** [palantir/tslint#3221]
Upcoming Babel 7 has ability to strip Typescript types like it can strip Flow types. There some caveats however since some Typescript features have some runtime implications. It would be nice to have tslint warn when those features are used.

For example enums have some issues https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-typescript

More info https://news.ycombinator.com/item?id=15236089

**Comment by ajafff** [comment]
So you basically want to forbid enums in your code?
IMO that use case seems too specific to be a core rule. It will be fairly easy to implement it as a custom rule though.

**Comment by epeli** [comment]
Babel 7 is still in beta and the implications of using babel strip types are not so clear yet. Just throwing the idea out there for now.

But yeah, this could be better as a separate rule set like tslint-react.

**Comment by JoshuaKGoldberg** [comment]
Yes, this would be a good external rule. Marking this as closed but please do post here if you create it!
