### ISSUE TITLE
tslint:disable comments are ignored when using --type-check

### ISSUE THREAD

**Issue by paxos** [palantir/tslint#3242]
### Bug Report

- tslint@5.7.0
- typescript@2.5.2
- __Running TSLint via__: (pick one) CLI

#### Actual behavior

Files including the `/* tslint:disable */` comment on top should not be linted.

#### Expected behavior

Files are linted.

This only happens when the `--type-check` param is used. It is required to use this param, otherwise unused imports are not correctly reported.

**Comment by ajafff** [comment]
The files are not linted, they are type checked. There is no way to ignore files while type checking.
So this is the behavior you opted into by using `--type-check`. If you don't want this behavior, you should stop using `--type-check`. TSLint will continue to work as expected without the flag. 

Related: https://github.com/palantir/tslint/issues/1603#issuecomment-317545074
