### ISSUE TITLE
New rule: remind trim strings before comparing them

### ISSUE THREAD

**Issue by bolatovumar** [palantir/tslint#3245]
I'm thinking of a rule which would warn you when you compare two strings before trimming them first.
Often you can end up with subtle bugs when you compare untrimmed strings, especially with user input.

I'm also thinking this rule should have an option which allows enabling a warning to convert strings to lowercase or uppercase before comparing them.

Would this be something that you are interested in?

Any suggestions for rule name, if there is interest?

**Comment by adidahiya** [comment]
This seems a little too specific / limited for a core rule. Would prefer to keep it in third party rulesets.

**Comment by bolatovumar** [comment]
Alright, makes sense. Thanks for responding.
