### ISSUE TITLE
Allow comma for type literal delimiter

### ISSUE THREAD

**Issue by allbto** [palantir/tslint#3266]
### Request

- __TSLint version__: 5.7.0
- __TypeScript version__: 2.5.3
- __Running TSLint via__: CLI

Is it possible to let us decide which delimiter to use for type-literal-delimiter? Whether semicolon (default), comma or none ?

#2787 Changed the default behavior of type-literal-delimiter from comma to semicolon.
While this can work for some, those of us with `"semicolon": [true, "never"]` rule would probably prefer not to use semicolon anywhere.
However, I do see the important of adding a delimiter for type literal, I just wish it wasn't semicolon.

**Comment by abhimanyujha** [comment]
Do we have any solution for the same. I am also facing the same issue in my project. An help how can i make it configurable to accept both comma and semi colon. Thanks

**Comment by saadq** [comment]
Ideally it would be something like [`member-delimiter-style`](https://github.com/nzakas/eslint-plugin-typescript/blob/master/docs/rules/member-delimiter-style.md) from `eslint-plugin-typescript`, which lets you choose `"semi"`, `"comma"`, or `"none"` for the delimiter.

**Comment by JoshuaKGoldberg** [comment]
☠️ *TSLint's time has come!* ☠️ 

TSLint is no longer accepting most feature requests per #4534. See **[typescript-eslint.io](https://typescript-eslint.io)** for the new, shiny way to lint your TypeScript code with **ESLint**. ✨ 

It was a pleasure open sourcing with you all!
