### ISSUE TITLE
Declare/sort scope functions together/alphabetically 

### ISSUE THREAD

**Issue by aervin** [palantir/tslint#3269]
### Rule suggestion
Because the declaration order of JS functions within a given scope is irrelevant, I like to place them together within a block or file (depending) and alphabetize them. I think it makes files easier to read, and it makes finding functions (when debugging or otherwise) much easier.

This is the code I want to lint against:
```
function foo(a: string): void {}
function z(c: boolean): void {}

class bar extends fooBar {
    // ... code
}

function bar(b: number): void {} // Same scope as foo and z functions. Why declare them separately?
```
#### Expected behavior
The linted result would be:
```
function bar(b: number): void {}
function foo(a: string): void {}
function z(c: boolean): void {}

class bar extends fooBar {
    // ... code
}
```
I imagine the file or scope's first function declaration would be the "anchor" for relocated functions.

**Comment by uccmen** [comment]
👏🏽

**Comment by JoshuaKGoldberg** [comment]
This seems pretty esoteric for a core rule. @aervin I would suggest making this in a separate repository + npm package, and linking to them in this issue.

Leaving this open in case there's a strong need for this kind of thing.

**Comment by JoshuaKGoldberg** [comment]
Looks like nobody piped up. Closing this issue per #4534. If you _really_ need the rule, custom rules are always an option and can be maintained outside this repo!
