### ISSUE TITLE
[site update suggestion] Add mention of astexplorer.net

### ISSUE THREAD

**Issue by aervin** [palantir/tslint#3287]
### Suggestion
I think most anyone charged with managing a Typescript codebase can see the value in `tslint`, but some may not see a clear path to implementing custom rules. The AST in particular can be mystifying upon first introduction. This [AST explorer tool](http://astexplorer.net/) (and there may be others like it) is very useful for bridging the gap in understanding between the Typescript one writes and the object representation `tslint` uses for linting. I would have benefited personally had such a tool been linked in the docs, so I thought I'd share. I'm proposing something between a mention of this tool in the "Custom rules" portion of the docs, or perhaps even a "Resources" section on the "Develop" page.

**Comment by ajafff** [comment]
Agreed. I think it belongs to "Develop". Having a separate page for "Resources" only makes sense if there's more than one link.
Also make sure to add a note that astexplorer.com is not always up to date. For example right now typescript@latest is 2.5.3 and astexplorer is still on 2.4.1

**Comment by ajafff** [comment]
Fixed by #3295
