### ISSUE TITLE
no-any rule exceptions

### ISSUE THREAD

**Issue by NN---** [palantir/tslint#330]
The rule is good but too restrictive.
Libraries and frameworks should be allowed to use 'any' type.
Some callbacks are required to receive 'any' type as well.
It is also impossible to create a function which just forwards arguments since it needs any.

Is it possible somehow to allow these scenarios ?

**Comment by adidahiya** [comment]
1. you probably shouldn't be linting the typings files for libraries you depend on
2. the advent of union types greatly reduces the number of real use cases for `any`
3. you can disable tslint rules inline like so: `/* tslint:disable no-any */`

**Comment by NN---** [comment]
1. Some frameworks have no knowledge about TSLint yet :)
2. It is true, but take for example console.log function, it can receive anything.
Writing wrapper is a problem:
function myLog(message: any) { console.log(message); } // Error ;(
3. Nice.

**Comment by adidahiya** [comment]
> Some frameworks have no knowledge about TSLint yet :)

How are you running tslint? What I mean to say is that you shouldn't feed those typings files to `grunt-tslint`, `gulp-tslint`, the `tslint` CLI, or whatever you're using to run the linter.

**Comment by NN---** [comment]
You are correct, this issue is solved.
What is more important to me is how to solve the "2".
Does TSLint has store/restore feature or one line/statement/expression ?
For instance:

```typescript
// storing original behaviour and changing to no-any: false
/* tslint: push, disable no-any */
var a: any = 1; // no warning
// restoring default behaviour
/* tslint: pop */
```

or smth simpler:

```typescript
/* tslint: expression, disable no-any */
var a: any = 1; // OK
var b: any = 2; // Error 
```

**Comment by ashwinr** [comment]
@NN--- you can remove `console.log` as an option from the ban rule in `tslint.json` or use `tslint:disable` and `tslint:enable` (please refer to the README)

**Comment by NN---** [comment]
Can I have tslint:restore ? I do not want to enforce , just to restore the original rulle.

**Comment by gscshoyru** [comment]
This already exists -- tslint:enable works exactly the same but in reverse. Please check the documentation in the readme for more details.

**Comment by NN---** [comment]
And how I force enable if 'enable' can just restore ?

**Comment by gscshoyru** [comment]
...I'm not sure quite what you mean. You can use disable to disable to disable all rules, or give it a list to disable specific once. You can use enable to re-enable all disabled rules, or give it a list to re-enable specific ones. You can't enable rules that aren't listed as enabled in your tslint.json. Does that answer your questions?

**Comment by NN---** [comment]
Oh, I see. Yes it does answer  my question.
Btw, is there any reason for not having option to forcibly enable rule without listing in tslint.json ?

**Comment by gscshoyru** [comment]
If you don't list the rule in tslint.json, the rule won't be loaded. And if the rule isn't loaded, it can't be enforced. 

Why is that something you'd want, anyways?

**Comment by NN---** [comment]
Nothing, it was just a question.
I got the answer I needed.
Thanks !
