### ISSUE TITLE
--type-check results include .d.ts files marked as excluded from CLI and tsconfig.json

### ISSUE THREAD

**Issue by jimmyheaddon** [palantir/tslint#3321]
Sorry if this has been raised elsewhere, I had a search but couldn't find anything obvious.  Hopefully this isn't just user error!

### Bug Report

- __TSLint version__: 5.7.0
- __TypeScript version__: 2.5.3
- __Running TSLint via__: CLI and Visual Studio Code

#### TypeScript code being linted

```ts
// Multiple TS, TSX and d.ts files across a react-redux project
```

with `tslint.json` configuration:

```json
{
    "extends": [
        "tslint:latest"
    ],
    "exclude": [
        "node_modules",
        "typings"
    ]
}
```

#### Actual behavior
Running `tslint --project tslint.json --type-check` results in all `d.ts` files under `node_modules` and `typings` directories being included.

A small excerpt:

```
Error at typings\globals\node\index.d.ts:3620:3: Duplicate identifier 'export='.
Error at typings\modules\react-measure\index.d.ts:8:21: A tuple type element list cannot be empty.
Error at typings\modules\react-measure\index.d.ts:9:21: A tuple type element list cannot be empty.
Error at typings\modules\react-measure\index.d.ts:10:25: Cannot find name 'bool'.
Error at typings\modules\react-measure\index.d.ts:11:20: Cannot find name 'bool'.
Error at typings\modules\react-measure\index.d.ts:13:25: Cannot find name 'bool'.
Error at typings\modules\react\index.d.ts:167:11: Type 'Component<P, S>' has no properties in common with type 'ComponentLifecycle<P, S>'.
```

Simply removing `--type-check` fixes this, with or without a `--config` argument being passed too.

Or... if you change the `excludes` section to the below, then it returns a slightly different set of results from the excluded paths, so I assume it's using these paths in some manner.

```
"exclude": [
  "**/node_modules/**",
  "**/typings/**"
]
```

I you provide zero `exclude` config, then it still behave the same.  Even if you pass globs on the CLI, such as:

`tslint --project tslint.json --type-check --exclude **/*.d.ts`

or

`tslint --project tslint.json --type-check --exclude **node_modules**

#### Expected behavior
The paths declared in `excluded` are honoured, as occurs when the `--type-check` argument is not provided.

**Comment by ajafff** [comment]
Does your project compile with plain `tsc -p .`? If not, there is nothing TSLint can do about it.

Note that `"exclude"` in tslint.json is not released, yet.

Also note that `--exclude` only excludes files from linting, not from type checking.

If you want to exclude files or folders from type checking, you need to exclude them from your project. Do that by adding them to the `"exclude"` section of your `tsconfig.json` (ts**config**).

The quick fix for your case is `"skipLibCheck": true` in your `tsconfig.json`'s `"compilerOptions"` section. That will alter how typescript checks dependencies of your project.

Last thing to note: you no longer need `--type-check` to enable rules which need type information. Just use `--project`.

**Comment by jimmyheaddon** [comment]
Hi @ajafff, thanks for that

The project compiles with `tsc -p .` no problem, and the linting works fine without the `--type-check` argument provided.

I didn't realise `exclude` wasn't released yet, is the documentation correct, just a little ahead of the code right now?  My `tsconfig.json` already has the exclusion entries for both `node_modules` and `typings`, and it's happy to honour that under the extra argument is declared.

I'm happy to exclude it if you don't believe it's necessary now, I was just going by the documentation I could find :)

Thanks again!

**Comment by ajafff** [comment]
> The project compiles with tsc -p . no problem

That's weird. Behind the scenes TSLint uses the same TypeScript API as `tsc` ...
I don't think it's worth investigating, though. See below.

> I'm happy to exclude it if you don't believe it's necessary now

You are safe to omit `--type-check`. Type checking should be done by the compiler anyway.
Without type checking the linter is notably faster.
And I just opened a PR to deprecate `--type-check` altogether. I expect it to be removed in the next major version.

> I didn't realise exclude wasn't released yet, is the documentation correct, just a little ahead of the code right now?

Documentation on palantir.github.io/tslint is always in sync with the latest release. I can't find any documentation about `exclude` in `tslint.json` there. The docs in this repo are ahead of the release, of course.

---

Let me know if this has resolved your problem so I can close this issue.

**Comment by IoannisLiapis** [comment]
nein

**Comment by jimmyheaddon** [comment]
Hi @ajafff, the removal of the `--type-check` argument resolves the issue yes.  I figured the exclusion documentation for the CLI would apply to type checking, but no worries if that's not the case.

I'll close this one off, thanks
