### ISSUE TITLE
Display violated rule number on output

### ISSUE THREAD

**Issue by jez9999** [palantir/tslint#3327]
When I run tslint I see a bunch of errors and the filename/line number the rule violation occurred.  I do not however see the rule number violated.  This would be very useful.  Please add it.

**Comment by ajafff** [comment]
By "rule number" you mean the rule name?
If yes, just use verbose formatter: add `-t verbose` CLI argument.

Or do you mean the total number of failures?

**Comment by jez9999** [comment]
Ah, verbose was what I wanted.

**Comment by ajafff** [comment]
fwiw #2228 tracks making `verbose` the default formatter.
