### ISSUE TITLE
Sort fileFailures by line and character?

### ISSUE THREAD

**Issue by eggggger** [palantir/tslint#3335]
😳

**Comment by ajafff** [comment]
Is this a feature request for the API or the CLI?
Can you please be elaborate a bit more about your use case?

**Comment by eggggger** [comment]
If i delete a line for fix  some errors like `no-unused-variable`, the next line number in error messages will go wrong, so I always fix errors  by bottom-up. But now the line number is unordered.

**Comment by ajafff** [comment]
@eggggger I see, so we are only talking about the formatted output when running TSLint CLI.

That means we don't need to sort the failures unconditionally. It's only required for formatters intended for human consumers.

**Comment by ajafff** [comment]
Fixed by #3345
