### ISSUE TITLE
prefer-conditional-expression: add option "avoid-nested"

### ISSUE THREAD

**Issue by ajafff** [palantir/tslint#3353]
We should try to avoid suggesting nested conditional expressions. We already avoid `if-else-if-else` when `"check-else-if"` is not enabled. However you still end up with nested conditional expressions if one of the assignments in an `if-else` contains a conditional expression:

```ts
if (foo) {
    bar = 0;
} else {
    bar = baz ? 1 : 2;
}

// requires you to write this:
bar = foo ? 0 : baz ? 1 : 2;
```

Do we want to avoid this by default and add an option to enable nested conditional expressions?
Or leave the default unchanged and add an option to avoid this behavior?

**Comment by JoshuaKGoldberg** [comment]
☠️ *TSLint's time has come!* ☠️ 

TSLint is no longer accepting most feature requests per #4534. See **[typescript-eslint.io](https://typescript-eslint.io)** for the new, shiny way to lint your TypeScript code with **ESLint**. ✨ 

It was a pleasure open sourcing with you all!
