### ISSUE TITLE
member-ordering is missing a code example disabling the alphabetize option

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [palantir/tslint#3357]
https://palantir.github.io/tslint/rules/member-ordering/

Although `alphabetize` is referenced in the descriptions, it's not shown in usage. Users would have to experiment locally and/or look through the rule source to verify that it's doable with just `[true, { alphabetize: false }]`.

**Comment by Falieson** [comment]
@JoshuaKGoldberg I disagree that the PR #3734 closes this issue.
https://palantir.github.io/tslint/rules/member-ordering/ should have an example of usage with the `alphabetize` option. Its not even included in the schema.

**Comment by Falieson** [comment]
@johnwiseheart  I disagree that the PR #3734 closes this issue.
https://palantir.github.io/tslint/rules/member-ordering/ should have an example of usage with the alphabetize option. Its not even included in the schema.
