### ISSUE TITLE
Program stucks when running `tslint **/*.ts` event if `tslint -e node_modules **/*.ts`

### ISSUE THREAD

**Issue by JounQin** [palantir/tslint#3366]
### Bug Report

- __TSLint version__: 5.8.0
- __TypeScript version__: 2.5.3
- __Running TSLint via__: CLI

#### Actual behavior
holding on linting node_modules .ts files

#### Expected behavior
except node_modules, just lint source code
For now I can only use `tslint {*.ts,src/*.ts,src/**/*.ts}` as a workaround.

**Comment by ajafff** [comment]
try `tslint -e 'node_modules/**' '**/*.ts'`

**Comment by JounQin** [comment]
Thx, that works.
