### ISSUE TITLE
no-implicit-dependencies: ignore type-only imports?

### ISSUE THREAD

**Issue by ajafff** [palantir/tslint#3375]
Follow-up on the dicussion in https://github.com/palantir/tslint/pull/3343#issuecomment-338426483.

We can probably detect if all imprted symbols of an import statement are only used in the type domain. Should be possible without the type checker. In that case the import statement is elided and not evaluated at runtime. Therefore the imported module doesn't need to be declared as dependency.

I don't know how common such a scenario is in "real world code". That's why I want to get more community feedback before implementing.

Maybe it's sufficient to just add a whitelist option to the rule.

/cc @balassy @alokito

**Comment by dsole** [comment]
I've been struck by this same issue - I have @types and @(my private account) modules that only export type definitions and cause no-implicit-dependencies to fail.

Perhaps #3343 should be reversed until this can be resolved ?

**Comment by ajafff** [comment]
@dsole modules that only contain type declarations can declare them as global types. They are automatically picked up by typescript without the need to import anything. I consider this a bug in the type declaration package.

I don't think TSLint should revert adding the rule. It still works for all regular imports.
You can disable the rule for such edge cases until we have sorted this out.

**Comment by JoshuaKGoldberg** [comment]
> Therefore the imported module doesn't need to be declared as dependency

Does it not? If types from implicit dependencies are relied upon by build, a modules update that happens to change one of those dependencies could unpredictably fail the build.

**Comment by dan-kez** [comment]
I realize this is an old issue but it would be very useful for our build system - not sure if there is any opportunity to tackle this issue.

**Comment by JoshuaKGoldberg** [comment]
☠️ *TSLint's time has come!* ☠️ 

TSLint is no longer accepting most feature requests per #4534. See **[typescript-eslint.io](https://typescript-eslint.io)** for the new, shiny way to lint your TypeScript code with **ESLint**. ✨ 

It was a pleasure open sourcing with you all!
