### ISSUE TITLE
Allow modifying rule config mid-file

### ISSUE THREAD

**Issue by jez9999** [palantir/tslint#3382]
At the moment you can use flags to enable/disable rules mid-file:

    /* tslint:disable:rule1 rule2 rule3... */

I think you should be able to change rule config too.  Maybe `enable` could optionally take an object param:

    /* tslint:enable:rule1 { severity: 'warning', options: [1, 2] } rule2 rule3... */

**Comment by ajafff** [comment]
Modifying `severity` may be possible.
Changing the rule options while processing on the other hand is not possible.

The current process works this way:
* apply all rules to a file and get all failures
* if there are failures, find all enable/disable comments
* determine the disabled ranges per rule
* remove all failures that intersect a disabled range

Here's the problem with changing the options mid-file:
You could change the config in the middle of a statement, expression, whatever AST node. The rule would need to check every time if and how a certain range should be handled. That increases complexity unnecessarily.
In addition it's not possible to change the configuration of a rule once it is created. And applying the changed config after the rule is done (similar to filtering the failures) doesn't make any sense.
