### ISSUE TITLE
ES5 set accessors: incorrect warning expected typedef for call-signature 

### ISSUE THREAD

**Issue by cwmacdon** [palantir/tslint#340]
class Foo {
	private _bar: boolean = false;

	get bar(): boolean {
		return this._bar;
	}
	set bar(theBar: boolean) {
		this._bar = theBar;
	}
}

gives error: expected call-signature: 'bar' to have a typedef

However, the typescript compiler throws an error if you try to give a typedef to the return value of a set accessor.

**Comment by adidahiya** [comment]
fix here: #334

**Comment by cwmacdon** [comment]
ty
