### ISSUE TITLE
Add "no undefined or null comparison" rule

### ISSUE THREAD

**Issue by jez9999** [palantir/tslint#3400]
When comparing values to `undefined` or `null`, it may be desirable to enforce the use of utility functions that treat the two values the same.  Directly comparing values to `null` or `undefined` in code may produce surprising results because both values could be considered so semantically similar that they are assumed to be equal.  This rule would therefore prohibit such direct comparisons.  Example utility functions:

```
/**
 * Checks whether the input is "unspecified" (ie. undefined or null).
 *
 * @param input The input value.
 * @returns If the input is "unspecified", true; otherwise false.
 */
public static isUnspecified<T>(input: undefined | null | T): input is undefined | null {
	/* tslint:disable-next-line:no-undefined-or-null-comparison */
	return (typeof input === "undefined") || (input === null);
}

/**
 * Checks whether the input is "specified" (ie. neither undefined nor null).
 *
 * @param input The input value.
 * @returns If the input is "specified", true; otherwise false.
 */
public static isSpecified<T>(input: undefined | null | T): input is T {
	return !Utils.isUnspecified(input);
}
```

**Comment by adidahiya** [comment]
We have a few other rules that deal with this -- I think we should focus on making them work well rather than adding yet another rule.

- `triple-equals`
- `no-null-keyword`
- `strict-type-predicates`

**Comment by jez9999** [comment]
All three of those are doing something rather different to this suggestion.  I think modifying any of them to add this functionality would be shoehorning new semantics into them.

**Comment by adidahiya** [comment]
I don't think they're so different. Some combination of them certainly hopes to address this:

> Directly comparing values to null or undefined in code may produce surprising results because both values could be considered so semantically similar that they are assumed to be equal.

I'm hesitant to add this rule to the core rule set until I hear broader support for it.

**Comment by jez9999** [comment]
Just in case you decide to add it, I have implemented it:

https://github.com/jez9999/tslint/commit/79dc7ffc04d9e231ef3f78d205749fba6b1906ec

**Comment by NN---** [comment]
@jez9999 What is wrong with regular undefined and null comparison ? They are very useful.

**Comment by jez9999** [comment]
Personally I always like to say "if it's null or undefined".  For me both are semantically pretty much the same thing.  Explicitly comparing to one or the other will only match one of the two.

**Comment by NN---** [comment]
Actually 'a == undefined' and 'a == null' both have the same result.
Pay attention '==' not triple '==='.
Check here: https://dorey.github.io/JavaScript-Equality-Table/

**Comment by jez9999** [comment]
Yeah but it's easy to make that mistake.  Easier to use a utility function.  Also, `undefined` can be redefined so it's better to check `typeof input === "undefined"`.

**Comment by NN---** [comment]
I see your point.
Is there a ready npm package for this to not copy paste the same code ?

**Comment by jez9999** [comment]
Huh??

**Comment by NN---** [comment]
I mean defining isUnspecified in each project seems like a bad copy paste.
It is better to have a ready package.

**Comment by jez9999** [comment]
Oh right, I just define a couple of functions in my personal utilities module.

**Comment by NN---** [comment]
That’s why I suggest making a package.

**Comment by JoshuaKGoldberg** [comment]
+1 to adidahiya's comments - this overlaps a bit too much with our existing rules. `!= null` is well-supported by the existing configuration options.

Closing this issue since there hasn't been a lot of need displayed for this rule, but please do post here if you feel that's wrong!
