### ISSUE TITLE
Output code warnings in yellow instead of red

### ISSUE THREAD

**Issue by jez9999** [palantir/tslint#3401]
Right now code warnings with the `codeFrameFormatter` output warning and error messages in red.  It's useful to distinguish between them by colour.

**Comment by ildoc** [comment]
yep, I said the same thing here -> https://github.com/palantir/tslint/issues/2569#issuecomment-339780676

warning and errors should be color-distinguished by default

**Comment by ajafff** [comment]
Fixed by #3402
