### ISSUE TITLE
Check for non-well-formed iterables

### ISSUE THREAD

**Issue by adidahiya** [palantir/tslint#341]
[Non-well-formed iterables](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#Non-well-formed_iterables) will result in runtime exceptions and/or bugs.

**Comment by ashwinr** [comment]
something for the future -- TS doesn't support `Symbol` yet

**Comment by andy-hanson** [comment]
What cases would a lint rule catch that TypeScript doesn't already? This code already fails:
```ts
const nonWellFormedIterable = { [Symbol.iterator]: () => 1 };
[...nonWellFormedIterable];
```

**Comment by adidahiya** [comment]
this request is likely out of date and was filed before iterators had matured in TS
