### ISSUE TITLE
Version on command line is out of date

### ISSUE THREAD

**Issue by park9140** [palantir/tslint#342]
Need to update version when new versions are released.
https://github.com/palantir/tslint/blob/1256c57638faa0eef0003f1f167ead443ab4e4e1/src/tslint.ts#L52

**Comment by gscshoyru** [comment]
You seem to be looking at an old patchset there -- current version in tslint.ts is here https://github.com/palantir/tslint/blob/master/src/tslint.ts#L54 and up to date.
