### ISSUE TITLE
objects/variables passed into Class constructor falsely marked unused 

### ISSUE THREAD

**Issue by nikmartin** [palantir/tslint#3420]
### Bug Report

- __TSLint version__: 5.5.0
- __TypeScript version__: 2.3.4
- __Running TSLint via__: (pick one) Ionic cli

#### TypeScript code being linted

```ts
export class SearchFiltersPage {
gameFilter: any[];
typeFilter: any[];
constructor(
     private propertyService: PropertyService,
  ) {
    this.typeFilter = propertyService.getPropertyTypesList();
    this.gameFilter = propertyService.getGameTypesList();
   }
}
```

with `tslint.json` configuration:

```json
{
  "rules": {
    "no-duplicate-variable": true,
    "no-unused-variable": [
      true
    ]
  },
  "rulesDirectory": [
    "node_modules/tslint-eslint-rules/dist/rules"
  ]
}

```

#### Actual behavior
tslint reports:
```
[16:54:29]  tslint: src/pages/search-filters/search-filters.ts, line: 51 
       Property 'propertyService' is declared but never used. 
       L51:  private propertyService: PropertyService,
```
#### Expected behavior
tslint understands that propertyService is a variable that was passed into the constructor function, so it is able to be used without `this.` being pre-pended

If I add this. to propertyService in the constructor, tslint stops complaining

**Comment by ajafff** [comment]
If you remove the `private` modifier, everything works as expected.
In typescript adding a modifier (`private`, `protected`, `public` or `readonly`) to a constructor parameter creates a parameter and a property (called "parameter property"). You only use the parameter while the property is never used. That's why you get an error.
