### ISSUE TITLE
Quickly Disable Style Rules - Feature Request

### ISSUE THREAD

**Issue by beandrake** [palantir/tslint#3428]
I just setup TSLint for the first time, but I've found that before I can start getting value from it, I have to overcome a specific hurdle: the default style lint settings.  Each project/team has their own preferred styles, so it's not surprising that there's a mismatch between TSLint's style preferences and my own.  

Ideally, it would be nice if TSLint didn't make any assumptions about user style preferences (i.e. style rules defaulted to off), thus allowing users to opt in to only the rules they deemed useful for their project.  Barring that, I want to suggest the addition of a quick and easy way to turn off all 48 style rules in one command.

Thanks for your consideration of this issue.

**Comment by adidahiya** [comment]
You don't start with any rules enabled by default. You can very easily build up your own preferred rule configuration by manually adding entries to `rules` in your `tslint.json`:

```json
{
  "rules": {
    // nothing is enabled until you add it here
  }
}
```

**Comment by beandrake** [comment]
Thank you for the quick reply, adidahiya.  It sounds like I misunderstood what TSLint was doing.  Thanks to your clarification I was able to quickly solve my issue.  Much appreciated!
