### ISSUE TITLE
chalk@2.2.0 minor update breaks test compilation due to type errors.

### ISSUE THREAD

**Issue by jhanschoo** [palantir/tslint#3431]
### Bug Report

- __TSLint version__: 5.8.0
- __TypeScript version__: N/A
- __Running TSLint via__: N/A

#### Actual behavior

Running `npm install && npm run compile` throws type errors from chalk dependency.

#### Expected behavior

No errors.

#### Cause

`chalk@2.2.0` provides its own type definitions, overriding type definitions from `@types/chalk` c.f.

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/21004#issuecomment-339673354

#### Proposed resolution

Change

    "chalk": "^2.1.0",

in `package.json` to

    "chalk": "~2.1.0",

and file a bug to refactor to use `chalk@2.2.0`.

**Comment by ajafff** [comment]
The contributing docs say you should use `yarn` to install dependencies. This repository contains a lock file for yarn.

**Comment by jhanschoo** [comment]
Ah got it. My bad.

**Comment by jez9999** [comment]
So why is there still a list of packages in packages.json?  Rather confusing isn't it?

**Comment by ajafff** [comment]
@jez9999 because `yarn.lock` is only used for development. `package.json` is used while installing as a dependency. For more information please refer to the docs of yarn and node modules.
