### ISSUE TITLE
New Rule: File Name Casing

### ISSUE THREAD

**Issue by elliotleelewis** [palantir/tslint#3434]
I think a `file-name-casing` rule might be a solid idea. Would be useful to have, especially on large projects in which there is a lot of files, in a lot of subfolders.

Available options would be the same as other casing options (camelCase, kebab-case, etc.).

Thanks :)

**Comment by mzx** [comment]
+1

**Comment by zoemond** [comment]
+1

**Comment by kashiif** [comment]
+1

**Comment by giladgray** [comment]
implemented in #3978
