### ISSUE TITLE
Add "no warning comments" rule

### ISSUE THREAD

**Issue by jez9999** [palantir/tslint#3451]
ESLint has a `no-warning-comments` rule which is very useful if you want to enforce clean code when committing changes; you may want to prevent stray "TODO" or "FIXME" comments as they are messy and indicate that code may not be production-ready.  The same rule should exist for TSLint.

**Comment by JoshuaKGoldberg** [comment]
This already exists in [`tslint-microsoft-contrib`](https://github.com/microsoft/tslint-microsoft-contrib) as `no-suspicious-comment`. Closing this particular issue as a subset of #1142.
