### ISSUE TITLE
Linting only after change and save

### ISSUE THREAD

**Issue by Fir3st** [palantir/tslint#3467]
### Bug Report

- __TSLint version__: 5.8.0
- __TypeScript version__: 2.5.3
- __Running TSLint via__: CLI

Hi, I have problem with starting TSLint. When I start it via CLI (or even IDE), it doesn't show anything until I change something and save file. 

Example:

I have object-literal-sort-keys error in my file, but it doesn't show until I change something and save file, then it works fine.

**Comment by ajafff** [comment]
`object-literal-sort-keys` has a bug in the current version. It doesn't report errors if you use `\r\n` line breaks.
I guess your editor changes it to `\n` when saving.

**Comment by Fir3st** [comment]
It works, thanks!
