### ISSUE TITLE
FR: Support no-undef rule: Check undeclared variables

### ISSUE THREAD

**Issue by brunolemos** [palantir/tslint#3480]
This one of the very useful of eslint, could tslint support it?
https://eslint.org/docs/rules/no-undef

**Comment by ajafff** [comment]
Why would you need a lint rule for that? The compiler already shows an error if it can't find a declaration of an identifier.

**Comment by brunolemos** [comment]
> Why would you need a lint rule for that? 

@ajafff Because it provides a great real time developer experience showing me all undeclared variables with a red underline on editor, specially useful after moving some code around. See:

But nevermind, vscode wasn'ts showing undeclared vars indicators to me on typescript but now it's showing just fine.

**Comment by doplumi** [comment]
> Because it provides a great real time developer experience showing me all undeclared variables with a red underline on editor, specially useful after moving some code around.
> But nevermind, I think it was a bug with my vscode, because now it's showing red underline on undeclared vars just fine.

Actually, this stopped happening in my VSCode since I disabled eslint. Did anything change?

**Comment by alanyinjs** [comment]
Any update on this feature request?

**Comment by JoshuaKGoldberg** [comment]
Hi! **TSLint is deprecated** and no longer accepting pull requests other than security fixes. See #4534. ☠️
We recommend you instead use **[typescript-eslint](https://typescript-eslint.io)** to lint your TypeScript code with ESLint. ✅

As for this particular feature request, TypeScript will still inform you if variables are unused or undefined - particularly if you enable `--strictNullChecks`. Check with your editor if that's not being surfaced for you.
