### ISSUE TITLE
space-within-parens should allow exceptions

### ISSUE THREAD

**Issue by mmakrzem** [palantir/tslint#3489]
I should be allowed to specify that I want a space inside parentheses but no space if there is nothing being passed in.  ie:

Foo( 2 ); //good
Bar(); //also good

as it is now, I have to place a space inside the second case. ie Bar( ); //boo I don't want to have to insert a space between the empty parentheses

See how eslint handles spaces inside parentheses here: https://eslint.org/docs/rules/space-in-parens

**Comment by ajafff** [comment]
I'd like to limit the scope to always allow '()' if there is nothing between the parens.
Exceptions like in ESLint can be implemented later on.

**Comment by ajafff** [comment]
Fixed by #3513
