### ISSUE TITLE
Implement bazels rules for typescript into tslint

### ISSUE THREAD

**Issue by pravdomil** [palantir/tslint#3523]
What about implementing these two features into tslint?
https://github.com/bazelbuild/rules_typescript/blob/master/docs/check-return-value.md
https://github.com/bazelbuild/rules_typescript/blob/master/docs/equals-nan.md

**Comment by ajafff** [comment]
1. is already discussed in #1154
2. is already implemented https://palantir.github.io/tslint/rules/use-isnan/
