### ISSUE TITLE
New rule: Limit Arrows Per Line

### ISSUE THREAD

**Issue by pablobirukov** [palantir/tslint#3545]
Multiple arrows a line usually reduce readability.

What do you think guys? Would you approve PR implementing this?

**Comment by ajafff** [comment]
Can you provide some code that would cause this rule to show errors?

**Comment by r00ger** [comment]
Basically, any line that has more than X arrows
```ts
const foo = () => () => () => undefined;
export type Thunk = (payload: {}) => (dispatch: (a: {}) => void, getState?: () => {}) => void;
const renderDefs = (id: (str: string) => string, href: (str: string) => string): JSX.Element => (
export default (store: Store<State>) => (next: Dispatch<State>) => (action: Action<ActionType, ActionPayload>) => {
```

**Comment by ajafff** [comment]
Just to make sure I understand it correctly:
This includes nested arrow functions as well as chained arrow functions? 

```ts
[].map(a => a + 1).forEach(a => log(a))
```

And in addition it also checks function types?

This is only about the number of fat arrows (`=>`) per line and does not consider anything else like nesting, complicity,...?

**Comment by r00ger** [comment]
Exactly, that's just dummy check for X arrows per line.

Initially, I checked Typescript's repo and my company's for three arrows on a line and found only complicated and unreadable cases. So I implemented the simplest check.

Now I think your example above and it still readable. However, as I have not found anything like this in my repo, I keep the rule turned on.

Do you think the check is too trivial to be a part or tslint?

**Comment by aervin** [comment]
I think I would use this rule, but for me the above code example is difficult to read because of the number of definitions per line.

**Comment by jefflage** [comment]
I would also like this rule

**Comment by JoshuaKGoldberg** [comment]
Per #4534, closing this formatting rule request. If you _really_ need the rule, custom rules are always an option and can be maintained outside this repo!
