### ISSUE TITLE
upgrade to TS 1.5

### ISSUE THREAD

**Issue by adidahiya** [palantir/tslint#356]
This issue is to track progress towards fully supporting TS 1.5 in tslint.

- [x] use new language services API
- [x] fix tests
- [x] ES6 modules
- [x] destructuring
- [x] spread operator
- [x] `for ... of` iteration
- [x] `let`, `const`

EDIT:
these 1.5 features don't require any changes in tslint since we don't have rules targeting them yet:
- decorators / annotations
- Symbols
- computed properties

**Comment by ashwinr** [comment]
started the upgrade here: https://github.com/palantir/tslint/pull/355. a few things broken as usual -- but seems fine mostly.

**Comment by SergioMorchon** [comment]
That sounds so good...!
Thank you, I'll wait patiently for the upgrade :D

**Comment by park9140** [comment]
@ashwinr, if you reference me when you are getting closer to release. We have a fairly large project, and we usually have one or two problems after a major upgrade.

**Comment by ashwinr** [comment]
@park9140 cool. The master branch is currently on 1.5, except we don't support any of the new 1.5 syntax. So, if you are still using pre-1.5 syntax, you can test it out right away! :)

**Comment by SergioMorchon** [comment]
Maybe a milestone would be better to track the progress, with separated issues (ie. as you can see at the typescript project https://github.com/Microsoft/TypeScript/milestones)

**Comment by adidahiya** [comment]
2.3.0-beta has been released which should support most of the 1.5 syntax -- please try it out :)

We haven't added many rules that enforce style on the new syntax features yet, but we're open to suggestions.

**Comment by vanko-dev** [comment]
problem with the semicolon rule

code:
import {Router} from 'aurelia-router';

tsling messages:
 error app.ts[6, 33]: missing semicolon
 error app.ts[7, 15]: missing semicolon

 "version": "2.3.0-beta",

**Comment by adidahiya** [comment]
@vanko-dev filed #441 for that bug
