### ISSUE TITLE
[bug] unnecessary space before parameter after running fixer for arrow-parens

### ISSUE THREAD

**Issue by mateuszwitkowski** [palantir/tslint#3563]
### Bug Report

- __TSLint version__: 5.8.0
- __TypeScript version__: 2.5.3
- __Running TSLint via__: VSCode

#### TypeScript code being linted

```ts
somearray.map((element) => doSomething(element));
```

with `tslint.json` configuration:

```json
"rules": {
    "arrow-parens": [
      true,
      "ban-single-arg-parens"
    ]

```

#### Actual behavior
After running fixer:
```ts
somearray.map( element => doSomething(element));
```
There`s unnecessary space before parameter.
#### Expected behavior
```ts
somearray.map(element => doSomething(element));
```
No space before parameter.

**Comment by ajafff** [comment]
Fixed by #3618
