### ISSUE TITLE
no-irregular-whitespace enforces strings/comments despite contrary documentation

### ISSUE THREAD

**Issue by cjc343** [palantir/tslint#3572]
### Bug Report

- __TSLint version__: 5.7.0
- __TypeScript version__: 2.5.2
- __Running TSLint via__: (pick one) CLI/NPM: `tslint -p ./tsconfig.json -c ./tslint.json -e '**/node_modules/**/*'`

#### TypeScript code being linted
Note - the claims in the 'code' below are untrue because GitHub is replacing nbsp chars with standard spaces. To repro, you must supply your own nbsp chars.

```ts
// this comment contains nbsp chars
const s = 'this string contains nbsp chars';
```

with `tslint.json` configuration:

```json
{
  "rules": {
    "no-irregular-whitespace": true
  }
}
```

#### Actual behavior

Lint failures occur on nbsp chars in string literals and comments.

#### Expected behavior

[Per docs](https://palantir.github.io/tslint/rules/no-irregular-whitespace/): Disallow irregular whitespace __outside of strings and comments__

----

I'm less bothered by the actual behaviour & more-so by the incorrect documentation - disabling the rule when irregular whitespace belongs in a string literal is a perfectly acceptable solution to me.

**Comment by ajafff** [comment]
As you already noted: this is a bug in the docs and should be fairly easy to fix.
