### ISSUE TITLE
Rule to ban ts-ignore comments?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [palantir/tslint#3626]
https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#suppress-errors-in-ts-files-using--ts-ignore-comments

```typescript
if (false) {
    // @ts-ignore: Unreachable code error
    console.log("hello");
}
```

**Comment by JoshuaKGoldberg** [comment]
Awesome, this was fixed by #3728. 🎉

**Comment by mickaeltr** [comment]
Hello,
That's maybe a dumb question by I am wondering why I can't see this rule in [the list](https://palantir.github.io/tslint/rules/)?
My project is using TSLint 5.11.0
Thanks

**Comment by JoshuaKGoldberg** [comment]
@mickaeltr what you're seeing is correct - TSLint 5.11.0 was released before this rule was merged in. A new version hasn't been released yet (folks from the Palantir side are still looking for a full-time maintainer). You'll have to wait for the next version. Sorry!

**Comment by mickaeltr** [comment]
Thanks for the answer @JoshuaKGoldberg, I missed that somehow.

**Comment by aes421** [comment]
Is there a way to ban `tslint:disable` comments?
