### ISSUE TITLE
The "curly" rule corrupts code with --fix

### ISSUE THREAD

**Issue by evanw** [palantir/tslint#3630]
### Bug Report

- __TSLint version__: 5.8.0
- __TypeScript version__: 2.6.2
- __Running TSLint via__: CLI

#### TypeScript code being linted

```ts
if (true) // comment
  foo();
else
  bar();
```

with `tslint.json` configuration:

```json
{
  "rules": {
    "curly": true
  }
}
```

#### Actual behavior

```ts
if (true) // comment {
  foo();
}
else {
  bar();
}
```

#### Expected behavior

```ts
if (true) { // comment
  foo();
}
else {
  bar();
}
```

**Comment by evanw** [comment]
Another example:

#### TypeScript code being linted

```ts
if (true) callback(() => {
  console.log('test');
});
```

with `tslint.json` configuration:

```json
{
  "rules": {
    "curly": true
  }
}
```

#### Actual behavior

```ts
if (true) callback(() => { {
  console.log('test');
});
}
```

#### Expected behavior

```ts
if (true) { callback(() => {
  console.log('test');
}); }
```

**Comment by aervin** [comment]
@evanw Looks like a [fix](https://github.com/palantir/tslint/pull/3473) for this bug is on its way.
