### ISSUE TITLE
Add new rules to the latest config

### ISSUE THREAD

**Issue by rafaelss95** [palantir/tslint#3660]
### Bug Report

- __TSLint version__:
- __TypeScript version__:
- __Running TSLint via__: (pick one) CLI / Node.js API / VSCode / grunt-tslint / Atom / Visual Studio / etc

#### Actual behavior
In the latest update, 5.9.0, the new rules weren't added to the `configs/latest` file.
#### Expected behavior
I'd expect the new rules to be added in `latest` file.

**Comment by adidahiya** [comment]
We don't always do this. Only rules that we expect to be in `tslint:recommended` eventually are added to `tslint:latest`. If you want to enable every rule, you should use `tslint:all`.

**Comment by rafaelss95** [comment]
Got it. Probably **latest** isn't the more intuitive name for this then.
