### ISSUE TITLE
API documentation link

### ISSUE THREAD

**Issue by alan-agius4** [palantir/tslint#3684]
I am not sure if this is the right place to ask. 

But I tried on `gitter` but had no luck.

Does anyone know where can I find the API documentation as I only managed to find the one for the CLI?

Thanks

**Comment by ajafff** [comment]
Short answer: there is none.
There's a small snippet about how to use the `Linter` to lint a typescript program: https://palantir.github.io/tslint/usage/type-checking/
But that's about it AFAICT.

If you have a specific question, you can just ask them in this issue.

**Comment by alan-agius4** [comment]
Thanks for your help @ajafff 

That will suffice
