### ISSUE TITLE
ES6 Spread arguments & arrays

### ISSUE THREAD

**Issue by adidahiya** [palantir/tslint#369]
https://github.com/Microsoft/TypeScript/issues/237
https://github.com/Microsoft/TypeScript/issues/238

**Comment by leeavital** [comment]
@ashwinr 

It looks like this is already supported. I'm not exactly sure why, but my guess is that the typescript api just reads a spread as a regular symbols.

I was able to lint the following:

````ts
var nums : number[] = [5, 6];

var nums2 : number[] = [...nums, 3, 4, ...nums];


function firstInt(...nums : number[]) {
  return nums[0];
}

console.log( firstInt( ...nums2 ) );
````

**Comment by ashwinr** [comment]
reopening -- let's make sure these are covered by unit tests
