### ISSUE TITLE
Incompatible with typescript 2.7

### ISSUE THREAD

**Issue by dbrockman** [palantir/tslint#3711]
### Bug Report

- __TSLint version__: 5.9.1
- __TypeScript version__: 2.7.1
- __Running TSLint via__: CLI

I'm getting a lot of errors thrown from within tslint when using tslint with typescript 2.7.1

Here's an abbreviated list of errors with the first location in the stack trace:

- `TypeError: Cannot read property 'declarations' of undefined` at `cb (node_modules/tslint/lib/rules/oneVariablePerDeclarationRule.js:57:73)`
- `TypeError: Cannot read property 'kind' of undefined` at `cb (node_modules/tslint/lib/rules/noSparseArraysRule.js:50:70)`
- `TypeError: Cannot read property 'kind' of undefined` at `cb (node_modules/tslint/lib/rules/noUnusedExpressionRule.js:109:75)`
- `TypeError: Cannot read property 'kind' of undefined` at `cb (node_modules/tslint/lib/rules/objectLiteralShorthandRule.js:69:27)`
- `TypeError: Cannot read property 'kind' of undefined` at `cb (node_modules/tslint/lib/rules/preferConstRule.js:163:98)`
- `TypeError: Cannot read property 'kind' of undefined` at `cb (node_modules/tslint/lib/rules/tripleEqualsRule.js:67:37)`
- `TypeError: Cannot read property 'kind' of undefined` at `isPlusExpression (node_modules/tslint/lib/rules/preferTemplateRule.js:112:69)`
- `TypeError: Cannot read property 'length' of undefined` at `cb (node_modules/tslint/lib/rules/noDuplicateVariableRule.js:79:66)`
- `TypeError: Cannot read property 'length' of undefined` at `cb (node_modules/tslint/lib/rules/noSparseArraysRule.js:59:54)`
- `TypeError: Cannot read property 'length' of undefined` at `Object.mapDefined (node_modules/tslint/lib/utils.js:159:55)`

It seems to me like some of the typescript AST nodes no longer has properties that tslint is using.

**Comment by mhegazy** [comment]
@andy-ms any idea what is going on?

**Comment by dbrockman** [comment]
If it helps, this is no longer a problem (for me) with TypeScript version `2.7.2`.
Maybe it was a bug in `2.7.1`?

**Comment by M-Zuber** [comment]
I am also on 2.7.2 and everything looks fine as well

**Comment by vire** [comment]
Same issue 

```
OSX: 10.13.3 (17D102)
yarn: 1.5.1,
tslint: 5.9.1, 
typescript: 2.7.2
```

**Comment by andy-ms** [comment]
@vire Try using npm and installing `tslint@latest` and `typescript@next`. The vscode error only happened when using yarn too.

**Comment by vire** [comment]
After installing latest `react-scripts-ts` the *problem disappeared for now* - I suspect their dependencies were somehow incorrect :/

Also worth to mention the issue was present also in the CLI not just vscode

**Comment by edevine** [comment]
I experience this with
yarn 1.5.1
tslint: 5.9.1,
typescript: 2.7.2

Downgrading to yarn 1.3.2 resolved the issue.

**Comment by giladgray** [comment]
![image](https://user-images.githubusercontent.com/464822/43476581-cc266b8e-94ad-11e8-8f2b-c36c04ae3b33.png)

**Comment by cvgaviao** [comment]
@smoke, can I ask you how to do to know if there are any dependency pulling `typescript@^8.2.0` ?

**Comment by smoke** [comment]
@cvgavio look at `package-lock.json` or `yarn.lock` - if you see different versions of typescript installed  there will be at least 2 records.
