### ISSUE TITLE
Tslint

### ISSUE THREAD

**Issue by adnan1naeem** [palantir/tslint#3725]
I am getting following error on travis build

TypeError: Cannot read property 'end' of undefined
    at CurlyWalker.checkStatement (/home/travis/build/BlueEastCode/bluerain-platform-reactxp/node_modules/tslint/lib/rules/curlyRule.js:123:47).
I am not getting  this error  locally on my desktop.but as soon as i make a PR then i get above error and my PR fails on travis
PRlink
[https://github.com/BlueEastCode/bluerain-platform-reactxp/pull/19]

**Comment by JoshuaKGoldberg** [comment]
It looks like your `tslint` version in your `package.json` is `^5.4.3`, though the newest version is `5.9.1`. Could you try updating to the latest both locally & on your PR branch, then see if either or both fix or break?

**Comment by johnwiseheart** [comment]
Hi there,

It would appear that this issue is not directly related to a bug or feature request. We request that you use StackOverflow to ask questions about tslint, and tslint rules. Going to close this issue, but please feel free to re-open if you think this is a bug.

Thanks,
TSLint Team
