### ISSUE TITLE
Junit formatter prevents Jenkins picking up results on success

### ISSUE THREAD

**Issue by DaemonExMachina** [palantir/tslint#3744]
### Bug Report

- __TSLint version__: 5.9.1
- __TypeScript version__: 2.7.1
- __Running TSLint via__: CLI

#### Actual behavior

Running `tslint -o lint-results.xml -t junit -p tsconfig.json` on a lint-free project results in an xml file with an empty `<testsuites>` element. While this is acceptable by some consuming tools, others reject it. Unfortunately for me, the latter includes Jenkins. Jenkins hits a non-breaking error trying to consume `lint-results.xml`, and skips it. Which makes generating the file in the first place pointless.

Before you added the core junit formatter, we could use tslint-junit-formatter, whose [last commit] before then seems to have been a fix for this very issue. But because tslint prioritises its own core formatters over external ones with the same name, this formatter can no longer be used (it's mostly redundant except for that one fix, anyway).

#### Expected behavior

A single "success" `<testsuite>` element is generated inside the `<testuites>`, and Jenkins is able to consume it (as is Bamboo, which has the same problem, according to the referenced tslint-junit-formatter [issue]).

I will say I'm happy to submit a PR for this one, if you'll have me!

[last commit]: https://github.com/GenoLogics-OpenSource/tslint-junit-formatter/commit/fc04c216465a16e3ceb98e512696e432539babce
[issue]: https://github.com/GenoLogics-OpenSource/tslint-junit-formatter/issues/8

**Comment by mastermatt** [comment]
https://github.com/palantir/tslint/pull/3838 would pave the way for this.

**Comment by spikyjt** [comment]
This is the same for Bamboo and probably other CI tools.

tslint-junit-formatter already does this, so it's solution could be used, see:
See https://github.com/GenoLogics-OpenSource/tslint-junit-formatter/issues/8

**Comment by LekoArts** [comment]
@DaemonExMachina 	You still want to create a PR for that? 👍

**Comment by darrena092** [comment]
Just added https://github.com/palantir/tslint/pull/4566 - that should fix the problem.

**Comment by LekoArts** [comment]
Thanks!
