### ISSUE TITLE
Feature request: Add rule for enforcing function parameter linebreak and indentation style

### ISSUE THREAD

**Issue by samal84** [palantir/tslint#3746]
### Feature request

There are several different types of styles for handling linebreaks and indentation for funtion parameters. Here are a few I could come up with:

```ts
function example1(arg1: string, arg2: number, arg3: boolean): number {
  return 123;
}

function example2(arg1: string,
                  arg2: number,
                  arg3: boolean): number {
  return 123;
}

function example3(
  arg1: string,
  arg2: number,
  arg3: boolean): number {
  return 123;
}

function example4(
  arg1: string,
  arg2: number,
  arg3: boolean,
): number {
  return 123;
}
```

I am personally partial to example4, as it enforces the shortest lines, but different people may want to enforce different styles in their codebases. The important part is that we can enforce a consistent style.

So I'm proposing a new rule, maybe called function-parameter-style or something like that. And then we need to come up with names for the different styles that we can set, or maybe we just number them.

**Comment by JoshuaKGoldberg** [comment]
@samal84 this already exists as the `align` rule.

**Comment by samal84** [comment]
I couldn't get what I wanted with the align parameters rule. The align parameters rule accepts all of my examples. I am proposing a rule that would only accept one of them.

**Comment by JoshuaKGoldberg** [comment]
Gotcha. In that case, since there's a lot of overlap, I'd recommend putting this new rule in a separate repository and linking to it here. TSLint's been moving away from investing in whitespace rules: #628.
