### ISSUE TITLE
tslint --fix flips between correct and non-correct state

### ISSUE THREAD

**Issue by rlz** [palantir/tslint#3753]
### Bug Report

- 5.9.1:
- 2.7.2:
- CLI

#### TypeScript code being linted

```ts
class X {
    public test = () => {
        //
    };
}
```

with `tslint.json` configuration:

```json
{
    "defaultSeverity": "warning",
    "extends": ["tslint:recommended"],
    "jsRules": {},
    "rulesDirectory": []
}
```

#### Actual behavior
Running `tslint --fix` few times in a row will flip ";". So if we have code with ";" as in example (error state) - it will remove it, but next run will return it back and so on.

#### Expected behavior
Just remove it and do not return after next run.

**Comment by JoshuaKGoldberg** [comment]
Amusing. This no longer repros with TSLint v5.11.0 thankfully.
