### ISSUE TITLE
The package distributed through npm is not up to date

### ISSUE THREAD

**Issue by jbroni** [palantir/tslint#376]
I have installed tslint version 2.1.1 through npm. However, the files in the build folder are not up to date. For example, I am missing the following commit: https://github.com/palantir/tslint/commit/1ed1736a1f75cff74ee5338576532308457c5916

Could you please distribute an updated package through npm? Thanks!

**Comment by ashwinr** [comment]
we're currently working on migrating to 1.5, so we'll release an updated package when the TS 1.5 beta comes out.

**Comment by Alxandr** [comment]
1.5 beta is out now. Could you notify here when there is a compatible release out?

**Comment by ashwinr** [comment]
We will. The beta broke a few things, so we're investigating.

Sent from a phone

On May 2, 2015, at 12:20, Alxandr <notifications@github.com<mailto:notifications@github.com>> wrote:


1.5 beta is out now. Could you notify here when there is a compatible release out?

**Comment by ashwinr** [comment]
we've released 2.2.0-beta that is built on 1.5-beta: https://npmjs.org/package/tslint. Still doesn't support newer 1.5 syntax -- we're working on it.
