### ISSUE TITLE
ban-single-arg-parens autofix adds left padding

### ISSUE THREAD

**Issue by OskarKlintrot** [palantir/tslint#3771]
### Bug Report

- __TSLint version__: ~5.8.0
- __TypeScript version__: 2.4.2
- __Running TSLint via__: ng lint

#### TypeScript code being linted

```ts
.map((response) => repsonse.json)
```

with `tslint.json` configuration:

```json
"arrow-parens": [true, "ban-single-arg-parens"]
```

#### Actual behavior
```ts
.map( response => repsonse.json)
```

#### Expected behavior
```ts
.map(response => repsonse.json)
```

**Comment by rafaelss95** [comment]
I can't reproduce this error, however I've reproduced an interesting case:

```
arr.map((
              url // my comment
            ) => url...
```

After run tslint with `fix`:


```
arr.map(url) => url...
```

... it removed the comment, is it the expected behavior?

**Comment by rafaelss95** [comment]
I can't reproduce this error, however I've reproduced an interesting case:

```
arr.map((
  url // my comment
) => url...
```

After run tslint with `fix`:


```
arr.map(url) => url...
```

... it removed the comment, is it the expected behavior?
