### ISSUE TITLE
TsLint rule directory accepting single path for directory

### ISSUE THREAD

**Issue by AkshanshSrivastava03** [palantir/tslint#3774]
### Bug Report

- __TSLint version__: 5.9.0
- __TypeScript version__: 2.5.2
- __Running TSLint via__:  CLI

I have 2 rules directories to run via CLI- 
1.) Microsoft contrib
2.) tslint-react

tslint -c ..\tslint.json  ..\src\scripts\**\*.ts* -e  **\Resources\*.ts* -e **\Generated\*.ts -e **\
Tests\*.ts* --rules-dir C:\Users\aksriv\AppData\Roaming\npm\node_modules\tslint-microsoft-contrib C:\Users\aksriv\AppData\Roaming\npm\node_modules\tslint-react

#### Actual behavior
It is not able to read two rule directories at a time. I tried to pass single directory and that worked fine

#### Expected behavior
The rules-directory should be accepting an array of rule directories

Can someone help me out with this? Is this an issue or something I am doing wrong from my side

**Comment by ggarek** [comment]
JIC @AkshanshSrivastava03, you can specify `rulesDirectory?: string | string[]` in the [config](https://palantir.github.io/tslint/usage/configuration/) _(you are already using in your example)_

**Comment by JoshuaKGoldberg** [comment]
Fixed by #3788! 🎉
