### ISSUE TITLE
Add rule for enforcing semicolon or commas for interfaces

### ISSUE THREAD

**Issue by fandy** [palantir/tslint#3775]
Is there a reason we can't enforce a consistent style of ending interface props? Since there isn't a benefit of using semicolons _and_ commas, I think it's useful to add a linting rule to enforce one.

I'm happy to submit a PR for this if it's wanted. Thoughts?

**Comment by ggarek** [comment]
@fandy, i think there is already a rule for this use case [`semicolon`](https://palantir.github.io/tslint/rules/semicolon/)
