### ISSUE TITLE
Add Examples For Rules

### ISSUE THREAD

**Issue by ghost** [palantir/tslint#3776]
It would be very nice to have code examples showing correct and incorrect code for the rules.

Could use ESLint docs for reference

**Comment by clemtrek** [comment]
I had a look through the test codes.

It may not be a hard work to add those to the website

**Comment by aervin** [comment]
@clemtrek This may be [in progress](https://github.com/palantir/tslint/pull/3602) already. Is that PR what you're after?

**Comment by JoshuaKGoldberg** [comment]
Duplicate of #1329.
