### ISSUE TITLE
new rule to disallow `var` declarations in favor of `let` and `const`

### ISSUE THREAD

**Issue by adidahiya** [palantir/tslint#378]

**Comment by josundt** [comment]
I want this! :+1:

**Comment by adidahiya** [comment]
@josundt sounds good, I made an issue for that: #388

**Comment by DickvdBrink** [comment]
I noticed this issue is assigned. Is it oke for me to pick this one up?

**Comment by adidahiya** [comment]
@DickvdBrink feel free to pick it up; we'll gladly review a PR
