### ISSUE TITLE
region check

### ISSUE THREAD

**Issue by RueDeRennes** [palantir/tslint#3791]
what is the best way to check are implementations in a region? like this:
// #region Imports
// #endregion

// #region Constructors
// #endregion

// #region Properties
// #endregion

// #region Methods
// #endregion

is there any rule for that?

**Comment by johnwiseheart** [comment]
Hi there,

It would appear that this issue is not directly related to a bug or feature request. We request that you use StackOverflow to ask questions about tslint, and tslint rules. Going to close this issue, but please feel free to re-open if you think this is a bug.

Thanks,
TSLint Team
