### ISSUE TITLE
[Feature Request] space-within-parens exception for comments

### ISSUE THREAD

**Issue by sam-s4s** [palantir/tslint#3798]
#### TypeScript code being linted

```ts
constructor( // this comment breaks the rule, because of the space before the //
    param1: string, // this comment is fine
    param2: string
) { }
```

with `tslint.json` configuration:

```json
"space-within-parens": [ true, 0 ]
```

#### Actual behavior
Comment with space in front of the // causes the rule to fire, generating an error.

#### Expected behavior
Spaces should be allowed for comments (you don't want a comment right up against the paren).

Even if there is an option to allow spaces around comments, or something?

**Comment by sam-s4s** [comment]
That sounds good, but just to confirm, there is a space between the parenthesis and the double slash - not technically inside the comment :) I think that's the main thing it's complaining about?

**Comment by delphiactual** [comment]
This should also ensure that comments written as `return import(/* webpackChunkName: "sqlLib" */ 'sql.js');` do not fire the error either

**Comment by JoshuaKGoldberg** [comment]
Per #4534, closing this formatting rule request. If you _really_ need the rule, custom rules are always an option and can be maintained outside this repo!
