### ISSUE TITLE
perf_hooks built-in produces "not listed as dependency" error in VSCode

### ISSUE THREAD

**Issue by aryzing** [palantir/tslint#3835]
### Bug Report

- __TSLint version__: 5.9.1
- __TypeScript version__: 2.8.1
- __Running TSLint via__: (pick one) VSCode

#### TypeScript code being linted

```ts
import { performance } from 'perf_hooks';
//                           ^^^^^^^^^^
```

with `tslint.json` configuration:

```json
{
  "extends": ["tslint:latest", "tslint-config-prettier"]
}
```

#### Actual behavior

Reports `perf_hooks` as not listed in dependencies.

```
[tslint] Module 'perf_hooks' is not listed as dependency in package.json (no-implicit-dependencies)
```

#### Expected behavior
For this error to not appear.

I've also tested it with the CLI, and this error does **not** appear! It only appears in VSCode through the tslint plugin.

**Comment by giladgray** [comment]
@aryzing have you installed `@types/node`? i'm closing this as external, not enough info
