### ISSUE TITLE
Enable deprecation rule in one of the built-in configurations

### ISSUE THREAD

**Issue by tkrotoff** [palantir/tslint#3856]
Using TSLint 5.9.1, `deprecation` rule should be enabled with preset "tslint:recommended" (`"deprecation": true`) because that makes a lot of sense

**Comment by JoshuaKGoldberg** [comment]
Removing the `Type: Breaking Change` label per #4811. Now accepting PRs!

**Comment by adidahiya** [comment]
Currently, we don't enable any rules which use the type checker in `tslint:recommended`, and I think we should keep it that way (they require extra setup). We might consider a new rule set `tslint:recommended-with-type-checker` which enables the deprecation rule.

**Comment by JoshuaKGoldberg** [comment]
IMO it's a little too late to add another ruleset. Let's just close this per #4534 🤷‍♂
