### ISSUE TITLE
Trailing comma rule can crash TSLint

### ISSUE THREAD

**Issue by Dignissi** [palantir/tslint#3860]
### Bug Report

- __TSLint version__: 5.9.1
- __TypeScript version__: 2.8.3
- __Running TSLint via__: CLI 

#### TypeScript code being linted

```ts
declare var Test: {
        some_data: {
                do_the_thing?(): {
                        got_the_number: number;
                };
                setStuff({ [index: string] : number });
        }
}
```

with `tslint.json` configuration:

```json
{
        "rules": {
                "trailing-comma": [true, {"multiline": "always", "singleline": "never"}]
        }
}
```

#### Actual behavior

This TS code crashes tslint.

#### Expected behavior

tslint should not crash

**Comment by JoshuaKGoldberg** [comment]
@Dignissi your TypeScript source has a syntax error. The object you're passing to `setStuff` looks like it's a type definition that's missing the parameter it's supposed to describe. Did you mean do write something like this?

```typescript
setStuff(param: { [index: string] : number });
```

See #3808 for discussion on whether TSLint should run when these kinds of errors exist.
