### ISSUE TITLE
Conditional types don't work

### ISSUE THREAD

**Issue by cshaa** [palantir/tslint#3867]
### Bug Report

- __TSLint version__:
- __TypeScript version__:
- __Running TSLint via__: VSCode / grunt-tslint / Atom / Visual Studio / etc

#### TypeScript code being linted

```ts
// code snippet
```

with `tslint.json` configuration:

```json

```

**Comment by Yogu** [comment]
Hm, they indeed don't work for me, did you fix it somehow?
