### ISSUE TITLE
New rule: grouping imports by type of imported entity

### ISSUE THREAD

**Issue by sanex3339** [palantir/tslint#3873]
In our projects we trying to keep imports clean as possible and we grouping imports by type of imported entity:

* imports from node modules (all things)
* imports from types
* imports from interfaces
* imports from enums
* other imports (classes, functions, constants)

```
import * as escodegen from 'escodegen-wallaby';
import * as espree from 'espree';
import * as ESTree from 'estree';

import { TObject } from './types/TObject';

import { IGeneratorOutput } from './interfaces/IGeneratorOutput';
import { IJavaScriptObfuscator } from './interfaces/IJavaScriptObfsucator';
import { ILogger } from './interfaces/logger/ILogger';
import { IObfuscationResult } from './interfaces/IObfuscationResult';
import { IOptions } from './interfaces/options/IOptions';
import { IRandomGenerator } from './interfaces/utils/IRandomGenerator';
import { ISourceMapCorrector } from './interfaces/source-map/ISourceMapCorrector';
import { ITransformersRunner } from './interfaces/node-transformers/ITransformersRunner';

import { LoggingMessage } from './enums/logger/LoggingMessage';
import { NodeTransformer } from './enums/node-transformers/NodeTransformer';
import { TransformationStage } from './enums/node-transformers/TransformationStage';

import { EspreeFacade } from './EspreeFacade';
import { NodeGuards } from './node/NodeGuards';
```

It will nice to have rule that will check that grouping by type of imported entity.
If few things are imported from the module - import should be attached to the group by most prevailing type of imported entity:

```ts
import {TFoo, TBar, IFoo} from '../../foo'; <- add to types group
```

**Comment by shivawu** [comment]
Up this. For a reference, in the python world, isort supports sectioning the imports, based on their properties: https://github.com/timothycrosley/isort#custom-sections-and-ordering

It would make the code very clean to read.

**Comment by giladgray** [comment]
i believe this is precisely the feature addressed in PR #3733, which will ship soon!

**Comment by sanex3339** [comment]
@giladgray no. Improt types in this PR is package, same folder or otjer folders.

**Comment by giladgray** [comment]
@sanex3339 yes, that's precisely what the PR I linked is about. i even left a comment there that the word "types" was confusing.

**Comment by giladgray** [comment]
(sorry, let the PR close it)
