### ISSUE TITLE
Looking for rule "No empty line allowed at the beginning of file"

### ISSUE THREAD

**Issue by janez-svetin** [palantir/tslint#3877]
Is it possible to achieve this without custom rule?

If not, any help / your own implementation of custom rule would be highly appreciated.

**Comment by giladgray** [comment]
@janez-svetin I don't see such a rule. Plenty of rules to check out for inspiration: `whitespace` or `newline-before-return` would be good places to start.

**Comment by janez-svetin** [comment]
@giladgray thanks, I actually solved this with a custom rule which checks the starting character in the file itslef.
