### ISSUE TITLE
Have the CLI run the checks in parallel

### ISSUE THREAD

**Issue by pspeter3** [palantir/tslint#389]
Is there a strict reason to run them in serial?

**Comment by adidahiya** [comment]
This wouldn't really do anything unless you also apply a utility that runs your JS across multiple threads / cores. I'd suggest something like [grunt-parallelize](https://github.com/teppeis/grunt-parallelize).

**Comment by pspeter3** [comment]
Thanks for the advice. Is there any reason not to load the files concurrently as opposed to sequentially? https://github.com/palantir/tslint/blob/master/src/tslint-cli.ts#L179-L183
