### ISSUE TITLE
Add `esSpecCompliant` to the trailing-comma rule in tslint:recommended

### ISSUE THREAD

**Issue by chaucerbao** [palantir/tslint#3892]
There was [some discussion](https://github.com/palantir/tslint/pull/3176#issuecomment-328969907) to add `esSpecCompliant` on the [trailing-comma rule](https://palantir.github.io/tslint/rules/trailing-comma/) to *tslint:recommended*.

That was about 8 months ago, so I'm not sure there was a reason against it, or if it just fell by the wayside. But I suggest that being compliant should be the default.

**Comment by giladgray** [comment]
@chaucerbao go for it! would happily review a PR.

**Comment by chaucerbao** [comment]
@giladgray One-liner PR #3899

**Comment by chaucerbao** [comment]
Thanks #4072
