### ISSUE TITLE
Fix breaking typescript@next tests

### ISSUE THREAD

**Issue by JKillian** [palantir/tslint#3914]
### Bug Report

- __TSLint version__:
- __TypeScript version__:
- __Running TSLint via__: (pick one) CLI / Node.js API / VSCode / grunt-tslint / Atom / Visual Studio / etc

https://github.com/Microsoft/TypeScript/issues/24142 is the cause of one of the issues, we should wait for a response there, hopefully a new nightly version of TS will resolve this issue.

Another test failure was caused by [a new diagnostic](https://github.com/Microsoft/TypeScript/pull/23805/files#diff-e119cc28df9582f9e1ca0d41720ea142R3554) which marks when all destructured elements are unused. We'll likely need to make a code change to handle this:

![image](https://user-images.githubusercontent.com/1400151/40086516-aa4b4336-586c-11e8-97f7-20a94d081d0c.png)

**Comment by JKillian** [comment]
Update: https://github.com/Microsoft/TypeScript/issues/24142 has been fixed, so after the next nightly is released we should see some of the issues resolve themselves. This just means we'll need to appropriately handle the new diagnostics noted above

**Comment by johnwiseheart** [comment]
I'm pretty sure theyre fixed now
