### ISSUE TITLE
no-internal-module flagged for class keywords

### ISSUE THREAD

**Issue by WorldMaker** [palantir/tslint#3915]
### Bug Report

- __TSLint version__: 5.9.1
- __TypeScript version__: 2.8.3
- __Running TSLint via__: `tslint-language-service` 0.9.9 via VSCode extension TSLint (vnext) 0.0.4

#### TypeScript code being linted

```ts
class ClassName { // no-internal-module
}

export default class SomeOtherClass { // no-internal-module
}
```

with `tslint.json` configuration:

```json
{
  "extends": ["tslint-config-standard"],
  "linterOptions": {
    "exclude": [
      "config/**/*.js",
      "node_modules/**/*.ts"
    ]
  }
}
```

#### Actual behavior

Any usage of `class` is getting a tslint warning for `no-internal-module`.

#### Expected behavior

No tslint error/warning for `class` keyword usage.

**Comment by giladgray** [comment]
@WorldMaker I cannot reproduce this in 5.11. can you?

**Comment by WorldMaker** [comment]
I haven't seen it in a while. I'm wondering if it might have been a confused combination of VS Code plugin version, tslint version, and TS version.
