### ISSUE TITLE
"recommended" preset has code style rules

### ISSUE THREAD

**Issue by denisw** [palantir/tslint#3917]
First of all, thank you for TSLint. It is an incredibly nice tool!

That being said, I think it is very unfortunate that the `tslint:recommended` set is way too opinionated by including many code style rules (including controversial things like required semicolons). I think it would be much better if the `recommended` set would be like `eslint:recommended` in that it is a conservative, coding-style-neutral set of rules that concentrates on preventing mistakes, and that all style-related rules are moved to a separate  ruleset named`tslint:recommended-style` or something.

**Comment by giladgray** [comment]
@denisw the `recommended` set is intentionally opinionated, that's why it's "recommended." this will not change.
