### ISSUE TITLE
Duplicate Object Key in VS Code Settings

### ISSUE THREAD

**Issue by DanJ210** [palantir/tslint#3920]
### Bug Report

- __TSLint version__: 5.10.0
- __TypeScript version__: 2.8.3
- __Running TSLint via__: (pick one)  VSCode 

There's no code being linted it's all working except there's 50 problems in the problem window and they are all Duplicate Object Key errors for TSLint settings. All I did was follow docs, `npm install -g typescript tslint` and then I installed the tslint extension for VSCode.

I did a search for an issue like this, nothing came up here. I did a search online and found stuff on the VSCode GitHub but no solution or description as to why. I did find another extension having this and they said that they were going to stop their extension from adding the settings. Idk if that helps or not.

Have I done something wrong in the install process? How could I fix this?

Thanks for all the work.

**Comment by giladgray** [comment]
@DanJ210 can you share a screenshot of VSCode with the errors? i've never seen this before. i also refuse to install these tools globally, instead using the workspace versions.

**Comment by DanJ210** [comment]
Yes, here's a screenshot. I mean I'm a junior dev so I'm installing globally for now as I haven't had a problem. For now I'll keep doing it until I'm more comfortable with the process entirely.

![tslint_problem](https://user-images.githubusercontent.com/16159685/41299117-be0ac246-6e30-11e8-8a6a-62f7d4347d8f.PNG)

**Comment by giladgray** [comment]
@DanJ210 this looks like an error in `jsonc`, not in `tslint` (per the tags at the beginning of each error)

**Comment by DanJ210** [comment]
So what does that mean? This only started happening with tslint. I've had VS Code going for months.

**Comment by DanJ210** [comment]
@giladgray The screenshot is showing only a short list of the 50+ errors so saying that the error is [jsonc] from that small amount of evidence is inaccurate. Also [jsonc] is what's showing the error message that I have duplicate entries all from tslint so that has nothing to do with the problem, it's only finding and reporting that I have duplicate entries.

tslint are the only settings that have duplicates. What issue is that?

Do I need to make another issue since this was erroneously closed?
