### ISSUE TITLE
Offer ability to add custom failure message for no-console

### ISSUE THREAD

**Issue by aervin** [palantir/tslint#3923]
I think `no-console` is among the most commonly `// tslint:disable-next-line`-ed rules I come across in projects. Often times, projects have specific logging mechanisms but devs new to the team don't know about them. It would be nice to add a custom failure message directing the devs to the logging class (or whatever) they ought to use to log things.

Possible config: 
```js
"rules": {
    no-console: [
        true,
        ['log', 'error'],
        'Instead of using console, try importing LogService'
    ]
}
```

**Comment by giladgray** [comment]
why not `ban`?

**Comment by aervin** [comment]
Closing because ban is an adequate alternative.
