### ISSUE TITLE
Can't find the rules to disable given the error

### ISSUE THREAD

**Issue by nuthinking** [palantir/tslint#3930]
I am new to TS, but how is it possible that given the error from the compiler, is almost impossible to find the matching rule to disable? Thanks

**Comment by giladgray** [comment]
@nuthinking yes as described above there are two tools at work here:

- `tsc` the TypeScript compiler, whose errors are game-breaking and must be addressed before proceeding (never produces warnings, only errors)
- `tslint` the linter, whose errors/warnings are typically style- or convention-related.
