### ISSUE TITLE
Fix for no-inferrable-types removes "?"

### ISSUE THREAD

**Issue by nhnb** [palantir/tslint#3944]
### Bug Report

- __TSLint version__: 5.8.0
- __TypeScript version__: 2.42
- __Running TSLint via__: ng lint

#### TypeScript code being linted

```ts
export class HisSearchCriterion {
    label: string;
    showNullItem?: boolean = false;
}
```

with `tslint.json` configuration:
```json
    "no-inferrable-types": [
      true,
      "ignore-params"
    ],
```

#### Actual behavior
`ng lint --fix` removes the boolean-type-declaration as expected. But it also removes the optional-indicator "?" resulting in `showNullItem = false;`

#### Expected behavior

The variable should stay optional: `showNullItem? = false;` and there should be no compiler error elsewhere in the code about that variable being required.

**Comment by giladgray** [comment]
the fixer is correct. you've declared the type as `boolean`, but then adding the `?` injects an implicit `| undefined`, which doesn't match the declared type so the fixer removes the `?`.

if you really want it optional (undefined-able) then the type should be `showNullitem: boolean | undefined = false`

**Comment by giladgray** [comment]
to be clear: explicit type declarations like `: boolean` win out over inferred types every time.
