### ISSUE TITLE
Inserts Spaces on autofix

### ISSUE THREAD

**Issue by DakshMiglani** [palantir/tslint#3947]
### Bug Report

- __TSLint version__:5.10.0
- __TypeScript version__:2.9.1
- __Running TSLint via__: VSCode

#### TypeScript code being linted

Video: https://i.gyazo.com/442e252625e11504e983a5f3fec1a12f.mp4
```ts
export const getModels = () => {
  const files = fs.readdirSync('./Models');
  const Models = {};
  files.forEach(file => {
    Models[file] = // after save, it inserts spaces here.
  });
};
```

with `tslint.json` configuration:

```json
{
  "defaultSeverity": "error",
  "extends": ["tslint-config-airbnb"],
  "jsRules": {},
  "rules": {
    "no-console": false,
    "member-access": false,
    "object-literal-sort-keys": false,
    "ordered-imports": false,
    "interface-name": false,
    "variable-name": false
  },
  "rulesDirectory": []
}
```

#### Actual behavior

When I save the file (I've enabled autoFixOnSave) it Inserts spaces.

#### Expected behavior

Should not insert spaces.

Even tho the code is wrong, the editor shouldn't insert spaces. It's scary behavior, and let's assume you've saved the file accidentally and you see random spaces there.

**Comment by DakshMiglani** [comment]
@palantirtech ?

**Comment by giladgray** [comment]
@DakshMiglani you haven't finished the statement, so the linter is just doing what it thinks is best. does it still insert spaces once you've assigned a right hand value? seems like lightweight user error to me.

**Comment by giladgray** [comment]
also fwiw, `object.push` does not exist.

**Comment by DakshMiglani** [comment]
I Know, but it shouldn't insert random spaces in there. if you save accidentally and see random spaces inserted there, how would you feel?
