### ISSUE TITLE
使用Object.defineProperty给对象添加属性后，tslint不识别，提示无此属性

### ISSUE THREAD

**Issue by ft1996** [palantir/tslint#3952]
![jietu20180609-195737](https://user-images.githubusercontent.com/18325669/41191261-674d0814-6c1f-11e8-9eee-70d3fde54d96.jpg)

**Comment by JKillian** [comment]
Hi @ft1996, what you're seeing there is an issue from TypeScript, not from tslint. TypeScript isn't able to tell that some object has a specific property when that property is dynamically created with `Object.defineProperty`.
