### ISSUE TITLE
VSCode: Module 'webpack' is not listed as dependency in package.json while it presents

### ISSUE THREAD

**Issue by budarin** [palantir/tslint#3991]
### Bug Report

- __TSLint version__: 5.10.0
- __TypeScript version__: 2.9.2
- __Running TSLint via__:  VSCode

#### TypeScript code being linted

```ts
import webpack from 'webpack';
```

with `tslint.json` configuration:

```json
{
    "defaultSeverity": "error",
    "extends": ["tslint:latest", "tslint-react", "tslint-config-prettier"],
    "jsRules": {},
    "rules": {
        "ordered-imports": false,
        "object-literal-sort-keys": false
    },
    "rulesDirectory": []
}
```

#### Actual behavior
webpack is installed and presents in package.json
```
        "webpack": "^4.12.0",
        "webpack-cli": "^3.0.8",
        "webpack-dev-server": "^3.1.4",
        "webpack-node-externals": "^1.7.2"
```

but in VSCode I have tslint error:

```
[tslint] Module 'webpack' is not listed as dependency in package.json (no-implicit-dependencies)
```

#### Expected behavior
expected - code without error

**Comment by giladgray** [comment]
@budarin check the options for this rule. you may need to enable the one that allows `devDependencies`.

**Comment by budarin** [comment]
@giladgray 
It did not help
I tried:
```js
"no-implicit-dependencies": [true, "dev"],
"no-implicit-dependencies": "dev"
"no-implicit-dependencies": false
```
any of that has helped :(

**Comment by giladgray** [comment]
well then. where is the package.json relative to your tslint.json and your source file? maybe the paths are confusing it.

**Comment by budarin** [comment]
in the root of the project on the same level
try in [repo](https://github.com/budarin/react-ssr-bootstrap-project)

**Comment by giladgray** [comment]
sorry mate I don't know what's up here. everything looks in order. it's likely some quirk of your setup.

**Comment by budarin** [comment]
so, how should I live with it? :)

**Comment by giladgray** [comment]
investigate further. have you installed `@types` for these packages? i honestly don't know the internals of this rule or your code so there's little i can do for you from over here.

**Comment by giladgray** [comment]
i checked out your code and can definitely repro this. i have no idea what's up.

**Comment by budarin** [comment]
I am confused by the fact that the error is intermittent: first, it was in the import webpack then moved on react-hot-loader

**Comment by giladgray** [comment]
@budarin my friend i have bad news. setting the correct config handily fixed this.
```
"no-implicit-dependencies": [true, "dev"]
```

**Comment by giladgray** [comment]
https://github.com/palantir/tslint/issues/3991#issuecomment-399704725 has a trailing comma after the `]` which may have caused the whole thing to blow up.

**Comment by budarin** [comment]
I have successfully  disabled this rule today 21:47, 27 июня 2018 г., Gilad Gray <notifications@github.com>:#3991 (comment) has a trailing comma after the ] which may have caused the whole thing to blow up.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

С уважением Бударин Вадим

**Comment by giladgray** [comment]
i checked out your code  and enabled it and it worked flawlessly.

**Comment by giladgray** [comment]
https://github.com/budarin/react-ssr-bootstrap-project/pull/1/files

**Comment by budarin** [comment]
But disabling it - is not good solution (21:49, 27 июня 2018 г., Gilad Gray <notifications@github.com>:i checked out your code  and enabled it and it worked flawlessly.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

С уважением Бударин Вадим

**Comment by budarin** [comment]
Thanks!
