### ISSUE TITLE
Can we have GitHub templates for issues vs. feature requests vs. rule requests?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [palantir/tslint#4000]
They're quite handy, and I feel awkward deleting lines of the suggested template when they don't apply. 😅

Prior art: https://github.com/facebook/jest/issues/new/choose

![image](https://user-images.githubusercontent.com/3335181/42012985-e4249120-7a4f-11e8-8628-04557f513bda.png)

**Comment by suchanlee** [comment]
i think it would be a good idea!

**Comment by giladgray** [comment]
yo absolutely!
