### ISSUE TITLE
[Rule request] disable `/* */` comments

### ISSUE THREAD

**Issue by euclio** [palantir/tslint#4005]
In a codebase, it' can be easy to accidentally type doc comments with a leading `/*`. If you use `//`-style comments everywhere else, this lint could catch cases where you meant to write a doc comment.

**Comment by johnwiseheart** [comment]
Happy to take a PR for a new rule for this.

**Comment by michaelblack** [comment]
PR for this at #4008

**Comment by johnwiseheart** [comment]
This has been merged
