### ISSUE TITLE
Optional inputs and whitespace

### ISSUE THREAD

**Issue by michael-letcher** [palantir/tslint#4007]
### Bug Report

- __TSLint version__: ~5.9.1
- __TypeScript version__: 2.9.1
- __Running TSLint via__:  CLI

#### TypeScript code being linted

```ts
// code snippet
@Input() editable?= true;
```

with `tslint.json` configuration:

```json
{
    "compileOnSave": false,
    "compilerOptions": {
        "outDir": "./dist/out-tsc",
        "sourceMap": true,
        "declaration": false,
        "moduleResolution": "node",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "target": "es5",
        "typeRoots": [
            "node_modules/@types"
        ],
        "lib": [
            "es2017",
            "dom"
        ],
        "baseUrl": "./src",
        "paths": {
            "@app/*": [
                "app/*"
            ],
            "@env/*": [
                "environments/*"
            ],
            "@shared/*": [
                "app/shared/*"
            ]
        }
    }
}

```

#### Actual behavior
```ts
// code snippet
@Input() editable? = true;
```

Is being formatted to 

```ts
// code snippet
@Input() editable?= true;
```

and the `?` has the error `[tslint] missing whitespace (whitespace)`

#### Expected behavior

```ts
// code snippet
@Input() editable? = true;
```

Should be valid, with not formatting or errors.

**Comment by JoshuaKGoldberg** [comment]
☠️ *TSLint's time has come!* ☠️ 

TSLint is no longer accepting formatting/whitespace requests per #4534. See **[typescript-eslint.io](https://typescript-eslint.io)** for the new, shiny way to lint your TypeScript code with **ESLint**. ✨ 

It was a pleasure open sourcing with you all!
