### ISSUE TITLE
Spaces before function parens are disallowed

### ISSUE THREAD

**Issue by Higginshuangjing** [palantir/tslint#4030]
### Bug Report

- __TSLint version__: 5.10.0
- __TypeScript version__: 2.9.2
- __Running TSLint via__:  VSCode

#### TypeScript code being linted

```ts
// code snippet
eventBusHandler (msg: any) { }
```
with `tslint.json` configuration:

```
{
  "defaultSeverity": "warning",
  "extends": [
    "tslint:recommended"
  ],
  "linterOptions": {
    "exclude": [
      "node_modules/**"
    ]
  },
  "rules": {
    "prefer-const": false,
    "quotemark": [true, "single"],
    "indent": [true, "spaces", 2],
    "interface-name": false,
    "ordered-imports": false,
    "object-literal-sort-keys": false,
    "no-trailing-whitespace": false,
    "no-consecutive-blank-lines": false,
    "semicolon": [true, "never"],
    "trailing-comma": [true, {"multiline": "never", "singleline": "never"}],
    "one-line": [true, "check-whitespace"]
  }
}

```

#### Actual behavior
WARNING in /Users/huangjing/Desktop/atnena/corporateclub-surfaces/src/common/msg.ts
52:23 Spaces before function parens are disallowed
    50 |    * 带参数错误处理
    51 |    */
  > 52 |   eventBusErrorHandler () {
#### Expected behavior
Hello, excuse me, I would like to ask, if I want to leave a space between the function name and (), which genus should I configure

**Comment by johnwiseheart** [comment]
@Higginshuangjing I believe its the `whitespace` rule
