### ISSUE TITLE
Avoid global imports (import * from)

### ISSUE THREAD

**Issue by jacopolanzoni** [palantir/tslint#4035]
### Rule suggestion

I would like to avoid global imports (e.g., `import * from 'lodash'`) for some modules, and force the user to import single exported functionalities (e.g., `import { includes } from 'lodash'`).

**Comment by Shinigami92** [comment]
Some packages only support this `import *` strategy

**Comment by johnwiseheart** [comment]
As @Shinigami92 mentioned, a lot of packages rely on the `import *` strategy. I don't believe TSLint currently supports a way to ban global imports, but if you were to write one we would likely accept it.

**Comment by JoshuaKGoldberg** [comment]
Note: per #4534, this issue will be closed in less than a month if no PR is sent to add the rule. If you _really_ need the rule, custom rules are always an option and can be maintained outside this repo!

**Comment by JoshuaKGoldberg** [comment]
Actually, this is a subset of #3851.
