### ISSUE TITLE
[Question] Identifier 'id' is never reassigned; use 'const' instead of 'let'. (prefer-const)

### ISSUE THREAD

**Issue by muyu66** [palantir/tslint#4045]
- tslint Version: 1.0.33
- Npm tslint Version: 5.3.2
- typescript Version: 2.9.2

Example code:

```
function User(){
	return { id: 1, name: 'Tom' };
}
let { id, name } = User();
name = 'Jook';
console.log(id, name);
```

Then, tslint warn me, "Identifier 'id' is never reassigned; use 'const' instead of 'let'. (prefer-const)".

I am confused. I can't change ''let' to ''const' because i want to reassign ''name'. Repeatedly reading User() with two lines of code, I think it is not advisable, if even User() is Promise Function.

How to write pretty code?

tslint.json
`{
    "defaultSeverity": "error",
    "extends": [
        "tslint:recommended"
    ],
    "jsRules": {
        "no-unused-expression": true
    },
    "rules": {
        "whitespace": false,
        "jsdoc-format": true,
        "prefer-for-of": false,
        "forin": false,
        "align": true,
        "new-parens": false,
        "no-angle-bracket-type-assertion": false,
        "no-console": false,
        "no-namespace": false,
        "eofline": false,
        "quotemark": [
            true,
            "single"
        ],
        "indent": false,
        "member-access": [
            false
        ],
        "ordered-imports": [
            false
        ],
        "max-line-length": [
            true,
            280
        ],
        "member-ordering": [
            false
        ],
        "curly": false,
        "interface-name": [
            false
        ],
        "array-type": [
            false
        ],
        "no-empty-interface": false,
        "no-empty": false,
        "arrow-parens": false,
        "object-literal-sort-keys": false,
        "no-unused-expression": false,
        "max-classes-per-file": false,
        "variable-name": [
            false
        ],
        "one-line": [
            false
        ],
        "one-variable-per-declaration": [
            false
        ]
    },
    "rulesDirectory": []
}`

**Comment by robjs827** [comment]
I'm a bit confused about such unpleasant error-lines,

![tslint](https://user-images.githubusercontent.com/19618859/47223318-ee1a1300-d3f3-11e8-8519-efbda5a52bbf.png)

**Comment by sibelius** [comment]
`"prefer-const": [true, {"destructuring": "all"}]`
