### ISSUE TITLE
no-unused-variable is deprecated.

### ISSUE THREAD

**Issue by ohrrkan** [palantir/tslint#4046]
### Bug Report

- __TSLint version__: 5.11.0
- __TypeScript version__: 2.9.2
- __Running TSLint via__: Node.js 

#### TypeScript code being linted

The   "tslint:all" rules give a : "no-unused-variable is deprecated. Since TypeScript 2.9. Please use the built-in compiler checks instead."

with `tslint.json` configuration:

```
{
    "extends": [
        "tslint:all"
    ],
    "defaultSeverity": "error",
    "rules": {
        "completed-docs": false,
        "prefer-for-of": false,
        "strict-type-predicates": false,
        "only-arrow-functions": [
            true,
            "allow-named-functions"
        ],
        "no-inferrable-types": [
            false,
            "ignore-params",
            "ignore-properties"
        ],
        "max-line-length": [
            false,
            170
        ],
        "align": [
            false
        ],
        "no-unnecessary-type-assertion": false,
        "prefer-switch": false
    }
}

```

**Comment by kachkaev** [comment]
I'm also not sure why I'm seeing the deprecation warning given that `"no-unused-variable"` has been un-deprecated in https://github.com/palantir/tslint/pull/2256. 🤔 

```bash
yarn tsc --version
# 2.9.2
yarn tslint --version
# 5.11.0
```

**Comment by johnwiseheart** [comment]
The deprecation is intentional. Please see https://github.com/palantir/tslint/pull/3919 for details.

**Comment by wcauchois** [comment]
Hi, what's the recommended way to detect unused imports (especially in the context of a CI system) with this change? Thank you.

**Comment by realtebo** [comment]
So, now how to get rid of this warning?

```
"tslint": "^5.11.0",
"typescript": "^3.0.1"

> tslint --project tsconfig.json

no-unused-variable is deprecated. Since TypeScript 2.9. Please use the built-in compiler checks instead.
```

ans this the config json

```
{
  "compilerOptions": {
    "lib": ["es6"],
    "module": "commonjs",
    "noImplicitReturns": true,
    "outDir": "lib",
    "sourceMap": true,
    "target": "es6",
    "allowJs" : true
  },
  "compileOnSave": true,
  "include": [
    "src"
  ]
}

```

I suggest to add at least a tip of what to do to fix, because  in my config this rules is not present.

**Comment by kachkaev** [comment]
The warning comes from `tslint.json` rather than `tsconfig.json`. Check if you have `"no-unused-variable"` right in there or in any of configs declared in `"extends"`.

**Comment by realtebo** [comment]
I removed from tslint.json and .eslintrc.json.

Warning is still here. How to 'mute' it? 

This demonstrate that a warning need additional infos to be usefull to users because not every dev know where it come from. I am one of them.

**Comment by franzisk** [comment]
Just let your tsling.json like this:
```
{
  "rules": {
    "no-duplicate-variable": true
  },
  "rulesDirectory": [
    "node_modules/tslint-eslint-rules/dist/rules"
  ]
}
```

**Comment by andyfleming** [comment]
I agree with @kachkaev that having a compilation failure is very annoying during active development. Linting _is_ specifically where I want to catch this issue.

**Comment by errorx666** [comment]
I want this rule so I can use `--fix` and fix it automatically.

**Comment by adidahiya** [comment]
continue discussion in #4100
