### ISSUE TITLE
[Feature Request] Custom Rule: Require new line after import statements.

### ISSUE THREAD

**Issue by lucasklaassen** [palantir/tslint#4052]
### Bug Report

- __TSLint version__:5.9.1
- __TypeScript version__:2.7.2
- __Running TSLint via__: (pick one) VSCode

#### TypeScript code being linted

```ts
import { NgModule } from '@angular/core';
import { NgbModule } from '../../../../node_modules/@ng-bootstrap/ng-bootstrap';
import { SharedModule } from '../../shared/shared.module';
import { ClubMembersRoutingModule } from './club-members-routing.module';
import { ClubMembersComponent } from './club-members.component';
@NgModule({
  imports: [
    SharedModule,
    ClubMembersRoutingModule,
    NgbModule
  ],
  declarations: [
    ClubMembersComponent
  ]
})
export class ClubMembersModule {}
```

with `tslint.json` configuration:

```json
"new-line-after-imports": true
```

#### Actual behavior

Right now there's no rule to require a new line to be included after the import statements in a typescript file.  Below in the expected behavior, I've listed how the code sample above should be linted.

#### Expected behavior
```ts
import { NgModule } from '@angular/core';
import { NgbModule } from '../../../../node_modules/@ng-bootstrap/ng-bootstrap';
import { SharedModule } from '../../shared/shared.module';
import { ClubMembersRoutingModule } from './club-members-routing.module';
import { ClubMembersComponent } from './club-members.component';
// New Line Required Here
@NgModule({
  imports: [
    SharedModule,
    ClubMembersRoutingModule,
    NgbModule
  ],
  declarations: [
    ClubMembersComponent
  ]
})
export class ClubMembersModule {}
```

**Comment by stocksr** [comment]
I would also like a rule (option on this rule) to prevent extra newlines inside the import block.

**Comment by omniscient** [comment]
@stocksr : This should be a separate request since there is already "import-spacing": true rule in place.

**Comment by amazzoccone** [comment]
Maybe we should think in rules for Typescript Decorators, because the package doesn't have any about it. Something like "newline-before-decorator"?

For example, in Stencil, you could have the following code:
```
  @State() device: IDevice;
  constructor() {
    ..
  }
```
and there is no rule to force a line between decorator and method.

**Comment by adidahiya** [comment]
Sorry, I don't think we will add new formatting rules at this point. See #4534
