### ISSUE TITLE
prefer-method-signature autofix produces broken code

### ISSUE THREAD

**Issue by yakirn** [palantir/tslint#4057]
### Bug Report

- __TSLint version__: 5.11.0
- __TypeScript version__:2.9.2
- __Running TSLint via__: (pick one) CLI

#### TypeScript code being linted

```ts
export interface Bar {
  someMethod: (
    someArg: Pick<HTMLAllCollection, "item">
  ) => string;
}
```

with `tslint.json` configuration:

```json
{
    "rules": {
        "prefer-method-signature": true
    }
}
```

#### Actual behavior
outputs:
```ts
export interface Bar {
  someMethod(
    someArg: Pick<HTMLAllCollection, "item">
: string;
}
```
#### Expected behavior
Should produce valid TS code, such as:
```ts
export interface Bar {
  someMethod(someArg: Pick<HTMLAllCollection, "item">): string;
}
```

The broken lines are effecting the output. The linting of this code:
```ts
export interface Bar {
  someMethod: (someArg: Pick<HTMLAllCollection, "item">) => string;
}
```
will be valid.

**Comment by JoshuaKGoldberg** [comment]
This was fixed by #4066. 🎉
