### ISSUE TITLE
is there any predefine rule to check the annotation on function 

### ISSUE THREAD

**Issue by RaneAshwini** [palantir/tslint#4078]
### Feature request
I have function in  ts like 
@check()
public abcfunction()
{
// some code
}

How do i add the rule to see that every function has the @check annotation ?

**Is your feature request that we implement a new rule?**
Please use the `Rule Suggestion` template instead

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by johnwiseheart** [comment]
There is no rule that would check this specifically. I would recommend implementing your own custom rule for this.
