### ISSUE TITLE
Rule option request: snake_case for file-name-casing rule

### ISSUE THREAD

**Issue by BigstickCarpet** [palantir/tslint#4088]
### Feature request

The [`file-name-casing` rule](https://palantir.github.io/tslint/rules/file-name-casing/) currently allows `camelCase`, `PascalCase`, and `kebab-case`.  It would be nice if it also allowed `snake_case`.

**Comment by giladgray** [comment]
see #4081, there's already a PR for this!

**Comment by BigstickCarpet** [comment]
Cool!  Glad to see there's already a PR. 👍 

I searched for an existing issue, but couldn't find one.  Didn't think to search PRs too.
