### ISSUE TITLE
Bad Spelling

### ISSUE THREAD

**Issue by ccorcos** [palantir/tslint#4113]
### Rule Suggestion

I'm having this issue where I want to spell lambda, but I often write lamdba on accident. Its happening all the time and its really hard to catch for some reason. Its not just variables, but file paths and strings that aren't type checked. It would be really nice if I could have very basic tslint rule to match invalid regex strings anywhere in your code to prevent these issues.

**Comment by michaeljota** [comment]
I think that you need a dictionary. If you are using VSCode I would suggest [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) extension.

**Comment by giladgray** [comment]
nope this is the job of a spellchecker, not a linter. plenty of great options out there already.
