### ISSUE TITLE
Rule override for object-literal-shorthand to never does not work

### ISSUE THREAD

**Issue by gingters** [palantir/tslint#4121]
### Bug Report

- __TSLint version__: 4.5.1
- __TypeScript version__: 2.9.2
- __Running TSLint via__: CLI

#### TypeScript code being linted

```ts
	const waitTime = 30; // this.configuration.waitTimeInSeconds;
	const shootingTime = 120; // this.configuration.arrowsPerEnd * this.configuration.timePerArrowInSeconds;

	let shooters = 'A/B'; // this.getShootersForEnd(true);

	let waitStart = 0;
	let shootingStart = waitStart + waitTime;
	let shootingEnd = shootingStart + shootingTime;
	let yellowPhaseStart = shootingEnd - 30; // this.configuration.yellowPhaseInSeconds;

	const events = [
		// 2x honk
		{ color: 'red', honks: 2, shooters: shooters, timer: waitTime, time: waitStart + 'ns' },
		// 1, honk, green, countdown wait time
		{ color: 'green', honks: 1, shooters: shooters, timer: shootingTime, time: shootingStart + 's' },
		// yellow for the last X seconds
		{ color: 'yellow', honks: 0, shooters: shooters, timer: null as number, time: yellowPhaseStart + 's' },
	];
```

with `tslint.json` configuration:

```json
{
  "extends": "tslint:latest",
  "rules": {
    "indent": [true, "tabs"],
    "member-ordering": [true, {
      "order": [
        "private-static-field",
        "private-instance-field",
        "protected-static-field",
        "protected-instance-field",
        "public-static-field",
        "public-instance-field",
        "public-constructor",
        "protected-constructor",
        "private-constructor",
        "public-static-method",
        "public-instance-method",
        "protected-static-method",
        "protected-instance-method",
        "private-static-method",
        "private-instance-method"
      ]
    }],
    "object-literal-shorthand": [true, "never"],
    "quotemark": [true, "single", "avoid-escape"]
  }
}
```

#### Actual behavior
TSLint errors out with message: `ERROR: src/tournament.ts[59, 30]: Expected property shorthand in object literal ('{shooters}').`

#### Expected behavior

Since I configured  `"object-literal-shorthand": [true, "never"],`, I expected TSlint NOT to throw an error and lint correctly.

#### Additional info:

Turning off the rule by setting  `"object-literal-shorthand": false,` makes the project lint, but does not enforce the rule that shorthands should not be allowed.

**Comment by benfavre** [comment]
Yep same

**Comment by giladgray** [comment]
@gingters i notice you're using tslint @ 4.x. we will not backport fixes.
does this repro on the latest version? 5.11

**Comment by JoshuaKGoldberg** [comment]
Closing this issue for housekeeping, but please do post if you're still seeing it in >=5.11 @gingters!

**Comment by dmitriivikorchuk** [comment]
Still the same with TSLint 5.12

**Comment by JoshuaKGoldberg** [comment]
Darn. Thanks for confirming @dmitriivikorchuk; are you able to provide a reproducible code snippet to go off of?

**Comment by dmitriivikorchuk** [comment]
You could use example from this issue. I tested TSLint 5.12 on it also, same result.
If you want, I could also create default angular project with packages and plugins that I use.

**Comment by JoshuaKGoldberg** [comment]
😕 This doesn't repro locally on my machine. That would be very helpful!

```
C:\Code\tstest  (tstest@1.0.0)
λ tslint --version && type tslint.json & type index.ts && tslint -c tslint.json index.ts
5.12.1
{
        "extends": "tslint:latest",
        "rules": {
          "object-literal-shorthand": [true, "never"]
        }
}
const waitTime = 30; // this.configuration.waitTimeInSeconds;
const shootingTime = 120; // this.configuration.arrowsPerEnd * this.configuration.timePerArrowInSeconds;

let shooters = "A/B"; // this.getShootersForEnd(true);

let waitStart = 0;
let shootingStart = waitStart + waitTime;
let shootingEnd = shootingStart + shootingTime;
let yellowPhaseStart = shootingEnd - 30; // this.configuration.yellowPhaseInSeconds;

const events = [
    // 2x honk
    { color: "red", honks: 2, shooters: shooters, timer: waitTime, time: waitStart + "ns" },
    // 1, honk, green, countdown wait time
    { color: "green", honks: 1, shooters: shooters, timer: shootingTime, time: shootingStart + "s" },
    // yellow for the last X seconds
    { color: "yellow", honks: 0, shooters: shooters, timer: null as number, time: yellowPhaseStart + "s" },
];
```

**Comment by dmitriivikorchuk** [comment]
I am so sorry that wasted you time :(
I did all checks in submodule of my project where I forgot to insert rule in tslint.json from main part.
All works fine!

**Comment by JoshuaKGoldberg** [comment]
😄 no worries, glad we can close this issue out & it's working for you!

**Comment by SimpleCookie** [comment]
So was this resolved? Feels like some information is missing in the discussion. I currently have the issue where TSLINT is complaining at:
```
let a = true;
let b = { a }
```
It says 

> [tslint] Value must be set for boolean attributes [jsx-boolean-value]

Not sure if it's a issue only I got or if it's a problem with the linter. I'm using Tslint version 5.12..1
