### ISSUE TITLE
Add tslint-playground link to README and other docs

### ISSUE THREAD

**Issue by johnwiseheart** [palantir/tslint#4125]
We now have this great tool: https://github.com/palantir/tslint-playground

Lets add it to all our docs.

**Comment by JoshuaKGoldberg** [comment]
_Yes yes yes please!_

Can it also be added to the suggested issue templates? It's nice how the TypeScript repo asks that bugs be filed with repro-able code samples.

**Comment by johnwiseheart** [comment]
Yeah we can definitely add it to the templates too! Unfortunately it only works for the rules included by tslint right now, but that is probably enough given generally people shouldn’t be making issues for external rule sets here.

**Comment by JoshuaKGoldberg** [comment]
Fixed by #4150. 🚀
