### ISSUE TITLE
Comments density

### ISSUE THREAD

**Issue by TristanFAURE** [palantir/tslint#4126]
### Rule Suggestion

**Is your rule for a general problem or is it specific to your development style?**
a General problem

**What does your suggested rule do?**
https://docs.sonarqube.org/display/SONAR/Metric+Definitions
comment_lines_density
Density of comment lines = Comment lines / (Lines of code + Comment lines) * 100
With such a formula:

    50% means that the number of lines of code equals the number of comment lines
    100% means that the file only contains comment lines

**List several examples where your rule could be used**
Determine if there are enough comments in the source code

**Additional context**

**Comment by giladgray** [comment]
@TristanFAURE this rule does not seem useful to me. why would i want to enforce a certain ratio of comments to code? seems like the wrong metric.

**Comment by TristanFAURE** [comment]
Hello @giladgray, I totally understand your comment and I was ready for it.

In some businesses like aeronautic, space, automotive... it exists standard that force us to give this kind of metric (like my other PR check function size). If we can't measure it we will not be able to use typescript for the development of some software :( (or we will have to find another linter)

I don't ask to make this parameter enable by default but it would be very nice to review this PR to let people who need it use it :(

**Comment by giladgray** [comment]
@TristanFAURE ah in that case this rule does not belong in the main TSLint repo, as it is specific to certain use cases. it belongs in your own codebase and can be enabled using the `ruleDirectories` option. you can develop it in a separate package and even publish it to NPM, but it does not belong here.

**Comment by TristanFAURE** [comment]
I understand your point of view but it is a little bit a pity because we are a lot working in this area and we all need it. But it is okay I can host it internally
