### ISSUE TITLE
Running CLI when checked out via a Git dependency does not work

### ISSUE THREAD

**Issue by wilg** [palantir/tslint#4131]
### Bug Report

- __TSLint version__: e766f517555580e155b6f58a582cff53c63563a9
- __TypeScript version__:3.0.1
- __Running TSLint via__: CLI

With TSLint included via Yarn with `"tslint": "https://github.com/palantir/tslint#master"` (or pinned to a recent master sha like e766f517555580e155b6f58a582cff53c63563a9), TSLint installs but the CLI does not work.

Using `"tslint": "5.11.0",` works fine.

#### Actual behavior

```
tslint --project tsconfig.json --format stylish 'lib/helltool/assets/**/*.ts' 'test/javascripts/**/*.ts'
module.js:529
    throw err;
    ^

Error: Cannot find module '../lib/tslintCli'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/wil/Code/looker/helltool/node_modules/tslint/bin/tslint:3:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
error Command failed with exit code 1.
```

No `lib` folder exists, presumably due to something in the compilation process:

```
› ls node_modules/tslint
CHANGELOG.md  README.md     bin/   node_modules/  scripts/  test/        yarn.lock
LICENSE       appveyor.yml  docs/  package.json   src/      tslint.json
```

When installed via a version on NPM (which works):

```
› ls node_modules/tslint
CHANGELOG.md  LICENSE  README.md  bin/  lib/  node_modules/  package.json
```

#### Expected behavior

TSLint's CLI works when installed in this way.

**Comment by giladgray** [comment]
@wilg tslint was never designed to be used that way. the repo does not contain compiled artifacts--only the published NPM package contains those. so of course it doesn't run: there's nothing to run!

**Comment by wilg** [comment]
I understand that, but I was under the impression there was some kind of package.json configuration (a `postinstall ` script?) that would allow this to work.

I am trying to use https://github.com/palantir/tslint/pull/3641 in my project, but without the ability to use TSLint from Git I don't see how I can use that until a release is created. Is there another way to do this? Does everyone just wait until a release is made to test TSLint against their code?

Alternatively, is there an expected date for the next release?

**Comment by giladgray** [comment]
@wilg instead of depending on the git repo, checkout the repo locally and build it. then `yarn link` (or `npm link`) to use your local copy.

**Comment by wilg** [comment]
Thanks, I will try that for testing, but it still means that I can't easily add the latest TSLint as a project dependency until an official release is made (because no other developers or build systems will be able to run it without a bunch of custom glue). 

It also seems like it would make contributing to TSLint a bit harder because I can't fork it to add something or fix a bug and then use my enhanced/fixed version until an official release is made.

**Comment by giladgray** [comment]
yes that is true and by design: you can not depend on the tip of `tslint`, only on published versions.

**Comment by JoshuaKGoldberg** [comment]
@giladgray Can we have nightly releases the way TypeScript does? There wouldn't be any guarantee of stability.

**Comment by karfau** [comment]
@wilg What I usually d in such cases is to create a fork, and after creating my fix, I branch of from the branch for the PR, and commit the compiled output into that branch only. This way I can put `github:user-or-org/repo#hash` (or the equivalent `https` link) as a depenency into `package.json`

**Comment by giladgray** [comment]
@JoshuaKGoldberg i'm in favor of nightlies 👍

**Comment by JoshuaKGoldberg** [comment]
Per #4534 this seems like not a priority anymore. If anybody actually does need this _(please do post here if so!)_ we can reopen.

You can always run TSLint with `ts-node`, so in theory there could be some hackery possible to get the raw git equivalent to work... Failing that, you can fork the repo, remove `.ts` files from `.gitignore`, and check in built artifacts. 🤷‍♂
