### ISSUE TITLE
TSLint is brought to you by: Racists

### ISSUE THREAD

**Issue by jamiebuilds** [palantir/tslint#4141]
Apologies to any contributors who aren't employees of Palantir. But to those that are:

Please find jobs elsewhere and stop helping Palantir [do horrible things](
https://theintercept.com/2017/03/02/palantir-provides-the-engine-for-donald-trumps-deportation-machine).

Also, stop using my tools (such as Lerna), I don't support you, and I don't want my work to benefit your awful company.

**Comment by jamiebuilds** [comment]
https://news.vice.com/en_us/article/paw9ky/toddler-died-after-getting-sick-in-ice-custody

**Comment by jamiebuilds** [comment]
https://twitter.com/ACLU/status/1033084026893070338

**Comment by jamiebuilds** [comment]
How's it feel to contribute to this institution?

**Comment by michaeljota** [comment]
So that's why they have been busy...

**Comment by michaeljota** [comment]
@palantirtech That will be actually your stand? Yes, we do that, but also we contribute to open source so who cares? Really? :/

**Comment by jamiebuilds** [comment]
They're human garbage, I asked nicely, now I'm going to force them.

**Comment by ajafff** [comment]
To anyone looking for an alternative to TSLint:
After leaving TSLint I startet developing my own linter, the [Fimbullinter project](https://github.com/fimbullinter/wotan). For a quick start guide, see [the documentation of Wotan, the linter runtime](https://github.com/fimbullinter/wotan/blob/master/packages/wotan/README.md)
There's a plugin to make Fimbullinter a drop-in replacement of TSLint: [Valtýr](https://github.com/fimbullinter/wotan/blob/master/packages/valtyr/README.md)
Another plugin allows you to use your existing (custom) TSLint rules while benefitting from all other features of the linter: [Heimdall](https://github.com/fimbullinter/wotan/blob/master/packages/heimdall/README.md)
Also note that it has [many builtin rules](https://github.com/fimbullinter/wotan/blob/master/packages/mimir/README.md#rules) that are either not available in TSLint or superior to their TSLint counterpart.

**Comment by unconed** [comment]
>I asked nicely, now I'm going to force them.

@jamiebuilds Everyone already knows that you asking "nicely" is just a pretense before you call in the mob, but nice of you to admit it. The mob asked nicely too if business owners wanted insurance.

Garbage is as garbage does.

**Comment by SRGOM** [comment]
@jamiebuilds is a well known clown, see the following and ignore him 

https://github.com/Microsoft/web-build-tools/issues/673


> Please stop mentioning me on this issue and contacting me about this, I'm done talking about it since Microsoft employees (Scott Hanselman) have gone out of their way to contact my friends and try to convince them to say shit about me publicly. You guys are assholes, now fuck off.

**Comment by BenniGER** [comment]
https://opensource.org/faq#commercial

**Can I stop "evil people" from using my program?**
> No. The Open Source Definition specifies that Open Source licenses may not discriminate against persons or groups. Giving everyone freedom means giving evil people freedom, too.

**Comment by kode54** [comment]
I actively support the notion of denying resources, a platform, and freedom, to evil people. I don't care if this isn't "true" freedom. Those people don't deserve freedom. Hell, I'd even go so far as to say they don't deserve to share this world with us.

**Comment by McSwaggens** [comment]
@kode54 

I actively support the notion of denying resources, a platform, and freedom, to **furries**. I don't care if this isn't "true" freedom. Those people don't deserve freedom. Hell, I'd even go so far as to say they don't deserve to share this world with us.

**Comment by michaeljota** [comment]
I do remember @jamiebuilds I also remember that he does not like being tagging. I guess that I'm really on edge, because as a person that was pushed to migrate I really fell the needs and the suffering of those who are in the same path as I am. Because of that I just would like an official statement from Palantir. As with Microsoft, if they are actually working with the US government, you are in your right to do so, but you can also be clear as water regarding what are you doing. 

Note to @jamiebuilds: Please, I don't know if you just want attention, but please stop trolling good companies for whatever reasons you may have. I do suffer this, the people I come from are being hunted and pointed, and I don't like when someone takes some statement like this just to make his name viral.

**Comment by nafg** [comment]
And they can also be as unclear as they like. Anyone who thinks the US government is evil can go live under a rock on a island somewhere and avoid contact with anything that was produced as a result of the US government. Alternatively, they can try doing research outside of the bubble of propaganda they apparently consume.

Enough with the brownshirt tactics.

**Comment by kode54** [comment]
The current administration and the entire cabinet put in place by it are certainly evil, or at least maliciously stupid. I also delight in your painting leftism as if it is a bad thing. I’ll just ignore that other comment.

**Comment by nafg** [comment]
Without getting into that, the ICE policy well predates the current administration

**Comment by SoaresMG** [comment]
Political matters should be away from the OSS community.
Everyone is free to choose their party and who they follow.

This is childish and irresponsible, instead you should create a medium article that no one will read.
