### ISSUE TITLE
can't use Array in firebase.firestore.CollectionReference | firebase.firestore.Query why ?

### ISSUE THREAD

**Issue by Omar-Qalei** [palantir/tslint#4142]
```
 const list = this.afs.collection( 'City').ref;
let queryCollection: firebase.firestore.CollectionReference | firebase.firestore.Query &  Array = list;
for (let _i = 0; _i < this.data.areaList.length; _i++) {

            if (this.data.areaList) {  queryCollection[_i] = queryCollection.where('areaList', '==', this.data.areaList[_i]);

          }
            console.log(this.data.areaList[_i]);
      }
```
Note: can't use let  only const why and how to change bug ?
I wanna use let queryCollection .

**Comment by FiretronP75** [comment]
Array: You must specify the type of the array, like `string[]` for example.
Const: You will be allowed to use let instead of const, after you have a statement that assigns a new value:
```
let queryCollection = something;
queryCollection = somethingElse;
```

**Comment by Omar-Qalei** [comment]
I can't because I will get snapshot of multiple Method this is example I have more one for loop
and I need get specific data .
array = [ ];
`queryCollection .get().then(snapshot => {
          snapshot.forEach(action => {
            array .push(action.data());
          
           console.log(array );
          }); });`

Note: my website need advanced filter :) 
Note2: const get data redundancy , if I push this data in array .

**Comment by giladgray** [comment]
the array is actually a const in your original code sample--you never modify the array reference itself. modifying items _in_ the array does not a new array make, so the `const` is correct.

(fwiw, i will rewrite code obsessively to avoid using `let` variables. the results are almost always worth it for legibility and maintainability.)

**Comment by Omar-Qalei** [comment]
yes please help me , I'm first time create website

**Comment by giladgray** [comment]
@Omar-Qalei sorry, this is not the place for advice on building web apps. the internet (especially StackOverflow) is full of useful information in this domain. best of luck!
