### ISSUE TITLE
Disable lint rule in css

### ISSUE THREAD

**Issue by KumailHussain** [palantir/tslint#4144]
Not working with css files 

/* tslint:disable-next-line*/
input:focus , input:valid 		{
  top:-20px;
  font-size:14px;
  color:#606060;
}

still showing the error how can i disable a rule in css file?

**Comment by giladgray** [comment]
@KumailHussain ummmm how are you even running tslint on css files? or better, why?? typescript and css are vastly different languages. pretty sure tslint can't even correctly parse stylesheets.

i recommend [stylelint](https://github.com/stylelint/stylelint) for all your stylesheet linting needs.

**Comment by KumailHussain** [comment]
than remove the rule unused css from tslint if it is not meant for css.
Thanks

**Comment by johnwiseheart** [comment]
FYI `no-unused-css` is a custom rule which is part of `codelyzer` and not `tslint`.
