### ISSUE TITLE
strict-boolean-expressions should ignore RHS of `&&` and `||`

### ISSUE THREAD

**Issue by dobesv** [palantir/tslint#4158]
Idiomatic JavaScript / TypeScript typically treat `||` or `&&` operators such that only the left operand is considered a "boolean expression" whereas the RHS might be any value that would be used as a result.

Currently an expression like `process.env.PORT || 8080` gives an error with `strict-boolean-expressions` because it rejects the RHS for being "always truthy".  This is a common enough pattern it should be accomodated by this rule.

This has already been discussed to some degree in https://github.com/palantir/tslint/issues/3279 but it doesn't have its own issue tracking it and I'm not sure what it's status is at this point.

I suggest an option to enable checking of the rhs of these operations, default would be not to check.

**Comment by JoshuaKGoldberg** [comment]
Duplicate of #3279. Still accepting PRs! 😊

**Comment by dobesv** [comment]
I did create a PR for this one, didn't I?

**Comment by JoshuaKGoldberg** [comment]
Ha, yes _(thanks for that, by the way!)_. Just closing duplicate issues to keep our issue count down.
