### ISSUE TITLE
Feature Request: Integrate circular dependency checker into tslint

### ISSUE THREAD

**Issue by AsiFefer** [palantir/tslint#4169]
### Feature request

Hello,

Typescript linter should have circular dependency check task. In case linter found any circular dependency, between 2 modules, then it should display a warning about it, In VS code Terminal window.

For example, let's assume that module A uses Module B which in turn uses Module A again. In that case the following warning should be displayed:

Warning: Circular dependency found: A -> B -> A.

circular dependency check is easy to implement:
Linter reads the content of the files in the project. It reads the Import section of each module. It then follows the imports to the next file. It does so, until he reaches a module that has no imports. In case it starts from some module, and on the way it gets back to that module again, then this is a circular dependency between 2 modules.

Thanks,
Asi.

**Comment by JoshuaKGoldberg** [comment]
> circular dependency check is easy to implement

No, it's not 😢 https://github.com/bcherny/tslint-no-circular-imports has some pretty difficult structural & performance challenges that are still being tackled. It technically works but https://github.com/bcherny/tslint-no-circular-imports/issues/19 remains.

Out of scope for TSLint core for now, but eventually *if* it's stable and fast enough, we could probably consider including it. 

...*if*.
