### ISSUE TITLE
Require Initial Value in Array.prototype.reduce()

### ISSUE THREAD

**Issue by jeppe-style** [palantir/tslint#4173]
### Rule Suggestion

When using `Array.prototype.reduce()` the `initialValue` parameter is optional. As per [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce#Description): "If the array is empty and no `initialValue` is provided, `TypeError` will be thrown." Therefore the suggestion is to provide a rule where the `initialValue` is required to be specified to avoid `TypeError`s being raised.

**Is your rule for a general problem or is it specific to your development style?**
It is a general problem that is likely to occur as the code grows.

**What does your suggested rule do?**
Requires `initialValue` to be specified when calling `Array.prototype.reduce()`

**List several examples where your rule could be used**
As per [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce#Description):
"It is usually safer to provide an initial value because there are three possible outputs without `initialValue`, as shown in the following example."

```
var maxCallback = ( acc, cur ) => Math.max( acc.x, cur.x );
var maxCallback2 = ( max, cur ) => Math.max( max, cur );

// reduce() without initialValue
[ { x: 22 }, { x: 42 } ].reduce( maxCallback ); // 42
[ { x: 22 }            ].reduce( maxCallback ); // { x: 22 }
[                      ].reduce( maxCallback ); // TypeError

// map/reduce; better solution, also works for empty or larger arrays
[ { x: 22 }, { x: 42 } ].map( el => el.x )
                        .reduce( maxCallback2, -Infinity );
```

Another example: when `reduce` is being called on an array passed in as a parameter, or injected (e.g.,  using [Redux](https://redux.js.org)), providing the `initialValue` parameter to `reduce` avoids having to check if the array is empty, however, that is easy to forget while coding.

```
function sumArray(values: number[]) {
    return values.reduce((a, b) => a + b);
}

sumArray([1,2]); // 3
sumArray([]); // TypeError

function sumArrayWithInitial(values: number[]) {
    return values.reduce((a, b) => a + b, 0);
}

sumArrayWithInitial([]); // 0
```

**Additional context**

**Comment by giladgray** [comment]
this is not an appropriate linter rule as it is far too specific to be generally useful -- pertaining to only one valid usage of one library function.

if you really want to enforce this in your codebase then write your own `reduce()` method that requires the `initialValue` arg and use the `ban` rule to prohibit use of `Array::reduce`.

**Comment by fkereki** [comment]
If this can be reconsidered, I just found problems in an existing code base, because of this problem; an ESLint rule would have avoided it.

**Comment by JoshuaKGoldberg** [comment]
@fkereki you might want to file an issue on ESLint itself; TSLint is deprecated and no longer accepting feature requests: #4534. ☠
