### ISSUE TITLE
Force all caps on comparing xyz.tagName with a string literal

### ISSUE THREAD

**Issue by lazarljubenovic** [palantir/tslint#4178]
### Rule Suggestion

**Is your rule for a general problem or is it specific to your development style?**

A general problem.

**What does your suggested rule do?**

It forces me to write all caps when comparing `tagName` with a string literal, or a template literal.

It laughs at me "lol you did it again" when I type:

```ts
if (document.activeElement.tagName == 'a')
```

and it autofixes to

```ts
if (document.activeElement.tagName == 'A')
```

**List several examples where your rule could be used**

```ts
document.activeElement.tagName == 'button'
document.activeElement.tagName == `button`
```

**Additional context**

> Why? Why is it not working? I've checked twice. I used a rubber duck. I told my problem to another developer. OK, `console.log` debugging time. Hmm. Nope. Why not? Debug time. Why?! Why!?!!? Oh. _Again._

**Comment by JoshuaKGoldberg** [comment]
Thanks for the write-up @lazarljubenovic - always good to see real-world examples of developers in pain who TSLint can help!

TSLint core tries to avoid platform- or library-specific rules, such as interacting with the DOM. If you're still interested in this issue, please file it on [`tslint-microsoft-contrib`](https://github.com/microsoft/tslint-microsoft-contrib) instead.
