### ISSUE TITLE
New rule suggestion: no-definitely-assigned-constructor-access

### ISSUE THREAD

**Issue by w0rp** [palantir/tslint#4179]
### Rule Suggestion

**Is your rule for a general problem or is it specific to your development style?**

This rule would be useful for anyone working with frameworks like AngularJS, which assign additional properties to objects after the `constructor()` is called.

**What does your suggested rule do?**

In combination with `--strictPropertyInitalization`, it would be nice to be able to enable a rule which emits warnings whenever a property which is asserted to be definitely assigned is accessed in a constructor. A common pattern for AngularJS code is to write something like this.

```ts
interface Bindings {
  someBinding: Foo
}

class Component implements Bindings {
  someBinding!: Foo

  constructor() {
    /* this.someBinding isn't ready yet here in Angular 1.6+ */
    this.someBinding // Emit an error here
  }

  $onInit(): void {
    /* this.someBinding can be used here, or in $onChanges. */
    this.someBinding // This is fine
  }
}
```

The same logic is applicable to any library which assigns additional attributes to objects after they have been constructed.

Let me know what you think. Maybe someone could come up with a better rule name.

**Comment by JoshuaKGoldberg** [comment]
@w0rp interesting idea, but it seems like it would be difficult to get right. Let's nail down in more detail how it could work and what the edge cases are. It could be that this kind of hard logic would be better suited for [`tslint-microsoft-contrib`](https://github.com/microsoft/tslint-microsoft-contrib).

**Comment by JoshuaKGoldberg** [comment]
Note: per #4534, this issue will be closed in less than a month if no PR is sent to add the rule. If you _really_ need the rule, custom rules are always an option and can be maintained outside this repo!

**Comment by w0rp** [comment]
Sure. I think this doesn't matter for TSLint now work is moving over to the ESLint plugin. I'll close this now.
