### ISSUE TITLE
Peer dependency complaint but I'm using typescript@3.1.0-dev.20180907

### ISSUE THREAD

**Issue by jpike88** [palantir/tslint#4184]

**Comment by JoshuaKGoldberg** [comment]
Related: #1556

In the meantime, should some 3.X peers be allowed?

**Comment by jpike88** [comment]
I'm guessing this discussion never got anywhere... this warning is beginning to drive me insane.

**Comment by JoshuaKGoldberg** [comment]
😢

Duplicate of #1556.
