### ISSUE TITLE
Indent before each chain function call.

### ISSUE THREAD

**Issue by RedTailBullet** [palantir/tslint#4186]
### Rule Suggestion

**Is your rule for a general problem or is it specific to your development style?**

It's a development style. However, I would reckon indent before a chain function call will contribute to the readability.

**What does your suggested rule do?**

Add indent in front of each chain function call.

**List several examples where your rule could be used**

```ts
database.query("user")
  .select(["name", "id"])
  .execute()
```

The current behavior is:

```ts
database.query("user")
.select(["name", "id"])
.execute()
```

**Additional context**

**Comment by JoshuaKGoldberg** [comment]
Unclear if this would be an addition to the `align` rule, part of `whitespace`, or its own rule. Also unclear whether TSLint itself should continue to invest in these: #3548 and friends.

**Comment by JoshuaKGoldberg** [comment]
Per #4534, closing this formatting rule request. If you _really_ need the rule, custom rules are always an option and can be maintained outside this repo!
