### ISSUE TITLE
fixer for no-consecutive-blank... should be run last

### ISSUE THREAD

**Issue by ozra** [palantir/tslint#4200]
- It seems like the fix isn't run last
- Other fixers remove for instance unused imports
- This may make previously separated blank lines adjacent / consecutive
- This alerts — despite that the no-cons-fixer should take care of it

Simply putting it  last / later should make it add up correctly.

**Comment by JoshuaKGoldberg** [comment]
This is a subset of #2556: Handle overlapping fixes.
