### ISSUE TITLE
A Generator similar to generator-eslint  will be very appreciated.

### ISSUE THREAD

**Issue by hsuehic** [palantir/tslint#4207]
### Feature request

**Describe the solution you'd like**
Best practice or templates for custom rule sets or custom rule. Help people to develop their own rule much easier.

https://github.com/eslint/generator-eslint

**Comment by JoshuaKGoldberg** [comment]
👏👏👏 Yes! This would be fantastic!

Now that TSLint itself has `--test`, there's not much configuration that would need to be done on top of a basic `tsconfig.json` + `tslint.json` + `package.json`.

**Comment by JoshuaKGoldberg** [comment]
Now that #4534 is tracking deprecation of TSLint, you'll likely be better off searching for such a tool in [typescript-eslint](http://typescript-eslint.io).
