### ISSUE TITLE
Can Tslint automatically delete unreferenced functions like the lint of the go language on save file?

### ISSUE THREAD

**Issue by muyu66** [palantir/tslint#4208]
Can Tslint automatically delete unreferenced functions like the lint of the go language on save file?

**Comment by JoshuaKGoldberg** [comment]
Yes, sort of. TSLint's `no-unused-variable` rule and TypeScript's `--noUnusedLocals` both support code fix actions (the little "apply fix" buttons in VS Code and other editors) that remove the unused things.

**Comment by muyu66** [comment]
@JoshuaKGoldberg 

it's cool.
I am using VSCODE, but neither of "editor.action.formatDocument" and "tslint.fixAllProblems" can automatically remove unused things,  just a hint that there is a problem.
