### ISSUE TITLE
Check if function name starts with lowercase.

### ISSUE THREAD

**Issue by lisemon** [palantir/tslint#4209]
### Rule Suggestion

**Is your rule for a general problem or is it specific to your development style?**
General

**What does your suggested rule do?**
Simply check if a function name starts with lowercase.

**List several examples where your rule could be used**
As a typescript novice, who usually works with C#, I remember this half  of the time.

**Additional context**
`public MyFunction(s: string) {
...
}`

**Comment by ajafff** [comment]
I have written a rule for fine-grained configuration of all kinds of identifiers in your code: https://github.com/ajafff/tslint-consistent-codestyle/blob/master/docs/naming-convention.md#examples

**Comment by lisemon** [comment]
thanks
