### ISSUE TITLE
whitespace check-module: missing in before import {x as y } not marked as error

### ISSUE THREAD

**Issue by mpsijm** [palantir/tslint#4210]
### Bug Report

- __TSLint version__: 5.11
- __TypeScript version__: 3.0.1
- __Running TSLint via__: CLI

#### TypeScript code being linted

```ts
import {x as y } from "z";
```

with `tslint.json` configuration:

```json
{
  "extends": [
    "tslint:recommended",
    "tslint-react"
  ],
  "jsRules": {},
  "rules": {
    "whitespace": [
      true,
      "check-module"
    ]
  },
  "rulesDirectory": []
}
```

#### Actual behavior

The missing whitespace before `x` is not marked as an error. Running the auto-fixer also does not fix this.

#### Expected behavior

The missing whitespace before `x` should be marked as an error.

Expected fix:
```ts
import { x as y } from "z";
```

**Comment by JoshuaKGoldberg** [comment]
Fixed by #4249! 🎉
