### ISSUE TITLE
[Rule Suggestion] Enforce trailing forward slash when importing from folder

### ISSUE THREAD

**Issue by ffflorian** [palantir/tslint#4212]
### Rule Suggestion

Enforce trailing forward slash when importing from folder and not stating the index file explicitly.

This can be helpful for the user to better distinguish if a module was imported from a file or from an index file in a folder.

**Negative example**
```ts
import { Foo } from '../bar';
```

**Positive example**
```ts
import { Foo } from '../bar/';
// or
import { Foo } from '../bar/index';
```

**Comment by JoshuaKGoldberg** [comment]
Duplicate of #2806
