### ISSUE TITLE
[Feature Request] --quiet flag for CLI

### ISSUE THREAD

**Issue by MarcusNotheis** [palantir/tslint#4218]
### Feature request

**Is your feature request that we implement a new rule?**
Please use the `Rule Suggestion` template instead

**Is your feature request related to a problem? Please describe.**
*We have some projects where we have set the severity of various rules to `warn`. Running `tslint` combines issues for severity `error` and `warn` which makes it harder to find the issues that are really errors.*

**Describe the solution you'd like**
*I would like to have `--quiet` flag the the CLI which will change the output to only emit errors.*

**Describe alternatives you've considered**
*I thought of using the output option and filter the generated file to only print errors, but I'm not that happy with that idea as we would have to manage this custom step in all projects.*

**Additional context**
*ESLint has implemented this feature: https://eslint.org/docs/user-guide/command-line-interface#handling-warnings*

**Comment by dawncold** [comment]
should close this issue as the feature had been merged on https://github.com/palantir/tslint/pull/4025
