### ISSUE TITLE
Disabling fixer for certain rules.

### ISSUE THREAD

**Issue by RedTailBullet** [palantir/tslint#4234]
### Feature request

**Is your feature request related to a problem? Please describe.**
When I set the fix when type on with the rule "prefer-const" on, it's a bit annoying that when I declare a variable using `let` and it got automatically turned into `const`, while it's not turned back again when I try to assign a new value to it.

**Describe the solution you'd like**
It's better that we are provided with options that enable us to disable fixer for certain rules or improve the fixer of the rule "prefer-const" and let it turn `const` into `let` when a new value is assigned to a `const` variable.

**Comment by JoshuaKGoldberg** [comment]
Related: #2625. 

Now that rules are under the new `"options": ...` format, we could have a `"fixEnabled"` boolean in there as well? 

As a hacky workaround while this is under discussion, you can always use a separate `tslint.fix.json` that only enables the rules you want to `--fix`.

**Comment by JoshuaKGoldberg** [comment]
Closing as #2625 has been declined. 😢
