### ISSUE TITLE
display rule name in error message

### ISSUE THREAD

**Issue by smollweide** [palantir/tslint#4236]
First of all thanks a lot for tslint 👍 

Something I struggling a lot is that the information about which rules creates the error is missing.
It would be great if the rule name is part of the error message:

*currently*
```
ERROR: Parentheses are prohibited around the parameter in this single parameter arrow function
```

*suggestion*
```
ERROR: Parentheses are prohibited around the parameter in this single parameter arrow function (arrow-parens)
```

That's how eslint did it and it's a really helpful information.

Thank you and best regards,
Simon

**Comment by JoshuaKGoldberg** [comment]
Yes, `-t verbose` or `-t stylish` would be a resolution for this.

#2228 tracks making that the default, if you're interested!
