### ISSUE TITLE
VSO formatter should report severity of rule violations

### ISSUE THREAD

**Issue by tklingert** [palantir/tslint#4248]
### Bug Report

- __TSLint version__: 5.11.0
- __TypeScript version__: 2.9.2
- __Running TSLint via__:  CLI

### VSO formatter
`tslint -p tsconfig.json -c tslint.json -t vso`

##vso[task.logissue type=**warning**;sourcepath=D:/dev/src/GET/cdm_frontend_WebUI/src/app/app.module.ts;linenumber=32;columnnumber=1;code=no-trailing-whitespace;]trailing whitespace

### Verbose formatter
`tslint -p tsconfig.json -c tslint.json -t verbose`

**ERROR**: (no-trailing-whitespace) D:/dev/src/GET/cdm_frontend_WebUI/src/app/app.module.ts[32, 1]: trailing whitespace

#### Expected behavior

VSO formatter doesn't apply hard-coded 'warning' severity too all issues:
[vsoFormatter.ts](https://github.com/palantir/tslint/blob/237fd905a9fb3c9ca9325d2da6e8145e4a44fe51/src/formatters/vsoFormatter.ts#L47)
[verboseFormatter.ts](https://github.com/palantir/tslint/blob/237fd905a9fb3c9ca9325d2da6e8145e4a44fe51/src/formatters/verboseFormatter.ts#L47)

**Comment by tcigrand** [comment]
I believe this is purposeful - https://palantir.github.io/tslint/formatters/vso/

**Comment by JoshuaKGoldberg** [comment]
Do VSO/TFS/VSTS/DevOps logging commands support different severities?

/cc @ian-craig, who's worked with them a bit more.

**Comment by tklingert** [comment]
@ian-craig According to the severity provided by the rule, yes.

e.g. 
> WARNING: .../bar.ts[18, 28]: HttpService is deprecated: use common/api-client/api-client-base instead (sample see common/permission/user-permission-service)
vs
> ERROR: .../foo.ts[10,11]: Type declaration of 'any' loses type-safety. Consider replacing it with a more precise type.

**Comment by JoshuaKGoldberg** [comment]
Removing the `Type: Breaking Change` label per #4811. Now accepting PRs!

**Comment by JoshuaKGoldberg** [comment]
#4286 was merged to address this 🙌
