### ISSUE TITLE
Cannot use same names for import, in different modules

### ISSUE THREAD

**Issue by Copainbig** [palantir/tslint#4257]
Hello there,
I am building a simple react/TS app, and am encountering issues with TSLint right now.
In 2 different modules I "`import * as React from 'react'`" and my IDE keeps yelling at me even though everything builds up and run like a charm.
 (here in GlobalForm.jsx and I do the same import in App.jsx.): 
![image](https://user-images.githubusercontent.com/8821701/47795368-bdef4000-dd22-11e8-928f-1cdd22912d21.png)

If I rename the "React" in my import, I am not bothered anymore.
Is it a bug or a feature I just don't get?

Here is my tslint.json : 
```
{
  "extends": ["tslint:recommended", "tslint-react", "tslint-config-prettier"],
  "linterOptions": {
    "exclude": [
      "config/**/*.js",
      "node_modules/**/*.ts",
      "coverage/lcov-report/*.js"
    ]
  },
  "rules": {
    "ordered-imports": false
  }
}

```
Thanks!

**Comment by JoshuaKGoldberg** [comment]
@Copainbig that's unfortunate! Sorry to see you're having weird errors pop up. 🙁

The error you're seeing isn't from TSLint; it's TypeScript. Four numbers prefixed by `"TS"` indicate it's a TypeScript diagnostic.

Closing this issue as external to TSLint, but if you'd still like some help with this, we can keep talking here or on https://gitter.im/palantir/tslint. What IDE are you using, and what are the full contents of that file? Have you tried restarting the IDE? What does your `tsconfig.json` look like?
