### ISSUE TITLE
auto-fixing invalid indent sizes

### ISSUE THREAD

**Issue by Ethan-Arrowood** [palantir/tslint#4262]
### Rule ~Suggestion~ Update to 'indent'

**Is your rule for a general problem or is it specific to your development style?**
This is something found in ESLint

**What does your suggested rule do?**
It will auto-fix invalid whitespace sizes

**List several examples where your rule could be used**
Similar to how prettier and eslint can be used to enforce an indent styling this will auto-fix whitespace counts

**Additional context**
Is a missing feature to the current rule [`indent`](https://palantir.github.io/tslint/rules/indent/)

**Comment by JoshuaKGoldberg** [comment]
@Ethan-Arrowood the `indent` rule already has auto-fixing when provided a desired indentation size. Is there some more fixing you'd like to see be able to happen?

Unrelated: changing the issue title to not seem to refer to the `whitespace` rule. 😉

**Comment by JoshuaKGoldberg** [comment]
Closing this issue for housekeeping, especially since TSLint core has been moving away from whitespace/formatting concerns (e.g. #2327) - but please do post again if there's more you need here!

Our general recommendation now is to use Prettier. TSLint itself isn't great at auto-fixing formatting.
