### ISSUE TITLE
Rule suggestion: pass-only-static-methods-by-name

### ISSUE THREAD

**Issue by KasMA1990** [palantir/tslint#4263]
### Rule Suggestion

**Is your rule for a general problem or is it specific to your development style?**
General

**What does your suggested rule do?**
Allows you to pass function A by reference as a callback, if and only if A is declared static. Does not preclude you from writing inline functions (arrow or not).

**List several examples where your rule could be used**

    class RequestHelper {
        /*...*/
        public static requestIsValid(request: SomeRequestType): boolean {
            return true;
        }
        public requestIsStateful(request: SomeRequestType): boolean {
             return this.someState;
        }
    }
    
    let validRequests1 = allRequests.filter(SomeClass.requestIsValid); // allowed; correct and concise
    let validRequests2 = allRequests.filter(req => SomeClass.requestIsValid(req)); // allowed; correct, but redundant

    let helper = new RequestHelper();
    let statefulRequests1 = allRequests.filter(helper.requestIsStateful); // disallowed; probably not correct
    let statefulRequests2 = allRequests.filter(req => helper.requestIsStateful(req)); // allowed; correct

**Additional context**
When passing a function as a callback, you can define a function inline, or you can pass reference to an existing function.
Passing a reference to an existing function can be risky because this changes the `this` for that function, which may not work as intended.
To be on the safe side, you can always wrap the call in an inline arrow function, but this is verbose for cases where it is not needed.

While it's probably not possible to vet if a function is completely safe to pass by reference, it should be possible to distinguish between static and non-static functions, where static functions are always safe to pass by reference.

**Comment by JoshuaKGoldberg** [comment]
👋 @KasMA1990, thanks for filing this! There's already a `no-unbound-method` rule, does that satisfy your use case?

**Comment by KasMA1990** [comment]
Hey @JoshuaKGoldberg, I think that exactly solves my issue; I just missed it because it didn't mention `static` on the rules page. Thanks!
