### ISSUE TITLE
It's not VSO or TFS or VSTS anymore; it's ✨DevOps✨

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [palantir/tslint#4269]
https://palantir.github.io/tslint/formatters/vso/

Formatter description here should mention all those names... 😂

**Comment by karthick-manoharan** [comment]
@JoshuaKGoldberg could you add some details?

**Comment by JoshuaKGoldberg** [comment]
Sure: TSLint documentation under the `vso` formatter still calls the service Visual Studio Online and Team Foundation Server. That should be updated to include the newer names for the service, namely VSTS (Visual Studio Team Services) and Azure DevOps.
