### ISSUE TITLE
Flag in rule metadata to mark legacy/discouraged rules

### ISSUE THREAD

**Issue by IllusionMH** [palantir/tslint#4290]
### Feature request

**Is your feature request related to a problem? Please describe.**
At this moment this repo contains `no-use-before-declare` rule that is

> generally discouraged and is kept around for legacy purposes

in its description that is visible only after click on rule name, however list of core rules doesn't have any indication.

**Describe the solution you'd like**
New metadata field like `notRecommended` and label "⚠Not recommended" or "⚠Legacy" in list.

**Describe alternatives you've considered**
Still add new field to metadata, but display such rules in separate section at the end of rules list (but without outstanding label).

**Additional context**
Are there other such rules?

This will also help with creation of recommended rule sets from other packages. Related issue: https://github.com/Microsoft/tslint-microsoft-contrib/issues/649

**Comment by JoshuaKGoldberg** [comment]
### 💀 _**It's time!**_ 💀

**TSLint is being deprecated** and no longer accepting pull requests for major new changes or features. See #4534. 😱

If you'd like to see this change implemented, you have two choices:
* **Recommended:** Check if this is available in [ESLint](https://eslint.org) + [typescript-eslint](https://typescript-eslint.io) ✅
* _Not Recommended: Fork TSLint locally_ 🤷‍♂️

👋 It was a pleasure open sourcing with you!

_If you believe this message was posted here in error, please comment so we can re-open the issue!_
