### ISSUE TITLE
TSLint is completely ignoring a directory

### ISSUE THREAD

**Issue by dwjft** [palantir/tslint#4292]
### Bug Report

- __TSLint version__: 5.11.0
- __TypeScript version__: 3.1.4
- __Running TSLint via__: (pick one) CLI

#### TypeScript code being linted

entire directory

with `tslint.json` configuration:

```json
{
  "extends": ["tslint:latest", "tslint-config-airbnb"],
  "rules": {
    "no-submodule-imports": false,
    "no-implicit-dependencies": false,
    "interface-over-type-literal": false,
    "max-line-length": false,
    "object-literal-sort-keys": false,
    "ordered-imports": false,
    "import-name": false,
    "align": false,
    "mocha-avoid-only": true,
    "trailing-comma": [
      true,
      {
        "esSpecCompliant": true
      }
    ]
  }
}

```

#### tsconfig.json

```json
  "include": [
    "test/**/*"
  ],
```

#### Actual behavior

    tslint -p tsconfig.json -t stylish
    > no output

#### Expected behavior

    tslint -p tsconfig.json -t stylish
    > lint error

For some reason, I can't get tslint to lint over my test directory. I can place any other directory structure in the `include` in my tsconfig and it'll work fine. I've even tried without a config and `tslint 'test/**/*'` which would work fine if it was `src/**/*`.

**Comment by dwjft** [comment]
A verbose option so we don't have to edit source code would be great! I spent a long time looking for that.

Interestingly, it seems the linter is finding the files but isn't actually pulling up any lint errors in those files.

The `Hello, world!` is being printed, and the file names are also being printed.

I removed the `src/` directory from my include path but the linter is still picking up files there. Is that because the linter follows file imports and scans them also?

```{  "fileName": "test/helpers/server.ts" }```

It found this and multiple other test files in there.

Rough layout for test:

```
test
- files
-- *.txt
- helpers
-- *.ts
```

tsconfig content:

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@test/*": ["./test/*"],
      "*": ["./src/*"]
    },
    "types": [
      "node",
      "mocha",
      "should"
    ],
    "typeRoots": [
      "./node_modules/@types",
      "./types"
    ],
    "lib": ["es2018"],
    "target": "es2018",
    "module": "commonjs",
    "noUnusedLocals": true,
    "inlineSources": true,
    "inlineSourceMap": true,
    "outDir": "build"
  },
  "include": [
    "src/**/*",
    "test/**/*"
  ],
  "exclude": [
    "build",
    "dist",
    "node_modules",
    "types",
    "config",
    "src/_scripts"
  ]
}
```

**Comment by dwjft** [comment]
```
"trailing-comma": [
      true,
      {
        "esSpecCompliant": true
      }
    ]```

It appears to be this rule causing an issue.

Even with just `trailing-comma: true` it does not pick up on these errors.

It seems that this rule has to be completely removed from `tslint.json` for it to work.

----

Looks like this bug is actually around that rule, then. Unfortunately my codebase is now stuck in limbo because I need the `esSpecCompliant` option to handle the conflicting `ts` and `tslint` rule errors.

**Comment by JoshuaKGoldberg** [comment]
> verbose option

Agreed, and great idea. `--verbose`? `--debug`? `--trace`? Would you like to file a separate issue with your thoughts on what you'd like to see in it? I can if not, but it'd be nice to fork into a separate discussion starting with what you're looking for.

> resolved the issue with the following rule

Well that's bizarre and unprecedented. Rule are run inside a `try`/`catch` so if it was throwing errors, you'd be getting nice stack traces... Any chance you could post & link your project here?

**Comment by dwjft** [comment]
I'll let you do the fork to kickstart that discussion if you're interested. I think the basic first version should just be those 2 commands you gave me to edit in to the file. `--verbose` just logging out to console those things would help immensely.

I can't post / link the project since it is private; but I'll go ahead and close this comment and reply to it after I re-produce it in a clean environment.

Thanks for your timely help / support.

**Comment by anasofiapaixao** [comment]
For anyone arriving here via google like I did, I was having a very similar issue. With no excludes configured, running
`tslint ./src/**/*.ts`
 worked, while running 
`tslint ./test/**/*.ts`
did not. I managed in my case to narrow down the problem to arbitrary depth wildcards, `**`, working like singular wildcards; the pattern was interpreted as `./folder/*/*.ts` and because the files in my `src` folder just happened to be at the right depth, the problem didn't manifest.

The workaround was [quoting the paths like this answer explains](https://stackoverflow.com/a/36456374/4719208). It seems that when the path is passed with quotes, it is handled with `node-glob` rather that natively by the OS and in this case this did the trick. So just change it to
`tslint './test/**/*.ts'`

with quotes.
