### ISSUE TITLE
Mark RuleWalker, ProgramAwareRuleWalker, and ScopeAwareRuleWalker as deprecated

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [palantir/tslint#4298]
Recapping #2522: `RuleWalker`-based rules are slow, so it's generally preferable to use `applyWithFunction` instead of `applyWithWalker`.

if folks shouldn't use `RuleWalker`, it would be good to actively encourage new PRs not to. TSLint could mark them as `@deprecated` in their doc comments and put `// tslint:disable-next-line:deprecation` with links to issue(s) tracking converting them to `walk` functions.

Edit: ~~Two~~Three thumbs up from over a month - marking as accepting PRs 😊

**Comment by adidahiya** [comment]
let's do this for 5.13.0. also need to update the relevant docs in docs/develop/custom-rules/index.md
