### ISSUE TITLE
Support valid-jsdoc natively

### ISSUE THREAD

**Issue by gpassero** [palantir/tslint#4300]
### Rule Suggestion

Add native support for [valid-jsdoc](https://github.com/buzinas/tslint-eslint-rules/blob/master/src/docs/rules/validJsdocRule.md) (or something alike).

**Is your rule for a general problem or is it specific to your development style?**
General problem. Right now we need to install an additional dependency (such as tslint-eslint-rules) to enable jsdoc validation.

**What does your suggested rule do?**
```
This rule enforces valid and consistent JSDoc comments. It reports any of the following problems:

- missing parameter tag: @arg, @argument, or @param
- inconsistent order of parameter names in a comment compared to the function or method
- missing return tag: @return or @returns
- missing parameter or return type
- missing parameter or return description
- syntax error
```
https://eslint.org/docs/rules/valid-jsdoc

**List several examples where your rule could be used**
Many examples can be found [here](https://eslint.org/docs/rules/valid-jsdoc).

**Additional context**
More information can be found in [tslint-eslint-rules](https://github.com/buzinas/tslint-eslint-rules/blob/master/src/docs/rules/validJsdocRule.md) and [eslint](https://eslint.org/docs/rules/valid-jsdoc) docs.

**Comment by JoshuaKGoldberg** [comment]
@gpassero agreed, that's a valuable rule. [`jsdoc-format`](https://palantir.github.io/tslint/rules/jsdoc-format) is the equivalent in TSLint core, though it doesn't capture quite everything in that list.

Accepting PRs for closing the feature gap.

**Comment by JoshuaKGoldberg** [comment]
☠️ *TSLint's time has come!* ☠️ 

TSLint is no longer accepting most feature requests per #4534. See **[typescript-eslint.io](https://typescript-eslint.io)** for the new, shiny way to lint your TypeScript code with **ESLint**. ✨ 

It was a pleasure open sourcing with you all!
