### ISSUE TITLE
member-ordering broke some code when using state

### ISSUE THREAD

**Issue by sibelius** [palantir/tslint#4303]
### Bug Report

- __TSLint version__: 5.11.0
- __TypeScript version__: 3.1.6
- __Running TSLint via__: CLI

member-ordering broke some code for me

I had `state` in my class below  `getValue` method

```jsx
state = {
    input: '',
    search: this.getValue() ? this.getValue().name : '',
    isFetching: false,
  };
```

so `member-ordered` moved `state` to the top and broke my code

#### Actual behavior

it moves state to the top

#### Expected behavior

it should keep state below `getValue` method inside class

**Comment by JoshuaKGoldberg** [comment]
### 💀 _**It's time!**_ 💀

**TSLint is deprecated** and no longer accepting pull requests other than security fixes. See #4534. ☠️ 
We recommend you instead use **[typescript-eslint](https://typescript-eslint.io)** to lint your TypeScript code with **ESLint**. ✅

👋 It was a pleasure open sourcing with you!
