### ISSUE TITLE
Allow customizing Rule.FAILURE_STRING by editing tslint.json

### ISSUE THREAD

**Issue by toasterpic** [palantir/tslint#4304]
### Feature request

**Is your feature request related to a problem? Please describe.**
When a rule is violated, the default Rule.FAILURE_STRING is emitted. That string does not include possible fixes, is not parameterized by rule parametrization, and a fixer won't do in case of more than one possible fix, or additional rules contradicting it's resulting fix.

**Describe the solution you'd like**
It would be great if one were able to add to Rule.FAILURE_STRING by parametrizing/customizing rules **in tslint.json**, which will also allow using project/team specific lingo.

**Describe alternatives you've considered**
At the moment it would seem one has to maintain a fork of tslint to override or extend rule behaviour (or implement complete custom ones), which may deter smaller teams.

**Additional context**
Use case:
Say 'export namespace ... {}' is banned by 'no-namespace' (where Rule.FAILURE_STRING  simply states "'namespace' and 'module' are disallowed"), but the rule was parameterized with "allow-declarations".
Ideally, the string would have taken that into account, or the rule offer a fix - any of said solutions currently require rebuilding from source where customizing the notification may be enough.

**Comment by JoshuaKGoldberg** [comment]
Interesting idea! There's some difficulty in the implementation details...

> When a rule is violated, the default Rule.FAILURE_STRING is emitted

This isn't completely accurate - many rules use have multiple possible error messages that could be printed. For example:
* `ban` has a `FAILURE_STRING_FACTORY` method
* `interface-name` has both `FAILURE_STRING` and `FAILURE_STRING_NO_PREFIX`

How would you propose those be overridden?

Maybe once the new `options` format is standardized and documented (#3100), rules can individually allow overrides in their options? Looks like this would have to be on a rule-by-rule basis, right?

**Comment by toasterpic** [comment]
Hi @JoshuaKGoldberg, good questions.
Going through the source again it would like the `FAILURE_STRING_NO_PREFIX` case is actually the exception, in fact being an entirely different (opposite) rule in disguise. If that is indeed the case, I would opt for adding a `interface-name-no-prefix` or something of the sort. 
I guess the issue there is the lack of some way to make sure enabled rules do not contradict one another (i.e., the configuration as a whole makes sense) which I alluded to, but that would be another discussion altogether.
`FAILURE_STRING_FACTORY` on the other-hand actually looks like a prime location to incorporate such customizations (design-pattern wise), these could be emitted according to some additional binary setting, selecting between overriding and appending.
And in any event, correct, this would be a rule-by-rule setup, with existing behaviour (modulo the `interface-name` case) as the default.

**Comment by giladgray** [comment]
👎 letting users edit error messages will break any hope of easy google support. the correct approach here is to submit a PR to improve the rule's message logic, as @JoshuaKGoldberg notes above.
