### ISSUE TITLE
Documentation for no-shadowed-variable isn't very clear

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [palantir/tslint#4306]
Following this http://bram-atmire.github.io/100daysofcode/2018/11/20/100-days-of-code-day-86-Angular-Testing.html from @bram-atmire, I agree that the two sentences + code snippet don't do a good job of explaining the rule.

We could borrow from the equivalent ESLint docs and/or come up with our own explanation. Either way, it'd be nice to better explain this rule.

**Comment by VincentLanglet** [comment]
@JoshuaKGoldberg Since the PR is merged, this issue should be closed, isn't it ?

**Comment by JoshuaKGoldberg** [comment]
Nice catch @VincentLanglet 😉 you're right!
