### ISSUE TITLE
configuration.findConfiguration problem

### ISSUE THREAD

**Issue by 979liyang** [palantir/tslint#4308]
There is a problem in configuration.js。
tslint.Configuration.findConfiguration('./tslint.json', file).results;
Always return all the rules, not the rules I defined.

**Comment by 979liyang** [comment]
deleted from  configuration.js,  Enforce the rules I defined.
`
 for (var _i = 0, _a = utils_1.arrayify(raw.extends); _i < _a.length; _i++) {
            var relativePath = _a[_i];
            var resolvedPath = resolveConfigurationPath(relativePath, dir);
            var extendedRaw = readConfig(resolvedPath);
            configs.push.apply(configs, loadExtendsRecursive(extendedRaw, path.dirname(resolvedPath)));
        }
`

**Comment by JoshuaKGoldberg** [comment]
Hey @979liyang thanks for submitting this bug report - but it's not clear what your issue is. Please post here:
* What was `results` before the 1775e4a3f221df3dd8447f93a9c040d6d8f65bec?
* What is `results` now?
* What are the contents of your `tslint.json`?

For example, here's the output I get for this `tslint.json`:

```json
{
    "rules": {
        "semicolon": true
    }
}
```

```shell
C:\Code\tstest  (tstest@1.0.0)
λ npm i tslint typescript tsutils
npm WARN tstest@1.0.0 No description
npm WARN tstest@1.0.0 No repository field.

+ tsutils@3.5.0
+ tslint@5.11.0
+ typescript@3.1.6
added 41 packages from 20 contributors, updated 1 package and audited 53 packages in 10.463s
found 0 vulnerabilities

C:\Code\tstest  (tstest@1.0.0)
λ node index.js
{ results:
   { extends: [],
     jsRules: Map {},
     linterOptions: {},
     rules: Map { 'semicolon' => [Object] },
     rulesDirectory: [] } }

C:\Code\tstest  (tstest@1.0.0)
λ npm link tslint
C:\Code\tstest\node_modules\tslint -> C:\Users\Dioge\AppData\Roaming\npm\node_modules\tslint

C:\Code\tstest  (tstest@1.0.0)
λ node index.js
{ results:
   { extends: [],
     jsRules: Map {},
     linterOptions: {},
     rules: Map { 'semicolon' => [Object] },
     rulesDirectory: [] } }
```

...which looks the same and correct both times.

**Comment by 979liyang** [comment]
> Hey @979liyang thanks for submitting this bug report - but it's not clear what your issue is. Please post here:
> 
> * What was `results` before the [1775e4a](https://github.com/palantir/tslint/commit/1775e4a3f221df3dd8447f93a9c040d6d8f65bec)?
> * What is `results` now?
> * What are the contents of your `tslint.json`?
> 
> For example, here's the output I get for this `tslint.json`:
> 
> ```json
> {
>     "rules": {
>         "semicolon": true
>     }
> }
> ```
> 
> ```shell
> C:\Code\tstest  (tstest@1.0.0)
> λ npm i tslint typescript tsutils
> npm WARN tstest@1.0.0 No description
> npm WARN tstest@1.0.0 No repository field.
> 
> + tsutils@3.5.0
> + tslint@5.11.0
> + typescript@3.1.6
> added 41 packages from 20 contributors, updated 1 package and audited 53 packages in 10.463s
> found 0 vulnerabilities
> 
> C:\Code\tstest  (tstest@1.0.0)
> λ node index.js
> { results:
>    { extends: [],
>      jsRules: Map {},
>      linterOptions: {},
>      rules: Map { 'semicolon' => [Object] },
>      rulesDirectory: [] } }
> 
> C:\Code\tstest  (tstest@1.0.0)
> λ npm link tslint
> C:\Code\tstest\node_modules\tslint -> C:\Users\Dioge\AppData\Roaming\npm\node_modules\tslint -> C:\Code\tslint
> 
> C:\Code\tstest  (tstest@1.0.0)
> λ node index.js
> { results:
>    { extends: [],
>      jsRules: Map {},
>      linterOptions: {},
>      rules: Map { 'semicolon' => [Object] },
>      rulesDirectory: [] } }
> ```
> 
> ...which looks the same and correct both times.

**Comment by 979liyang** [comment]
thank you JoshuaKGoldberg
In my definition have  "extends": "tslint:recommended", extends should be null.
Looking at the source code this morning I found out how to fix it.
