### ISSUE TITLE
Is there a rule to force class methods to be arrow functions?

### ISSUE THREAD

**Issue by Tsury** [palantir/tslint#4316]
`only-arrow-functions` does not care about class methods it seems.

**Comment by JoshuaKGoldberg** [comment]
Hi @Tsury, correct: such a rule or option does not exist. Would you want it to, and why?

When class methods are arrow lambdas, a new method is generated in each constructor call. That can become an undesirable performance bloat or confusing with `===` checks:

```typescript
class Foo {
    bar = () => {}
}
```

...is the equivalent of...

```javascript
var Foo = /** @class */ (function () {
    function Foo() {
        this.bar = function () { };
    }
    return Foo;
}());
```

_([typescriptlang.org/play link](http://www.typescriptlang.org/play/#src=class%20Foo%20%7B%0D%0A%20%20%20%20bar%20%3D%20()%20%3D%3E%20%7B%7D%0D%0A%7D))_

This seems like it might be an undesirable rule for many, so perhaps it might not belong in TSLint core.

**Comment by JoshuaKGoldberg** [comment]
Closing here for housekeeping. If you feel strongly this should be a rule, you can always create your own contributed ruleset and link it here. That'll let you create the rule and iterate without being locked into the TSLint release cycle.
