### ISSUE TITLE
Custom rule sets don't work

### ISSUE THREAD

**Issue by ArthurConan** [palantir/tslint#4317]
I use TSLint just to scan files ( not whole project)  with js or ts code there through command line.
I decided to implement rules:  "tslint-config-security","tslint-microsoft-contrib", "tslint-sonarts".
My steps: 
1) npm install tslint-microsoft-contrib
(npm install tslint-config-security)
(npm install tslint-sonarts)
2) include to extends
 "extends": ["tslint:recommended", "tslint-config-security","tslint-microsoft-contrib", "tslint-sonarts", ],
3) include path to rules
"rulesDirectory": ["node_modules/tslint-microsoft-contrib", "node_modules/tslint-config-security/dist/rules","node_modules/tslint-sonarts/lib/rules"],
4) all necessary rules are TRUE
5) and run
tslint folder/file.js

WHY these rules don't work?? 
I just get errors with common TSLint rules such:  "Forbidden 'var' keyword, use 'let' or 'const' instead", "non-arrow functions are forbidden" and so on
And don't get error such  "no-document-domain", "no-document-write" (these functions ARE in files)
WHAT am I doing wrong?

Thanks in advance!!!!!!

**Comment by JoshuaKGoldberg** [comment]
Hi @ArthurConan! This issue tracker is generally used for filing bugs or feature requests on TSLint itself. Community rules are working pretty well in other projects so this is likely a call for help better suited for [StackOverflow with the `tslint` tag](https://stackoverflow.com/questions/tagged/tslint) or the [palantir/tslint Gitter.im channel](https://gitter.im/palantir/tslint). 

One suggestion: it's hard to diagnose errors with the amount of details you've given. If you're still having problems using custom rules, please post there with some way to show your exact project files, such as (even preferably) a link to a public repository.
