### ISSUE TITLE
How do I disable tslint warnings tslint.json 

### ISSUE THREAD

**Issue by xyz92** [palantir/tslint#4320]
### Bug Report

- __TSLint version__: 5.11.0
- __TypeScript version__: 2.4.2

How do I disable the following 2 tslint warnings:

Warning - tslint: error typedef: expected arrow-parameter: 'item' to have a typedef
Warning - tslint: error no-string-literal: object access via string literals is disallowed

**Comment by JoshuaKGoldberg** [comment]
Hi @ArthurConan! This issue tracker is generally used for filing bugs or feature requests on TSLint itself. This looks like a call for help better suited for [StackOverflow with the `tslint` tag](https://stackoverflow.com/questions/tagged/tslint) or the [palantir/tslint Gitter.im channel](https://gitter.im/palantir/tslint). 

One suggestion: it's hard to diagnose errors with the amount of details you've given. If you're still having problems using custom rules, please post there with some way to show your exact project files, such as (even preferably) a link to a public repository.

**Comment by JoshuaKGoldberg** [comment]
Hi @xyz92! This issue tracker is generally used for filing bugs or feature requests on TSLint itself. This looks like a call for help better suited for [StackOverflow with the `tslint` tag](https://stackoverflow.com/questions/tagged/tslint) or the [palantir/tslint Gitter.im channel](https://gitter.im/palantir/tslint). 

One suggestion: it's hard to diagnose errors with the amount of details you've given. If you're still having problems using custom rules, please post there with some way to show your exact project files, such as (even preferably) a link to a public repository.

**Comment by xyz92** [comment]
@JoshuaKGoldberg Thanks!
