### ISSUE TITLE
Provide fix for == to ===

### ISSUE THREAD

**Issue by grosch** [palantir/tslint#4330]
### Feature request

The vast majority of the time your lint rule for replace == with === is the correct thing to do.  Please provide an autofix for it so that an IDE, like PhpStorm, can take care of it for us.

**Comment by JoshuaKGoldberg** [comment]
@adidahiya does this require #2625 to be resolved first (adding in something like a `--fix-unsafe`)?

**Comment by adidahiya** [comment]
@JoshuaKGoldberg yeah, it probably does, good catch

**Comment by giladgray** [comment]
this feels generally very risky. we already have a fixer for `!= null` and `!== undefined`.

**Comment by Magrangs** [comment]
I am also interested in this. What would be the risks involved?

**Comment by JoshuaKGoldberg** [comment]
Closing as #2625 has been declined. 😢
