### ISSUE TITLE
Suggestion: add a --debug option to the CLI

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [palantir/tslint#4334]
### Feature request

**Is your feature request related to a problem? Please describe.**

See discussion in https://github.com/palantir/tslint/issues/4292. In working with @dwjft trying to narrow down where a rule was failing, part of the investigation involved manually going into `node_modules/tslint` and modifying .js files. That seems a little silly to ask users to do.

> Also, to help see where in the `tslint` command things are going wrong, can you add these logs to the `node_modules/lib/linter.js` file under the `tslint` package _(you might have to use `which`/`where` to find its location)_ and post the result here?
> * Last line of the file: `console.log("Hello, world!");` _(just to make sure it's being run)_
> * Line 95, first line of `Linter.prototype.lint`: `console.log({ fileName });`

**Describe the solution you'd like**

If `--debug` mode is provided, how about dumping all output to a file _and_ marking when various important methods such as `Linter.prototype.lint` are started?

```shell
tslint --debug # outputs to tslint.debug.log
tslint --debug my-logs.log
```

Perhaps a request for `tslint.debug.log` contents could be added to the Bug report issue template?

**Describe alternatives you've considered**

`--verbose` could be confusing given the naming overlap with `-t verbose`.

Maybe also outputting to the screen? But it's rare that debug-level outputs are actually desirable on the screen _(right?)_; they're generally best as outputs.

**Comment by adidahiya** [comment]
+1 for a `tslint.debug.log` file

**Comment by JoshuaKGoldberg** [comment]
### 💀 _**It's time!**_ 💀

**TSLint is being deprecated** and no longer accepting pull requests for major new changes or features. See #4534. 😱

If you'd like to see this change implemented, you have two choices:
* **Recommended:** Check if this is available in [ESLint](https://eslint.org) + [typescript-eslint](https://typescript-eslint.io) ✅
* _Not Recommended: Fork TSLint locally_ 🤷‍♂️

👋 It was a pleasure open sourcing with you!

_If you believe this message was posted here in error, please comment so we can re-open the issue!_
