### ISSUE TITLE
tslint autofix is not removing unused imports

### ISSUE THREAD

**Issue by ajain17** [palantir/tslint#4337]
### Bug Report

- __TSLint version__:5.11.0
- __TypeScript version__:3.2.1
- __Running TSLint via__: (pick one) **CLI**

#### TypeScript code being linted
Following is an unused import
```ts
import Actions from "../Actions/ActionTypeKeys"; 
```

with `tslint.json` configuration:
I didn't add no-unused-variable here since it was deprecated. I instead have this option in my tsconfig.json
```json
   "noUnusedLocals": true /* Report errors on unused locals. */,
```

#### Actual behavior
When I run ```tslint -p ./tsconfig.json -c ./tslint.json --fix``` it doesn't autofix or even report the unused import in my file. Though the VSCode editor shows this as being an unused import:
![image](https://user-images.githubusercontent.com/5581487/49414174-4fd5d880-f727-11e8-8f58-6b392fcf550e.png)

#### Expected behavior
When I run ```tslint -p ./tsconfig.json -c ./tslint.json --fix``` it should auto remove the unused import.

**Comment by JoshuaKGoldberg** [comment]
Hi @ajain17!

> I didn't add no-unused-variable here since it was deprecated. I instead have this option in my tsconfig.json

> ```json
>   "noUnusedLocals": true /* Report errors on unused locals. */,
> ```

Yup, since you're not using the deprecated TSLint rule and relying on TypeScript's `noUnusedLocals`, TypeScript is what should be removing those imports. VS Code should give you a suggested action with the lightbulb to remove them:

![image](https://user-images.githubusercontent.com/3335181/49414318-d094d480-f727-11e8-8ca3-860a06b3d842.png)

This is powered by TypeScript, so if it's not working for you, you'll want to file an issue on them. Thanks!

**Comment by ajain17** [comment]
@JoshuaKGoldberg  the lightbulb option is there but the tslint --fix command doesn't remove the unused import. Is that the expected behavior while using the tsconfig? How can I automate removal of such unused imports then?

**Comment by scott-ho** [comment]
@JoshuaKGoldberg Since Microsoft/TypeScript#14549 is fixed now, there is typescript support for those auto fixing. Is there a change we could integrate it into tslint?

**Comment by JoshuaKGoldberg** [comment]
@scott-ho unlikely that that API would change much here. #4100's discussion is on how to enable using language service APIs altogether; the new API in that issue is another example of those.

**Comment by JimLynchCodes** [comment]
@JoshuaKGoldberg

I agree with the other users here- the current way things are is absolutely _**not good.**_

running ts-lint with the `--fix` option should remove unused imports from the project.

**Comment by adidahiya** [comment]
@JimLynchCodes TSLint is deprecated, see #4534. Any feature requests you have for a lint rule to remove unused imports should be raised in typescript-eslint or eslint-plugin-import.
