### ISSUE TITLE
New Release ( waiting for backtick )?

### ISSUE THREAD

**Issue by jas99** [palantir/tslint#4340]
I have been waiting for #4029 and its in master but there has not been release for while now.
Any ideas about next release?

Thx

**Comment by ShayBox** [comment]
That's fair, it has been 5 months since the last release, also waiting for that pr's feature but i'm sure there are a lot of other ones I don't know about.

**Comment by JoshuaKGoldberg** [comment]
@jas99 @ShayBox @iclanton @nickpape-msft 5.12.0 is available now! 🎉

#4074 tracks discussions around the release process.
