### ISSUE TITLE
Restore original only-arrow-functions rule by making 'this' exception optional

### ISSUE THREAD

**Issue by Antony74** [palantir/tslint#4341]
### Rule Option Suggestion

Should the only-arrow-functions rule permit or fail the following code?

```
setTimeout(function() { 
    this.oops(); 
}, 500);
```

Once upon a time only-arrow-functions meant only arrow functions (versions 3.12.0 to 4.5.1 inclusive, rule first released June 2016).  Then #2229 came along (version 5.0.0 released March 2017) and the rule was altered to allow traditional functions containing the `this` keyword to pass.  This seems more than a little incongruous with the stated rationale of the rule:

> Traditional functions don’t bind lexical scope, which can lead to unexpected behavior when accessing ‘this’.

The current rule does not guard against unexpected behavior when accessing 'this' (all it does is enforce the arrow function aesthetic against non-error-prone uses of traditional functions).

Can we have the original rule back please!

Obviously #2229 was a legitimate feature request which satisfied a genuine need, so perhaps the best way to bring back the original only-arrow-functions rule is as an option to the current rule?  The option could be called no-this-exception.

**Is your rule option for a general problem or is it specific to your development style?**

The desire to keep code free of traditional functions due to the difficulty in seeing what the `this` keyword is bound to and the annoyance of having to bind it is a general problem.  However there are some development styles that attempt to put the `this` keyword to good use for which this proposed option is not suitable.  The best known example of this is the JQuery library with which you will frequently be writing callbacks utilizing a `this` keyword bound for you by JQuery.  

**List several examples where your rule option could be used**

```
class MyClass {

  hello() {
    console.log('hello');
  }

  myFunction() {
    setTimeout(function() {
      this.hello();
    }.bind(this), 500); 
  }

}
```

**Additional context**

Originally reported as a bug (#4314), and I'm not entirely convinced it isn't, but it looks a little less like a bug now I've updated the documentation (#4336)

**Comment by JoshuaKGoldberg** [comment]
@Antony74 this is a great writeup. Thanks for adding the context!

Following #4314, this seems reasonable as a rule option. A couple of questions:
* TypeScript's [`--noImplicitThis`](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#--noimplicitthis) will catch unsafe `this` references - maybe it would be good to mention that in the rule's docs?
* Should this be opt-in or opt-out?

The rule hasn't shipped, so it wouldn't be a breaking change to make it opt-out (on by default).

**Comment by Antony74** [comment]
Thanks, I didn't know about `--noImplicitThis`.  I look forward to playing with it at some point.

If the only-arrow-functions rule hadn't shipped, then I would be all for making this on by default.  That would be more intuitive because only-arrow-functions could mean only arrow functions, and there'd be an option to make functions containing `this` an exception.  However, my understanding was that this horse has already left the stable:

> # Change Log
>
> ## v5.0.0
>
> -   [enhancement] `only-arrow-functions` allow functions that use `this` in the body (#2229)

**Comment by JoshuaKGoldberg** [comment]
Oh, yes - good catch 😄

**Comment by Antony74** [comment]
`--noImplicitThis` is a very good workaround thanks, except that it appears to be an error that can either by switched on or off.  To clean up a sizeable code-base over time requires a warning, thus the full workaround is a bit too involved:

1. Switch on `--noImplicitThis`
2. Litter the code with // @ts-ignore comments to make the errors go away
3. Wait for the ban-ts-ignore rule to ship (#3728)
4. Switch that on as a warning
5. Clean up the code-base over time

**Comment by JoshuaKGoldberg** [comment]
Yeah not a great story right now. #4215 tracks `--noImplicitAny`; in theory it should also be doable for `--noImplicitThis`.

**Comment by JoshuaKGoldberg** [comment]
☠️ *TSLint's time has come!* ☠️ 

TSLint is no longer accepting most feature requests per #4534. See **[typescript-eslint.io](https://typescript-eslint.io)** for the new, shiny way to lint your TypeScript code with **ESLint**. ✨ 

It was a pleasure open sourcing with you all!
