### ISSUE TITLE
Value of a rule's ruleArguments varies when unset in config

### ISSUE THREAD

**Issue by mogzol** [palantir/tslint#4348]
### Bug Report

- __TSLint version__: 5.11.0
- __TypeScript version__: 2.9.2
- __Running TSLint via__: N/A

While fixing some configuration tests (#4346) I noticed that when no arguments are specified for a rule in a config, the value assigned to the rule's ruleArguments property varies. For example, the old-style boolean configurations result in ruleArguments being an empty array, while the normal config format results in ruleArguments being undefined (when empty).

#### Actual behavior

When ruleArguments are not defined in the config, they get set to either `[]` or `undefined` depending on the format of the config.

#### Expected behavior

When ruleArguments are not defined in the config, a common default value should be assigned to them, such as `[]`

**Comment by JoshuaKGoldberg** [comment]
### 💀 _**It's time!**_ 💀

**TSLint is deprecated** and no longer accepting pull requests other than security fixes. See #4534. ☠️ 
We recommend you instead use **[typescript-eslint](https://typescript-eslint.io)** to lint your TypeScript code with **ESLint**. ✅

👋 It was a pleasure open sourcing with you!
