### ISSUE TITLE
Suggest a new rule 'no-plusplus'

### ISSUE THREAD

**Issue by loveonelong** [palantir/tslint#4354]
It like eslint:
no-plusplus: ["error", { "allowForLoopAfterthoughts": true }]

Resean:
1、Because the unary ++ and -- operators are subject to automatic semicolon insertion, differences in whitespace can change the semantics of source code.
2、`a++` or `++a` is difficult to understand sometimes.

Refrence:
EN: resean-1
http://eslint.cn/docs/rules/no-plusplus
CN: resean-2
http://www.yinwang.org/blog-cn/2013/03/15/language-design-mistake1

**Comment by JoshuaKGoldberg** [comment]
You're in luck, @loveonelong! That rule already exists in [tslint-microsoft-contrib](https://github.com/microsoft/tslint-microsoft-contrib). 

#1142 tracks migrating rules from there into TSLint core. For now you'll want to follow the instructions in tslint-microsoft-contrib to use the rule.

**Comment by loveonelong** [comment]
thx

**Comment by loveonelong** [comment]
> You're in luck, @loveonelong! That rule already exists in [tslint-microsoft-contrib](https://github.com/microsoft/tslint-microsoft-contrib).
> 
> #1142 tracks migrating rules from there into TSLint core. For now you'll want to follow the instructions in tslint-microsoft-contrib to use the rule.

thx
