### ISSUE TITLE
no-object-literal-type-assertion should allow unknown type

### ISSUE THREAD

**Issue by NN---** [palantir/tslint#4355]
### Feature request

**Is your feature request related to a problem? Please describe.**
There is 'as any' exception for the rule. #2716
With the new unknown type there should be exception for 'as unknown' as well.

**Describe the solution you'd like**
Add exception for 'as unknown'.

**Comment by JoshuaKGoldberg** [comment]
Agreed, thanks for bringing this up @NN---! This should be doable along with #4356.

**Comment by NN---** [comment]
I'll try with PR 
My goal is to remove all "any"s in the code and replace them with "unknown"s.

**Comment by NN---** [comment]
The only problem is that tests cannot be written since they require 'unknown' keyword which presents only in TS 3.0

**Comment by JoshuaKGoldberg** [comment]
@NN--- you can get around the issue with something like:

```typescript
(ts.SyntaxKind as any).UnknownKeyword
```
