### ISSUE TITLE
Got different result between using global and inline npm script

### ISSUE THREAD

**Issue by pea3nut** [palantir/tslint#4358]
I found tslint is work correctly when I use command:

    tslint -c tslint.json --project tsconfig.json 'src/**/*.ts'

But when I moved it to npm script, I found it seems don't read `tslint.json`.

My package.json like:

    {
      "name": "short-night",
      "scripts": {
        "tslint": "tslint -c tslint.json --project tsconfig.json 'src/**/*.ts'"
      },
      "devDependencies": {
        "ts-lint": "^4.5.1",
        "tslint": "^5.11.0",
        "tslint-config-airbnb": "^5.11.1",
        "typescript": "^2.9.2",
      },
      "dependencies": {
      }
    }

[There][1] is my project.

  [1]: https://github.com/FoXZilla/short-night/blob/stackoverflow-lint/package.json#L8

**Comment by JoshuaKGoldberg** [comment]
Hi @pea3nut - remove the `'`s from the command and it should work. Generally you don't need to manually pass file paths to the `tslint` command if you also pass a `--project`, as it'll pick up paths from the project.

```diff
- "tslint": "tslint -c tslint.json --project tsconfig.json 'src/**/*.ts'",
+ "tslint": "tslint -c tslint.json --project tsconfig.json src/**/*.ts",
```

Are you on Windows, by any chance? I'm going to close this as I suspect the files just aren't being passed to tslint. If this is actually a bug in the file name parsing someone can post here again and we could accept a PR.

**Comment by pea3nut** [comment]
I have removed the `'`, but it still works incorrectly. @JoshuaKGoldberg 

Did you download & run [my project](https://github.com/FoXZilla/short-night/blob/stackoverflow-lint/package.json#L8) and it works very well in your computer?

I used the MacOS:

![image](https://user-images.githubusercontent.com/13781420/49784340-e887dc00-fd57-11e8-84d7-52bbe9bcafd6.png)

**Comment by JoshuaKGoldberg** [comment]
Yup, I downloaded and ran it. Seems like a dup of #4360.

Maybe TSLint isn't correctly handling `'`s?

**Comment by giladgray** [comment]
@pea3nut quoting globs prevents the shell from expanding them for you. it's possible that tslint then won't expand them itself (not sure of the internals). 

so unquoted globs are the preferred way to write them, as the terminal itself will expand it and pass the full array to the command.

**Comment by pea3nut** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/13781420/49849217-7ecd0800-fe13-11e8-853f-777050f2dd32.png">

@Aqours Got difference too.

**Comment by pea3nut** [comment]
<img width="787" alt="image" src="https://user-images.githubusercontent.com/13781420/49851764-16832400-fe1d-11e8-969e-03cc8216e54e.png">

I installed global and local tslint in one day.

My local tslint is working incorrectly that is the actual question. It's likely doesn't read `tslint.json`.

I have set the indent to 2, but tslint still error me `Expected indentation of 2 spaces but found 4.`

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/13781420/49852595-885c6d00-fe1f-11e8-8e7c-3672ff7f3dc2.png">

**Comment by giladgray** [comment]
Sorry that comment above is wrong.

Look, just use the local version and call it a day. Don't install Dev tools globally for the reasons I noted above.

**Comment by pea3nut** [comment]
@giladgray But the local tslint is working incorrectly. The globally is correct.

**Comment by johnwiseheart** [comment]
@pea3nut you said above:

`I have set the indent to 2, but tslint still error me: Expected indentation of 2 spaces but found 4.`

This means that you have code with an indent of 4 but you have set tslint to 2 so its giving you an error. That seems to be working correctly.

**Comment by pea3nut** [comment]
I'm sorry that I mean is I [have set indent to 4](https://github.com/FoXZilla/short-night/blob/stackoverflow-lint/tslint.json#L5). But got the error `Expected indentation of 2 spaces but found 4.`

**Comment by pea3nut** [comment]
My mistake, see https://stackoverflow.com/questions/53694592/tslint-got-different-result-between-using-global-and-inline-npm-script/53791763#53791763

Maybe tslint should emit an error when it can't find the "extends" from the config file.

**Comment by JoshuaKGoldberg** [comment]
@pea3nut that one was because they were using an old duplicate package named `ts-lint` published by someone else instead of `tslint`. `ts-lint` looks like a 2 year old copy of `tslint`, though I haven't checked if it has extra features _(or [bitcoin thievery](https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident))_.

/cc @ericanderson as FYI
