### ISSUE TITLE
Lint multiple globs

### ISSUE THREAD

**Issue by mikefrancis** [palantir/tslint#4360]
I have a `next.js` TypeScript project which has a file structure like the following:

```
root/
├── pages/
│   ├── index.tsx
│   ├── _document.tsx
├── components/
│   ├── Header.tsx
│   ├── Footer.tsx
```

I want to point TSLint to look for any `.ts` or `.tsx` files in either of these directories but an having trouble figuring out the glob (or if it's possible?).

So far I have tried:

```
tslint 'pages/**/*.ts?(x) components/**/*.ts?(x)'
tslint 'pages/**/*.ts?(x),components/**/*.ts?(x)'
tslint '{components|pages}/**/*.ts?(x)'
tslint '(components|pages)/**/*.ts?(x)'
```

But none of them work. If I try a single directory, for example:

```
tslint 'pages/**/*.ts?(x)'
```

It works perfectly.

I can't find anyone having the same issue and I cannot modify the directory structure as next.js requires the `/pages` dir.

Any help would be appreciated 😄

**Comment by JoshuaKGoldberg** [comment]
😕 this works for me using normal wildcards _(albeit on Windows)_ with a simplified version of your directory structure. Odd. Is this `next.js` project something you can post a link to here, so I can try it out locally?

```shell
C:\Code\tstest  (tstest@1.0.0)
λ tslint "src/a/*.ts?(x)" "src/b/*.ts?(x)"

ERROR: src/a/a.ts:1:1 - Forbidden 'var' keyword, use 'let' or 'const' instead
ERROR: src/b/b.ts:1:1 - Forbidden 'var' keyword, use 'let' or 'const' instead
```

_(relevant Twitter thread: https://twitter.com/_mikefrancis/status/1072136071302053888)_

**Comment by mikefrancis** [comment]
Hmm, just tried a slight variation on your version and it works! Very strange.

Thanks for taking a look, will close this 😄
