### ISSUE TITLE
Custom formatters are not used if they have the same name as built in formatters

### ISSUE THREAD

**Issue by spikyjt** [palantir/tslint#4363]
### Bug Report

- __TSLint version__: 5.11.0
- __TypeScript version__: 3.2.1
- __Running TSLint via__: CLI

#### TypeScript code being linted
(N/A)
```ts
// code snippet
```

with `tslint.json` configuration:

```json
{
  "defaultSeverity": "warning",
  "extends": [
    "tslint:recommended",
    "tslint-eslint-rules"
  ],
  "linterOptions": {
    "exclude": [
      "node_modules/**"
    ]
  },
  "rules": {
    "one-line": false,
    "brace-style": [ true, "allman", { "allowSingleLine": false } ],
    "quotemark": [ true, "single" ],
    "space-before-function-paren": [ true, "always" ],
    "no-unused-expression": [ true, "allow-new" ],
    "object-literal-shorthand": [ true, "never" ],
    "ter-func-call-spacing": [ true, "never" ],
    "ter-padded-blocks": [ true, { "classes": "always" } ],
    "no-console": false
  }
}
```

#### Actual behavior
Even with formatters-dir specified on the CLI, the built in formatters are used with preference to custom ones. This means plugins such as tslint-junit-formatter cannot be used.

#### Expected behavior
Customer formatter should be used even if it has the same name as a built in one, because the formatters-dir has been specified explicitly.

**Comment by spikyjt** [comment]
Just to clarify I used the following command:
```sh
tslint --project ./tsconfig.json --formatters-dir ./node_modules/tslint-junit-formatter/formatters --format junit
```

In case someone says "who cares? there is already a built in junit formatter, why do you need another?" this module has a feature I need that the built in one doesn't (which I will also submit here as a feature request).

**Comment by JoshuaKGoldberg** [comment]
Seems reasonable, thanks for pointing this out @spikyjt! Although it's a breaking change, it's one users have to opt into and can easily remove, so it seems fine to accept PRs for now.

**Comment by LekoArts** [comment]
@spikyjt 	Do you mean this feature? https://github.com/palantir/tslint/issues/3744
I also need that :/
