### ISSUE TITLE
Extending formatters to include ending position when available

### ISSUE THREAD

**Issue by rocky** [palantir/tslint#4386]
### Feature request

**Is your feature request related to a problem? Please describe.**

I see that only in the json formatter, there is provision for an end location. It would be helpful if other formatters or new formatters were extended to include ending position when that is available.

**Describe the solution you'd like**

In https://github.com/eslint/eslint/issues/11176 I discuss some possiblities for extending the "stylish" format. 

**Describe alternatives you've considered**

Finding a package that has provision for this. Or writing a custom formatter that isn't contributed back but just used in the tool I am working on.

**Comment by JoshuaKGoldberg** [comment]
@rocky what would you want to use this end position information for? The formatters such as `stylish` intentionally omit the end position because, in addition to the points nzakas made in the linked thread, it's not really necessary for most users. For most use cases it's wasted space on the terminal.

The JSON formatter does have an end location because, unlike most other formatters, it's intended for consumption by code.

**Comment by rocky** [comment]
> it's not really necessary for most users

I find it helpful obviously since that's why I mentioned it. 

How does one determine that it is not necessary for most users? Is the column number necessary for most users? Decades ago this level of precision wasn't around and people got by. So how is it that nowadays that we are comfortable with adding a starting column position, but insist that this clearly is enough, even when more detail is available? 

> The JSON formatter does have an end location because, unlike most other formatters, it's intended for consumption by code.

The argument _against_  extending in the link cited is that it might mess up tools that parse the output. In other words, in some cases that output is consumed by code. And one of the points of this project is that the output format is the way it is so it can be parsed to position editors at the point of error. 

Conceivably those tools that parse this could also make use of the end location. The editor I use is able to highlight a region of code.

**Comment by JoshuaKGoldberg** [comment]
> I find it helpful obviously since that's why I mentioned it.

Lol, yes, but _why_ is it helpful? What about the output becomes easier when you also have the ending position?

> How does one determine that it is not necessary for most users? 

Excellent question. I certainly don't have the ability to answer it. But - generally, TSLint and other CLIs tend to try to keep output as information-dense as possible. In theory we could add loads of information that's not there now, but it would make it harder for users to visually scan through the output and see what's relevant. Unless there's a documented reason why something is worth the visual space, it's probably not worth putting it in.

I don't intend these responses to be blunt arguments against adding it in, by the way. There just should be a good, documented reason why changes are justified before these happen.

**Comment by rocky** [comment]
> but why is it helpful? What about the output becomes easier when you also have the ending position?

If you look at my github projects you'll see I have worked a lot on both debuggers and precise location reporting. Why? Well, because I make a _lot_ of mistakes. I don't do this as a (very labor intensive) academic excercise. 

So I guess I have a particular insight into this that perhaps others don't.The reason an error message is an error message is because it is, well,  _unexpected_ or suprising. So yes, you could give me the starting spot and maybe for a number of situations that would be enough. But as someone who makes a lot of mistakes I might make a mistake in understanding the thing you are talking about too.  Here is a contrived example. Suppose I get this error

```
Type error

      x = a * b + c
          ^
``` 

I look and see that _a_ and _b_ are both let say integers so I don't get it. But suppose the error was that _c_ is a string.  Well if you had something like 

```
Type error

      x = a * b + c
          ^^^^^^^^^
``` 

as opposed to: 

```
Type error

      x = a * b + c
          ^^^^^
``` 

that would more clearly indicate that we were talking about the expression of a*b with c. 

Let me give another analogy. In English prepositions are often used and that is good enough for most people. But for some there can still be confusion. A number of jokes are based on switching the meaning of what prepositions refer to. 

Therefore, avoiding prepositions while not necessary for most people, is helpful for some. And this leads me to what feels like a little bit of hypocracy given that tslint is in the linting business. 

A number of the linting rules are based on this kind of principle like I just mentioned where you should aviod the use of a preposition because it might confuse someone. Specifically there are rules involving the use a consistent indenting scheme or when optional semicolons and commas are not needed or should be used. If I understand this correctly the motivation behind that is to reduce the possibilty of any extra cognative effort or the possibility of a confusion. 

But when it comes to how the linting tool reports what's there is now this different point of view, well, it's good enough for most people to figure what I mean. 

Now as for the extra verbiage in giving a range. You could get by with an additional 2-4 characters which would cover most of the cases.  So instead o 12:4 for "line 12 column 4" you might have 12:4.6 to mean "line 12 column 4", for a length of 6 characters.

**Comment by JoshuaKGoldberg** [comment]
It sounds like the problem you're trying to address is that the `stylish` reporter isn't precise enough for some errors. Is that common from what you've seen?

Would the [`codeFrame`](https://palantir.github.io/tslint/formatters/codeFrame/) reporter do it for you?

```
src/components/Payment.tsx
Parentheses are required around the parameters of an arrow function definition (arrow-parens)
  21 |     public componentDidMount() {
  22 |         this.input.focus();
> 23 |         loadStripe().then(Stripe => Stripe.pay());
     |                          ^
  24 |     }
  25 |
  26 |     public render() {
```

...or do you want something between the conciseness of `stylish` and the specificity of `codeFrame`?

Alternately, how would you propose the stylish formatter's output be changed?

**Comment by rocky** [comment]
It is about precision, not the format used to show location. An interval conveys more information than a single positon does. 

> Alternately, how would you propose the stylish formatter's output be changed?

Both here and in the link I suggested possibilities. The simplest and shortest one is to add a dot followed by a length of characters. For example: 12:4.6 would  mean "line 12 column 4", for a length of 6 characters.  I think I have seen this used elsewhere. However if there is existing art that is more widely used, I'd go with that instead. 

I haven't focused on that part because it doesn't make sense to investigate this when there has already been this much resistance over its inclusion.

**Comment by johnwiseheart** [comment]
I think if there are specific errors you’re coming up against that are unclear without an interval, that is probably a failure on the rule description. 

As mentioned in the eslint issue, any changes to formatters at this point would be a breaking change. Perhaps a change like #3783 may be helpful here, in making it easier to use your own formatter?

Also happy to leave this open to see what the community thinks - if there’s sufficient support then we may want to look into making this change in a future major version.

**Comment by johnwiseheart** [comment]
In your example, you would also have a starting character, no? That should give you a pretty good place to start looking. 

To note: I'm not necessarily against the change - just that it's a big one to make, and I don't want to make that decision lightly.

You mentioned that you're writing a parser of some type. Is there a reason you can't use the JSON formatter? I assume this is what the vscode react plugin uses, as it is able to highlight the full width of the error. It's not intended that any of the other formatters should be read programmatically, if that was your intention.

All of that said, if the current selection of formatters still doesn't meet your needs, I think the best bet is probably to develop one yourself, and if we receive substantial community support for this change, we can consider merging it in to TSLint.

**Comment by JoshuaKGoldberg** [comment]
> the best bet is probably to develop one yourself, and if we receive substantial community support for this change, we can consider merging it in to TSLint.

☝️ that!
