### ISSUE TITLE
Add code coverage

### ISSUE THREAD

**Issue by adidahiya** [palantir/tslint#439]
We could even get a fancy coverage % badge via https://coveralls.io/

**Comment by ashwinr** [comment]
+1 for coveralls + istanbul

**Comment by leeavital** [comment]
It looks like istanbul works by hooking into require() statements to differentiate between external libraries and testable code. I'm going to wait on doing this until  #465 (ES6 modules) is done.

**Comment by adidahiya** [comment]
hmm that shouldn't be the case; we were able to set up Istanbul on front end projects that don't use `require()` imports. But I'm also totally cool with doing the module conversion first.

**Comment by adidahiya** [comment]
https://coveralls.io/github/palantir/tslint

**Comment by adidahiya** [comment]
we're pretty good on this front now.
