### ISSUE TITLE
Rule suggestion: max-methods-per-class

### ISSUE THREAD

**Issue by goktugyil** [palantir/tslint#4417]
### Rule Suggestion

**Is your rule for a general problem or is it specific to your development style?**

General

**What does your suggested rule do?**

max-methods-per-class

**List several examples where your rule could be used**

Example: We have a file with 1 class and under the maximum line length limit. But it has 50 methods doing various tasks, making the class too complex

https://softwareengineering.stackexchange.com/a/177102/118745

**Comment by goktugyil** [comment]
https://github.com/palantir/tslint/issues/3228 also suggested here

**Comment by JoshuaKGoldberg** [comment]
Yup, this is a duplicate (subset) of #3228. Thanks for suggesting & the link!
