### ISSUE TITLE
Rule interface-name: Change the default value

### ISSUE THREAD

**Issue by VincentLanglet** [palantir/tslint#4418]
Since the introduction of the 'never-prefix' option here (https://github.com/palantir/tslint/issues/512) it's seems to be agreed by everyone that the I prefix is not a good practice for TS (https://github.com/palantir/tslint/issues/1520)

The rule will be removed from tslint:recommended (https://github.com/palantir/tslint/pull/4312) but is still active in tslint:all

What about simply change the default value from 'always-prefix' to 'never-prefix' ?

**Comment by JoshuaKGoldberg** [comment]
> it's seems to be agreed by everyone that the I prefix is not a good practice for TS (#1520)

Alas, not so ☹. The option was added because some folks and projects prefer it, but there isn't a single agreed-upon good practice. 

Since #4312 already exists and this request is a subset of #4305, closing this issue as duplicate.
