### ISSUE TITLE
Run typed rules on .js files

### ISSUE THREAD

**Issue by samclearman** [palantir/tslint#4419]
### Feature request

**Is your feature request related to a problem? Please describe.**
I have a project which mostly consists of .js files, which we run through tsc with the checkJs option.  It would be nice to be able to run the typed rules on these files.

**Describe the solution you'd like**
In linter.js If I just change `var isJs = /\.jsx?$/i.test(fileName);` to `var isJs = false;` I get the behavior that I want for my project (the only rule I've tried is `no-floating-promises`).  I guess what I want is that isJs is determined not by file extension but by whether the typescript compiler is getting run on a file.

**Comment by jbwyme** [comment]
I'm having a related issue: https://github.com/palantir/tslint/issues/4422

I think if tslint simply deferred to whatever files are matched by tsc, it would make life better.

**Comment by JoshuaKGoldberg** [comment]
### 💀 _**It's time!**_ 💀

**TSLint is being deprecated** and no longer accepting pull requests for major new changes or features. See #4534. 😱

If you'd like to see this change implemented, you have two choices:
* **Recommended:** Check if this is available in [ESLint](https://eslint.org) + [typescript-eslint](https://typescript-eslint.io) ✅
* _Not Recommended: Fork TSLint locally_ 🤷‍♂️

👋 It was a pleasure open sourcing with you!

_If you believe this message was posted here in error, please comment so we can re-open the issue!_
