### ISSUE TITLE
Rule suggestion: collapsible-if

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [palantir/tslint#4427]
### Rule Suggestion

**Is your rule for a general problem or is it specific to your development style?**

General problem

**What does your suggested rule do?**

Identifies nested if statements that can be combined into one.

**List several examples where your rule could be used**

Instead of:

```typescript
if (foo) {
    if (bar) {
        // ...
    }
}
```

Prefer:

```typescript
if (foo && bar) {
    // ...
}
```

See https://github.com/ajafff/tslint-consistent-codestyle/blob/master/docs/no-collapsible-if.md

**Additional context**

Spinning off of #2040: moving some rules of tslint-consistent-codestyle to tslint core.
Note that as ajafff mentioned, copied code without substantial changes needs to retain the original license.

**Comment by armano2** [comment]
rules like this are implemented for tslint and eslint already by @SonarSource

https://www.npmjs.com/package/tslint-sonarts
https://github.com/SonarSource/eslint-plugin-sonarjs

**Comment by JoshuaKGoldberg** [comment]
Closing in favor of the linked typescript-eslint issue.
