### ISSUE TITLE
Rule suggestion: unnecessary-else

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [palantir/tslint#4429]
### Rule Suggestion

**Is your rule for a general problem or is it specific to your development style?**

General problem

**What does your suggested rule do?**

If an if block contains a return, throw, continue or break statement, the else block becomes unnecessary. Its contents can be placed outside of the block.

**List several examples where your rule could be used**

Instead of:

```typescript
if (foo) {
    throw new Error();
} else {
    // ...
}
```

Prefer:

```typescript
if (foo) {
    throw new Error();
}

// ...
```

See https://github.com/ajafff/tslint-consistent-codestyle/blob/master/docs/no-unnecessary-else.md

**Additional context**

Spinning off of #2040: moving some rules of tslint-consistent-codestyle to tslint core.
Note that as ajafff mentioned, copied code without substantial changes needs to retain the original license.

**Comment by debsmita1** [comment]
I am working on tis at the moment. Do let me know if there is something that I should keep in mind. :)

**Comment by debsmita1** [comment]
@JoshuaKGoldberg Could you kindly review this PR and tell me where am I going wrong ? :)
