### ISSUE TITLE
Rule suggestion: padding-line-between-statements

### ISSUE THREAD

**Issue by Ivanca** [palantir/tslint#4435]
### Rule Suggestion

https://eslint.org/docs/rules/padding-line-between-statements

**Comment by JoshuaKGoldberg** [comment]
Also tracked in https://github.com/buzinas/tslint-eslint-rules/issues/361.

TSLint core is somewhat moving away from these whitespace/stylistic rules (#3548) - it's unclear now whether this rule should land here or in tslint-eslint-rules.

**Comment by glen-84** [comment]
Not everyone wants to [use Prettier](https://github.com/palantir/tslint/issues/2814#issuecomment-373062865), and having to pull in another dependency like `tslint-eslint-rules` is not always possible/ideal.

**Comment by Ivanca** [comment]
Everything in tslint/eslint is stylistic: the semicolons rules, the template strings over concatenation so singling out spacing is unexpected and weird; the one reason to use tslint/eslint is to have consistency across the code base.

**Comment by adidahiya** [comment]
> Absolutely everything in tslint/eslint is stylistic

I disagree with this; we have multiple rule categories which are not "style" or "formatting": https://palantir.github.io/tslint/rules/

As per #4534, I'm going to close this and avoid adding new code formatting rules to TSLint core. If you want to enforce this specific check with tslint, it can live happily in a custom rule set outside this repo.
