### ISSUE TITLE
[Feature Request] Allow to specify tsc version in tslint:disable

### ISSUE THREAD

**Issue by MaceWindu** [palantir/tslint#4464]
### Feature request

**Is your feature request related to a problem? Please describe.**
I want to have an option to temporary disable part of tslint functionality based on version of tsc used. 

Why:

E.g. I have some code, that violates project's tslint policy, but this code exists to workaround bug in typescript, which expected to be fixed in next version. I wan't tslint to be silent about it for current tsc version and start to complain, when I will update tsc dependency. This will tell me that I need to check this place and remove workaround or update ignored tsc version, if issue is not fixed.

So basically, you don't need to track issue externally somehow, you will be pinged automatically, when there are chances, that situation changed.

**Describe the solution you'd like**
Looking at [current syntax](https://github.com/palantir/tslint/blob/master/docs/usage/rule-flags/index.md) for tslint directive, I think something like optional version parameter (don't think version ranges needed for this feature):
```
// tslint:disable-next-line(tsc:VERSION)
// tslint:disable(tsc:VERSION)
or if it will not conflict with rules parsing
// tslint:disable-next-line:ver-VERSION
// tslint:disable:ver-VERSION
```

**Describe alternatives you've considered**
Well, my current alternative is to mark code with tslint:disable:<rule> and then somehow remember to check it on next update (todo list, bugtracker, etc)

**Additional context**
Nope

**Comment by adidahiya** [comment]
This feature feels out of scope for tslint and relatively high-effort to design correctly & maintain. I think we'd implement #4264 first before something like this. Does this feature exist in other linters or code analysis tools? I'm declining this request for now but will leave this issue open to see if there is broad community interest in it.

**Comment by JoshuaKGoldberg** [comment]
5 months later... 😢
