### ISSUE TITLE
no-unnecessary-callback-wrapper fixer dont ignore keywords

### ISSUE THREAD

**Issue by Shinigami92** [palantir/tslint#4466]
### Bug Report

- __TSLint version__: ^5.12.0
- __TypeScript version__: 3.2.2
- __Running TSLint via__: ALL

#### TypeScript code being linted

```ts
// code snippet
observable.pipe(switchMap(i => of(i)))
//                        ~~~~~~~~~~
```

with `tslint.json` configuration:

`no-unnecessary-callback-wrapper`

#### Actual behavior

Wants to fix to
```observable.pipe(switchMap(of))```

#### Expected behavior

Ignore js keywords

**Comment by JoshuaKGoldberg** [comment]
@Shinigami92 what is `of`? The rule's implementation seems to ignore keywords.

Running in a Chrome devtools console:

```js
let a = 3;
let b = of(a);

VM164:2 Uncaught ReferenceError: of is not defined
    at <anonymous>:2:9
```

**Comment by Shinigami92** [comment]
@JoshuaKGoldberg https://github.com/ReactiveX/rxjs/blob/master/src/internal/observable/of.ts

**Comment by JoshuaKGoldberg** [comment]
Gotcha. Why wouldn't you want `switchMap(of)` over `switchMap(i => of(i))`, then? It's not a keyword, just a function commonly exported from rxjs.

**Comment by Shinigami92** [comment]
.-. strange, now I tested it again and its working...
maybe it was related to another mistake?!
