### ISSUE TITLE
Allow Line comment in tslint.json

### ISSUE THREAD

**Issue by sokcuri** [palantir/tslint#4484]
If Line comment is present in tslint.json, the following error occurs.
```js
SyntaxError: D:\repo\noname\tslint.json: Unexpected token / in JSON at position 2895
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:707:27)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```
https://github.com/Microsoft/TypeScript/blob/master/tslint.json

I have noticed that copying tslint.json from the Microsoft Typescript repository will cause an error. I think there will be enough cases to write line comment during development.

The JSON specification does not officially support Line comment, so I get the above error, but I would like to be able to comment on line.

**Comment by JoshuaKGoldberg** [comment]
@sokcuri very much agreed! I typically do write inline comments in `tslint.json`, so you getting an error there is a bit confusing. How are you running TSLint, and what version are you using? For example, on the command line, or via an IDE extension?
https://github.com/palantir/tslint/blob/master/tslint.json itself has comments.

**Comment by adidahiya** [comment]
As @JoshuaKGoldberg mentioned, TSLint itself already supports comments in `tslint.json`, so this issue is external to TSLint. For other config file format requests, see https://github.com/palantir/tslint/issues/1721 and #1071

**Comment by sokcuri** [comment]
I have figured out why this is happening. The package.json below is the npm script where the error occurred.

```json
"scripts": {
  "lint": "node tslint 'src/**/*.{ts,tsx}'"
}
```

The node is excluded, so it works normally. tslint is not installed globally.
Depending on whether you're attaching a node or not, it's operating inconsistent.
