### ISSUE TITLE
Meta-feature request: do not think of compiler options as equivalent to tslint options

### ISSUE THREAD

**Issue by estaub** [palantir/tslint#4485]
### Meta-feature request

I do not want to treat lint-level errors as fatal prior to publish, and thus decisions that 

> Nobody needs rule A in tslint because there's tsc compiler option `--no-A`; rule A should therefore be deprecated.

assume a style of usage that is not mine.  I sometimes need to keep flow state to deal with the big picture, and forcing lint-level errors to be immediately fixed is disruptive to that.

I don't have any idea how many folks are in the same place.  

If tsc had a "warning" feature, and IDE's understood it, I wouldn't care.

**Comment by adidahiya** [comment]
That's fair, I think there are many other users of TSLint who like to use it in the same way as you.

Is there a specific compiler-option-lint-option equivalency you are concerned with? For `no-unused-variable`, there has already been a lot of discussion in other threads: https://github.com/palantir/tslint/issues/4100

**Comment by estaub** [comment]
I thought there were more, but it looks like `no-unused-variable` is the only one.

**Comment by adidahiya** [comment]
Closing in favor of #4100, but I'm open to re-opening if there is further discussion about other rules
