### ISSUE TITLE
Force color output

### ISSUE THREAD

**Issue by pronebird** [palantir/tslint#4499]
### Bug Report

- __TSLint version__: 5.12.1
- __TypeScript version__: 3.2.4
- __Running TSLint via__: CLI

#### Actual behavior

Running tslint with `tslint -t stylish -p . | less -r` on macOS Terminal does not emit the coloured output. Although `tsc` suffers from a similar issue, it supports the `--pretty` option that allows to force the color output.

#### Expected behavior

Color output works in terminal

**Comment by JoshuaKGoldberg** [comment]
### 💀 _**It's time!**_ 💀

**TSLint is being deprecated** and no longer accepting pull requests for major new changes or features. See #4534. 😱

If you'd like to see this change implemented, you have two choices:
* **Recommended:** Check if this is available in [ESLint](https://eslint.org) + [typescript-eslint](https://typescript-eslint.io) ✅
* _Not Recommended: Fork TSLint locally_ 🤷‍♂️

👋 It was a pleasure open sourcing with you!

_If you believe this message was posted here in error, please comment so we can re-open the issue!_
