### ISSUE TITLE
[Question] How to debug custom rule with vscode?

### ISSUE THREAD

**Issue by alxpsr** [palantir/tslint#4532]
Hi there!
I create custom rule for tslint, but i have some troubles for debugging my new rule. Can you explain me about right rule debugging?

**Comment by JoshuaKGoldberg** [comment]
Hi @alxpsr! Awesome that you're developing a custom rule! In general, you should be able to use [VS Code to debug](https://github.com/Microsoft/vscode-recipes/tree/master/nodemon).

If you still have questions on that, it like the [Gitter channel](https://gitter.im/palantir/tslint) would be a better avenue to discuss.
