### ISSUE TITLE
react-ssr-friendly

### ISSUE THREAD

**Issue by cyberhck** [palantir/tslint#4550]
### Rule Suggestion

**Is your rule for a general problem or is it specific to your development style?**
This is a general purpose rule which actually should be enabled by default IMO (but that can be discussed later)

**What does your suggested rule do?**
It should check few methods in react projects, constructor, getDerivedStateFromProps, componentWillMount (deprecated), render (maybe more? We can list them later), and see if the code will be able to run in node env, it won't be perfect, but can we blacklist few things to be used there.

Example would include: document, window, localStorage (other types of browser storage etc)

**List several examples where your rule could be used**
I could enable this rule and later if project decides to use server side rendering, thanks to this rule, we'd have avoided those refactoring awkwardness.

**Additional context**
Not sure entirely, I've not written a lot of rules (just maybe around 3-4), let's discuss and see if we can proceed, if I get some time, I could also send a PR.

**Comment by JoshuaKGoldberg** [comment]
👋 @cyberhck, great idea! But: this repository is just for core rules that aren't tied to particular frameworks. You'll want to file a request in [tslint-react](https://github.com/palantir/tslint-react), or failing that, [eslint-plugin-react](https://github.com/yannickcr/eslint-plugin-react).

You could also publish this as a standalone package on npm if you don't want to be tied into their release cycles.

**Comment by cyberhck** [comment]
can we move this issue to maybe tslint-react? since it's same organization, I think there's a feature to do that now in gh
