### ISSUE TITLE
custom rule for specific files/folder

### ISSUE THREAD

**Issue by yantrab** [palantir/tslint#4570]
Hi, i wont to create custom rule that fit only for models. 
So, any suggestion how can i do that?
rule config should look like:

        "no-property-without-decorator":{
            "options": {
                "paths": [
                    "path/to/models1"
                ],
                "files":["*/**model.ts"]
            }
        }

**Comment by JoshuaKGoldberg** [comment]
Hi @yantrab! It's a little unclear what you're asking here. Are you...

* ...asking for help implementing a custom rule?
* ...trying to change which rules are applied to certain files?
* ...trying to do something else?

**Comment by Akuukis** [comment]
@yantrab create another `tslint.json` file in your subfolder and it will take precedence over the one in root folder.

**Comment by JoshuaKGoldberg** [comment]
😢. Please do post here if you're still interested!
