### ISSUE TITLE
a prameter to CLI to run a check only for a few selected rules

### ISSUE THREAD

**Issue by aleksey-bykov** [palantir/tslint#4571]
### Feature request

**Is your feature request that we implement a new rule?**
No

**Is your feature request related to a problem? Please describe.**
Unable to run a check for one single rule.

**Describe the solution you'd like**
Add a parameter to CLI that allows running a one single rule (or few rules) by their names.

**Describe alternatives you've considered**
Disabling all rules in tslint.json except a few.

**Comment by JoshuaKGoldberg** [comment]
Hi @aleksey-bykov - how about having multiple configuration files? You could either:
* have standalone files with just the rules you want enabled separate from your main `tslint.json`
* have files that extend from your main `tslint.json` or each other

Given that TSLint is slowly being deprecated, it's tempting to just close this as a use case mostly satisfied by that workaround.

**Comment by aleksey-bykov** [comment]
can you explain why/how it is getting deprecated?

**Comment by JoshuaKGoldberg** [comment]
Sure: https://github.com/palantir/tslint/issues/4534

**Comment by adidahiya** [comment]
This looks close to #3447, and as @JoshuaKGoldberg mentioned, we're reluctant to add new configuration features to TSLint because of #4534.

**Comment by aleksey-bykov** [comment]
understood
