### ISSUE TITLE
Add import declaration in fix. 

### ISSUE THREAD

**Issue by yantrab** [palantir/tslint#4572]
Hi, someone can help me with [that](https://stackoverflow.com/questions/55059203/how-to-add-import-when-fix-by-ts-lint)?

I have custom rule that need import when fix.

I found way to do that by replace all file, but then fix all not working.(maybe because is async ?)

```
            fix =
                new Lint.Replacement(node.getSourceFile().getStart(),
                    node.getSourceFile().getWidth(), fileLines.join('\n'))
```

**Comment by JoshuaKGoldberg** [comment]
👋 @yantrab - that would be a very nice thing to figure out, but unfortunately it's outside the scope of TSLint. Let's hope your SO post gets traction!
