### ISSUE TITLE
Rule suggestion: semi-spacing

### ISSUE THREAD

**Issue by cwgorman** [palantir/tslint#4592]
### Rule Suggestion

We have some code with an extra space before the semicolon, and I'd like to disallow that. eg,
```ts
const a = 2;
const b = 3 ;
```

ESLint has a rule covering this: [semi-spacing](https://eslint.org/docs/rules/semi-spacing). It has quite a few options though, so I'd be fine with even just the older [no-space-before-semi](https://eslint.org/docs/rules/no-space-before-semi) if that proves hard to implement.

Thanks!

**Is your rule for a general problem or is it specific to your development style?**

**What does your suggested rule do?**

**List several examples where your rule could be used**

**Additional context**

**Comment by adidahiya** [comment]
unfortunately have to decline this, see #4534
