### ISSUE TITLE
Remove old npm package `ts-lint`

### ISSUE THREAD

**Issue by wasserholz** [palantir/tslint#4611]
### Feature request

**Is your feature request that we implement a new rule?**
No

**Is your feature request related to a problem? Please describe.**
`ts-lint` npm package is easily confused with `tslint` npm package

**Describe the solution you'd like**
Remove `ts-lint` npm package from register. Only serve `tslint` npm package.

**Describe alternatives you've considered**
Mark `ts-lint` npm package as obsolete and consider deleting it in the future.

**Additional context**
`tslint` npm - https://www.npmjs.com/package/tslint
`ts-lint` npm url - https://www.npmjs.com/package/ts-lint

**Comment by adidahiya** [comment]
That's not our package and we don't control its publishing, but thanks for bringing it to our attention. We might be able to ask NPM to take it down since it's a confusing, deceptive, and potentially malicious package (it doesn't link to its source code).

**Comment by wasserholz** [comment]
Thanks for taking action. It was linking to your github repository, so I expected it to be closely related.

**Comment by adidahiya** [comment]
that repository link is determined by whatever someone puts in the `repository` field in `package.json`, so it can be easily faked. don't rely on it.
