### ISSUE TITLE
Usage of no-parameter-properties

### ISSUE THREAD

**Issue by ShadabFaiz** [palantir/tslint#4612]
### Rule Suggestion
**no-parameter-properties** if set to true, then 
``` typescript

 // This will be invalid
class SomeClass {
    constructor(public someVar: number) {} 
}
```
however, in angular, we do require in some of our class's constructor to have parameters to use services.

**Is your rule for a general problem or is it specific to your development style?**
General

**What does your suggested rule do?**
Does not conflict with angular rules

**List several examples where your rule could be used**
``` typescript
export class SomeClassComponent {
    constructor(private service: SomeService) {}
 }
```

**Comment by JoshuaKGoldberg** [comment]
Hi @ShadabFaiz! You can always disable a rule in your `tslint.json`. https://palantir.github.io/tslint/usage/configuration/

Personally, I like parameter properties in code that uses [InversifyJS](https://github.com/inversify/InversifyJS).
