### ISSUE TITLE
Rules Documentation cut off after `Format` heading

### ISSUE THREAD

**Issue by erichiller** [palantir/tslint#4620]
### Bug Report
This is limited to the tslint website, no tslint version required, tried a few days ago, and today. I ended up just reading the rules files from GitHub.

I'd expect to see rules such as
`typedef-whitespace` displayed on the [rules doc](https://palantir.github.io/tslint/rules/). Instead it ends right after the `Format` header.

**Comment by ClarenceL** [comment]
Yea was looking for `semicolon`, Ctrl+F confused me greatly, please fix.

**Comment by komputerwiz** [comment]
Per @Tschrock on https://github.com/palantir/tslint/pull/4638#issuecomment-482268051:

> Looking at the current website, it doesn't seem to have updated with this fix yet. Is there something else that needs to happen before it goes live?

It seems this issue has not yet been resolved. My gut feeling is that the `gh-pages` branch needs to be updated.

**Comment by adidahiya** [comment]
Should be fixed now.

**Comment by komputerwiz** [comment]
Just verified. Thanks, @adidahiya!

And thanks for the great work! I don't know how I would manage to do my work without tslint! 😁
