### ISSUE TITLE
member-access doesn't work for getters and setters

### ISSUE THREAD

**Issue by snebjorn** [palantir/tslint#4631]
### Bug Report

- __TSLint version__: 5.15.0
- __TypeScript version__: 3.3.3
- __Running TSLint via__: VSCode

#### TypeScript code being linted

```ts
export class FooClass {
  set foo(bar) {
  }
  get foo() {
  }
}
```

with `tslint.json` configuration:

```json
'member-access': true
```

#### Actual behavior
No linting error is given for getter/setters.
Also the fixer doesn't auto-fix this, or even suggest a change.

#### Expected behavior
A linting error should be shown for getters/setters and the fixer should suggest a fix.

**Comment by adidahiya** [comment]
There is a rule option for this, it is not enabled by default. It's probably not a default because we didn't want to make it a breaking change when adding that option. https://palantir.github.io/tslint/rules/member-access/

**Comment by snebjorn** [comment]
I see, thanks for the help
