### ISSUE TITLE
[Question] Formatting configuration

### ISSUE THREAD

**Issue by CyberMew** [palantir/tslint#4636]
Is it possible to format code like this so that beginning indents in subsequent lines are removed for interfaces/classes and braces are shifted to a new line:
```
export interface ISomeParamA
  extends ISomeParamB {
  ...
}
```
becomes 
```
export interface ISomeParamA
extends ISomeParamB
{
  ...
}
```
Same for class with extends and implements:
```
export class MyClassThatAlsoHaveAVeryLongName
  extends MyBaseClassWithAVeryLongName
  implements ISomeInterfaceDefinitionWithAVeryLongName {
```
to
```
export class MyClassThatAlsoHaveAVeryLongName
extends MyBaseClassWithAVeryLongName
implements ISomeInterfaceDefinitionWithAVeryLongName
{
```

And for multi-line formatted ternary operator, from the default behaviour:
```
this.animatedValue = new Animated.Value(
  props.selected
    ? SELECTED_FRAME
    : DESELECTED_FRAME,
);
```
to
```
this.animatedValue = new Animated.Value(
    props.selected ?
        SELECTED_FRAME
    :
        DESELECTED_FRAME,
);
```

I am using Prettier with tslint to format document. How would I go about formatting to our style?

**Comment by adidahiya** [comment]
Nope, tslint doesn't support that kind of formatting (it might go in the `align` rule if it did), and we don't plan to add it. See #4534
