### ISSUE TITLE
testNext is broken in CI builds

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [palantir/tslint#4644]
Oh no! 😱

Example failure: https://circleci.com/gh/palantir/tslint/13978

`test/rules/no-inferred-empty-object-type/test.ts.lint` is no longer creating some complaints it used to be expected to.

**Comment by ericbf** [comment]
I dug into this – those types are now inferred as unknown instead of {} according to the type checker. Recommendations? Disable test/rule at the versions below where they start inferring as unknown? Or modify the rule to disallow inferring {} *and* unknown? Or make another rule for unknown?

**Comment by ericbf** [comment]
Obviously since they are now inferred as unknown, they fail (or pass 😎) the rule's check to see if they are inferred as {} (empty object).
