### ISSUE TITLE
Wrong JSDoc for "no-unused-variable" rule

### ISSUE THREAD

**Issue by knafteN** [palantir/tslint#4659]
### Bug Report

- __TSLint version__: 5.11.0
- __TypeScript version__: 3.1.6
- __Running TSLint via__: (pick one) CLI

#### Actual behavior
The JSDoc for "no-unused-variable" says "Three optional arguments may be optionally provided:"

#### Expected behavior
The JSDoc for "no-unused-variable" says "**Two** optional arguments may be optionally provided:" and the schema only validates two optional parameters

**Comment by JoshuaKGoldberg** [comment]
Heh, good catch...
