### ISSUE TITLE
Better documentation around linting rules/options (especially TypeScript-specific rules)

### ISSUE THREAD

**Issue by Kyle-Muir** [palantir/tslint#467]
Not sure if this is the right place to raise this, however, the documentation for the linting is fairly light in comparison to, say, jshint\eslint. For a lot of the rules it's no big deal because they are fairly self explanatory - e.g. `curly` enforces braces around `if`,`else`,`do`,`while` statements.

Taking the `curly` example, on the documentation it is stated like this: 

> `curly` enforces braces for `if`/`for`/`do`/`while` statements.

JSHint docs explains the same rule as:

> This option requires you to always put curly braces around blocks in loops and conditionals. JavaScript allows you to omit curly braces when the block consists of only one statement, for example:
> 
> while (day)
>   shuffle();
> However, in some circumstances, it can lead to bugs (you'd think that sleep() is a part of the loop while in reality it is not):
> 
> while (day)
>   shuffle();
>   sleep();

For the TypeScript specific rules it would be nice to know why those rules are suggested and why I would want to enforce them on my project. For example, `no-constructor-vars` under what conditions would this be a useful rule to enforce and where did this rule come from (e.g. text from a MSDN blog discussing it with an associated link)?

The documentation on the rules\justifications in general would also be useful, having to check jslint, jshint and eslint to double check or clarify rules I haven't come across before (I'm looking at you `eofline`) is a bit annoying and time consuming as they're often named similarly but slightly different (`eofline` vs `eol-last` in eslint).

**Comment by adidahiya** [comment]
These are valid suggestions. We could certainly improve our docs.

**Comment by adidahiya** [comment]
This is being addressed as a part of #830.

**Comment by Kyle-Muir** [comment]
Awesome, I look forward to it :+1:

**Comment by JKillian** [comment]
@Kyle-Muir feel free to make some PRs to the `next-rule-metadata` branch and add some rationales for rules!

Here's [an example](http://palantir.github.io/tslint/rules/radix/) and [here's the code](https://github.com/palantir/tslint/blob/a7890fe693ed9605c5423d42f39ca13c8fb9e607/src/rules/radixRule.ts#L26-L29). 

Turns out writing these for about 60 rules is quite cumbersome haha. Most of the rules near the end of the alphabet still have no rationale and many of the other rules could be improved.

**Comment by Kyle-Muir** [comment]
@JKillian I have some free time coming up over Christmas, I might just try my hand at that :)

**Comment by JKillian** [comment]
@Kyle-Muir Great! I'm also thinking we should add an example or two of passing/failing code for each rule so you can see at a glance what the rule does.

**Comment by JKillian** [comment]
Related: #1311

**Comment by adidahiya** [comment]
I think we're in a much better place now. Open to PRs for specific improvements to docs.
