### ISSUE TITLE
/* tslint:disable */ not ignoring undeclared variable error.

### ISSUE THREAD

**Issue by pk091990** [palantir/tslint#4680]
TSLint rule flag are not ignoring unused variable error, neither displaying any quick fix in my VS code. I've installed TSLint extension in my Visual Studio code. Also install typescript-tslint-plugin in my dev dependency and added plugin property in tsconfig.json as described here [https://github.com/Microsoft/typescript-tslint-plugin#configuration-options](url)

However still getting error on **context** parameter i.e. "**Property 'context' is declared but its value is never read"**

Visual Studio Code version :1.33.1
Could you please confirm that Is there any other extension I need to install or any property need to set to make it work.

![image](https://user-images.githubusercontent.com/46436213/56666502-aa1d0900-66c9-11e9-9acf-2f85c771be34.png)

![image](https://user-images.githubusercontent.com/46436213/56666536-bc974280-66c9-11e9-9be0-5902243eb7b7.png)

**Comment by adidahiya** [comment]
That's probably a `tsc` error, not a `tslint` error. Let us know if you still have the problem when running the TSLint CLI.
