### ISSUE TITLE
Use typescript nightly package

### ISSUE THREAD

**Issue by ashwinr** [palantir/tslint#474]
This is to keep TSLint up to date with latest TypeScript

**Comment by adidahiya** [comment]
update: the 'publish-nightly' task has merged in the TS repo: https://github.com/Microsoft/TypeScript/pull/3875

**Comment by adidahiya** [comment]
http://blogs.msdn.com/b/typescript/archive/2015/07/27/introducing-typescript-nightlies.aspx
