### ISSUE TITLE
New tslint version

### ISSUE THREAD

**Issue by ericbf** [palantir/tslint#4740]
### Feature request

Putting this under feature request, but just wondering when we can expect the newest version to come out (to include the latest fixes)

**Comment by Shinigami92** [comment]
Maybe end of 2019? #4534

**Comment by adidahiya** [comment]
no, we will continue to release. I plan to cut a release in the next couple days.

**Comment by ericbf** [comment]
Great!

**Comment by Shinigami92** [comment]
So is it dying at the moment and not already dead? Do not get me wrong, I use TSLint in all my projects. At work and at home.

**Comment by adidahiya** [comment]
@Shinigami92 please see #4534
