### ISSUE TITLE
Fixer for no-void-expression

### ISSUE THREAD

**Issue by Goodwine** [palantir/tslint#4753]
### Feature request

**Is your feature request related to a problem? Please describe.**
Some void expressions are easy to make "non void expressions"
for example:
```ts
x(() => console.log());
return console.log();
```

**Describe the solution you'd like**
I want to upstream a fixer that converts the above into:
```ts
x(() => { console.log(); });
console.log();
return;
```

**Describe alternatives you've considered**
I wish I can remove "return" if it's the last statement on a function, but I figured this could be delegated to a different rule.

**Comment by JoshuaKGoldberg** [comment]
Unfortunately, this could end up changing code in unexpected ways. Being declared to return `void` does not guarantee a function call does so. Consider this completely valid TypeScript:

```ts
function curryVoid(returnsVoid: () => void): void {
    return returnsVoid();
}

curryVoid(() => "gotcha");
```

See #2625 for discussion on these "dangerous" fixes.

**Comment by Goodwine** [comment]
I'm pretty sure it does work as intended because of TS upcasting, for example:
```ts
declare function foo(x: () => void): void;
declare function bar(): string;

foo(() => "x"); // becomes foo(() => { "x"; }); because upcasting affects inline declaration
foo(bar); // stays as foo(bar); because upcasting does not affect existing declaration
```

I'll add a test case for this just in case

**Comment by Goodwine** [comment]
heh, I was wrong... :(

**Comment by Goodwine** [comment]
That said, I think if you have this, you had a bug and if you depended on that behavior, you were depending on a bug, so if it breaks, it's going to be WAI, no?
```ts
declare function foo(x: () => void): void;
declare function print(x: string): void;
print(foo(() => "bar") as any);
```

**Comment by JoshuaKGoldberg** [comment]
> you had a bug and if you depended on that behavior, you were depending on a bug

Hence the discussion in #2625 :wink: let's discuss there. If and when `--fix unsafe` becomes a part of TSLint, this would be an excellent addition to the rule.

**Comment by JoshuaKGoldberg** [comment]
Closing as #2625 has been declined. 😢
