### ISSUE TITLE
Relax promise-function-async for short parenthesized arrow functions

### ISSUE THREAD

**Issue by localnet** [palantir/tslint#4757]
### Feature request

**Is your feature request related to a problem? Please describe.**
Related https://github.com/palantir/tslint/issues/2637

**Describe the solution you'd like**
Same as https://github.com/palantir/tslint/issues/2637

**Additional context**
My reasoning is that if TSLint permit this:

```typescript
async function foo() {
  return 1;
}

const bar = () => foo();
```
then too should to permit:

```typescript
async function foo() {
  return 1;
}

const bar = () => (
  foo()
);
```

with tslint.json configuration:

```json
{
  "rules": {
    "promise-function-async": true
  }
}
```

**Comment by JoshuaKGoldberg** [comment]
Heya @localnet, I'm confused. #2637 was resolved by #4553. This feature should be available.

Is there a separate thing you're looking for? Specifically, what's the difference between this issue and #2637?

**Comment by localnet** [comment]
Excuse me if I have not explained myself well @JoshuaKGoldberg

Yes, https://github.com/palantir/tslint/pull/4553 solved the issue https://github.com/palantir/tslint/issues/2637 and permit this:
```typescript
async function foo() {
  return 1;
}

const bar = () => foo();
```
But it don't solve this:
```typescript
async function foo() {
  return 1;
}

const bar = () => (
  foo()
);
```
And to me seems it the same, practically.

**Comment by JoshuaKGoldberg** [comment]
Got it - totally reasonable. Thanks for the clarification! 😊
