### ISSUE TITLE
Bump: strange behavior when installing via yarn@1.1.0, e.g. whitespace "check-separator" in JSDoc

### ISSUE THREAD

**Issue by tohjg** [palantir/tslint#4758]
### Bug Report

Related issue: #3251 

I would like to address issue stated on the subject as related issue has being closed. Please see [my comment](https://github.com/palantir/tslint/issues/3251#issuecomment-500284939).

Thanks.

**Comment by JoshuaKGoldberg** [comment]
☠️ *TSLint's time has come!* ☠️ 

TSLint is no longer accepting formatting/whitespace requests per #4534. See **[typescript-eslint.io](https://typescript-eslint.io)** for the new, shiny way to lint your TypeScript code with **ESLint**. ✨ 

It was a pleasure open sourcing with you all!
