### ISSUE TITLE
Do not toggle rule 'interface-over-type-literal' for mapped types

### ISSUE THREAD

**Issue by wischli** [palantir/tslint#4777]
### Bug Report

- __TSLint version__: 5.17.0
- __TypeScript version__: 3.5.2
- __Running TSLint via__: Atom

#### Reproduction using [TSLint Playground](https://palantir.github.io/tslint-playground)

https://www.typescriptlang.org/play/#src=type%20Keys%20%3D%20'option1'%20%7C%20'option2'%3B%0D%0A%2F%2F%20TSLint%3A%20Use%20an%20interface%20instead%20of%20a%20type%20literal.%20(interface-over-type-literal)%0D%0Atype%20Tflags%20%3D%20%7B%20%5BK%20in%20Keys%5D%3A%20boolean%20%7D%3B%20%0D%0A%0D%0A%2F%2F%20BUT%20the%20mapped%20type%20cannot%20be%20used%20for%20interfaces%0D%0Ainterface%20Iflags%20%7B%20%5BK%20in%20Keys%5D%3A%20boolean%20%7D%3B%20%0D%0A

#### TypeScript code being linted

```ts
type Keys = 'option1' | 'option2';
// TSLint: Use an interface instead of a type literal. (interface-over-type-literal)
type Tflags = { [K in Keys]: boolean }; 

// BUT the mapped type cannot be used for interfaces
interface Iflags { [K in Keys]: boolean }; // error
```

with `tslint.json` configuration:

```json
{
    "defaultSeverity": "error",
    "extends": [
      "tslint:latest",
      "tslint-config-airbnb",
      "tslint-config-prettier"
    ],
    "jsRules": {},
    "rules": {
      "trailing-comma": [true, {"multiline": "always", "singleline": "never"}],
      "align": [false],
      "max-line-length": [true, 120],
    },
    "rulesDirectory": []
}
```

#### Actual behavior
TSLint throws a warning`Use an interface instead of a type literal. (interface-over-type-literal)`

#### Expected behavior
TSLint should recognize this as a mapped type and not throw a warning

**Comment by ychen10** [comment]
Hi @wischli - I wasn't able to reproduce the error using [TSLint playground](https://palantir.github.io?saved=N4Igxg9gJgpiBcID0SAEBlALgQwE6dUwE8AHASwDsBzVSwgCxlUllQCMIAPQiVKmAgGcc+GFAB0AHQrTiJJgGkYRQagC8qAOQQSmMhAoBGTagA+WnXoMAmTQG5pKVABV0AGUqZ4qAKqCm2BS0FJgwuABm2GBMlMIw2FCoEOGo2ISkTAA2ZKG42JniqAAUnmGR0QC0EABuYRVyMBXZufkAlLIZLuGZ2FSqGsCoANoKwahKKgC63hwQmfFBAL52qNKOaABCPs4MTAC22CTyiQ3MgRQQBGxMAK7+ieEQuMG55TCC0qURUUwAkt29VSDEZjCaCabsCBzBaoZaoJxhXBPEAAGnABnCZCoCGQaAAmhAbmcgntoGRwkRdswMVibnkrEFGLgmAB3HL0VBEQnPCAsihSChOACy2AA1kxBHSmJh6NgCFy6agAFaCAy0VTVfJkKAo1IURLkzmE1C4G5BTwQdZJGVhdWS966zC4SlgRhgUWUGg26kUVXzVCPZ6Ip6CAXSYDSVBR1YgWCRG6ZTDoGC1XA5IiSBAx4O4TMoyPRzMwTihfUfLNDAvRmOYQTZELwHqhYR5quFkC1+uYCqQCiYqgVbBkXBsChsVtBas1uueHs0gckZmYPRhTNtyb5ydRzMqgBKCfeme8wEWm+rmdN83Lx7b247eTI9YHkD2ByPwydNxguojID2Cb0esYHfTN8hZbAVDzGNBE9eYgJAkAKBTVcQEWDdbxjLUqBkCtIkyfx0K3dsDk4JpKEaeZqBld8hk-b9UEMawAAZCKnGMvjeKpU3qDIyJaTJ3zottTzbC8D0EAARYcYDATAngzCtJmkRY1goVCgA). It seems that the current rule already uses `isTypeLiteralNode` from `tsutils` to exclude mapped types. In actual tests, it does not seem to lint mapped types as well.

Could you post a more detailed description of how you get the error?
