### ISSUE TITLE
Have interface-over-type-literal replace trailing comma delimiters with semicolons

### ISSUE THREAD

**Issue by ychen10** [palantir/tslint#4795]
### Feature request

**Is your feature request related to a problem? Please describe.**
The `interface-over-type-literal` rule essentially turns a type alias into an interface. As semicolons are the preferred delimiter for marking the end of a line, it's better to handle the case where the type alias to be fixed used comma as separators.

It would add clarity to the shape of the object, e.g.,
```
interface User {
  someData: {
    firstName: string,
    lastName: string,
    registered: boolean,
  };
  location: string;
  quantity: number;
}
```
instead of
```
interface User {
  someData: {
    firstName: string,
    lastName: string,
    registered: boolean,
  },
  location: string,
  quantity: number,
}
```

**Describe the solution you'd like**
Add an additional step to the fixer so that it checks if the type alias uses comma as its separator for member property. If so, replace them with semicolons.

**Describe alternatives you've considered**
Be less aggressive and add a warning instead, but I think it complicates the process. Automatically changing the separators makes more sense.

**Comment by JoshuaKGoldberg** [comment]
👋 @ychen10, thanks for filing this issue!

> As semicolons are the preferred delimiter for marking the end of a line

Although I personally agree with you on this from a style perspective, it's not the responsibility of the `interface-over-type-literal` rule to fix interfaces to use semicolons over commas. [`type-literal-delimiter`](https://palantir.github.io/tslint/rules/type-literal-delimiter/) does that instead. TSLint rules intentionally don't care about stylistic preferences from other rules to keep themselves simple and single-purpose.

Given that TSLint is being deprecated (#4534) and there are existing structural issues with rule fixes overlapping (#2556), I'm going to mark this issue as declined.

**Comment by ychen10** [comment]
Hi @JoshuaKGoldberg  - 
`type-literal-delimiter` does not actually handles the case of an interface, as interfaces don't really have a `typeLiteralNode` in their AST. Is there an equivalent rule that applies the delimiter check to interfaces?

**Comment by JoshuaKGoldberg** [comment]
No, but if you'd like to file an issue for a new `interface-literal-delimeter` rule that seems reasonable.

**Comment by ychen10** [comment]
Actually, I think the `[semicolon](https://palantir.github.io/tslint/rules/semicolon/)` rule already does that.
