### ISSUE TITLE
Release timeline for TSLint v6

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [palantir/tslint#4811]
There are a bunch of otherwise-actionable [issues](https://github.com/palantir/tslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22Type%3A+Breaking+Change%22) and [pull requests](https://github.com/palantir/tslint/issues?q=is%3Apr+is%3Aopen+label%3A%22Type%3A+Breaking+Change%22) marked as breaking changes. Let's come up with a timeline for getting to that fabled TSLint 6.x version! 🙌

Straw man proposal:

* 8/1: close new rule issues lacking PRs per #4534 
* 8/2: release the last 5.X minor version
* 8/2-9: one week waiting period in case there needs to be a 5.X patch, in case of critical bugs
* 8/10: ~remove~ ignore 'breaking change' label from existing issues & PRs, and start merging them in
* 8/24: release `tslint@6.0.0-beta0`
* 9/1: release `tslint@6.0.0-beta1`
* 9/8: release `tslint@6.0.0`

Thoughts? 

/cc @adidahiya 

---

Updated proposal ~~9/3~~ ~~9/9~~ 10/4:

* 9/9: release the last 5.x minor version, prepare breaking changes to merge right after
* 10/11: release `tslint@6.0.0-beta0`
* 10/17: release `tslint@6.0.0-beta1`
* 10/23: release `tslint@6.0.0`

**Comment by adidahiya** [comment]
Sounds good to me 👍

**Comment by JoshuaKGoldberg** [comment]
Bump @adidahiya - are you able to publish a minor version update?

**Comment by adidahiya** [comment]
@JoshuaKGoldberg sorry for the delay, I was OOTO the past 2 weeks... I can release a minor version this week.

**Comment by jpike88** [comment]
@adidahiya Thanks this would be great, am aching to get at a rule I contributed

**Comment by adidahiya** [comment]
5.19.0 is released now

**Comment by adidahiya** [comment]
updated release timeline in OP

**Comment by JoshuaKGoldberg** [comment]
😅  looks like we blew past that timeline. The 'breaking change' issues and PRs now ok to merge are linked here. I'll edit the revised timeline in the OP to push forward a month and start merging these in (read: bugging authors for merge conflicts).

FYI @adidahiya

**Comment by JoshuaKGoldberg** [comment]
@adidahiya I think we're ready to release?

**Comment by adidahiya** [comment]
@JoshuaKGoldberg sounds good, it's on my list to do this weekend.

**Comment by adidahiya** [comment]
just released v6.0.0-beta0

**Comment by JounQin** [comment]
It's a bad practice to release a beta npm package on `latest` tag.

**Comment by adidahiya** [comment]
@JounQin I fixed that: https://github.com/palantir/tslint/issues/4886#issuecomment-549940875

**Comment by JoshuaKGoldberg** [comment]
@adidahiya are we ready to release `6.0.0`?

**Comment by adidahiya** [comment]
6.0.0 has been released and marked as deprecated on NPM. This will mean that new installs of the package will get the warning, while existing installs of 5.x will not.

```
$ npm info tslint

tslint@6.0.0 | Apache-2.0 | deps: 13 | versions: 178
An extensible static analysis linter for the TypeScript language
https://palantir.github.io/tslint

DEPRECATED ⚠️  - TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
```
