### ISSUE TITLE
tslint does not autofix on my project with fix: true

### ISSUE THREAD

**Issue by WebMasterSam** [palantir/tslint#4818]
Hi folks,

Currently I'm struggling to make tslint work for the autofix feature. I copy-paste a working example on another project and I'm just unable to make it work.

tslint 4.5.1
typsecript 3.4.5
gulp-tslint 7.1.0 via vs code

I've used the following gulp script :

```
const gulp = require('gulp')
const gulpTsLint = require('gulp-tslint')

gulp.task('tslint-fix', () =>
	gulp
		.src(['./{src,test}/**/*.{ts,tsx,js,jsx}'])
		.pipe(
			gulpTsLint({
				configuration: require.resolve('@cope/external-tslint/target/dist/tslint.json'),
				fix: true,
				formatter: 'verbose'
			})
		)
		.pipe(gulpTsLint.report())
)
```

```
export function doSomething(): any {
	continueToDoSomething()
	return { 'data': 'value' }
}
```

Gives me the **newline-before-return** invalid rule, but does not auto correct it. On the other project, it just simply works... I've compared every file, every relevan node_modules but I cannot find anything that's missing. 

How could I diagnose this ? Is there anyway to debug the fixers ?

**Comment by JoshuaKGoldberg** [comment]
Hi @WebMasterSam !I looks like your issues are with [gulp-tslint](https://github.com/panuhorsmalahti/gulp-tslint), which is a Gulp task for TSLint and a separate project from this (TSLint itself). You'll want to file your issue over there.

If you & they can't wrestle it into working, you can try [running TSLint on the CLI](https://palantir.github.io/tslint/usage/cli/):

```shell
tslint -p ./tsconfig.json -c ./tslint.json --fix
```
