### ISSUE TITLE
Mention tslint-to-eslint-config more prominently

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [palantir/tslint#4820]
RIght now the only mention of using https://github.com/typescript-eslint/tslint-to-eslint-config to migrate packages is a comment deep in #4534. @adidahiya, mind if I edit that thread's OP to mention it, and send a PR to add it to the README? 

I'm also curious if there are other tools folks are using to migrate that we should post links to!

**Comment by adidahiya** [comment]
done (back in august)
