### ISSUE TITLE
Difficulties excluding parent folder

### ISSUE THREAD

**Issue by lemoustachiste** [palantir/tslint#4825]
Not sure if actual bug or not. But I need help figuring this out.

### Maybe a Bug Report

- __TSLint version__: 5.18.0
- __TypeScript version__: 3.5.3
- __Running TSLint via__:  CLI

#### TypeScript code being linted

`src` directory, when not supposed to.

directory structure:
```
-- src
-- tests
    |-- tsconfig.json
    |-- tslint-tests.json 
-- tsconfig.json
-- tslint.json
```

with `tslint.json` configuration:

I have a main `tslint.json` for the whole project. I use this one to lint `src`.

```
{
  "extends": "tslint-config-semistandard",
  "rules": {
    "no-empty": false,
    "deprecation": {
      "severity": "warning"
    }
  },
  "linterOptions": {
    "format": "stylish"
  }
}
```

Now I am trying to lint my test files exclusively with a second configuration, located in my `tests` folder and named `tslint-tests.json`.

```
{
  "extends": "../tslint.json",
  "rules": {
    "no-unused-variable": true
  }
}
```
In my `src` there might be some `unused-variable`s that are actually used since I am using Aurelia and the view template (HTML) feeds on the view model (and uses these variables), hence the difference.

I tried using 
```
"exclude": [
    "../src"
  ]
```
in the subfolder `tslint-test.json`, but that didn't work. I also tried circumventing the issue with the `tsconfig.json` file, but that does not change anything either.

#### Actual behavior
Running the command `tslint -p tests/tsconfig.json -c tests/tslint-tests.json` also reports linting errors from `src` (which I am trying to exclude).

#### Expected behavior
No verification should happen on `src` with the above command. What is the correct configuration?

**Comment by adidahiya** [comment]
You can try `{ linterOptions: { exclude: ["../src/**/*"] } }` in your `tslint.json`. See these docs: https://palantir.github.io/tslint/usage/configuration/

**Comment by lemoustachiste** [comment]
That fixed it, somehow I had missed the `linterOptions` and it was necessary to also had the wildcards. 

Thanks for your help!
