### ISSUE TITLE
no-invalid-void links to 404

### ISSUE THREAD

**Issue by DerZyklop** [palantir/tslint#4829]
### Bug Report

[Changelog for v5.19.0](https://github.com/palantir/tslint/blob/master/CHANGELOG.md#v5190) says there is a new rule no-invalid-void. The new rule is linked to 

https://palantir.github.io/tslint/rules/no-invalid-void/

The linked page is a 404.

**Comment by BBosman** [comment]
The actual name is [invalid-void](https://palantir.github.io/tslint/rules/invalid-void/) .
