### ISSUE TITLE
XML Formatter for Jenkins Violations Plug-in

### ISSUE THREAD

**Issue by awn70** [palantir/tslint#487]
Hi,
is a formatter available which is compatible with Jenkins' Violations plug-in?
Thanks
Andreas

**Comment by adidahiya** [comment]
Looking at the [project page for the plugin](https://wiki.jenkins-ci.org/display/JENKINS/Violations), it seems like it supports PMD format XML files.

There is indeed a PMD formatter available in tslint. It looks like this fact is missing from the README, so I'll create a task to add it there.

**Comment by adidahiya** [comment]
closing this issue for now. please comment if you run into any issues with the PMD formatter.

**Comment by hadalin** [comment]
If I run `tslint` on multiple files:

`tslint -o tslint_pmd.xml -t pmd src/**/*.ts`

It creates malformed XML.

**Comment by adidahiya** [comment]
@hadalin that sounds like an existing issue: https://github.com/palantir/tslint/issues/656
