### ISSUE TITLE
run tslint to specific folder

### ISSUE THREAD

**Issue by dsadfasd** [palantir/tslint#4920]
How to run tslint for specific folder. For example i want to run tslint for specific module?
I need your help

**Comment by JoshuaKGoldberg** [comment]
👋  Hi! **TSLint is deprecated** and no longer accepting pull requests other than security fixes. See #4534. ☠️
We recommend you instead use **[typescript-eslint](https://typescript-eslint.io)** to lint your TypeScript code with ESLint. ✅

If you need help with something that is not a feature request or bug report, please ask on [StackOverflow](https://stackoverflow.com/questions/tagged/tslint). Thank you!
