### ISSUE TITLE
Improve codeFrame formatter to include rule severity with each failure

### ISSUE THREAD

**Issue by adidahiya** [palantir/tslint#4937]
Although TSLint is deprecated, we are still using it for some rules while we switch over to ESLint. We have a use case in a build tool which wraps the `tslint` CLI where we'd like to see the rule severity represented in more than one way. Currently, the only distinction between errors and warnings is the color of the failure string: 
https://github.com/palantir/tslint/blob/24d29e421828348f616bf761adb3892bcdf51662/src/formatters/codeFrameFormatter.ts#L70

I propose prepending `error: ` or `warning: ` before every rule failure string in the codeFrame formatter output.

**Comment by JoshuaKGoldberg** [comment]
@adidahiya mind if I close this out as not-intended-to-happen? Seems like something that could be implemented externally with clever CLI magicks and/or using the JSON output.
