### ISSUE TITLE
package.json "main" and "bin" entries excluded from repo via .gitignore

### ISSUE THREAD

**Issue by adidahiya** [palantir/tslint#502]
This prevents users from depending on the master branch, `palantir/tslint`, in their `package.json`

**Comment by adidahiya** [comment]
https://github.com/palantir/tslint/blob/master/.gitignore#L4

Both `bin/tslint-cli.js` and `lib/tslint.js` should be included in the repo so that the references in `package.json` make sense.

Also, according to [npm docs](https://docs.npmjs.com/files/package.json#bin), we can simplify the `bin` line to:

```json
"bin": "./bin/tslint"
```

or

```json
"bin": "./bin/tslint-cli.js"
```

**Comment by adidahiya** [comment]
This is more complicated than I thought. I've tried to fix this [here](https://github.com/palantir/tslint/tree/fix-package-json-main) but the problem is that `tslint.js` expects `../build/formatters/` and `../build/rules/` to have the right built JS files. Do we want to include all those in the repo? Is that cost worth it to support the use case of installing tslint from a git URL?

@gscshoyru @ashwinr

**Comment by JKillian** [comment]
Fixed awhile ago, closing!
