### ISSUE TITLE
Angular-specific rules

### ISSUE THREAD

**Issue by snebjorn** [palantir/tslint#511]
I was wondering if anyone have written some custom rules that can lint angular apps?
Much like [eslint-plugin-angular](https://github.com/Gillespie59/eslint-plugin-angular) for eslint.

Would be handy if there was a place where people could publish their custom rules :)

**Comment by Gillespie59** [comment]
:+1:

**Comment by adidahiya** [comment]
agreed, this would be great to have. we haven't yet figured out the tslint plugin story (made #582 to start the discussion). feel free to leave suggestions for angular-specific rules in this thread.

**Comment by snebjorn** [comment]
My goto angular guidelines are these https://github.com/johnpapa/angular-styleguide

**Comment by snebjorn** [comment]
For folder structure I use these:
http://www.johnpapa.net/structuring-an-angular-project/
https://scotch.io/tutorials/angularjs-best-practices-directory-structure

**Comment by adidahiya** [comment]
Check out https://github.com/mgechev/ng2lint, it has a bunch of Angular 2 rules

**Comment by ajafff** [comment]
We don't add any library specific rules to TSLint core. Angular shouldn't be an exception. Hence this issue is not really actionable.
https://github.com/mgechev/codelyzer provides some pretty good rules to enforce suggestions from the official angular styleguide.
