### ISSUE TITLE
rule suggestion: no-internal-module

### ISSUE THREAD

**Issue by vvakame** [palantir/tslint#513]
https://github.com/Microsoft/TypeScript/issues/2159
TypeScript 1.5.3 released. it has `namespace` keyword.
internal module is confusion name. I think use `namespace` instead of internal module.

if I create the pull request, will you accept it?

**Comment by ashwinr** [comment]
yes please. let's call the rule name `no-module-keyword`.

**Comment by vvakame** [comment]
@ashwinr yeah! I have one question. external module syntax are required in es6 module context.
like this.

```
declare module "foobar" {
	export default function (): string;
}
```

can I use `no-module-keyword` ?

**Comment by ashwinr** [comment]
But that's a module declaration and not a module definition. We should only be forbidding module definitions using the `module` keyword. Maybe the rule name should be `no-module-definition`

**Comment by adidahiya** [comment]
how about `no-internal-module`? I think "module definition" may be confusing / require lookup in our documentation

**Comment by ashwinr** [comment]
sgtm.
