### ISSUE TITLE
Nightly typescript support

### ISSUE THREAD

**Issue by s-panferov** [palantir/tslint#524]
Hello! What do you thinks about supporting a version with TypeScript's master or [ntypescript](https://github.com/TypeStrong/ntypescript) support?

It will help such hipsters as me to lint my code which is based on upstream of TS.

**Comment by adidahiya** [comment]
yep, adding support for the latest TS master is definitely a priority for us! already filed here: #474

**Comment by s-panferov** [comment]
@adidahiya thanks
