### ISSUE TITLE
Rule to use the namespace keyword rather than the module keyword

### ISSUE THREAD

**Issue by weswigham** [palantir/tslint#526]
In the newest versions of TS, ES6 module syntax and a desire to clarify the language has caused the `module` keyword to be all be replaced by the `namespace` keyword for "internal modules".

**Comment by adidahiya** [comment]
there is a PR open for this: #517

**Comment by weswigham** [comment]
Sorry, just glanced at that PR's name and thought that it was to disallow the `module` (or `namespace`) keyword entirely.
