### ISSUE TITLE
Support the is keyword

### ISSUE THREAD

**Issue by weswigham** [palantir/tslint#529]
At present, any appearance of the `is` keyword causes a missing semicolon lint error on that line.

**Comment by adidahiya** [comment]
blocked on #474

**Comment by adidahiya** [comment]
Just tried this out with `v2.5.0-dev.1` and some of the code from https://github.com/Microsoft/TypeScript/pull/3262/files and it seems to work. We'll need to add regression tests.

Please comment if you hit any issues and I'll reopen this.
