### ISSUE TITLE
Breaking changes should be behind major version bumps

### ISSUE THREAD

**Issue by NickHeiner** [palantir/tslint#530]
According to the Changelog, [v2.4.0 included a breaking change](https://github.com/palantir/tslint/blob/master/CHANGELOG.md#v240). Node modules are versioned according to [semver](http://semver.org). When a breaking change like this occurs, people who are depending on your module will see their code no longer work. Is there a compelling reason that semver could not be followed in this case?

(I don't want to sound too grumpy – in general, I am very happy with this module and I appreciate you contributing it to the community. :smile:)

**Comment by ashwinr** [comment]
hey @NickHeiner, we'll make sure to up the major next time. thanks for the feedback.

**Comment by adidahiya** [comment]
Sorry about that. In retrospect, we should've deprecated the cli option in 2.4 and removed it completely in 3.x
