### ISSUE TITLE
Contrast ratio on TSLint site is very poor

### ISSUE THREAD

**Issue by jelbourn** [palantir/tslint#531]
The contrast ratio of the blue text on the blue background on http://palantir.github.io/tslint is [a very poor 2.1](http://leaverou.github.io/contrast-ratio/#%23BBF5F6-on-%233AB4B4), which makes it difficult for low-vision users to read. [The W3C recommends](http://www.w3.org/TR/WCAG20-TECHS/G18.html) a ratio of 4.5 for text of this size.

**Comment by adidahiya** [comment]
finally fixed!
