### ISSUE TITLE
Add option to quotemark rule to disallow all quotes

### ISSUE THREAD

**Issue by adidahiya** [palantir/tslint#539]
A valid coding style would be to only use template strings for all strings.

Ideas for the rule option name:
- `none`
- `backtick`

**Comment by adidahiya** [comment]
the corresponding option in eslint is called `"backtick"`: http://eslint.org/docs/rules/quotes

**Comment by OliverJAsh** [comment]
Keen to see this! I want to use backticks everywhere instead of single/double quotes. https://ponyfoo.com/articles/template-literals-strictly-better-strings

**Comment by slikts** [comment]
Supporting this; using backticks by default has the benefits of not needing to escape quotes and not needing to convert string literals to template literals in case interpolation needs to be used. The current quotemark rule feels backwards in only having options for disallowing backticks.

**Comment by ericferreiralife** [comment]
Took a stab at that PR. @adidahiya or other contributors, could y'all take a look?

**Comment by JoshuaKGoldberg** [comment]
Looks like #4029 fixed this! 🎉
