### ISSUE TITLE
Disallow contextual "any"

### ISSUE THREAD

**Issue by use-strict** [palantir/tslint#541]
Problem is described here: https://github.com/Microsoft/TypeScript/issues/4126

It was suggested that TSLint might be able to handle the given case with a special rule. I see that something like this was already suggested back in 2014 (https://github.com/palantir/tslint/issues/80). Have things changed since then or is it still a no-go?

**Comment by adidahiya** [comment]
I haven't investigated type-based rules much yet but this sounds useful and should be doable.

**Comment by use-strict** [comment]
@adidahiya , it seems I can't implement this without https://github.com/palantir/tslint/issues/680. Blocked tag? :(

**Comment by ajafff** [comment]
Is this still an issue now that we have `no-unsafe-any`?
