### ISSUE TITLE
Feature Request: "avoid-escape" for "quotemark"

### ISSUE THREAD

**Issue by readme42** [palantir/tslint#543]
If `quotemark` is configured as follows

```"quotemark": [true, "double"] ```

this statement would be illegal

```html
{
    template: '<div class="x"></div>'
}
```

It would be great so set an option `avoid-esape` which will make tslink marking this green if otherwise escaping would be necessary.

See equivalent at [ESLint](http://eslint.org/docs/rules/quotes) rule.

**Comment by mizunashi-mana** [comment]
:+1:
