### ISSUE TITLE
use-strict not working on module

### ISSUE THREAD

**Issue by sebasrodriguez** [palantir/tslint#544]
I'm trying to use the use-strict rule for modules and I can't make it to work properly. 

I've have a stripped down version of a module with an interface:

```ts
module app.myModule {
	export interface IListener {
		listeners: Array<any>;
	}
}
```

Running grunt tslint doesn't returns the use-strict error.

I've debugged the rule and it looks like when the depth is 2 for that file the node.body.kind is ModuleDeclaration and not ModuleBlock.

Am I missing something?

**Comment by ArturDorochowicz** [comment]
I've been experiencing the same issue. 

The explanation by @sebasrodriguez is spot on, basically the rule does not handle this case at all. The walker receives a ```ModuleDeclaration``` for ```app``` first and then a ```ModuleBlock``` for ```myModule```, but that is already on depth=3 and the rule only looks for ```ModuleBlock``` at depth=2.
