### ISSUE TITLE
comment-format rule "check-lowercase" option should allow whitelist of exceptions

### ISSUE THREAD

**Issue by adidahiya** [palantir/tslint#562]
I'd like to allow exceptions to the `check-lowercase` rule option via a whitelist that looks something like:

``` json
"comment-format": [true,
    ["check-lowercase", "TODO", "HACKHACK"],
    "check-space"
]
```

**Comment by IllusionMH** [comment]
As I can see format with nested arrays isn't supported in system.
What about optional array of whitelisted words as last argument?
