### ISSUE TITLE
Rule set plugin architecture

### ISSUE THREAD

**Issue by adidahiya** [palantir/tslint#582]
ESLint has robust plugin support: http://eslint.org/docs/developer-guide/working-with-plugins

How should we manage framework-specific rules?

**Comment by adidahiya** [comment]
https://github.com/Microsoft/tslint-microsoft-contrib is related here

**Comment by pburgmer** [comment]
+1 for plugin support

**Comment by adidahiya** [comment]
We now have shareable configs with the `extends` feature as of v3.7.1. Which other features of plugins are you interested in for TSLint?

**Comment by pburgmer** [comment]
Oh, sorry, didn't know that. I just saw this open ticket, searching for some angular 2 rules.
Thanks for the fast response.

**Comment by adidahiya** [comment]
That being said, there is no documentation for this new feature in the README :) will that fix soon.

**Comment by adidahiya** [comment]
plugins (configs, custom rules) are now generally supported and widely used
