### ISSUE TITLE
Make rulesDirectory option accept an array of files, not just a single file

### ISSUE THREAD

**Issue by HamletDRC** [palantir/tslint#590]
I would like the rulesDirectory option to accept an array of files/paths, not just a single path. For backwards compatibility, I think you'll need to accept either a string or an array of strings as a valid value. 

I am making use of the rulesDirectory option because I wrote some of my own rules. I am in the process of publishing my ruleset to github but not all of my custom rules are fit to publish (or even useful beyond my project). So what I need is to point RulesDirectory to two different locations and have the behavior for looking up the rule files be: 
* first search tslint
* then search the first entry in the rulesDirectory array
* then search the next entry, ... 

Thanks.

**Comment by adidahiya** [comment]
cool, sounds like a reasonable request

**Comment by pspeter3** [comment]
This is copied from #645 but I propose

From the CLI

```sh
tslint --config tslint.json --rule noTrailingComma.js --rule tools/noEval.js --file src/index.ts
```

From JavaScript

```js
var options = {
  configuration: { /* config here */ },
  rules: [
    'noTrailingComma.js',
    'tools/noEval.js'
  ]
};
```

The hope is that it makes the dependencies of the command more explicit

**Comment by pspeter3** [comment]
Is there anything being done here for this?

**Comment by adidahiya** [comment]
#800 adds a `rulesDirectory` option to `tslint.json` which supports an array of filepaths. I'll review that PR this week.

**Comment by adidahiya** [comment]
#800 has merged. I'll cut a `next` release soon so y'all can test out this new functionality in tslint.json

**Comment by adidahiya** [comment]
@HamletDRC @pspeter3 @buzinas `v3.1.0-dev.1` has been published to `tslint@next` on NPM
