### ISSUE TITLE
Log a message if a rule cannot be found

### ISSUE THREAD

**Issue by HamletDRC** [palantir/tslint#598]
Assuming that you have written all your rule config in a file called "tslint.json" then I would like to see a console error if one of the referenced rules cannot be found. 

For example, if I define  "no-unused-whatever" and that rule cannot be found, then I want to see something on the console. 

It looks like you just need to add a console.log message in the `ruleLoader.ts::findRule()` function. Right above `return undefined`

**Comment by JKillian** [comment]
This will be handled by #953. Right now it's going to throw an error - do you think just a log message would be better (see https://github.com/palantir/tslint/pull/953#discussion_r51509416)

**Comment by adidahiya** [comment]
Fix is now available in `v3.4.0-dev.1`
