### ISSUE TITLE
Enable no-whitespace rule for inline variables in TSX

### ISSUE THREAD

**Issue by rcchen** [palantir/tslint#603]
We want to be consistent with spacing in our TSX code.

Specifically, this should be ok: `{myAwesomeElement}`
while this should not be ok: `{ myAwesomeElement }`

Adding a rule to capture no-whitespace for inlined variables in TSX would be very helpful!

**Comment by avanderhoorn** [comment]
Would be really nice to have this one.

**Comment by JoshuaKGoldberg** [comment]
@rcchen @avanderhoorn this is covered by [`tslint-react`](https://github.com/palantir/tslint-react)'s `jsx-curly-spacing` rule and [`tslint-microsoft-contrib`](https://github.com/microsoft/tslint-microsoft-contrib)'s `react-tsx-curly-spacing` rule.
