### ISSUE TITLE
Request: rule for requiring JSDoc comments for all functions

### ISSUE THREAD

**Issue by maxmantz** [palantir/tslint#623]
Having a rule to enforce using JSDoc style comments for every function would help a lot with code documentation. This rule could be further refined by only needing to provide comments for public functions, only commenting once per occurrence - for example an exception to not comment a class implementation when it was already commented in an interface, etc.

**Comment by adidahiya** [comment]
Sure, that sounds like a reasonable request. Would you want to require type annotations on parameters in those jsdoc comments? Or just look for a /** block comment right before the function declaration? I'm strongly inclined towards the latter since TS already has type annotations.

**Comment by maxmantz** [comment]
I don't think that type annotations on parameters in those comments are necessary, as you've pointed out. However needing to describe the parameters would be another useful requirement for the rule. Another useful rule could be that double-slash quotes are required on (public) properties of a class. Here is an example of what I have in mind:

    interface IDemoClass {
    // I am an optional requirement
    property1: string;

    /**
     * This comment is required
     * @param {string} input This description is an optional requirement
     */
    doSomething(input: string): void;
    }

    class DemoClass implements IDemoClass {
    
    // I am also optional requirement, since the interface has already provided a comment
    property1: string;

    // I am also optional, since the property is private
    private property2: number;

    /**
     * A constructor comment is required
     * @param {string} prop1 Describing the parameters
     * @param {string} prop2 is a useful (optional) requirement
     */
    constructor(prop1: string, prop2: number) {
        this.property1 = prop1;
        this.property2 = prop2;
    }

    // no comment required, since it's been commented in the interface
    doSomething(input: string): void {
        // do something...
    }

    /**
     * This comment is required
     * @returns this is optional
     */
    doSomethingPublicly(): number {
        return 123;
    }

    /**
     * An optional requirement for private functions
     * @param {string} input optional as well
     * @returns optional requirement
     */
    private doSomethingPrivately(input: string): string {
        return 'foo';
    }
    }

The types of the params in my JSDoc comments have been automagically generated by my IDE, but they should be optional as well.

**Comment by nchen63** [comment]
fixed by #2095
