### ISSUE TITLE
New Rule: no-use-before-initialization

### ISSUE THREAD

**Issue by adidahiya** [palantir/tslint#624]
Suggested in https://github.com/Microsoft/TypeScript/issues/2234

If the typechecker knows that a value is `undefined` at a certain point in the program, this rule would disallow:
1. accessing properties or indexing into an object or array
   
   ``` ts
   var arr: number[];
   var obj: any;
   arr.push(1);
   obj.foo = "bar";
   ```
2. returning a primitive value or using it in a RHS expression
   
   ``` ts
   function dd(): number {
     var x: number;
     return x;
   }
   
   function ddd() {
     var x: number;
     x++;
   }
   ```

**Comment by pawciobiel** [comment]
Would it make sense to fix those too?

```typescript
var a: number = 2;
var b: number;
var c: number = null;  // build error or runtime exception
console.log(a + b);  // build error or runtime exception
console.log(b + c);  // build error or runtime exception
console.log(a + c);  // build error or runtime exception
```

**Comment by adidahiya** [comment]
@pawciobiel yep, I think that would fall under the category of RHS (right-hand-side) expressions

**Comment by adidahiya** [comment]
blocked on #680 I believe

**Comment by andy-hanson** [comment]
`no-use-before-declare` seems to do this.

**Comment by adidahiya** [comment]
In v5.0 with the change to be a typed rule, `no-use-before-declare` does seem to do this.
