### ISSUE TITLE
undefined is not a function

### ISSUE THREAD

**Issue by pspeter3** [palantir/tslint#640]
This is happening on version and `2.4.5` in scan at `node_modules/tslint/lib/tslint.js:3179:31` when I use tslint programmatically

**Comment by pspeter3** [comment]
The issue was that the code was passing a Buffer instead of a string

**Comment by adidahiya** [comment]
Can you post the whole stack trace please? And maybe a snippet of your code that uses the TSLint JS API? That line (3179) looks like a part of the distributed lib which corresponds to the compiler source code.

**Comment by pspeter3** [comment]
I think this was my poor usage of the library, not yours
