### ISSUE TITLE
Rules file list as opposed to directory

### ISSUE THREAD

**Issue by pspeter3** [palantir/tslint#645]
It would be nice to pass an explicit list of files as opposed to a directory for test purposes

**Comment by JKillian** [comment]
Can you elaborate on what the syntax would like like for this via the CLI?

**Comment by pspeter3** [comment]
From the CLI

```sh
tslint --config tslint.json --rule noTrailingComma.js --rule tools/noEval.js --file src/index.ts
```

From JavaScript

```js
var options = {
  configuration: { /* config here */ },
  rules: [
    'noTrailingComma.js',
    'tools/noEval.js'
  ]
};
```

The hope is that it makes the dependencies of the command more explicit

**Comment by JKillian** [comment]
I'm going to close this because it's really similar to #590, but the discussion can continue there. I think I might like your version of the idea slightly better, would you mind commenting in #590 with your proposal?
