### ISSUE TITLE
Tslint crashes with parameter destructuring

### ISSUE THREAD

**Issue by lbesson** [palantir/tslint#652]
Following code compiles fine with typescript 1.5.3, but tslint crashes

```javascript
function a() {
  var b = ({c: d}) => {};
}
```

```
$ tslint test.ts

noUseBeforeDeclareRule.js:90
        for (var _i = 0; _i < highlights.length; _i++) {
                                        ^
TypeError: Cannot read property 'length' of undefined
    at NoUseBeforeDeclareWalker.validateUsageForVariable 
```

Not sure exactly why yet, so the issue title is probably wrong.
Tslint is fine if we remove surrounding function.

**Comment by JKillian** [comment]
Thanks for the report @lbesson, this should be fixed in a release with in a week or so. In the meantime, I'd just disable the rule for that specific location in your code

**Comment by lbesson** [comment]
Thanks!
Le 10 sept. 2015 9:03 PM, "Jason Killian" <notifications@github.com> a
écrit :
