### ISSUE TITLE
add 'default' for enable|disable of rule

### ISSUE THREAD

**Issue by melgish** [palantir/tslint#659]
enable/disable are all-or-nothing.  Consider:

``` ts
import something = require("something");
/* tslint:disable:no-unused-expression */
something; // force inclusion for requirejs
/* tslint:enable:no-unused-expression */
```

This suppresses the error, but leaves the rule _on_ for the rest of the file, even if it was _off_ to begin with.  Suggesting something like below, which would restore the default rule state.

``` ts
import something = require("something");
/* tslint:disable:no-unused-expression */
something; // force inclusion for requirejs
/* tslint:default:no-unused-expression */
```

The rational is that today I _know_ the rule needs to be suppressed for _this_ occurrence, but I shouldn't have to come back and touch this file if I decide later to turn the rule off across the board.

**Comment by adidahiya** [comment]
that sounds kind of dangerous -- why wouldn't you want to come back and touch this part of your codebase to remove these enable/disable lines if you decide to turn off the rule across the board? otherwise you're just left with dead comments littering your codebase.

**Comment by melgish** [comment]
I don't know of any case where I've used  "enable a rule / "have some code" / disable the rule".  I can't even imagine one where I wouldn't enable the rule at the project level.  It's like saying "this tiny block of code is perfect, so it's safe to be strict"

So in my mind the only use case is "disable the rule" / "violate the rule" / "enable the rule".  But more accurately what is desired is "make sure the rule is off" / "violate the rule" / "restore the previous state." The initial state of the rule on entry being the correct state on exit.

Hope this clarifies...

**Comment by adidahiya** [comment]
I agree that the second case constitutes the majority of usage of TSLint's enable/disable flags ("disable the rule" / "violate the rule" / "enable the rule").

However, I'm not sold on the semantics of "restore the previous state" because changing a rule at the top level _should_ force you to go through your code base and re-consider any instances of disabling that rule.

**Comment by ajafff** [comment]
Closing this, because it already works that way. You cannot enable a rule that is disabled in tslint.json
