### ISSUE TITLE
Readout all available rules & options

### ISSUE THREAD

**Issue by nelo112** [palantir/tslint#674]
Hello,
is there a good way to readout all current rules & their options? I'm working on a TSLint Plugin for Sonar and currently the Rules are all entered manually wich is obviously far from perfect. A simple json or xml file would be good.
Greetings
Manuel

**Comment by adidahiya** [comment]
ok, I'd be happy to support some kind of "schema" JSON or XML file that describes all the rule names & options, but it would need a more detailed proposal that describes its format / structure.

**Comment by alexkrauss** [comment]
The main obstacle here seems to be #629: Currently, rule configuration is basically untyped, and there is no sensible way of specifying the allowed rule arguments formally.

**Comment by JKillian** [comment]
Instead of a schema JSON or XML file, I'm thinking that rule options should be specified in code somehow. Maybe something sort of like this: https://github.com/Microsoft/TypeScript/blob/master/src/compiler/commandLineParser.ts, except that each rule would contain it's own metadata instead of having one file like this.

**Comment by JKillian** [comment]
Experimental rule option schemas implemented on the [`next-rule-metadata` branch](https://github.com/palantir/tslint/tree/next-rule-metadata)

**Comment by JKillian** [comment]
#1311 should help with this, each rule will now contain a schema for its options

**Comment by adidahiya** [comment]
All the rules now have metadata. There is also a `tslint:all` configuration that enables (almost) all of them.
