### ISSUE TITLE
interface-name warning decorator is wrong

### ISSUE THREAD

**Issue by nlenoire** [palantir/tslint#675]
Hello,
I do not want tslint to warn in case interface name does not start with 'I'. Also, I configured tslint.json with the rule:
<code>
"interface-name": false,
</code>

However, my editor is still displaying a warning decorator saying "Interface name must be capitalized I" (whatever is the value of the interface-name rule, actually).
Note that if I run tslint using the command line, then rule is applied correctly.

**Comment by adidahiya** [comment]
this looks like an issue with how you've configured your editor plugin or the plugin itself. which editor are you using? I'd suggest filing this issue on the project page for the plugin rather than TSLint itself.

**Comment by nlenoire** [comment]
I'm using Eclipse-TypeScript editor (still from Palantir)

**Comment by adidahiya** [comment]
moved to https://github.com/palantir/eclipse-tslint/issues/15
