### ISSUE TITLE
`use-strict` is (partially?) obsolete

### ISSUE THREAD

**Issue by jiaweihli** [palantir/tslint#678]
Due to https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#module-bodies-are-parsed-in-strict-mode

**Comment by adidahiya** [comment]
cool, looks like we can deprecate the `use-strict` rule soon

**Comment by ArturDorochowicz** [comment]
IMO ```use strict``` rule is very much not obsolete and I would urge you not to remove it.

The fact that the compiler parses some code applying strict mode constraints has little to do with the runtime strict mode and this is what the ```use strict``` rule is really about.

Parsing and runtime is only equivalent when compiler output is ES6 and the code is in a module or class. In all other cases (ES5, ES3, "global" code) these are two different things and we still need a rule to enforce ```use strict``` directive to have runtime strict mode.

**Comment by tsvetomir** [comment]
@ArturDorochowicz the compiler [will output](http://www.typescriptlang.org/play/index.html#src=export%20function%20foo()%20%7B%0D%0A%09console.log(1)%3B%0D%0A%7D%0D%0A) `"use strict";` on the module level where it applies to all the functions in the module.

**Comment by ArturDorochowicz** [comment]
@tsvetomir Yes, that is correct now, but wasn't when I commented on the issue. This has been introduced in TypeScript 1.8, see:
https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#modules-are-now-emitted-with-a-use-strict-prologue

**Comment by rcollette** [comment]
I'm not sure why this rule was removed.   When compiling with internal modules (namespaces) use strict is not generated in the output.   If the developer forgets it, then browser JIT optimizations do not occur.

For example this source:
```
// tslint:disable use-strict
namespace app.precache {
  angular.module('app.precache', ['ngResource', 'app.config']);
}
// tslint:enable use-strict
```

Becomes
```
// tslint:disable use-strict
var app;
(function (app) {
    var precache;
    (function (precache) {
        angular.module('app.precache', ['ngResource', 'app.config']);
    })(precache = app.precache || (app.precache = {}));
})(app || (app = {}));
// tslint:enable use-strict
```
There is no auto-generated 'use strict'; statement in this case and none is assumed by the browser.

I could be wrong, but that is my current understanding.

**Comment by nchen63** [comment]
The TypeScript release notes says it should be generated, so this may be a regression or oversight on their side

**Comment by adidahiya** [comment]
@nchen63 the release notes say it is generated for _modules_, not _scripts_. @rcollette seems to be right here, but at this point I would just suggest using `use-strict` as a custom rule -- I don't want to bring it back into the core rules since its usage seems pretty low.

**Comment by adidahiya** [comment]
actually, TS 2.1+ now has a `--alwaysStrict` option to emit "use strict" for everything. Try it out @rcollette https://github.com/Microsoft/TypeScript/pull/11473

**Comment by rcollette** [comment]
Fair enough.  We're dealing with a pre web pack app.  Starting new I would be using external modules.
On Nov 22, 2016 6:44 PM, Adi Dahiya <notifications@github.com> wrote:@nchen63 the release notes say it is generated for modules, not scripts. @rcollette seems to be right here, but at this point I would just suggest using use-strict as a custom rule -- I don't want to bring it back into the core rules since its usage seems pretty low.
