### ISSUE TITLE
Lint Programs as a Whole

### ISSUE THREAD

**Issue by JKillian** [palantir/tslint#680]
Right now, TSLint lints files individually. This means that any information in one file (such as type information) is not available while linting other files.

One possible alternative is to, at startup, create a language services instance that has the source for the entire program and pass this to the rules. Full program information could then be used by the rules.

**Comment by ashwinr** [comment]
what additional features does this enable? we're not linting types yet anyway.

**Comment by JKillian** [comment]
Possibly stuff like this: https://github.com/palantir/tslint/issues/577

**Comment by adidahiya** [comment]
basically any rule that needs to inspect types will need all the type information from the compilation path in order to work reliably

**Comment by dallonf** [comment]
It'd at least be nice to pass a glob to `tslint` and lint multiple files.

**Comment by JKillian** [comment]
@dallonf When using it programmatically I assume? (Since obviously a glob will work when using it via the CLI)

**Comment by dallonf** [comment]
@JKillian I didn't know that was supposed to work ;) Created a ticket for my seperate issue: https://github.com/palantir/tslint/issues/688

**Comment by myitcv** [comment]
Picking up  [@aleksey-bykov's comment](https://github.com/Microsoft/TypeScript/issues/7306#issuecomment-192333122), I wonder if we can kick start some sort of effort on this.... We have a long list of rules that we want to write (let's ignore the fact many of these rules should in fact be part of TypeScript core)

@adidahiya @JKillian - are you aware of anyone who has tried to progress this?

As @aleksey-bykov points out, the effort involve in creating a custom linter that does have type information is not hard. The more complicated bit will be working out how to integrate this into `tslint`

**Comment by JKillian** [comment]
Sorry for the delayed response here @myitcv. I'm not aware of any progress on this so far, feel free to go for it if you have the time! I'm happy to discuss how we can integrate this kind of thing into TSLint as it is now

**Comment by alexeagle** [comment]
How will this approach match the compiler options of tsc with those passed to tslint?

For example, we need the same input files, same typings, same moduleResolution flag, same `baseUrl`,`rootDirs` (https://github.com/Microsoft/TypeScript/issues/5039), `--skipDefaultLibCheck` and so on. Otherwise the typecheck will fail when `tslint` runs, and the user has to carefully duplicate these settings.

One option is to read tsconfig.json as an input to `tslint`, but some users may have configuration in another place (we often wrap the compiler API to workaround differences in filesystem layout).

Another option is to work with the typescript team to run additional static analysis checks in the compiler itself, using some extensibility mechanism.

**Comment by myitcv** [comment]
@alexeagle - the approach we are following with [`tsvet`](https://github.com/palantir/tslint/issues/1048#issuecomment-199420447) is to reference the same `tsconfig.json` that is referenced by `tsc`.

As it stands, we only run `tsvet` once a compilation via `tsc` has succeeded. This obviates the need to ignore/dedup the compilation errors during the `tsvet` run.

Ultimately we could do away with the _`tsc`_ step entirely and output compilation errors _and_ our own custom errors in the `tsvet` step. This would need `tsvet` support for `--watch` and friends to become a reality practically speaking.

**Comment by alexeagle** [comment]
If the user will run a single program to type-check, run diagnostics,
produce custom errors, and emit, why not have tsc be that single program?
It seems simpler than replacing it by a different end-user application that
behaves the same as tsc.

**Comment by myitcv** [comment]
@alexeagle - completely agree. That would be ideal. `tsvet` is something we can do today... and with relative ease, independent of the `tsc` compiler. 

I see you've already commented on [the issue](https://github.com/Microsoft/TypeScript/issues/3003) that I believe is tracking this in TypeScript core.

Our work on `tsvet` is of course compatible with https://github.com/Microsoft/TypeScript/issues/3003 by  virtue of our 'rules' being defined in terms of the compiler API.

**Comment by adidahiya** [comment]
Full-program linting is now possible thanks to @ScottSWu's work in #1363! Please try out the new APIs, let us know how they work out, and file follow up issues as necessary ❤️

**Comment by JoshuaKGoldberg** [comment]
Love it!
