### ISSUE TITLE
tslint.d.ts exported member does not match JavaScript code

### ISSUE THREAD

**Issue by Knagis** [palantir/tslint#686]
Currently the `tslint.d.ts` file contains the following:
```js
declare module "tslint" {
    export = Lint;
}
```

but the code used to invoke the linter is:
```js
var Linter = require("tslint");
var ll = new Linter(fileName, contents, options);
```

For this to work the .d.ts file has to be changed to:
```js
declare module "tslint" {
    export = Lint.Linter;
}
```

**Comment by Knagis** [comment]
Also the `tslint.d.ts` file should reference `typescriptServices.d.ts`.

```js
/// <reference path="../typings/typescriptServices.d.ts" />
```

**Comment by pspeter3** [comment]
I agree with the reference. Right now it seems like custom rules will not compile.

**Comment by JKillian** [comment]
Thanks for the heads up, we'll fix the bug with the typings file. We're not going to add the reference (because of how the project is structured) but we'll update the readme to make it clear that you also have to reference `typscriptServices.d.ts` in your rule.
