### ISSUE TITLE
Can't use a glob in the CLI on Windows

### ISSUE THREAD

**Issue by dallonf** [palantir/tslint#688]
When using the `tslint` CLI on Windows, globs are interpreted as literal filepaths:

```text
> node_modules\.bin\tslint.cmd src\**\*.{ts,tsx}
Unable to open file: src\**\*.{ts,tsx}
```

And just for fun, trying to use `/` seperators:
```text
> node_modules\.bin\tslint.cmd src\**\*.{ts,tsx}
Unable to open file: src\**\*.{ts,tsx}
```

According to https://github.com/palantir/tslint/issues/680#issuecomment-143776713, this is "obviously" supposed to work. Does this rely on some Bash convention that cmd doesn't have?

**Comment by JKillian** [comment]
@dallonf Ah, I see, wasn't thinking about the Windows side of things - I'm unsure of how that works out, but I'll take a look into it.

On the *nix side of things, bash, zsh, or whatever shell you're using takes the glob and expands it into a list of filenames automatically. So way you had a folder with files `a.ts`, `b.ts`, and `tslint.json`. Running `tslint *.ts` or running `tslint a.ts b.ts` looks the exact same to tslint. That is, tslint is passed the same command line arguments by the shell in both cases.

It seems like that's not the case on Windows though. I'll look into how node programs that accept a list of files normally handle globs on Windows.

**Comment by dallonf** [comment]
Well, I learned something today! :smile: Before today, I thought Unix programs took globs by convention, not as an actual feature of Bash...

Anyways I think a lot of node programs also accept a directory name and recursively search for files in that directory; `eslint` does this, for example.

**Comment by adidahiya** [comment]
Made a new issue for this category of feature requests: #692. If you feel like I've sufficiently captured your use case, then we can move discussion over there

**Comment by dallonf** [comment]
That issue describes things a lot better than I did! Thanks.

**Comment by radek-holy** [comment]
FYI, I was told that a lot of Node programs handles globs using https://www.npmjs.com/package/minimatch

**Comment by louy** [comment]
#827 solves this.
