### ISSUE TITLE
treat namespace the same as module with respect to "missing semicolon" rule

### ISSUE THREAD

**Issue by daviddowneyx** [palantir/tslint#705]
the following throws an error for two missing semicolons on the first line:

common/common.module.ts[1, 10]: missing semicolon
common/common.module.ts[1, 21]: missing semicolon

    namespace app.common {
    	'use strict';
    	angular
    		.module('app.common', [
    			'ngResource',
		]);
    }

this doesn't throw any errors:

    module app.common {
	'use strict';
	angular
		.module('app.common', [
			'ngResource',
		]);
    }

perhaps I am missing something, but I feel like they should be treated the same.

**Comment by JKillian** [comment]
There shouldn't be any missing semicolon errors for either of those examples. I can't seem to duplicate your problem though, what version of TSLint are you using?

**Comment by daviddowneyx** [comment]
gulp-tsling@1.5.0

**Comment by daviddowneyx** [comment]
gulp-tslint != tslint?? perhaps I am in the wrong place?

**Comment by daviddowneyx** [comment]
You can close this.  gulp-tslint only started using tslint@2.5.0 6 days ago.  I updated and it seems to be working now.

**Comment by adidahiya** [comment]
@daviddowneyx note that gulp-tslint has support for providing your own custom tslint module, which means you can use whatever version you want: https://github.com/panuhorsmalahti/gulp-tslint#specifying-the-tslint-module
