### ISSUE TITLE
Add typescript-formatter verification to build

### ISSUE THREAD

**Issue by adidahiya** [palantir/tslint#728]
suggested by @myitcv 

sample usage: https://github.com/myitcv/typescript_test/blob/master/scripts/build.sh#L7

**Comment by myitcv** [comment]
Credit to @vvakame here for developing `tsfmt` in the first place :+1:

**Comment by JoshuaKGoldberg** [comment]
Although `tsfmt` is awesome, it looks like we've moved to Prettier. Closing as aged away.
