### ISSUE TITLE
add more visitor methods to RuleWalker

### ISSUE THREAD

**Issue by HamletDRC** [palantir/tslint#736]
I have a need for a visitor method for the following SyntaxKind types: 
* NoSubstitutionTemplateLiteral
* StringLiteral
* EmptyStatement
* WithStatement
* TypeReference

Currently, I just override visitNode and look at the node.kind, but a visitor method would be nicer.

**Comment by JKillian** [comment]
@HamletDRC We don't have a StringLiteral one? Yikes! I can add these for you

**Comment by JKillian** [comment]
@HamletDRC What should the node type be for NoSubstitutionTemplateLiteral? `StringLiteral` perhaps?

**Comment by adidahiya** [comment]
you should add these methods in an ad-hoc manner as you find the need for them in your rule walkers. we don't need to pre-emptively add methods for walking all syntax kinds. if you need this in custom rules, you can override the `visitNode` method in your custom rule walker and call `super.visitNode` accordingly.

**Comment by JKillian** [comment]
I think custom rules should be able to expect these methods to be implemented - there's no reason there should only be methods available for the built-in rules. Forcing custom rules to override visitNode makes them use a different paradigm than built-in rules, which is non-obvious. 

The only downside of adding the methods is the performance impact of one more case in a switch statement and one more method call deep on the stack. But if that was critical, then we'd make the built-in rules only handle the cases they care about, which we don't. We could even switch things away from a switch statement to a data-structure with constant access performance, but I doubt that would speed things up really. (Although worth trying maybe sometime?)

**Comment by HamletDRC** [comment]
@adidahiya These 5 are the SyntaxKind entries that I am explicitly testing against in my visitNode methods in my rule set. 

@JKillian Is the type perhaps ts.TemplateExpression? If the kind entry does not map to a Node subclass then don't bother adding the visit method.

**Comment by JKillian** [comment]
NoSubstitutionTemplateLiteral and EmptyStatement have no corresponding SyntaxKind so not going to add them. The two PRs above have StringLiteral, WithStatement, and TypeReference added though

**Comment by HamletDRC** [comment]
This is merged then. At what point is the issue closed?

**Comment by JKillian** [comment]
Now :)
