### ISSUE TITLE
Allow Conflicting Rules to Exist but not Be Concurrently Enabled

### ISSUE THREAD

**Issue by JKillian** [palantir/tslint#739]
Recently, we had an issue where we added a new rule that conflicted with a previous rule (see https://github.com/palantir/tslint/issues/711). We also have a rule PR that could conflict with future rules (see https://github.com/palantir/tslint/pull/722). 

To solve these kinds of issues, I propose that TSLint at startup checks its configuration for conflicts, and prints an error and/or aborts if a conflict is found.

**Comment by JoshuaKGoldberg** [comment]
This seems like it won't be happening.
