### ISSUE TITLE
Ability to check promises that miss error handling

### ISSUE THREAD

**Issue by userpixel** [palantir/tslint#744]
I work on a healthcare project where patient safety is extremely important and we really need to make sure that no errors are ignored. We use tslint extensively to improve code quality and consistency (thanks a lot, great tool).

It would be very helpful if there was a rule so that we could check that all promises have an error handler. Something like https://www.npmjs.com/package/thenlint

**Comment by myitcv** [comment]
This is ultimately going to require #680 to be done 'properly' (i.e. catch all situations) I think

**Comment by userpixel** [comment]
Well, I suspect it is complicated due to the chaining feature of promises, but for our application it would help even if all `then()`s are checked to have both their **resolve** and **reject** callbacks.

**Comment by myitcv** [comment]
#680 gives us types for everything, which actually makes it relatively straightforward from that point onwards....

A rough version using string matching could be done now... but probably not worth the effort.

**Comment by nschurmann** [comment]
+1, this is very needed for code consistency in promises chains.

**Comment by nschurmann** [comment]
How is this going?

**Comment by HeorhiiWW** [comment]
Vote on this.Otherwise this is to simple to skip rejected promises. Right now chrome writes to console about unhandled errors in promises but only at runtime when resolve() or throw happens. It would be super cool to check in at build time

**Comment by chrismbarr** [comment]
Just discovered this issue today while searching for a possible tslint solution to this same issue.  We would also love for this to become a rule for all the reasons listed above.

**Comment by ajafff** [comment]
That should be covered by `no-floating-promises`.

**Comment by dscho** [comment]
> That should be covered by `no-floating-promises`.

@ajafff That was my initial understanding, too. But that rule does not cover this case:

```typescript
async function isThisTrue(expression: string): Promise<boolean> {
    ....
}

if (isThisTrue()) {
    ...
}
```

Note how the `if (isThisTrue())` is rather obviously missing the `await`.

Following my analysis in https://github.com/palantir/tslint/issues/3929, I have to conclude that `no-floating-promises` really only cares whether the Promise is assigned or used in any other way. The rule does not care that it is never handled.

Do we need another rule, say, `no-unhandled-promises` that verifies that Promises are either `await`ed, or alternatively handled via `.catch()`?

**Comment by dprogramming** [comment]
> Do we need another rule, say, no-unhandled-promises that verifies that Promises are either awaited, or alternatively handled via .catch()?
Such a rule would be great @dscho! Does something like this exist already?
