### ISSUE TITLE
Add warning/failure when rule is not found or parameter is not found

### ISSUE THREAD

**Issue by HamletDRC** [palantir/tslint#754]
I would like my grunt build to tell me /something/ when my rules file references a rule that is not found or when it references a parameter that is not found. 

A few releases ago the typedef rule parameter "callSignature" changed to "call-signature". I did not realize this and the change effectively turned that rule off for my build. We know have several hundred errors to fix. 

I would like tslint to fail (or optionally fail through a command line parameter) when the rules file defines a rule that cannot be loaded or a parameter is set on a rule that does not exist.

**Comment by JKillian** [comment]
Agreed, this would be a very good thing.
Related: https://github.com/palantir/tslint/issues/629

**Comment by ajafff** [comment]
Enabling a non-existent rule in your tslint.json gives you a warning.
Validating rule options is tracked by #889
