### ISSUE TITLE
New Rule: type operator spacing

### ISSUE THREAD

**Issue by adidahiya** [palantir/tslint#756]
I like this rule and want to bring it into core (as an option for the `whitespace` rule): https://github.com/Microsoft/TypeScript/pull/5366

**Comment by myitcv** [comment]
Agree it's nice, but just worth pointing out that if you enforce in a given project that every file must be formatted via `tsfmt` then it becomes unnecessary.

**Comment by adidahiya** [comment]
duplicate of #488
