### ISSUE TITLE
Link to tslint-microsoft-contrib in README

### ISSUE THREAD

**Issue by JKillian** [palantir/tslint#757]
There are lots of custom rules here, it makes sense to provide a link in the README to them in case users are looking for rules we don't have:
https://github.com/Microsoft/tslint-microsoft-contrib

**Comment by buzinas** [comment]
Is it possible to add [my repository](/buzinas/tslint-eslint-rules) to the README too?

We have all the "recommended" ESLint rules for TSLint, and we'll be adding more every week.

I'll do the PR if you accept that! :)

**Comment by JKillian** [comment]
Yep! Be happy to do that as well. I've delayed on this issue because I want to clean up the documentation and move it to github pages. (Feel like the readme is a little long right now and would benefit from being split up a little more)

**Comment by buzinas** [comment]
@JKillian should I fork master or next branch?

**Comment by buzinas** [comment]
Forked master, let me know if I need to fix anything, please :)

**Comment by JKillian** [comment]
Master was right, thanks!

**Comment by buzinas** [comment]
I appreciate that :)
