### ISSUE TITLE
[no-use-before-declare] Breaks with aliased imports

### ISSUE THREAD

**Issue by blakeembrey** [palantir/tslint#778]
![image](https://cloud.githubusercontent.com/assets/1088987/10982588/f16b6ad8-83c2-11e5-8d41-c4d3879f35c9.png)

Not sure what's technically going on in the linter, but `resolve` is definitely not used before it's defined.

**Comment by adidahiya** [comment]
looks like a bug. we don't have many tests for aliases in binding patterns like that.

**Comment by JKillian** [comment]
@blakeembrey You're seeing the problem because tslint thinks that your `{ resolve as resolveURL }` is you trying to use the `resolve` you imported in the next line. However, I can only seem to duplicate the behavior when I import things from the same module twice. If you don't mind, can you post the full text of your import statements?

**Comment by blakeembrey** [comment]
@JKillian Thanks, I figured. Here's the source: https://github.com/typings/cli/blob/master/src/lib/dependencies.ts#L8-L9.

**Comment by JKillian** [comment]
Thanks @blakeembrey. I'm checking into this in more detail, to find out if it's something we need to fix or if it's a TypeScript bug: https://github.com/Microsoft/TypeScript/issues/5551

**Comment by JKillian** [comment]
:+1: on getting this fixed from @ShadowManu, who also encountered this issue.

**Comment by loicraux** [comment]
```ts
import * as React from 'react';
import ReactTestUtils = React.addons.TestUtils;
```
This is also broken ^^

**Comment by adidahiya** [comment]
in TSLint 5.0, no-use-before-declare uses the compiler's implementation of that check. going to close this as external, let me know if it pops up again. if it persists, it's likely a compiler bug.
