### ISSUE TITLE
Glob in the CLI

### ISSUE THREAD

**Issue by blakeembrey** [palantir/tslint#779]
Any thoughts on using `glob` like https://github.com/substack/tape/blob/master/bin/tape? It'd be useful for consumers of the CLI, especially but the `ignore` option supported.

**Comment by JKillian** [comment]
@blakeembrey Are you using tslint on Windows? If you're using bash or a normal *nix shell, it should expand CLI globs into a list of files for you automatically.

**Comment by blakeembrey** [comment]
@JKillian Yes, I know. But where possible I like to support Windows users.

**Comment by JKillian** [comment]
Yep, that's fair. See https://github.com/palantir/tslint/issues/692 also

**Comment by blakeembrey** [comment]
@JKillian For loading and parsing `tsconfig.json` files there's https://github.com/TypeStrong/tsconfig. However, it's not the same there, since `tsconfig.json` can be only entry points, and the linter doesn't follow imports. That would be a nice feature though, to detect dead code. Maybe that can be another issue, if it sounds reasonable?

**Comment by adidahiya** [comment]
What do you mean `tsconfig.json` can be only entry points? I wasn't aware that's supported.

**Comment by blakeembrey** [comment]
@adidahiya Yes, that's all I ever use. Otherwise `tsconfig.json` wouldn't be maintainable.

**Comment by adidahiya** [comment]
cool. I added this as a sub-issue of #692

**Comment by JKillian** [comment]
Going to close this issue since it's now part of #692. 

Thanks for the report and for the info @blakeembrey. I wasn't aware that tsc would follow imports from files in a `tsconfig.json` file. tslint should do the same thing when linting files based off of `tsconfig.json`.
