### ISSUE TITLE
Left hand side of For...of cannot use type annotation, but tslint requires it

### ISSUE THREAD

**Issue by BrandonCKrueger** [palantir/tslint#786]
When using the TypeScript `for...of` loop, TSLint throws a typedef error expecting the first variable to have a type definition, however that is not allowed in TypeScript.

Sample:
```javascript
let names: string[] = [...]
for (let name in names) {
    ...
}
```

TSLint wants `name` to have a typedef, however that is not allowed in TypeScript.

**Comment by adidahiya** [comment]
duplicate of #743
