### ISSUE TITLE
"[file ...]" in the usage does not match the reality

### ISSUE THREAD

**Issue by radek-holy** [palantir/tslint#789]
AFAIK, "[]" means that the argument is optional. However, running just `tslint` outputs:

> Usage: /usr/bin/node ./node_modules/.bin/tslint [options] [file ...]
> 
> Options:
>  -c, --config          configuration file
>  -h, --help            display detailed help
>  -o, --out             output file
>  -r, --rules-dir       rules directory
>  -s, --formatters-dir  formatters directory
>  -t, --format          output format (prose, json, verbose)  [default: "prose"]
>  -v, --version         current version
>
> Missing files

and returns a non-zero exit status. I guess that it shouldn't at least return the non-zero code if the usage is valid.

The brackets are present both in the README and in the CLI output.

**Comment by JKillian** [comment]
Good point @radek-holy, thanks for the heads-up. I think the best way to solve this is by just removing the brackets, as you really do have to have at least one file.
