### ISSUE TITLE
TypeScript version dependency for tslint@next

### ISSUE THREAD

**Issue by myitcv** [palantir/tslint#791]
Picking up on https://github.com/palantir/tslint/pull/726#issuecomment-151720524

Specifically:

> I think we ought to fix TS to a specific version for the `next` branch. So instead of the dependency being `typescript: next`, we ought to fix it to something like `typescript: 1.8.0-dev.20151027` and then update that each week.

At the moment with `tslint@next` depending on `typescript@next` this forces our project to also depend on `typescript@next`. Otherwise, we see errors like [these](https://github.com/palantir/tslint/pull/726#issuecomment-151715202). 

But being forced to depend on `typescript@next` means our CI build is not stable from one day to the next (because `typescript@next` points to a nightly build)

One option would be to fix the dependency as [suggested by @JKillian](https://github.com/palantir/tslint/pull/726#issuecomment-151720524) and bump on a weekly basis. This has the downside of constraining our project to also depend on that same version and only moving when `tslint@next` updates its dependency.

Would it instead be possible to have `tslint@next` depend on TypeScript as a peer dependency? Would that work?

I'll admit now I don't understand all the factors at play here.. so please dismiss this suggestion if it's a load of rubbish!

cc @weswigham given his previous thoughts/comments on this topic

**Comment by adidahiya** [comment]
Thanks for bringing this up again and the writeup! I'm in favor of making TS a peer dependency. That makes it so TS is installed in a deterministic location for `tslint`, custom rules, and apps to consume.

**Comment by JKillian** [comment]
@myitcv Do you think this should also be done for the master branch?

**Comment by adidahiya** [comment]
I think we should do the same on the master branch, yes. We'll make that change with 3.0, for same reason I mentioned above (deterministic location for tsc).

**Comment by myitcv** [comment]
Sounds good @adidahiya @JKillian

**Comment by adidahiya** [comment]
published `3.0.0-dev.3` with the peer dependency change.

**Comment by adidahiya** [comment]
3.0 release PR: #804
