### ISSUE TITLE
Possibility to add the rulesDirectory property in tslint.json

### ISSUE THREAD

**Issue by buzinas** [palantir/tslint#795]
Today we have a single property named `rules` in our `tslint.json` file.

I would like to have the ability to put a `rulesDirectory` property, instead of having to use the CLI for that:

```json
{
  "rulesDirectory": "dist/rules",
  "rules": {
    "no-constant-condition": true,
    "no-any": true
  }
}
```

It's difficult to tell people to run `tslint [file] -r node_modules/[package name]/[folder]/rules`.

That suggestion would be great in addition to #590, e.g:

```json
{
  "rulesDirectory": ["dist/rules", "node_modules/tslint-eslint-rules/dist/rules"],
  "rules": {
    "no-constant-condition": true,
    "no-any": true
  }
}
```

Btw, I'm open to contribute with a pull request if needed.

**Comment by adidahiya** [comment]
sounds great. I prefer this over the proposed options in #590 and would like to move towards having `tslint.json` contain the majority of TSLint options (just like `tsconfig.json`).

**Comment by buzinas** [comment]
@adidahiya created the pull request #800.
