### ISSUE TITLE
Rule to force any type definition if expression type is inferred as any

### ISSUE THREAD

**Issue by gerich-home** [palantir/tslint#80]
It would be cool to have a rule that forces you to specify any keyword expliciltly if compiler infer variable type as any:

function convert(x: any): any {
    ...
}

var person = { Name: "Pedro" };
var personObservable = f(person); // type is not set explicitly

**Comment by marknadig** [comment]
@ashwinr any update on this? I was surprised that the linter complained when I:
for (var i = 0;....

and it wanted me to type 'i'.
