### ISSUE TITLE
Tautology Checker in Conditions

### ISSUE THREAD

**Issue by JKillian** [palantir/tslint#803]
I was writing code to check if two objects were equivalent and wrote code like this:

``` typescript
function areEqual(obj1: SomeClass, obj2: SomeClass) {
return obj1 != null
    && obj2 != null
    && obj1.foo === obj1.foo
    && obj1.foo === obj2.bar
    && obj1.baz === obj2.baz
}
```

The error in the code above is comparing `obj1.foo === obj1.foo`. In very few cases is an obviously true condition like this actually what the developer intended. While tslint probably doesn't want to be attempting to evaluate expressions on each side of a condition, it could do a simple textual comparison to catch mistakes like this.

**Comment by noamyogev84** [comment]
Hi @JKillian ,I'd like to tackle this one.
Can you share some code pointers?
