### ISSUE TITLE
missing use strict

### ISSUE THREAD

**Issue by RandallFlagg** [palantir/tslint#807]
If I am not mistaken this message should not appear if I have "use strict"; in the head of the file.

Using TS 1.6 in VS2015 using the [Web Analyzer extension](https://visualstudiogallery.msdn.microsoft.com/6edc26d4-47d8-4987-82ee-7c820d79be1d) I get this error on all of my functions.

This is the same as: https://github.com/palantir/tslint/issues/344

The reason for closing is not clear as the issue still exist and should not be like that.

**Comment by adidahiya** [comment]
you're right; i'll reopen the original issue and clarify its title
