### ISSUE TITLE
Documentation Overhaul

### ISSUE THREAD

**Issue by JKillian** [palantir/tslint#830]
#### Problem

There are two current sources of documentation: the [README](https://github.com/palantir/tslint/blob/07cfb439f174895c959495d2a6b0d870c8cd3dbb/README.md) and  the [Github Pages site](http://palantir.github.io/tslint/). ~~The GitHub pages site is out-of-date and visually hard to read. Currently, it should not be used or referenced at all.~~ The README is up-to-date but very long and hard to quickly grok. The current GitHub pages site has the exact same structure and content as the README.
#### Proposal

Keeping all documentation in the README isn't sustainable or user-friendly. Moving content to the built-in wiki isn't a great idea because the [collaborative features are lacking](https://github.com/isaacs/github/issues/333). Instead, let's redo the GitHub pages site and make it the authoritative documentation source. The README will simply contain headings and links to the most important pages in the documentation.

_Questions:_
- What tooling do we want to use to create/maintain the site? Jekyll? Or something else? _Answer: We're using Jekyll, I'm a big fan of its combination of simplicity and features_

_Fancy Possible Features:_
- Generate documentation of rules automatically from metadata contained in each rule (#674). _Edit: This is in progress now_

**Comment by adidahiya** [comment]
related: #531

**Comment by szahn** [comment]
It would be helpful to have an explanation and example of some of the rules and how they affect quality as I'm not sure how too much or too little white space affects code quality. Some of these rules may be more about style and writing error-free code, but a guide outlining the differences between style and quality would be helpful. The following rules were especially confusing to me as I couldn't figure out how important they are to overall quality: align, member-ordering, whitespace.

**Comment by myitcv** [comment]
Also related, [this comment](https://github.com/palantir/tslint/issues/717#issuecomment-145749210)

**Comment by JKillian** [comment]
[Website](http://palantir.github.io/tslint/) updated so it's at least readable and reflects the content of the current README. More changes coming in the future

**Comment by JKillian** [comment]
[Reference](https://gist.github.com/chrisjacob/833223#gistcomment-1627809) for a good way to set things up so that you can generate documentation for source code easily onto the gh-pages branch.

**Comment by JKillian** [comment]
The new documentation site is progressing slowly: http://palantir.github.io/tslint/
It's (very obviously) a WIP, so if anyone is interested in contributing their design or Jekyll skills, let me know!
