### ISSUE TITLE
Remove node 0.10 from Travis CI

### ISSUE THREAD

**Issue by adidahiya** [palantir/tslint#835]
It slows down our builds.

I don't think it's really relevant anymore, is it?

**Comment by JKillian** [comment]
I'd like the CI to be faster as well. However, not sure removing  Node 0.10 is a good idea yet. I asked in the node IRC room, they recommended still supporting 0.10, as some of the major linux distros still ship with it. I checked the [Debian package list](https://packages.debian.org/stable/web/) and it looks like they still ship 0.10.

**Comment by adidahiya** [comment]
cool, ok, we'll wait a bit longer until 0.10 is truly deprecated.
