### ISSUE TITLE
ES6 destructuring causes exception when running tslint as a dependency

### ISSUE THREAD

**Issue by jseanxu** [palantir/tslint#837]
Slightly modified the README sample as `lint.js`:
```js
var fileName = "test.ts";
 
var configuration = {
    rules: {
        "no-unused-variable": true
    }
};
 
var options = {
    formatter: "json",
    configuration: configuration,
    rulesDirectory: "customRules/",
    formattersDirectory: "customFormatters/"
};
 
var Linter = require("tslint");
var fs = require("fs");
var contents = fs.readFileSync(fileName, "utf8");
 
var ll = new Linter(fileName, contents, options);
var result = ll.lint();
```

Where the contents of `test.js` is simply:
```js
import something from "something";
```

...then running:
```node lint.js```

...causes this error:
```
node_modules\tslint\lib\rules\noUnusedVariableRule.js:142
        var moduleSpecifier = importDeclaration.moduleSpecifier.getText();
                                               ^

TypeError: Cannot read property 'moduleSpecifier' of undefined
    at NoUnusedVariablesWalker.visitNamespaceImport
...
```

This __only__ repros when using tslint as a node dependency, running the tslint cli works fine. This might be related to or a regression of #399?

**Comment by adidahiya** [comment]
@jseanxu thanks for the detailed report. Which versions of TSLint and TypeScript are you using?

**Comment by jseanxu** [comment]
Latest versions today, so `tslint@3.1.0` and `typescript@1.7.3`

**Comment by JKillian** [comment]
This seems to me like something weird going on with the version of TS that tslint is using when running and perhaps the version of TS that it was compiled with. But if you're using `tslint@3.1.0` and `typescript@1.7.3` you should be fine. Just to play it safe, can you delete your `node_modules` directory, reinstall your dependencies and see if the error still occurs?

**Comment by jseanxu** [comment]
3.1.0 still repros this issue, but 3.1.1 fixed it :)
