### ISSUE TITLE
Custom Rules Dont Load

### ISSUE THREAD

**Issue by harry8525** [palantir/tslint#853]
Hey,

So I tried upgrading to the newest TSLint and hit an issue with our custom rules not loading. After some debugging I found issues with this commit https://github.com/palantir/tslint/commit/524adba3aee69407c19d2be9b5c54fa99d50e55c . The issue is that getRulesDirectories gets called twice during linting on the same set of rule directories which causes getRelativePath to be called twice. This of course messes up looking up the rules because the base path duplicated twice :(

You can see both calls from here:
Call 1: https://github.com/palantir/tslint/commit/524adba3aee69407c19d2be9b5c54fa99d50e55c#diff-ededbfb45b98df37e86145d291a6344fR46
Call To loadRules: https://github.com/palantir/tslint/commit/524adba3aee69407c19d2be9b5c54fa99d50e55c#diff-ededbfb45b98df37e86145d291a6344fR48
Call to findRule: https://github.com/palantir/tslint/commit/524adba3aee69407c19d2be9b5c54fa99d50e55c#diff-a3e85752b29612a2eceb177a33556d2fR38
Call to getRulesDirectory number 2: https://github.com/palantir/tslint/commit/524adba3aee69407c19d2be9b5c54fa99d50e55c#diff-a3e85752b29612a2eceb177a33556d2fR61

I think the proper fix is to probably make a non public find rule and have it not call getRulesDirectory and then have the public one call the non public one after calling getRulesDirectory.

Thanks,

Harry

**Comment by adidahiya** [comment]
hi @harry8525, this was actually fixed by #844 but we haven't cut a release with the fix yet. I'll try to make a release sometime in the next couple days!

**Comment by harry8525** [comment]
Awesome Thanks!

**Comment by adidahiya** [comment]
@harry8525 I just published v3.2.0-dev.1 on the "next" dist-tag. Can you try it out to verify the fix? `npm install tslint@next`. Thanks!

**Comment by thomas-darling** [comment]
I was having the same issue, with custom rules not being loaded.
I can confirm that this fixed it for me - thanks!
