### ISSUE TITLE
Location of tslint.json

### ISSUE THREAD

**Issue by indiesquidge** [palantir/tslint#859]
Thanks for making this linter. I am running into some issues when trying to configure my `tslint.json`. Unless I have the `tslint.json` file in the same directory as the file I am running it against, I get no errors. The only other location that appears to give errors is when I configure a global `tslint.json` at the root of my home directory.

Is there now way to have a `tslint.json` configured on a per-project basis? I would prefer to have project-level linting configuration, if that is at all possible.

Thank you.

**Comment by adidahiya** [comment]
are you using the CLI? there's a command line flag to point to a specific `tslint.json` filepath

**Comment by indiesquidge** [comment]
I'm not running it from the CLI but rather from inside a Vim buffer. The errors are showing up with Syntastic. I originally had the `tslint.json` file in `src/ts/tslint.json` while my files were in `src/modules/app/`, which was not working at all. If I move the `tslint.json` into the root directory of the project (same level as `/src/`) then it works. This is better, and makes sense to me. The thing is, the project is not just mine, and I would prefer to not have to move the `tslint.json` file away from where it is now, because it seems to be working for other people on the team who are using. However, if the only solution is to get it in the root directory of the project, that is good enough.

**Comment by adidahiya** [comment]
Yeah I can't imagine how we would auto-detect a config file at `src/ts/tslint.json` if `tslint` is run with cwd `src/modules/app/`. So I'm going to close this with the answer "use the config option in the CLI or Node API".

**Comment by indiesquidge** [comment]
@adidahiya, my apologies. Apparently the file _wasn't_ working in that location for other people, they had just thought it was so it looked like it was only me having the issue. It works fine in the project root and has since been moved there. Thanks for your time.
