### ISSUE TITLE
max-line-length configurable separately for code & comments?

### ISSUE THREAD

**Issue by Bartvds** [palantir/tslint#86]
This is a vague idea for your feedback:

Would it make sense to be able to customise/toggle `max-line-length` rule independently for code and comments?

I ask because on DefinitelyTyped we might (one day) [lint the definitions](https://github.com/borisyankov/DefinitelyTyped/issues/1569) but have a conceptual complication:

The declaration statements themselves can get quite lengthy, with all the generics and creative hackery needed to make them match the libraries. 

But then the comments (JSDoc or regular) are slightly different case. There is no real reason to let them get out of hand, especially if users might navigate to the definition file to find out how to use the module. Then something like ~120 cols would be more optimal.

What do you think? Is this a general case?

**Comment by blacktaxi** [comment]
What's the preferred workaround in case I don't want to implement my own rule? `tslint:disable` before and `tslint:enable` after? Since you can't `// tslint:disable-line` if the line is a comment already. Which is my use case – long URLs in comments.

**Comment by adidahiya** [comment]
@blacktaxi you can try `// tslint:disable-next-line`
