### ISSUE TITLE
Multi type function property: Cannot invoke an expression whose type lacka a call signature

### ISSUE THREAD

**Issue by unional** [palantir/tslint#862]
````
interface Route {
  match: ((context: RouteContext) => any) | string | RegExp
}
````

![image](https://cloud.githubusercontent.com/assets/3254987/11701913/605bdb38-9e87-11e5-982e-32d884560541.png)

**Comment by adidahiya** [comment]
That is a TS error in Atom. TSLint errors are yellow and say "TSLint" instead of "TS".
