### ISSUE TITLE
Documentation On Custom Rules Not clear

### ISSUE THREAD

**Issue by mconner** [palantir/tslint#864]
I'm trying to compile a custom rule, following the instructions in the wiki page
[https://github.com/palantir/tslint/wiki/Custom-Rules].  When I compile, it can't find tslint.d.ts:
```
C:\tmp\tsrule>tsc -m commonjs --noImplicitAny noImportsRule.ts tslint.d.ts
error TS6053: File 'tslint.d.ts' not found.
```
I find it in my node_modules, and adjust, but get: 
```
C:\tmp\tsrule>tsc -m commonjs --noImplicitAny noImportsRule.ts C:\Users\mconner\AppData\Roaming\npm\node_modules\tslint\lib\tslint.d.ts
noImportsRule.ts(1,23): error TS2307: Cannot find module 'tslint/lib/lint'.
noImportsRule.ts(2,21): error TS2307: Cannot find module 'tslint/node_modules/typescript'.
noImportsRule.ts(8,21): error TS2339: Property 'applyWithWalker' does not exist on type 'Rule'.
noImportsRule.ts(8,37): error TS2346: Supplied parameters do not match any signature of call target.
noImportsRule.ts(8,74): error TS2339: Property 'getOptions' does not exist on type 'Rule'.
noImportsRule.ts(15,14): error TS2339: Property 'addFailure' does not exist on type 'NoImportsWalker'.
noImportsRule.ts(15,30): error TS2339: Property 'createFailure' does not exist on type 'NoImportsWalker'.
```
So, please document what setup is necessary to get this to compile?

**Comment by adidahiya** [comment]
which version of `tsc` are you using?

**Comment by JKillian** [comment]
@mconner The wiki isn't necessarily an up-to-date source of information - this is my fault, I was looking at migrating the majority of our documentation to the wiki, but decided not to for various reasons. (I've gone ahead and disabled the wiki now.) The corresponding section in the README should be up-to-date.

**Comment by mconner** [comment]
OK, I'm clearly not an expert on node/npm.  I thought the install instructions were either/or.  I ran the global install (CLI), and not the library.  So I didn't have the node_modules in the dir where I was doing the compile, and I guess I assumed that tsc somehow referenced npm. (In retrospect, I'm not really sure what I was thinking, there).   Once I ran the lib, it worked.  Thanks!

**Comment by JKillian** [comment]
No worries! We should probably elaborate a little bit more on when you'd want to install it globally vs. locally.
