### ISSUE TITLE
Rule Suggestion: Check for string.indexOf(...) == null

### ISSUE THREAD

**Issue by elisee** [palantir/tslint#872]
A common error is comparing the result of `string1.indexOf(string2)` to `null` instead of `-1`. A rule to check for that would be nice.

**Comment by adidahiya** [comment]
This seems pretty specific and doesn't generalize beyond `String.prototype.indexOf()`. `null` comparisons should always be allowed (unless you've turned on the `no-null-keyword` rule, of course), so it wouldn't help to compare the return type of `indexOf` with `null` and report a lint failure. I'd encourage you to create a [custom rule](https://github.com/palantir/tslint#writing-custom-rules) in your codebase for this.

**Comment by elisee** [comment]
My take was that it is a common-enough gotcha that it made sense as a default rule. Nobody ever wants to do `string.indexOf(...) == null` on purpose, and without it, you won't catch the bug until runtime.

I'll give a go at writing a custom rule for it and try and post a link here when/if I get around to it.
