### ISSUE TITLE
trailing-comma option for object literal with one key, but written over multiple lines

### ISSUE THREAD

**Issue by Zjaaspoer** [palantir/tslint#876]
The option `singleline: always/never` seems to treat these two both as `singleline`:

```
let foo = {foo: 'bar'}
````
```
let foo = {
  foo: 'bar',
}
```
As I love this rule for keeping my code properly formatted for (irrelevant) conflict free merges I would really appreciate if I can distinguish between the two.

As the first one doesn't need a trailing comma, but the second one does.

(or am I missing something? :) )

**Comment by adidahiya** [comment]
I updated your comment to what I believe was your intended formatting. Let me know if this was wrong.

Looks like a duplicate of #856

**Comment by Zjaaspoer** [comment]
Indeed! You we're right with the formatting, and right about this issue being a duplicate. Sorry I didn't find that one my self :)
