### ISSUE TITLE
Deprecate `label-undefined` rule (covered by compiler)

### ISSUE THREAD

**Issue by JKillian** [palantir/tslint#877]
I think the `label-undefined` rule is covered by `tsc`:

```ts
foo: while (false) { }
while (true) { break foo; }
// => error TS1116: A 'break' statement can only jump to a label of an enclosing statement.
```

**Comment by adidahiya** [comment]
Is it exactly the same error? Can you try compiling `labelundefined.test.ts`? From a brief review of the source, it looks very similar but our rule expects labels to be in the same scope, whereas the compiler check expects the `break` / `continue` to go to a more specific location?

**Comment by JKillian** [comment]
For the test file, the compiler generates lots of these:

```
main.ts(6,9): error TS1107: Jump target cannot cross function boundary.
```

Seems like its got things pretty well-covered, I'm not sure what else this rule could really check for.

**Comment by adidahiya** [comment]
Cool, let's deprecate the rule.
