### ISSUE TITLE
Complement to [one-line]?

### ISSUE THREAD

**Issue by Bartvds** [palantir/tslint#88]
Is it possible to enforce this style of having some blocks on the next line from the expression preceding them? Like the reverse of [one-line]

```
if (foo) {
    // ...
}
else {
    // ...
}
```

```
try {
    // ...
}
catch (e) {
    // ...
}
```

**Comment by VolleMelk** [comment]
Is there any news on this? I would really like to enforce if/else etc on the next line. This is a very old issue, do you have a solution for your rule-conflict situation? (ie: `one-line` and `next-line`) can be enabled simultaneously.

Maybe it should be possible to enable them at the same time. Then you can do something like

```json
    "one-line": [
      true,
      "check-open-brace",
      "check-else",
      "check-whitespace"
    ],
    "next-line": [
      true,
      "check-finally",
      "check-catch"
    ]
```

Why one would want this, don't ask me.. But it's always nice to find a use-case to unwanted behaviour ;-) Just let the last definition of `check-*` win

**Comment by glen-84** [comment]
I am/was considering using a PHP [PSR-2](http://www.php-fig.org/psr/psr-2/) style, where classes, interfaces, and methods have the brace on a new line, and if/else/try/catch/etc. have it on the same line.

Simple example:

```ts
class Example
{
    public method(): void
    {
        if (true) {
            // ...
        } else {
            // ...
        }
    }
}
```

I think it looks neat, albeit not so common in the JS/TS world.

It might make sense to support this as well (i.e. allow each brace position to be specified individually).

**Comment by linusbrolin** [comment]
I also prefer using next-line for `else`, `catch` and `finally`.
The rules would look something like this for me:

    "one-line": [
      true,
      "check-open-brace",
      "check-whitespace"
    ],
    "next-line": [
      true,
      "check-else",
      "check-catch",
      "check-finally"
    ]

Basically, I want to force open braces to be on the previous line, and close braces to be on a new line.
Similarly, I do not want to allow this:

    if (test === 1) {
      // do stuff
    } if (test !== 1 && test2 === 1) {
      // do stuff
    } else if (test !== 1 && test2 === 2) {
      // do stuff
    } else {
      // do stuff
    }

Instead, I would want to force the above like this:

    if (test === 1) {
      // do stuff
    }
    if (test !== 1 && test2 === 1) {
      // do stuff
    }
    else if (test !== 1 && test2 === 2) {
      // do stuff
    }
    else {
      // do stuff
    }

It makes it way more readable in my opinion.
Also, it makes it possible to put a debug breakpoint on each if statement, if one would want to, which would not be possible in the one-line approach.
I just think it makes more sense.

**Comment by JoshuaKGoldberg** [comment]
Closing this issue per #4534. Thanks for the discussion, folks!
