### ISSUE TITLE
Suggestion: Rule for Lambda pitfalls

### ISSUE THREAD

**Issue by aersamkull** [palantir/tslint#882]
I discovered some code in our project like this:
```TypeScript
{
            additonalData: () => { RoleId: 0; OrganisationUnitId: 0 }
}
```
What was actually intended was something like this:
```TypeScript
{
            additonalData: () => ({ RoleId: 0, OrganisationUnitId: 0 })
}
```
It is even worse with the following example:
```TypeScript
() => { RoleId: 0 } // Compiles to:  additonalData: function () { RoleId: _this.roleId; }
() => ({ RoleId: 0 }) // Compiles to: additonalData: function () { return ({ RoleId: _this.roleId }); }
```
Can we me a rule for this? any ideas? 
Something like ()=>{ }  without any assignment/increment/decrement/return Statement is forbidden?

**Comment by myitcv** [comment]
The rule could, I think, be made to simply ban `LabeledStatement`'s:

```typescript
x: 5;
```

This would then cover your lambda scenario.

**Comment by JKillian** [comment]
@aersamkull If you use the [`label-position` rule](http://palantir.github.io/tslint/rules/label-position/) does it catch your bug?

**Comment by myitcv** [comment]
@aersamkull also worth noting that in `typescript@next` (`1.8.0-dev.20151220` at the time of writing) the following generates a compile error:

```typescript
let y = () => {x: 5};
``` 

```
app.ts(1,16): error TS7028: Unused label.
```

**Comment by myitcv** [comment]
(sorry previous message sent too early) 

...which would make such a rule unnecessary.

**Comment by aersamkull** [comment]
Ok, label-position makes the thing. Thank you!
