### ISSUE TITLE
class extended by namespace — variable used before declaration

### ISSUE THREAD

**Issue by Avol-V** [palantir/tslint#884]
In TypeScript we can merge namespaces with classes, and class declaration must be before namespace declaration, but tslint gives an error:

``` typescript
class Test
{
    public method(): void
    {
        console.log( Test.TEST_CONST ); // variable used before declaration
    }
}
namespace Test
{
    export const TEST_CONST: number = 1;
}
```

**Comment by JKillian** [comment]
Thanks for the report @Avol-V! Looks like a bug to me

**Comment by JKillian** [comment]
This is a little bit tricky, because the variable is being used before its declaration (although that's what one must do in this case). I'm unsure of the best way to special-case this construct.

**Comment by JoshuaKGoldberg** [comment]
`no-use-before-declare`, per its description, is generally discouraged and kept around for legacy purposes. Closing this issue for housekeeping.
