### ISSUE TITLE
NoUseBeforeDeclareWalker.validateUsageForVariable aborted

### ISSUE THREAD

**Issue by reversi-fun** [palantir/tslint#886]
the code is:

```ts
var radius = 12;
//const PI = 3.14;
with (Math) {
    var area = PI * radius * radius;
}
console.log(area)
////
```

its causes:

```
TypeError: Cannot read property 'length' of undefined
    at NoUseBeforeDeclareWalker.validateUsageForVariable \node_modules\tslint\build\rules\noUseBeforeDeclareRule.js:90:41
)
    at NoUseBeforeDeclareWalker.visitVariableDeclaration node_modules\tslint\build\rules\noUseBeforeDeclareRule.js:82:18
)
    at NoUseBeforeDeclareWalker.SyntaxWalker.visitNode (node_modules\tslint\bin\tslint-cli.js:49761:26)
    at NoUseBeforeDeclareWalker.ScopeAwareRuleWalker.visitNode (node_modules\tslint\bin\tslint-cli.js:49903:40)
    at node_modules\tslint\bin\tslint-cli
.js:49776:67
    at visitEachNode (node_modules\tslint
\bin\tslint-cli.js:7209:30)
    at Object.forEachChild (node_modules\
tslint\bin\tslint-cli.js:7367:24)
    at NoUseBeforeDeclareWalker.SyntaxWalker.walkChildren (\node_modules\tslint\bin\tslint-cli.js:49776:16)
    at NoUseBeforeDeclareWalker.SyntaxWalker.visitNode (node_modules\tslint\bin\tslint-cli.js:49770:26)
    at NoUseBeforeDeclareWalker.ScopeAwareRuleWalker.visitNode (node_modules\tslint\bin\tslint-cli.js:49903:40)
//
```

Using TSLint 3.2.0 and TS 1.7.5

**Comment by jumnichi-kose** [comment]
├─┬ tslint@3.2.0
│ ├─┬ findup-sync@0.2.1
│ │ └─┬ glob@4.3.5
│ │   ├─┬ inflight@1.0.4
│ │   │ └── wrappy@1.0.1
│ │   ├── inherits@2.0.1
│ │   ├─┬ minimatch@2.0.10
│ │   │ └─┬ brace-expansion@1.1.2
│ │   │   ├── balanced-match@0.3.0
│ │   │   └── concat-map@0.0.1
│ │   └─┬ once@1.3.3
│ │     └── wrappy@1.0.1
│ ├─┬ glob@6.0.1
│ │ ├─┬ inflight@1.0.4
│ │ │ └── wrappy@1.0.1
│ │ ├── inherits@2.0.1
│ │ ├─┬ minimatch@3.0.0
│ │ │ └─┬ brace-expansion@1.1.2
│ │ │   ├── balanced-match@0.3.0
│ │ │   └── concat-map@0.0.1
│ │ ├─┬ once@1.3.3
│ │ │ └── wrappy@1.0.1
│ │ └── path-is-absolute@1.0.0
│ ├─┬ optimist@0.6.1
│ │ ├── minimist@0.0.10
│ │ └── wordwrap@0.0.3
│ └── underscore.string@3.1.1
├─┬ tslint-eslint-rules@1.0.1
│ └─┬ doctrine@0.7.2
│   ├── esutils@1.1.6
│   └── isarray@0.0.1
├── tslint-microsoft-contrib@1.0.0
└── typescript@1.7.5

**Comment by JKillian** [comment]
Thanks for the bug report @jumnichi-kose! 

The error almost certainly has to do with the presence of the `with` statement in that code. I'd recommend avoiding `with` if possible, as [its use is generally discouraged](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/with).

**Comment by jumnichi-kose** [comment]
Thanks for acceptance NoUseBeforeDeclare Bug report.

But, I  want to feature of "no use Variable of with".
for example , reporting to the "PI" or other many  imported Valiables .
I want  TSLint  to enumerate all of the token that must be corrected.
(as "PI"  replace  to "Math.PI" and many other Tokens.)

**Comment by adidahiya** [comment]
Sure, you are free to use the `with` syntax, and we are open to accepting PRs which prevent TSLint from crashing on that syntax in cases like this. However this is pretty low priority for us since `with` is generally accepted as bad practice in JavaScript, and the clear workaround is to remove its usage.

**Comment by reversi-fun** [comment]
I see.
