### ISSUE TITLE
`no-unused-expression` should permit `await`

### ISSUE THREAD

**Issue by andy-hanson** [palantir/tslint#887]
The following code causes a linter error:

	async function f(foo: Promise<void>): Promise<number> {
		await foo
		return 0
	}

The output I get is:

	src/foo.ts[2, 2]: expected an assignment or function call

Here's my `tslint.json`:

	{
		"rules": {
			"no-unused-expression": true
		}
	}

**Comment by JKillian** [comment]
Thanks for the bug report @andy-hanson. I bet the issue comes from not handling `await` statements correctly. What versions of `tsc` does this apply to with which compiler settings? I know `async`/`await` support is still somewhat limited, correct?

**Comment by andy-hanson** [comment]
This is tested with typescript 1.7.5, using `tslint src/*.ts --target ES6`. `await foo()` does work, as does `const x = await foo`.

**Comment by JKillian** [comment]
@andy-hanson This is fixed on master now, and we'll likely do a release on NPM within the next week or so.

**Comment by adidahiya** [comment]
fix is available in `tslint@next` (v3.2.2-dev.1)
