### ISSUE TITLE
Feature request: typedef-whitespace should have options for both sides of colons

### ISSUE THREAD

**Issue by andy-hanson** [palantir/tslint#888]
`"typedef-whitespace": [true, {"call-signature": "space"}]` permits a missing space on the right side:

	function f() :number {
		return 0
	}

Wheras "nospace" permits a space on the right side:

	function f(): number {
		return 0
	}

I think this rule should have options for ensuring space on both sides of a colon.
People selecting `space` likely want everything to look like `foo : bar` and not `foo :bar`.
People selecting `nospace` may vary; personally I want to mandate `foo: bar` and forbid `foo:bar` (this is what http://www.typescriptlang.org/Handbook uses), but many likely want the opposite.

**Comment by JKillian** [comment]
Agreed, it's somewhat limited / counterintuitive as it is now.

**Comment by b0r3as** [comment]
The first thing, that is still unclear to me, is, if the `"space"` option means exactly one space or at least one space. The latter is currently implemented. Should all three cases be configurable (nospace, space, spaces) or is either exactly one or at least one space preferable?

Secondly, how should we handle the configuration of whitespace after the colon? I propose something like this:

```json
"typedef-whitespace": [
  true,
  {
    "call-signature": {
      "left": "nospace/space/spaces",
      "right": "nospace/space/spaces"
    },
    "index-signature": "nospace/space/spaces"
  }
]
```

The second form, demonstrated with `"index-signature"`, could either be used as a shorthand, if both left and right are equal or could retain the current functionality for compatibility reasons.

Any thoughts on this? I would be willing to make a PR if we can agree on a specification.
