### ISSUE TITLE
wrong linting semicolon when using string literal type in atom

### ISSUE THREAD

**Issue by techird** [palantir/tslint#903]
Screenshot

![image](https://cloud.githubusercontent.com/assets/1901286/12190108/b7fdaf76-b5ff-11e5-9d53-dd13141d9f67.png)

**Comment by JKillian** [comment]
@techird It's possible that the TSLint is using a 1.7.x version of TS which doesn't recognize string literal types correctly. [linter-tslint's package.json](https://github.com/AtomLinter/linter-tslint/blob/master/package.json) specifies a TypeScript version of `>=1.7.5` which unfortunately will not match prerelease versions like the line of 1.8 nightlies that TypeScript releases. If you swap out the older version of TypeScript for a newer nightly version, does the error go away? Not 100% sure, but I'd look in `~./atom/packages/linter-tslint/node_modules/tslint/node_modules/typescript`.

**Comment by techird** [comment]
@JKillian That's true! I used to consider that string liternals was supported in 1.7.x.

**Comment by JKillian** [comment]
@techird I just verified that this issue goes away if you're using a TypeScript nightly release. Looks like this isn't a bug then, which is good!

**Comment by polshgiant** [comment]
@JKillian I'm getting the missing semicolon error everywhere we have unioned string literal types like in the screenshot.  We're using gulp-tslint 5.0.0 and TS 1.8.3.  How would I determine if the issue is with tslint or gulp-tslint?

**Comment by JKillian** [comment]
Hmm, hard to say, although the root cause sounds like an old version of `typescript` itself somewhere in the mix. If you run `npm ls tslint gulp-tslint typescript` what output do you get?

**Comment by polshgiant** [comment]
ASP.NET@1.0.0 G:\snip\main\Library
├── gulp-tslint@5.0.0
├── UNMET PEER DEPENDENCY tslint@3.2.2 extraneous
└── typescript@1.7.5  extraneous

npm ERR! peer dep missing: tslint@^3.7.3 || 3.7.0-dev.5 || >=3.8.0-dev || >=3.9.0-dev || >=3.10.0-dev || >=3.11.0-dev, required by gulp-tslint@5.0.0
npm ERR! extraneous: typescript@1.7.5 G:\snip\main\Library\node_modules\typescript

**Comment by JKillian** [comment]
Ah, that explains it! You'll need at least TypeScript 1.8 to have string literal types supported. I'd also recommend upgrading to the most recent version of TSLint, 3.10.1. Lots of good new rules and bugfixes and such, all listed [in the CHANGELOG](https://github.com/palantir/tslint/blob/master/CHANGELOG.md) 😄
