### ISSUE TITLE
I want to suppress the no-Unused-Valiable under the "declare module"

### ISSUE THREAD

**Issue by reversi-fun** [palantir/tslint#914]
In my private repository, I tried to fix.
I  would like to be re-examined by you.
https://github.com/reversi-fun/tslint-microsoft-contrib/blob/master/src/agUnusedVarsRule.ts
This code is not microsoft's. it 's my OWN.

**Comment by adidahiya** [comment]
can you elaborate a bit? what was broken? what was the expected result from the linter and how did the actual result differ?

**Comment by reversi-fun** [comment]
>actual result differ?

declare module M {
function f(a,b); // default "no-Unused-Valiable " linter is reject.
//   but my fix is supress error,because function body is un-needed.
}
module M {
function f(a,b) {// body is needed
 // is args a and b is no-Unused-Valiable , it rejects
}
}

**Comment by adidahiya** [comment]
I don't see `declare module` used in the file you linked. Do you have a more realistic piece of sample code?

`declare module` is for ambient typings

**Comment by johnwiseheart** [comment]
I think we can close this, as it seems to be a request for help for a rule and is now significantly dated. Feel free to re-open if you're still having this issue.
