### ISSUE TITLE
Add docs/api-example.js and tonicExampleFilename to package.json

### ISSUE THREAD

**Issue by adidahiya** [palantir/tslint#920]
A tonic "try it out" link is added to our [NPM page](https://www.npmjs.com/package/tslint) automatically. Might as well provide a template for the [generated snippet](https://tonicdev.com/npm/tslint).

**Comment by ajafff** [comment]
Does this add any benefit for the average user?
Most of the users would want to try the rules instead of playing around with the API.

**Comment by adidahiya** [comment]
Yeah, that's fair. This is a pretty random FR, I'm going to close it out.
