### ISSUE TITLE
Line-break in a return statement causes "unreachable code" error

### ISSUE THREAD

**Issue by YetiCGN** [palantir/tslint#927]
This code validates fine:
```typescript
return (this.intervalInMilliseconds >= 10000) && (this.intervalInMilliseconds <= 100000);
```
while this does not (error "unreachable code" after the semicolon):
```typescript
return
	// Validate minimum interval
	(this.intervalInMilliseconds >= 10000)
	&&
	// Validate maximum interval
	(this.intervalInMilliseconds <= 100000)
;
```

Additionally, the error is also caused by simply adding a line break after return.

**Comment by adidahiya** [comment]
thanks for the bug report. we're open to PRs here, but unreachable code detection is coming to the compiler in 1.8 and we're going to deprecate it in TSLint soon (https://github.com/palantir/tslint/issues/661), so it's low priority.

**Comment by andy-hanson** [comment]
The code is in fact unreachable. The addition of the line break puts the `return` on its own line, so you return `undefined`.

**Comment by JKillian** [comment]
Good insight @andy-hanson! Indeed, TSLint is giving you a very helpful warning here @YetiCGN, [this article on semicolon insertion](http://inimino.org/~inimino/blog/javascript_semicolons) talks a little bit about similar situations with `return` and other constructs.

**Comment by YetiCGN** [comment]
Thanks for the clarification! I was not aware of this particular quirk in TS/JS, since I'm used to writing return statements like this from other languages. It didn't even compile, so I had no chance to see the error in JS. ;)
