### ISSUE TITLE
Default rules ignored if tslint.json is present

### ISSUE THREAD

**Issue by Zorgatone** [palantir/tslint#930]
tslint is ignoring all the default rules if I have a tslint.json file present in the current directory.

It doesn't matter the content of the json, I can't seem to get the default rules again without having to specify them all (one by one).
I also tried to set the "rulesDirectory" to "node_modules/tslint/lib/rules" where tslint is installed, but it's not loading them.

I get absolutely no warnings/errors if the tslint.json file is present. If I delete it I get the warnings again.

I'm using the cli version which is installed globally.
I have installed both `tslint@next` and `typescript@next` both globally and locally.

What I was trying to do (and failed) was to use all the default rules and override just a couple of them, but I didn't find a way to do that without specifying every single rule I want (even the defaults).
Also I don't really get in the documentation if I can change the rules of a file with a comment, instead of just turning the rule on and off (ie. specify single-quote vs double-quote rule, not just disabling the rule completely).

Also `tslint --rules-dir node_modules/tslint/lib/rules` didn't read that rules directory. How is it supposed to work?

**Comment by JKillian** [comment]
@Zorgatone The default configuration is only used if you don't specify a config on your own at all. So if you have a `tslint.json` around you will have to go through and specify each rule you want to enable. Unfortunately, there's no way to override only a part of the default configuration.

Through comments, you can only disable/enable certain rules but not change their options. It's an interesting idea, but it would probably would not work with the implementation of some of the rules.

Your use of `--rule-dir` is correct mainly, but it's designed for pointing to a directory of custom rules that you wrote (since the built-in rules are included by default). You still have to enable the rules in a `tslint.json` file after including them via `--rules-dir`.

I'm going to close this issue, but if you have any follow-up questions/comments, feel free to respond!

**Comment by Zorgatone** [comment]
That's very annoying though.. I wanted to use tabs in my project, and to
lint my code I have to specify every one of the default rules.

I'm used to eslint where I can specify a default ruleset and then override
single rules

Il venerdì 22 gennaio 2016, Jason Killian <notifications@github.com> ha
scritto:

**Comment by nschloe** [comment]
I'm just using tslint for the the first time, and I'm kind of taken aback by this too. All other linting tools preserve the defaults that you don't override. This is a pretty understandable use case too: You'd like to use the defaults, except setting "xyz". Right now, I wouldn't see how that's possible with tslint.

**Comment by JKillian** [comment]
Hmm, I didn't realize this was the common behavior. This can be reconsidered, it seems like a fairly easy change to make. I am concerned that it could suddenly enable new rules for users who upgrade TSLint.

**Comment by Zorgatone** [comment]
@JKillian
>I am concerned that it could suddenly enable new rules for users who upgrade TSLint.

That would happen even with the current behavior, wouldn't it?
If you're worried to enable new rules for users who upgrade TSLint, you could make the new rules disabled by default maybe.

**Comment by adidahiya** [comment]
@Zorgatone yes, it _could_ happen with the current behavior for users that supply no configuration of their own if we add new rules to the [default config](https://github.com/palantir/tslint/blob/master/src/configuration.ts#L23). However, in practice, this is extremely rare -- I'm pretty sure most users supply a configuration.

The breaking change @JKillian is referring to would occur if a user has not specified whether one of the `DEFAULT_CONFIG` rules is enabled and suddenly they upgrade and get, for example, `no-var-keyword` lint failures everywhere and have to add `"no-var-keyword": false` to their config to fix it. I don't see how you would get around this by "disabling them by default" as you wrote. It's not a _huge_ breaking change (relatively easy to mitigate), but it is breaking nonetheless.

**Comment by Zorgatone** [comment]
I haven't experimented much with different linters, I know that with eslint you can specify one of the default present. Not sure if you can say in the config file that you want to load a preset and then overwrite some rules.

At the very least the most of them provide a way to set some rules per-file basis (ie. with comments), to turn on/off and configure certain rules, and even ignore some lines

**Comment by adidahiya** [comment]
TSList has rule flags via comments as well, see https://github.com/palantir/tslint#tslint-rule-flags. We currently don't support configuration inline (just enabling / disabling), but that would be a welcome feature request!

**Comment by Zorgatone** [comment]
I know. But it's only on/off though. I'd love to contribute if I had the
time, but I don't

**Comment by wangshan** [comment]
Just started using tslint, I'm hit by this problem too. At the moment I have to copy https://github.com/Microsoft/tslint-microsoft-contrib/blob/master/recommended_ruleset.js and modify  the part I want to change, is this a widely accepted rule set?

**Comment by adidahiya** [comment]
At this point tslint ships with recommended / latest configurations available via the `"extends"` field in tslint.json. I think that sufficiently addresses all the issues in this thread. https://github.com/palantir/tslint#configuration
