### ISSUE TITLE
Options to force trailing comma on interfaces declaration

### ISSUE THREAD

**Issue by Strate** [palantir/tslint#960]
I want to force trailing comma on interface declaration:
```ts
interface A {
  prop1: string,
  prop2: string,
  prop3: string,
}
```
Is there any option to do this?

**Comment by JKillian** [comment]
The `trailing-comma` rule only checks array literals, object literals, named import lists, and destructuring constructs right now, so unfortunately there's no way to have object literal _types_ checked, whether in an interface declaration like this or as a declared type somewhere else.

Seems like a reasonable feature request though - I've tagged it as such.

**Comment by adidahiya** [comment]
aren't fields in an interface supposed to end with a trailing semicolon?

http://www.typescriptlang.org/Handbook#interfaces

**Comment by JKillian** [comment]
I had thought so also, but [the Interface grammar](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#71-interface-declarations) allows for [semicolons or commas](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#383-object-type-literals).

**Comment by JKillian** [comment]
See #1233 for discussion on this issue. The "ignore-interfaces" option for the `semicolon` rule will let users make a custom rule for this request if desired.

**Comment by schickling** [comment]
Since version 4.0 this seems to be always enforced when using `multiline: "always"`. Is there a way to allow to omit trailing commas for interfaces? I imagine the following: 

```json
  "rules": {
    "trailing-comma": [
      true,
      {
        "multiline": "always",
        "singleline": "never"
      },
      "ignore-interfaces"
    ]
  }
```

Unfortunately this change seemed to have broke all of our build once we upgraded to v4.

**Comment by schickling** [comment]
Maybe @JKillian knows something about this?

**Comment by adidahiya** [comment]
@schickling the `"ignore-interfaces"` is supported in the semicolon rule, not the trailing-comma rule (see the linked PR #1233). What exact format are you looking to write interfaces with? I'm a little hesitant to add more options to this rule, especially since TSLint v4 will automatically fix all violations of the trailing-comma rule for you.

**Comment by schickling** [comment]
This is the way how we write interfaces:

```ts
interface Post {
  title: string
  age: number
}
```

**Comment by Zjaaspoer** [comment]
We're writing our interfaces the exact same way as @schickling (basically interfaces without semicolons). Right now Tslint is adding trailing commas to the last row like so:

```
interface Post {
  title: string
  age: number,
}
```

which is a bit undesirable... :) I'm not sure what the best strategy is to resolve this, but probably the trailing comma's should only be added if the other rows in the interface already have a comma?

**Comment by adidahiya** [comment]
Yeah that makes sense @Zjaaspoer; filed #1810 for you and @schickling

**Comment by Zjaaspoer** [comment]
great thanks!

**Comment by theodorejb** [comment]
We use commas to separate interface properties, and I'd really like an option to enforce this.

**Comment by muuvmuuv** [comment]
This affects this case as well:

```ts
fs.writeFile(
    ContentsJSONFile,
    JSON.stringify(ContentsJSON, null, 2),
    (err) => {
      if (err) {
        throw new Error(err.message)
      }

      console.log(chalk.green(`Wrote \`Contents.json\` file for ${set.name}!`))
    } // <!-- Missing trailing comma (trailing-comma) tslint(1)
  )
```
