### ISSUE TITLE
Class implementing Interface throws error (cannot find error definition)

### ISSUE THREAD

**Issue by Tomino2112** [palantir/tslint#964]
Hi,

Taking basic example from TypeScript handbook:

```
interface IClock {
    currentTime: Date;
}

class Clock implements IClock  {
    currentTime: Date;
    constructor(h: number, m: number) {
        return;
    }
}
```

TSLint throws error : default access modifier on member/method not allowed (member-access)

Screenshot: 
![2016-02-09_101302](https://cloud.githubusercontent.com/assets/1140217/12913678/0a4db664-cf18-11e5-832e-767737bd0971.jpg)

I couldn't find what this error means

**Comment by adidahiya** [comment]
https://github.com/palantir/tslint#supported-rules

> `member-access` enforces using explicit visibility on class members

You must declare the member as `public` or `private` or `protected`, etc.
