### ISSUE TITLE
install package with typescript@next

### ISSUE THREAD

**Issue by rolandjitsu** [palantir/tslint#970]
It seems like I cannot install this package because I am also installing `typescript@next` and I keep getting `npm WARN EPEERINVALID tslint@3.3.0 requires a peer of typescript@>=1.7.3 but none was installed.`. How do I make this work with the nightly build of TS?

**Comment by adidahiya** [comment]
use [`tslint@next`](https://github.com/palantir/tslint#next-branch)

**Comment by rolandjitsu** [comment]
Thanks, that seems to fix it, but now gulp-tslint complains :) I'll see if I can remove the gulp plugin and use tslint directly.
