### ISSUE TITLE
Error while initiate react context

### ISSUE THREAD

**Issue by andrewBalekha** [palantir/tslint#976]
In my code I have provider with store
`static contextTypes = {
    store: PropTypes.object.isRequired
  };`

tslint is throwing error 

>  default access modifier on member/method not allowed

Is that someone faced with this?

**Comment by adidahiya** [comment]
That failure is reported by the member-access rule. The verbose formatter will tell you which rule triggered each failure and you can look up rule semantics in the readme / docs site. Perhaps in this case the error message should be improved to mention the tokens `public`, `private`, etc.
