### ISSUE TITLE
npm install tslint@next is pointing to older pre-release in NPM Registry

### ISSUE THREAD

**Issue by ChrisPearce** [palantir/tslint#986]
v3.4.0 of tslint has now been released.

However, when I currently run "npm install tslint@next", the older pre-release tslint@3.4.0-dev.2 seems to get installed from the NPM registry.

If I run "npm install tslint" I get the latest release (v3.4.0).

Looking at the "next" branch in GitHub, it's latest release is showing as 3.4.0-dev.2 rather than the 3.4.0

**Comment by adidahiya** [comment]
what do you expect `tslint@next` to point to? `3.4.0-dev.2` is in fact the latest "next" release. we have stable (`latest`) and dev (`next`) dist-tags on NPM to mirror typescript's release channels. the functionality in `3.4.0-dev.2` should be identical to that of `3.4.0`.

**Comment by JKillian** [comment]
@ChrisPearce This is correct behavior (but can be a little surprising). The `next ` releases of TSLint, that is, all those ending with `-dev.x` are set up to be used with the nightly releases of TypeScript, where as our stable non-dev releases are set up to work with the stable releases of TypeScript. Right now, they're very similar, but at times they diverge more depending on what new features are being added to TS.

**Comment by ChrisPearce** [comment]
Thank you very much for the clarification
