### ISSUE TITLE
Proposal: Baseline Testing System

### ISSUE THREAD

**Issue by JKillian** [palantir/tslint#989]
#620 has worked out very well so far - it's made tests much more intuitive and easier to read and write. However, the current setup still has a few flaws. The biggest area of concern is test duplication. Because you mark in where lint failures should be in the test file, each test file can only work properly with one configuration. If you want to test the linter on the same code with multiple different configurations, you must duplicate the test file and change the error markup, which can be tedious.

I propose adapting the current system to use a baseline system similar to how [TypeScript](https://github.com/Microsoft/TypeScript) tests things. In short, test files would be plain .ts/.tsx files. Running the test command would generate test results for all test files and compare them to the baselines. (These files would use the same error markup syntax that is currently in use.) Any difference would cause the build to fail. The developer would then compare the test results with the baselines and accept the results as the new baselines if they are correct.
#### Pros
- Less test file duplication
- Don't have to write out error markup by hand
- Can test different configurations easier
- Test files are actual .ts/.tsx files, so your editor will be happier with them
#### Cons
- Writing out error markup explicitly is a good exercise in ensuring that your rules produce the results you want
- Would have to rethink how the `--test` command works which lets users test their custom rules. (On the other hand, the `--test` command may be able to remain unchanged, it would just use a slightly different paradigm than our tests.)
- Possibly less intuitive than current sytem

There are still a few details to flesh out with this idea, such as how to specify multiple configurations for a test file, directory structure, etc.

**Comment by JKillian** [comment]
Looking at https://github.com/palantir/tslint/pull/1546, I began to think that this change is becoming more and more useful. @alexeagle / @ScottSWu you've both had PRs lately that have had to change lots of test code. Do you think adjusting the current system to make it more like TS's system would be useful?

**Comment by JoshuaKGoldberg** [comment]
Given #4534 this seems less relevant now. Ah well!
