### ISSUE TITLE
Use update-notifier to notify users of new versions in a non-intrusive way

### ISSUE THREAD

**Issue by adidahiya** [palantir/tslint#990]
https://www.npmjs.com/package/update-notifier

**Comment by davieschoots** [comment]
Hi @adidahiya, 

I would like to help by adding this feature to the tslint cli, can you let me know if this is ok?

Do have some questions, but I'll ask them if you're ok with it :)

Kind regards,

Davie

**Comment by adidahiya** [comment]
Sure, sounds good to me, we can discuss here

**Comment by davieschoots** [comment]
Cool, thank you!

I'm wondering what your thoughts are about the default message and the interval for the check on updates. 

I think for the update check once every week or 2 weeks should be fine (the default it's once a day). 

Are you ok with this and do you prefer having a custom message or leave the default?

**Comment by davieschoots** [comment]
Hi @nchen63, this issue should be on closed, right?
