### ISSUE TITLE
Extend configuration files

### ISSUE THREAD

**Issue by adidahiya** [palantir/tslint#997]
ESLint has a nice feature that allows you to extend configuration files. We should add support for this as well.

(edit: updated link) http://eslint.org/docs/user-guide/configuring#extending-configuration-files

**Comment by unional** [comment]
I can give it a try. Most work are in `ruleLoader.ts`, right?

**Comment by unional** [comment]
A better link: http://eslint.org/docs/user-guide/configuring#extending-configuration-files
:rose:

**Comment by unional** [comment]
Simple TODO list (idea welcome):
* [x] Support extends with relative path
* [ ] Support extends with package (`tslint-config-X`)
* [ ] Support extends with array
* [ ] Circular reference
* [ ] Multiple extends points to the same rulesDirector(ies)
* [ ] Rules merging? (I assume rule overrides)

**Comment by JKillian** [comment]
@unional Just wanted to say that I don't think all these features are necessary, at least to start. We only need to support `.json` files and let's stick with rule overrides. "extends with package" is an interesting feature, I don't think it's necessary for the first iteration though, although it doesn't seem too difficult to implement either, so either way is fine for it. Let's not worry about sub-rules in packages or circular references either.

**Comment by unional** [comment]
extends with package is what I really needed so I definitely want it in. :smirk:
Others are fine with me, that is just a brainstorming list on what can be done.
Maybe create another PR to keep track of them when basic support are done?

How about "Multiple extends points to the same rulesDirectory"? Does tslint support that correctly today? I have not do any filtering in my PR.

**Comment by JKillian** [comment]
Duplicate paths to the same rulesDirectory shouldn't hurt anything. TSLint right now would end up searching the directory multiple times, but that can be fixed easily in the future, and it's not a big deal.

**Comment by CKGrafico** [comment]
Are you supporting yml now?

**Comment by JKillian** [comment]
@CKGrafico no, but we have [an `"extends"` option now.](https://palantir.github.io/tslint/usage/tslint-json/)

**Comment by ikokostya** [comment]
Have your plans for support `configuration-cascading` (http://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy)?

**Comment by adidahiya** [comment]
@ikokostya we'd probably take a PR for that; can you open a new issue to track your request?

**Comment by ikokostya** [comment]
Created https://github.com/palantir/tslint/issues/2302
